-- Additive editorial/link corrections after clean-D1 regression. Legacy remains unchanged.
DELETE FROM v2_sentence_vocabulary_links WHERE id LIKE 'c-vl-%' AND expression_id NOT LIKE 'legacy-%' AND expression_id NOT LIKE 'lesson-%';
UPDATE v2_sentence_expressions SET sort_order=100+(SELECT sort_order FROM v2_sentence_units u WHERE u.id=unit_id) WHERE id LIKE 'legacy-%' OR id LIKE 'lesson-%';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-21-en-1' WHERE id='c-vl-2614';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-21-en-0' WHERE id='c-vl-2613';
UPDATE v2_sentence_grammar_links SET turn_id='legacy-21-en-0',displayed_form='How was your weekend?' WHERE id='c-gl-1412';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-21-ja-1' WHERE id='c-vl-2616';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-21-ja-0' WHERE id='c-vl-2615';
UPDATE v2_sentence_grammar_links SET turn_id='legacy-21-ja-0',displayed_form='週末はどうだった？' WHERE id='c-gl-1414';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-27-en-1' WHERE id='c-vl-2630';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-27-en-0' WHERE id='c-vl-2631';
UPDATE v2_sentence_grammar_links SET turn_id='legacy-27-en-0',displayed_form='That sounded a bit harsh.' WHERE id='c-gl-1450';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-27-ja-1' WHERE id='c-vl-2632';
UPDATE v2_sentence_grammar_links SET turn_id='legacy-27-ja-0',displayed_form='ちょっときつく聞こえたよ。' WHERE id='c-gl-1452';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-129-en-0' WHERE id='c-vl-2896';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-129-en-0' WHERE id='c-vl-2897';
UPDATE v2_sentence_grammar_links SET turn_id='legacy-129-en-0',displayed_form='You seem quiet today.' WHERE id='c-gl-2091';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-129-ja-0' WHERE id='c-vl-2898';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-129-ja-0' WHERE id='c-vl-2899';
UPDATE v2_sentence_grammar_links SET turn_id='legacy-129-ja-0',displayed_form='今日は静かだね。' WHERE id='c-gl-2093';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-135-en-0' WHERE id='c-vl-2918';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-135-en-0' WHERE id='c-vl-2916';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-135-en-0' WHERE id='c-vl-2917';
UPDATE v2_sentence_grammar_links SET turn_id='legacy-135-en-0',displayed_form='I know you mean well, but I feel pressured.' WHERE id='c-gl-2129';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-135-ja-0' WHERE id='c-vl-2919';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-135-ja-0' WHERE id='c-vl-2920';
UPDATE v2_sentence_grammar_links SET turn_id='legacy-135-ja-0',displayed_form='心配してくれるのはわかるけど、少し負担に感じる。' WHERE id='c-gl-2131';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-33-en-0' WHERE id='c-vl-2646';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-33-en-1' WHERE id='review-vl-21';
UPDATE v2_sentence_grammar_links SET turn_id='legacy-33-en-0',displayed_form='How long is the wait?' WHERE id='c-gl-1488';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-33-ja-0' WHERE id='review-vl-22';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-33-ja-1' WHERE id='c-vl-2647';
UPDATE v2_sentence_grammar_links SET turn_id='legacy-33-ja-0',displayed_form='どのくらい待ちますか。' WHERE id='c-gl-1490';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-39-en-1' WHERE id='c-vl-2659';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-39-en-1' WHERE id='c-vl-2660';
UPDATE v2_sentence_grammar_links SET turn_id='legacy-39-en-0',displayed_form='I think there''s been a mix-up.' WHERE id='c-gl-1526';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-39-ja-1' WHERE id='review-vl-24';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-39-ja-0' WHERE id='c-vl-2661';
UPDATE v2_sentence_grammar_links SET turn_id='legacy-39-ja-0',displayed_form='注文と違うものが来たようなんですが。' WHERE id='c-gl-1528';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-117-en-1' WHERE id='c-vl-2868';
UPDATE v2_sentence_grammar_links SET turn_id='legacy-117-en-0',displayed_form='Are you feeling any better?' WHERE id='c-gl-2015';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-117-ja-1' WHERE id='c-vl-2869';
UPDATE v2_sentence_grammar_links SET turn_id='legacy-117-ja-1',displayed_form='少しね。でも、まだだるい。' WHERE id='c-gl-2017';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-123-en-0' WHERE id='c-vl-2880';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-123-en-0' WHERE id='c-vl-2881';
UPDATE v2_sentence_grammar_links SET turn_id='legacy-123-en-0',displayed_form='Is it constant or does it come and go?' WHERE id='c-gl-2053';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-123-ja-0' WHERE id='c-vl-2882';
UPDATE v2_sentence_grammar_links SET turn_id='legacy-123-ja-0',displayed_form='ずっと痛みますか。それとも時々ですか。' WHERE id='c-gl-2055';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-165-en-0' WHERE id='c-vl-2987';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-165-en-1' WHERE id='c-vl-2986';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-165-en-1' WHERE id='review-vl-116';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-165-en-0' WHERE id='c-vl-2985';
UPDATE v2_sentence_grammar_links SET turn_id='legacy-165-en-0',displayed_form='Can you help me with this?' WHERE id='c-gl-2319';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-165-ja-1' WHERE id='c-vl-2988';
UPDATE v2_sentence_grammar_links SET turn_id='legacy-165-ja-0',displayed_form='これ、手伝ってもらえる？' WHERE id='c-gl-2321';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-171-en-0' WHERE id='c-vl-2999';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-171-en-1' WHERE id='c-vl-3002';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-171-en-1' WHERE id='c-vl-3000';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-171-en-1' WHERE id='c-vl-3001';
UPDATE v2_sentence_grammar_links SET turn_id='legacy-171-en-0',displayed_form='Could you take care of the whole thing?' WHERE id='c-gl-2357';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-171-ja-0' WHERE id='c-vl-3003';
UPDATE v2_sentence_grammar_links SET turn_id='legacy-171-ja-0',displayed_form='全部お願いできる？' WHERE id='c-gl-2359';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-141-en-1' WHERE id='c-vl-2931';
UPDATE v2_sentence_grammar_links SET turn_id='legacy-141-en-0',displayed_form='What are you watching these days?' WHERE id='c-gl-2167';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-141-ja-1' WHERE id='c-vl-2932';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-141-ja-0' WHERE id='review-vl-93';
UPDATE v2_sentence_grammar_links SET turn_id='legacy-141-ja-1',displayed_form='料理番組。意外と落ち着くんだ。' WHERE id='c-gl-2169';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-147-en-1' WHERE id='c-vl-2943';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-147-en-0' WHERE id='review-vl-99';
UPDATE v2_sentence_grammar_links SET turn_id='legacy-147-en-0',displayed_form='Have you thought of doing it professionally?' WHERE id='c-gl-2205';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-147-ja-1' WHERE id='c-vl-2945';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-147-ja-0' WHERE id='c-vl-2944';
UPDATE v2_sentence_grammar_links SET turn_id='legacy-147-ja-1',displayed_form='少しね。でも、純粋に楽しめなくなるのは嫌かな。' WHERE id='c-gl-2207';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-57-en-1' WHERE id='c-vl-2710';
UPDATE v2_sentence_grammar_links SET turn_id='legacy-57-en-0',displayed_form='Are you using the washing machine?' WHERE id='c-gl-1639';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-57-ja-1' WHERE id='c-vl-2711';
UPDATE v2_sentence_grammar_links SET turn_id='legacy-57-ja-1',displayed_form='ううん、使っていいよ。' WHERE id='c-gl-1641';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-63-en-1' WHERE id='c-vl-2724';
UPDATE v2_sentence_grammar_links SET turn_id='legacy-63-en-0',displayed_form='I hate to bother you, but the noise carries.' WHERE id='c-gl-1677';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-63-ja-0' WHERE id='c-vl-2725';
UPDATE v2_sentence_grammar_links SET turn_id='legacy-63-ja-0',displayed_form='すみません、音がかなり響いているんですが。' WHERE id='c-gl-1679';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-177-en-0' WHERE id='c-vl-3014';
UPDATE v2_sentence_grammar_links SET turn_id='legacy-177-en-0',displayed_form='Are you still going away this weekend?' WHERE id='c-gl-2394';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-177-ja-1' WHERE id='c-vl-3017';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-177-ja-0' WHERE id='c-vl-3016';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-177-ja-0' WHERE id='c-vl-3015';
UPDATE v2_sentence_grammar_links SET turn_id='legacy-177-ja-1',displayed_form='ううん、代わりに家で過ごすことにした。' WHERE id='c-gl-2396';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-183-en-1' WHERE id='c-vl-3027';
UPDATE v2_sentence_grammar_links SET turn_id='legacy-183-en-0',displayed_form='Was the trip worth it after all?' WHERE id='c-gl-2430';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-183-ja-0' WHERE id='c-vl-3028';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-183-ja-0' WHERE id='review-vl-134';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-183-ja-0' WHERE id='review-vl-133';
UPDATE v2_sentence_grammar_links SET turn_id='legacy-183-ja-0',displayed_form='結局、行った甲斐はあった？' WHERE id='c-gl-2432';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-45-en-1' WHERE id='review-vl-31';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-45-en-1' WHERE id='c-vl-2671';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-45-en-0' WHERE id='c-vl-2670';
UPDATE v2_sentence_grammar_links SET turn_id='legacy-45-en-0',displayed_form='Can you handle the slides?' WHERE id='c-gl-1564';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-45-ja-1' WHERE id='c-vl-2674';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-45-ja-1' WHERE id='c-vl-2673';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-45-ja-1' WHERE id='review-vl-32';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-45-ja-0' WHERE id='c-vl-2672';
UPDATE v2_sentence_grammar_links SET turn_id='legacy-45-ja-1',displayed_form='いいよ。数字を確認してもらえる？' WHERE id='c-gl-1566';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-51-en-0' WHERE id='c-vl-2696';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-51-en-1' WHERE id='c-vl-2694';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-51-en-0' WHERE id='c-vl-2693';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-51-en-0' WHERE id='c-vl-2695';
UPDATE v2_sentence_grammar_links SET turn_id='legacy-51-en-0',displayed_form='We may need to narrow the scope.' WHERE id='c-gl-1601';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-51-ja-0' WHERE id='c-vl-2697';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-51-ja-1' WHERE id='c-vl-2698';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-51-ja-0' WHERE id='c-vl-2699';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-51-ja-0' WHERE id='c-vl-2700';
UPDATE v2_sentence_grammar_links SET turn_id='legacy-51-ja-0',displayed_form='範囲を絞る必要がありそうですね。' WHERE id='c-gl-1603';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-81-en-0' WHERE id='review-vl-53';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-81-en-0' WHERE id='review-vl-54';
UPDATE v2_sentence_grammar_links SET turn_id='legacy-81-en-0',displayed_form='Do you take cards?' WHERE id='c-gl-1789';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-81-ja-0' WHERE id='c-vl-2773';
UPDATE v2_sentence_grammar_links SET turn_id='legacy-81-ja-0',displayed_form='カードは使えますか。' WHERE id='c-gl-1791';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-87-en-1' WHERE id='c-vl-2789';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-87-en-0' WHERE id='c-vl-2790';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-87-en-0' WHERE id='c-vl-2791';
UPDATE v2_sentence_grammar_links SET turn_id='legacy-87-en-0',displayed_form='Does the warranty cover accidental damage?' WHERE id='c-gl-1827';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-87-ja-1' WHERE id='c-vl-2792';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-87-ja-1' WHERE id='c-vl-2793';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-87-ja-1' WHERE id='c-vl-2794';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-87-ja-0' WHERE id='c-vl-2795';
UPDATE v2_sentence_grammar_links SET turn_id='legacy-87-ja-0',displayed_form='うっかり壊した場合も保証の対象ですか。' WHERE id='c-gl-1829';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-153-en-0' WHERE id='c-vl-2955';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-153-en-1' WHERE id='c-vl-2956';
UPDATE v2_sentence_grammar_links SET turn_id='legacy-153-en-0',displayed_form='This is my friend, Alex.' WHERE id='c-gl-2243';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-153-ja-0' WHERE id='c-vl-2957';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-153-ja-1' WHERE id='c-vl-2958';
UPDATE v2_sentence_grammar_links SET turn_id='legacy-153-ja-1',displayed_form='初めまして。お話はよく聞いています。' WHERE id='c-gl-2245';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-159-en-1' WHERE id='c-vl-2970';
UPDATE v2_sentence_grammar_links SET turn_id='legacy-159-en-0',displayed_form='Come on, stay for one more.' WHERE id='c-gl-2281';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-159-ja-1' WHERE id='c-vl-2971';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-159-ja-1' WHERE id='c-vl-2972';
UPDATE v2_sentence_grammar_links SET turn_id='legacy-159-ja-0',displayed_form='もう少しだけいようよ。' WHERE id='c-gl-2283';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-69-en-0' WHERE id='c-vl-2739';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-69-en-1' WHERE id='c-vl-2738';
UPDATE v2_sentence_grammar_links SET turn_id='legacy-69-en-0',displayed_form='Shall we meet outside at six?' WHERE id='c-gl-1713';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-69-ja-0' WHERE id='review-vl-43';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-69-ja-1' WHERE id='c-vl-2740';
UPDATE v2_sentence_grammar_links SET turn_id='legacy-69-ja-0',displayed_form='六時に外で会おうか。' WHERE id='c-gl-1715';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-75-en-1' WHERE id='c-vl-2759';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-75-en-0' WHERE id='c-vl-2757';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-75-en-1' WHERE id='c-vl-2760';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-75-en-1' WHERE id='c-vl-2758';
UPDATE v2_sentence_grammar_links SET turn_id='legacy-75-en-0',displayed_form='Could we keep that afternoon flexible?' WHERE id='c-gl-1751';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-75-ja-0' WHERE id='c-vl-2764';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-75-ja-1' WHERE id='c-vl-2763';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-75-ja-0' WHERE id='c-vl-2761';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-75-ja-1' WHERE id='c-vl-2762';
UPDATE v2_sentence_grammar_links SET turn_id='legacy-75-ja-1',displayed_form='いいよ。予定が固まったら教えて。' WHERE id='c-gl-1753';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-93-en-0' WHERE id='c-vl-2806';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-93-en-1' WHERE id='c-vl-2805';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-93-en-1' WHERE id='c-vl-2807';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-93-en-0' WHERE id='c-vl-2804';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-93-en-0' WHERE id='review-vl-58';
UPDATE v2_sentence_grammar_links SET turn_id='legacy-93-en-0',displayed_form='Does this train go to the airport?' WHERE id='c-gl-1865';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-93-ja-0' WHERE id='c-vl-2808';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-93-ja-0' WHERE id='c-vl-2809';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-93-ja-0' WHERE id='review-vl-59';
UPDATE v2_sentence_grammar_links SET turn_id='legacy-93-ja-1',displayed_form='中央駅で乗り換えてください。' WHERE id='c-gl-1867';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-99-en-1' WHERE id='c-vl-2818';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-99-en-1' WHERE id='c-vl-2819';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-99-en-0' WHERE id='c-vl-2820';
UPDATE v2_sentence_grammar_links SET turn_id='legacy-99-en-0',displayed_form='Will my bag go straight through?' WHERE id='c-gl-1903';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-99-ja-1' WHERE id='c-vl-2821';
UPDATE v2_sentence_grammar_links SET turn_id='legacy-99-ja-0',displayed_form='荷物は最終目的地まで預けられますか。' WHERE id='c-gl-1905';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-105-en-0' WHERE id='c-vl-2834';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-105-en-0' WHERE id='c-vl-2835';
UPDATE v2_sentence_grammar_links SET turn_id='legacy-105-en-0',displayed_form='Shall we still go for a walk?' WHERE id='c-gl-1939';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-105-ja-1' WHERE id='c-vl-2838';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-105-ja-0' WHERE id='c-vl-2837';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-105-ja-0' WHERE id='c-vl-2836';
UPDATE v2_sentence_grammar_links SET turn_id='legacy-105-ja-1',displayed_form='雨がやむまで中にいよう。' WHERE id='c-gl-1941';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-111-en-1' WHERE id='c-vl-2854';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-111-en-0' WHERE id='c-vl-2853';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-111-en-1' WHERE id='c-vl-2852';
UPDATE v2_sentence_grammar_links SET turn_id='legacy-111-en-0',displayed_form='The forecast keeps changing.' WHERE id='c-gl-1977';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-111-ja-1' WHERE id='c-vl-2855';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-111-ja-1' WHERE id='review-vl-73';
UPDATE v2_sentence_vocabulary_links SET turn_id='legacy-111-ja-0' WHERE id='c-vl-2856';
UPDATE v2_sentence_grammar_links SET turn_id='legacy-111-ja-1',displayed_form='様子を見て、明日決めよう。' WHERE id='c-gl-1979';
INSERT OR IGNORE INTO v2_vocabulary_topics(item_id,topic_id) SELECT DISTINCT l.item_id,u.topic_id FROM v2_sentence_vocabulary_links l JOIN v2_sentence_expressions e ON e.id=l.expression_id JOIN v2_sentence_units u ON u.id=e.unit_id;
INSERT INTO v2_vocabulary_items(id,language,lemma,type,stage,ipa,part_of_speech,register,publication_state,sort_order) VALUES ('en-c-rain-noun','en','rain','word',1,'reɪn','noun','neutral','published',2000),('en-c-work-verb','en','work','word',1,'wɜːrk','verb','neutral','published',2001);
INSERT INTO v2_vocabulary_senses(id,item_id,meaning_zh,usage_zh) VALUES ('en-c-rain-noun-1','en-c-rain-noun','雨','不可数名词；与动词rain下雨分开。'),('en-c-work-verb-1','en-c-work-verb','工作；从事工作','动词；after work中的work则为名词。');
INSERT INTO v2_vocabulary_examples(id,item_id,kind,text,translation_zh) VALUES ('c-ve-rain-noun','en-c-rain-noun','example','I expect rain.','我预计会下雨。'),('c-ve-work-verb','en-c-work-verb','example','I had to work.','我不得不工作。');
UPDATE v2_sentence_vocabulary_links SET item_id='en-c-work-verb',sense_id='en-c-work-verb-1',note_zh='此处work为动词。' WHERE id='c-vl-3020';
UPDATE v2_sentence_vocabulary_links SET item_id='en-c-work-verb',sense_id='en-c-work-verb-1',note_zh='此处work为动词。' WHERE id='c-vl-3048';
UPDATE v2_grammar_points SET form_name='be + adjective / state phrase' WHERE id='en-be-adjective';
