import {$,esc,url,detail,names,langName,badge,heading,domains,languages,pagination,empty,load,api,shell,section,reading,aiLink,relationCards,reverseCards,legacyState,posNames,posTaxonomy,compactPos,fullPos,registerNames,preview,account,privateApi} from './shared.js';
import {dynamicExamplesPanel,bindDynamicExamples} from './ai-examples.js';
import {renderTutor} from './ai-tutor.js';
const page=document.body.dataset.page,p=Object.fromEntries(new URLSearchParams(location.search));
const lang=p.lang==='ja'?'ja':'en';
shell(['index'].includes(page)?'home':['academic','academic-about','ielts','jlpt'].includes(page)?'academic':page==='review'?'progress':['ai','progress'].includes(page)?page:'learn');
const domainCards=()=>`<div class="grid">${[['vocabulary','字','词汇库','Vocabulary','把词义、搭配与容易混淆的用法分清楚。','Stage 1–6 · 独立词汇阶段'],['grammar','式','语法库','Grammar','理解结构的核心感觉，再回到真实表达。','Level 1–6 · 建议学习路径'],['sentences','句','句子与表达','Sentences & Expressions','从想说的中文意思出发，学习自然用法。','生活主题 · 三维难度']].map(([k,i,n,en,d,m])=>`<a class="card domain-card ${k}" href="${url(k)}"><span class="domain-icon">${i}</span><div><div class="eyebrow">${en}</div><h3>${n}</h3></div><p>${d}</p><div class="end"><span>${m}</span><span aria-hidden="true">↗</span></div></a>`).join('')}</div>`;
function profile(l,expanded=false){const s=legacyState(),level=s.levels?.[l]?.level;const count=Object.values(s.mastery?.[l]||{}).filter(x=>x==='learned').length;return `<section class="card"><div class="profile"><div><h3>${langName(l)}</h3><p class="muted">${Number.isInteger(level)&&level>=1&&level<=6?'原版定位 Level '+level:'原版尚未定位'}${count?' · 已学 '+count+' 项':''}</p></div>${badge('领域档案预览','preview')}</div><div class="progress-domains">${['词汇阶段','语法水平','表达能力'].map(n=>`<div><strong>${n}</strong><span>尚未独立评估</span></div>`).join('')}</div>${expanded?`<p class="notice">以上领域尚无独立掌握度。原版定位与学习记录继续保留，不换算为词汇或语法分数。</p><a class="text-link" href="/legacy/progress.html">旧版学习（兼容） · 查看进度 →</a>`:''}</section>`;}
async function home(){
 const sample=(await api('sentences/not-eaten')).data;
 $('#main').innerHTML=`<section class="hero"><div class="hero-copy"><div class="eyebrow">A little understanding, a little further.</div><h1>先理解，<br>再说出你的世界。</h1><p>学会一个词，读懂一个结构，连成一句自然的表达。<br>从中文意思出发，分别建立英语与日语的理解。</p><div class="actions"><a class="button primary" href="/sentences.html">从一句话开始 ↗</a><a class="button" href="/vocabulary.html">探索词汇库</a></div></div><div class="hero-art" aria-label="中文理解与独立双语表达示例"><div class="eyebrow">今天，从这句话开始</div><div class="line"><small>想表达的意思</small>${esc(sample.anchor_zh)}</div><div class="line" lang="en"><small>ENGLISH</small>${esc(sample.expressions.find(e=>e.language==='en').text)}</div><div class="line" lang="ja"><small>日本語</small>${reading(sample.expressions.find(e=>e.language==='ja').text,sample.expressions.find(e=>e.language==='ja').readings)}</div><a class="text-link" href="/sentence.html?id=not-eaten">看看这句话用了哪些词与语法 →</a></div></section><section class="section"><div class="section-head"><h2>三个入口，一起走向表达</h2><span class="muted">双语分阶段课程</span></div>${domainCards()}</section><section class="section"><div class="section-head"><h2>你的两条学习路径</h2><a class="text-link" href="/progress.html">我的学习 →</a></div><div class="grid two">${profile('en')}${profile('ja')}</div></section><section class="section grid two"><a class="callout" href="/academic.html"><div class="eyebrow">A focused direction</div><h2>给学习一个考试目标</h2><p>IELTS 5.0–7.0+ · JLPT N5–N1<br>选择目标，开始学习词汇、语法与表达。</p><span class="text-link">探索学术 / 考试 →</span></a><a class="card" href="/ai.html"><div class="eyebrow">Practice, in context</div><h2>English / 日本語 AI Tutor</h2><p>造句、表达纠错、词汇与语法问答，也能带入当前课程。</p><p class="text-link">开始对话 →</p></a></section>`;
}
const options=(items,value)=>items.map(([v,n])=>`<option value="${esc(v)}" ${String(value??'')===String(v)?'selected':''}>${esc(n)}</option>`).join('');
const select=(key,label,items)=>`<label>${label}<select name="${key}" aria-label="${label}">${options([['','不限'],...items],p[key])}</select></label>`;
const nums=Array.from({length:6},(_,i)=>[String(i+1),String(i+1)]);
const stageDescriptions=['基础生活词汇','常见日常表达','更广泛的生活交流','细致的词义与搭配','正式与专业场景','进阶词义辨析'];
const grammarDescriptions={en:['基础句子结构','日常动作与时间','可能性与连接表达','复杂时间与背景说明','细致的逻辑关系','语境与结构的进阶运用'],ja:['基础句型与判断','常用变化与日常表达','状态、推测与意图','背景说明与复杂连接','细致的语气区分','语境与结构的进阶运用']};
const topicName=t=>({body:'身体 / 身体部位',health:'健康 / 身体状态'})[t.id]||t.name_zh;
async function library(kind){
 const topics=(await api('academic/topics')).data;
 const isV=kind==='vocabulary',isG=kind==='grammar',groups=lang==='en'?[...'ABCDEFGHIJKLMNOPQRSTUVWXYZ','#']:['あ行','か行','さ行','た行','な行','は行','ま行','や行','ら行','わ行','その他'];
 const activeBrowse=isV&&!p.search&&(groups.includes(p.browse)?p.browse:groups[0]);
 const pageLimit=isV?40:12,shown=isV?Math.max(pageLimit,Math.min(400,Number(p.shown)||pageLimit)):pageLimit;
 const query={language:lang,limit:pageLimit,offset:'0',...(activeBrowse?{browse:activeBrowse}:{})};
 for(const k of ['stage','level','type','part_of_speech','register','topic','search','unit_type','overall_difficulty','vocabulary_difficulty','grammar_difficulty'])if(p[k])query[k]=p[k];
 const response={data:[],pagination:{limit:pageLimit,offset:0,has_more:false,next_offset:null}};
 while(response.data.length<shown){const batch=await api(kind+'?'+new URLSearchParams({...query,limit:Math.min(100,shown-response.data.length),offset:response.data.length}));response.data.push(...batch.data);response.pagination=batch.pagination;if(!batch.pagination.has_more||!batch.data.length)break;}
 const n=names[kind],band=isV?'stage':'level';
 const initial=kind==='sentences'?select('topic','生活主题',topics.map(t=>[t.id,topicName(t)])):'';
 const advanced=isV?select('type','词汇类型',[['word','单词'],['fixed_expression','固定表达']])+select('part_of_speech','词性',posTaxonomy[lang])+select('register','语域',Object.entries(registerNames))+select('topic','主题',topics.map(t=>[t.id,topicName(t)])):isG?'':select('unit_type','表达类型',[['sentence','句子'],['scenario','情境'],['dialogue','对话']])+select('overall_difficulty','综合难度',nums)+select('vocabulary_difficulty','词汇难度',nums)+select('grammar_difficulty','语法难度',nums);
 const levelNav=kind==='sentences'?`<div class="pills" aria-label="生活主题">${topics.map(t=>`<a class="${p.topic===t.id?'active':''}" href="${esc(url(kind,{lang,topic:t.id}))}">${esc(topicName(t))}</a>`).join('')}</div>`:`<div class="pills" aria-label="${isV?'词汇阶段':'语法水平'}">${nums.map(([v])=>`<a class="${p[band]===v?'active':''}" href="${esc(url(kind,{lang,[band]:v}))}">${isV?'Stage':'Level'} ${v}</a>`).join('')}</div><p class="results-note">${p[band]?(isV?stageDescriptions:grammarDescriptions[lang])[Number(p[band])-1]||'请选择 1–6':''}</p>`;
 const browseNav=isV&&!p.search?`<nav class="vocab-index-selector" aria-label="${lang==='en'?'按英文字母浏览':'按五十音浏览'}">${groups.map(g=>`<a class="${activeBrowse===g?'active':''}" ${activeBrowse===g?'aria-current="page"':''} href="${esc(url(kind,{...Object.fromEntries(Object.entries(p).filter(([k])=>!['offset','shown','detail'].includes(k))),lang,browse:g}))}">${esc(g)}</a>`).join('')}</nav>`:'';
 const resultClass=isV?'vocab-index':'grid';
 $('#main').innerHTML=heading(isV?'Build your vocabulary':isG?'Understand the structure':'Say what you mean',n+'，从理解开始',isV?'先用紧凑索引定位词条，再打开完整义项、搭配与例句。':isG?'两种语言，两套独立的语法库。按水平探索，也可以自由跳转。':'先想清楚想说什么，再看看英语和日语各自怎么表达。')+domains(kind)+languages({...p,lang},kind)+levelNav+browseNav+`<form class="filters" id="library-filters" method="get"><input type="hidden" name="lang" value="${lang}">${activeBrowse?`<input type="hidden" name="browse" value="${esc(activeBrowse)}">`:''}${kind!=='sentences'&&p[band]?`<input type="hidden" name="${band}" value="${esc(p[band])}">`:''}<div class="filter-row">${initial}<label class="search-label">${kind==='sentences'?'搜索中文意思':'搜索中文或目标语言'}<input name="search" value="${esc(p.search)}" placeholder="${isV?'试试：期待 / expect':isG?'试试：现在完成 / ている':'试试：吃饭'}" maxlength="100"></label><button class="primary" type="submit">搜索</button><a class="button" href="${url(kind,{lang})}">清除</a></div>${advanced?`<details ${Object.keys(p).some(k=>['type','register','part_of_speech','unit_type','overall_difficulty','grammar_difficulty','vocabulary_difficulty'].includes(k))?'open':''}><summary>更多筛选</summary><div class="filter-row">${advanced}<button type="submit">应用筛选</button></div></details>`:''}</form><p class="results-note" id="library-count">当前显示 ${response.data.length} 项${response.pagination.has_more?'，可以继续加载':''}。</p><div class="${resultClass}" id="library-results">${response.data.map(x=>listCard(kind,x)).join('')||empty()}</div>${isV&&response.pagination.has_more?'<div class="load-more-wrap"><button id="vocab-load-more" type="button">加载更多</button></div>':!isV?pagination(response.pagination,kind,{...p,lang}):''}`;
 decorateProgress(kind);
 if(isV){
  bindVocabularyRows();
  const form=$('#library-filters');form.addEventListener('submit',()=>{if(form.elements.search.value.trim())form.elements.browse?.remove();});
  if($('#vocab-load-more')){let offset=response.pagination.next_offset;$('#vocab-load-more').onclick=async()=>{const b=$('#vocab-load-more');b.disabled=true;b.textContent='正在加载…';try{const more=await api(kind+'?'+new URLSearchParams({...query,limit:pageLimit,offset}));$('#library-results').insertAdjacentHTML('beforeend',more.data.map(x=>listCard(kind,x)).join(''));bindVocabularyRows();decorateProgress(kind);offset=more.pagination.next_offset;b.hidden=!more.pagination.has_more;b.textContent='加载更多';const count=document.querySelectorAll('.vocab-row').length;$('#library-count').textContent=`当前显示 ${count} 项${more.pagination.has_more?'，可以继续加载':''}。`;const u=new URL(location.href);u.searchParams.set('shown',String(count));history.replaceState(history.state,'',u);}catch{b.textContent='加载失败，点击重试';}finally{b.disabled=false;}};}
  if(p.detail)await openVocabularyOverlay(p.detail,false);
 }
}
function listCard(kind,x){return kind==='vocabulary'?`<a class="vocab-row" data-vocab-id="${esc(x.id)}" data-progress-id="${esc(x.id)}" data-progress-type="vocabulary" href="${detail(kind,x.id,lang)}"><strong class="vocab-headword" lang="${x.language}">${esc(x.lemma)}${x.language==='ja'&&x.reading?`<span>（${esc(x.reading)}）</span>`:''}<span data-progress-slot></span></strong><span class="vocab-pos">${esc(compactPos(x.language,x.part_of_speech))}</span><span class="vocab-meaning">${esc(x.meaning_zh)}</span><span class="vocab-arrow" aria-hidden="true">›</span></a>`:`<a class="card list-card" ${kind==='grammar'?`data-progress-id="${esc(x.id)}" data-progress-type="grammar"`:''} href="${detail(kind,x.id,lang)}">${kind==='grammar'?`<h2>${esc(x.title_zh)}</h2><p lang="${x.language}">${esc(x.form_name)}</p><p class="muted">${esc(x.purpose_zh)}</p><div class="chips">${badge('Level '+x.level)}${badge('自由学习')}<span data-progress-slot></span></div>`:`<div class="eyebrow">${esc(({sentence:'一句话',scenario:'生活情境',dialogue:'简短对话'})[x.unit_type])}</div><h2>${esc(x.anchor_zh)}</h2><p class="muted">探索${langName(lang)}的词汇与语法用法</p><div class="chips">${badge('查看语言独立难度')}<span aria-hidden="true">→</span></div>`}</a>`;}

async function decorateProgress(kind){
 if(!['vocabulary','grammar'].includes(kind)||(await account()).authenticated!==true)return;
 const cards=[...document.querySelectorAll(`[data-progress-type="${kind}"]:not([data-progress-loaded])`)];if(!cards.length)return;
 cards.forEach(card=>card.dataset.progressLoaded='1');
 try{const ids=cards.map(card=>card.dataset.progressId),response=await privateApi(`/api/progress/${kind}?ids=${encodeURIComponent(ids.join(','))}`),byId=new Map(response.data.map(row=>[row.id,row]));
  for(const card of cards){const row=byId.get(card.dataset.progressId),slot=card.querySelector('[data-progress-slot]');if(!row||!slot)continue;const label=row.state==='familiar'?'已熟悉':'学习中';slot.innerHTML=`<span class="progress-pill ${row.state}">${label} · ${row.correct_count}/${row.attempts}</span>`;}
 }catch{}
}

let vocabOverlayClosing=false,vocabOverlayScroll=0;
function vocabularyOverlayContent(x){const examples=x.examples.map(e=>`<div class="example"><p lang="${x.language}">${reading(e.text,e.readings)}</p><p>${esc(e.translation_zh)}</p>${e.note_zh?`<small>${esc(e.note_zh)}</small>`:''}</div>`).join('');return `<h2 id="preview-title" class="lexeme" lang="${x.language}">${esc(x.lemma)}</h2>${x.ipa||x.reading?`<p class="pronunciation">${esc(x.ipa?'/'+x.ipa+'/':x.reading)}</p>`:''}<p>${badge(fullPos(x.language,x.part_of_speech))} ${badge(registerNames[x.register]||x.register)}</p>${section('完整意思与用法',x.senses.map(s=>`<article class="sense"><h3>${esc(s.meaning_zh)}</h3><p>${esc(s.usage_zh)}</p>${s.register_note?`<p class="muted">${esc(s.register_note)}</p>`:''}</article>`).join(''))}${section('搭配、结构与例句',examples)}${section('相关词汇',relationCards(x.relations,'vocabulary'))}<a class="button" href="${detail('vocabulary',x.id,x.language)}">打开独立详情页</a>`;}
async function openVocabularyOverlay(id,push=true,opener=null){const d=$('#preview'),body=$('#preview-body');vocabOverlayScroll=scrollY;sessionStorage.setItem('vocabulary-index-state',JSON.stringify({url:location.pathname+location.search,scroll:vocabOverlayScroll}));body.innerHTML='<p class="status" role="status">正在加载词汇详情…</p>';if(!d.open)d.showModal();if(push){const u=new URL(location.href);u.searchParams.set('detail',id);history.pushState({vocabularyOverlay:true},'',u);}try{const x=(await api('vocabulary/'+encodeURIComponent(id))).data;body.innerHTML=vocabularyOverlayContent(x);}catch(e){body.innerHTML=`<div class="error" role="alert"><h2 id="preview-title">详情暂时无法打开</h2><p>${esc(e.message)}</p></div>`;}d.addEventListener('close',()=>{if(vocabOverlayClosing)return;if(new URL(location.href).searchParams.has('detail')){vocabOverlayClosing=true;if(history.state?.vocabularyOverlay)history.back();else{const u=new URL(location.href);u.searchParams.delete('detail');history.replaceState(null,'',u);}setTimeout(()=>{scrollTo(0,vocabOverlayScroll);vocabOverlayClosing=false;opener?.focus();},0);}},{once:true});}
function bindVocabularyRows(){document.querySelectorAll('.vocab-row').forEach(a=>{if(a.dataset.bound)return;a.dataset.bound='1';a.onclick=e=>{if(e.button!==0||e.metaKey||e.ctrlKey||e.shiftKey||e.altKey)return;e.preventDefault();openVocabularyOverlay(a.dataset.vocabId,true,a);};});}
addEventListener('popstate',()=>{const d=$('#preview');if(d?.open&&!new URL(location.href).searchParams.has('detail')){vocabOverlayClosing=true;d.close();setTimeout(()=>{scrollTo(0,vocabOverlayScroll);vocabOverlayClosing=false;},0);}});
async function detailPage(kind){
 const x=(await api(kind+'/'+encodeURIComponent(p.id||''))).data;
 if(kind==='sentences')return sentencePage(x);
 const isV=kind==='vocabulary',title=isV?x.lemma:x.title_zh,lessonId=/^(?:en|ja)-s[1-6]-l[1-9]$/.test(p.lesson||'')?p.lesson:'';
 document.title=title+' · 言间';
 const examples=x.examples.map(e=>`<div class="example"><p class="reading" lang="${x.language}">${reading(e.text,e.readings)}</p><p>${esc(e.translation_zh)}</p>${e.note_zh||e.explanation_zh?`<small>${esc(e.note_zh||e.explanation_zh)}</small>`:''}</div>`);
 const content=isV?section('意思与用法',x.senses.map((s,i)=>`<article class="sense"><div class="sense-number">义项 ${i+1}</div><h3>${esc(s.meaning_zh)}</h3><p>${esc(s.usage_zh)}</p>${s.register_note?`<p class="muted">${esc(s.register_note)}</p>`:''}</article>`).join(''))+section('常见搭配与结构',examples.filter((e,i)=>x.examples[i].kind!=='example').join(''))+section('在例句中理解',examples.filter((e,i)=>x.examples[i].kind==='example').join(''))+section('相关与容易混淆的词',relationCards(x.relations,'vocabulary')):section('核心感觉',`<p>${esc(x.core_zh)}</p><p class="muted">${esc(x.purpose_zh)}</p>`)+section('基本结构',`<div class="formula" lang="${x.language}">${esc(x.formula)}</div>`)+section('什么时候使用',`<p>${esc(x.when_zh)}</p>`)+section('正式例句',examples.join(''))+dynamicExamplesPanel(x.id,lessonId)+section('常见错误',x.mistakes_zh?`<p>${esc(x.mistakes_zh)}</p>`:'')+section('细微差别',x.nuance_zh?`<p>${esc(x.nuance_zh)}</p>`:'')+section('建议先了解',x.prerequisites.length?'<p class="muted">只是学习建议，可以直接学习当前语法。</p>'+relationCards(x.prerequisites,'grammar'):'')+section('相关语法与对比',relationCards(x.relations,'grammar'))+section('接下来可以探索',relationCards(x.recommended_for,'grammar'));
 const prompt=isV?`根据中文“${x.senses[0]?.meaning_zh||'这个意思'}”，写出${langName(x.language)}词汇。`:`根据“${x.title_zh}”，写出目标语法形式。`;
 const selfCheck=`<section class="card learning-check" data-learning-check><h2>快速自测</h2><p>${esc(prompt)}</p><div data-check-body><p class="muted">正在确认登录状态…</p></div></section>`;
 $('#main').innerHTML=`<div class="breadcrumb"><a href="/">首页</a> / <a href="${url(kind,{lang:x.language})}">${names[kind]}库</a> / ${esc(title)}</div><div class="page-heading"><div class="eyebrow">${langName(x.language)} · ${names[kind]}</div><h1 lang="${isV?x.language:'zh-CN'}">${esc(title)}</h1>${isV?`<p class="pronunciation">${esc(x.ipa?'/'+x.ipa+'/':x.reading)}</p>`:`<p lang="${x.language}">${esc(x.form_name)}</p>`}<div class="chips">${badge((isV?'Stage ':'Level ')+(x.stage||x.level))}${isV?badge(posNames[x.part_of_speech]||x.part_of_speech):''}${badge(registerNames[x.register]||x.register)}</div></div><div class="detail-layout"><div class="detail-main">${content}${section('在这些表达中出现',x.sentences.data.length?reverseCards(x.sentences.data)+`<div id="reverse-more"></div>${x.sentences.pagination.has_more?'<button id="load-reverse">加载更多表达</button>':''}`:'<p class="muted">暂时没有关联表达。</p>')}</div><aside class="detail-aside">${selfCheck}${section('从理解到使用',`<p class="muted">带着当前${names[kind]}询问 AI Tutor。</p>${aiLink(kind,x.id,x.language)}`)}<div class="card"><h2>继续探索</h2><a class="text-link" href="${url(kind,{lang:x.language})}">返回${names[kind]}库 →</a></div></aside></div>`;
 bindLearningCheck(kind,x);
 bindDynamicExamples($('#main'));
 if($('#load-reverse')){let offset=x.sentences.pagination.next_offset;$('#load-reverse').onclick=async()=>{const b=$('#load-reverse');b.disabled=true;try{const r=await api(`${kind}/${x.id}/sentences?limit=10&offset=${offset}`);$('#reverse-more').insertAdjacentHTML('beforeend',reverseCards(r.data));offset=r.pagination.next_offset;b.hidden=!r.pagination.has_more;}catch{b.textContent='加载失败，点击重试';}finally{b.disabled=false;}};}
}

async function bindLearningCheck(kind,x){
 const root=$('[data-learning-check]'),body=root&&$('[data-check-body]',root),signedIn=await account();if(!root)return;
 if(!signedIn.authenticated){body.innerHTML='<p class="muted">登录后可以保存真实答题记录。</p><a class="button" href="/auth.html">登录并开始记录</a>';return;}
 body.innerHTML=`<form data-check-form><label for="learning-answer">你的答案</label><input id="learning-answer" autocomplete="off" maxlength="200" required><button class="primary" type="submit">提交答案</button><p class="check-status" role="status" aria-live="polite"></p></form>`;
 const form=$('[data-check-form]',root),status=$('.check-status',form);let attemptId=null;
 form.onsubmit=async event=>{event.preventDefault();const answer=$('#learning-answer',form).value.trim(),button=$('button',form);if(!answer)return;attemptId ||= crypto.randomUUID().replaceAll('-','');button.disabled=true;status.className='check-status';status.textContent='正在核对…';
  try{const response=await privateApi('/api/learning/attempt',{method:'POST',body:JSON.stringify({attempt_id:attemptId,content_type:kind,content_id:x.id,answer})}),result=response.data;status.classList.add(result.correct?'success':'wrong');status.textContent=result.correct?`回答正确。累计 ${result.progress.correct_count} / ${result.progress.attempts} 次正确。`:`这次还不对。参考答案：${result.expected_answer}。累计 ${result.progress.correct_count} / ${result.progress.attempts} 次正确。`;attemptId=null;}
  catch(error){status.classList.add('wrong');status.textContent=error.message+' 再次提交会安全重试，不会重复计数。';}finally{button.disabled=false;}
 };
}
const difficulty=e=>`<div class="difficulty"><span>词汇 ${e.vocabulary_difficulty} / 6</span><span>语法 ${e.grammar_difficulty} / 6</span><span>综合 ${e.overall_difficulty} / 6</span></div><details><summary>理解这些难度</summary><p class="muted">${esc(e.difficulty_note_zh)} 各语言独立评定，不是你的能力分数。</p></details>`;
let chunkActions=[];
function chunkButton(text,links,language){const index=chunkActions.push({links,language})-1;return `<button class="chunk" data-chunk="${index}" aria-label="查看 ${esc(text)} 的词汇或语法">${esc(text)}</button>`;}
function interactiveText(text,e,turnId=null){
 const links=[...e.vocabulary_links.map(l=>({...l,domain:'vocabulary',target:l.item_id})),...e.grammar_links.map(l=>({...l,domain:'grammar',target:l.grammar_id}))].filter(l=>l.turn_id===turnId);
 const spans=links.map(l=>{let start=-1;for(let i=0;i<l.occurrence;i++){start=text.indexOf(l.displayed_form,start<0?0:start+l.displayed_form.length);if(start<0)return null;}return {start,end:start+l.displayed_form.length,links:[l]};}).filter(Boolean).sort((a,b)=>a.start-b.start||b.end-a.end);
 const merged=[];for(const s of spans){const last=merged.at(-1);if(last&&s.start<last.end){last.end=Math.max(last.end,s.end);last.links.push(...s.links);}else merged.push(s);}
 let at=0,result='';for(const s of merged){result+=esc(text.slice(at,s.start))+chunkButton(text.slice(s.start,s.end),s.links,e.language);at=s.end;}return result+esc(text.slice(at));
}
async function sentencePage(x){
 chunkActions=[];const related=(await api('sentences?topic='+encodeURIComponent(x.topic_id)+'&language='+lang+'&limit=6')).data.filter(s=>s.id!==x.id);
 $('#main').innerHTML=`<div class="breadcrumb"><a href="/sentences.html">句子与表达</a> / ${esc(x.anchor_zh)}</div>${heading('Meaning first',x.anchor_zh,'同一个中文意思，两种语言各自自然表达。')}${x.context_zh?`<div class="context"><strong>情境</strong><p>${esc(x.context_zh)}</p></div>`:''}<div class="grid two">${x.expressions.map(e=>`<section class="card"><div class="section-head"><h2>${langName(e.language)}</h2>${badge(e.is_primary?'主要表达':'另一种说法')}</div>${x.unit_type==='dialogue'?e.turns.map(t=>`<div class="turn"><span class="speaker">${esc(t.speaker)}</span><div><div class="expression" lang="${e.language}">${interactiveText(t.text,e,t.id)}</div>${e.language==='ja'?`<details><summary>查看读音</summary><p class="reading" lang="ja">${reading(t.text,t.readings)}</p></details>`:''}</div></div>`).join(''):`<div class="expression" lang="${e.language}">${interactiveText(e.text,e)}</div>${e.ipa?`<p class="pronunciation">${esc(e.ipa)}</p>`:''}${e.language==='ja'?`<details><summary>查看读音 / 振假名</summary><p class="reading" lang="ja">${reading(e.text,e.readings)}</p></details>`:''}`}${difficulty(e)}<p class="muted">${esc(registerNames[e.register]||e.register)}${e.note_zh?' · '+esc(e.note_zh):''}</p><div class="link-group"><h3>用到的词汇</h3><div class="chips">${e.vocabulary_links.map(l=>{const i=chunkActions.push({links:[{...l,domain:'vocabulary',target:l.item_id}],language:e.language})-1;return `<button data-chunk="${i}">${esc(l.lemma)}</button>`;}).join('')||'<span class="muted">暂无标注</span>'}</div></div><div class="link-group"><h3>用到的语法</h3><div class="chips">${e.grammar_links.map(l=>{const i=chunkActions.push({links:[{...l,domain:'grammar',target:l.grammar_id}],language:e.language})-1;return `<button data-chunk="${i}">${esc(l.title_zh)}</button>`;}).join('')||'<span class="muted">暂无标注</span>'}</div></div><div class="section">${aiLink('sentences',x.id,e.language)}</div></section>`).join('')}</div><div class="section">${section('英语 × 日语：表达的区别',`<p>${esc(x.comparison_zh||'从交际意图理解，不把两种语言逐词对齐。')}</p>`)}</div><section class="section"><h2>同一主题，再看一句</h2><div class="grid">${related.map(s=>listCard('sentences',s)).join('')||'<p class="muted">当前主题暂无其他示例。</p>'}</div></section>`;
 document.querySelectorAll('[data-chunk]').forEach(b=>b.onclick=()=>{const action=chunkActions[Number(b.dataset.chunk)];preview(`<h2 id="preview-title">这段表达怎么理解</h2>${action.links.map(l=>`<article class="sense">${badge(names[l.domain])}<h3>${esc(l.lemma||l.title_zh||l.displayed_form)}</h3><p>${esc(l.meaning_zh||l.note_zh||'在当前表达中使用这个结构。')}</p><p class="muted">原文：${esc(l.displayed_form)}</p><a class="button primary" href="${detail(l.domain,l.target,action.language)}">查看${names[l.domain]}详情 →</a></article>`).join('')}`);});
}
async function academicHub(){
 const targetLinks=(pageName,key,targets,prefix='')=>`<div class="target-links">${targets.map(t=>`<a class="button" href="${esc(url(pageName,{[key]:t}))}">${prefix}${esc(t)}</a>`).join('')}</div>`;
 $('#main').innerHTML=heading('Choose your goal','学术与考试','选择学习目标，直接开始学习。')+`<div class="grid two academic-goals"><section class="goal-hero"><div class="eyebrow">English</div><h2>IELTS</h2><p>选择目标分数</p>${targetLinks('ielts','target',['5.0','5.5','6.0','6.5','7.0+'])}</section><section class="goal-hero"><div class="eyebrow">日本語</div><h2>JLPT</h2><p>选择目标等级</p>${targetLinks('jlpt','level',['N5','N4','N3','N2','N1'])}</section></div><a class="about-link" href="/academic-about.html">关于考试目标</a>`;
}
async function academicAbout(){
 $('#main').innerHTML=`<div class="breadcrumb"><a href="/academic.html">学术 / 考试</a> / 关于考试目标</div>${heading('About these learning tracks','关于考试目标','了解课程范围、估计方式与数据来源。')}<section class="card prose"><h2>课程范围</h2><p>IELTS Band 词汇池是言间（JIJI）按词频、通用性与学术用途建立的累计课程目标，不是 IELTS 官方逐词表，也不构成成绩保证。</p><p>JLPT N5–N1 分组来自社区资料与课程估计。JLPT 官方不发布完整逐词表；边界词可能因资料与课程取舍而不同。</p><p>词汇 Stage、语法 Level 与表达难度仍各自独立，不与考试目标机械换算。</p></section><section class="card prose"><h2>词汇数据与署名</h2><p>英语批量词汇基于 ECDICT（MIT，© Linwei / skywind3000），经过 lemma、频率、噪声与重复清洗。日语词汇的社区等级来自 Jonathan Waller 数据，经 Japanese Language Data 整理；reading/POS 与中文释义来自 JMdict/EDRDG 与 Tomoshi Open Data Layer 的 CC BY-SA 4.0 数据。</p><p>批量词条只导入 headword、读音/音标、词性、简明释义、频率/课程分组；没有批量生成 AI 例句。原有人工审校 usages 与 examples 保持不变。</p><p><a href="https://github.com/skywind3000/ECDICT">ECDICT</a> · <a href="https://github.com/jkindrix/japanese-language-data">Japanese Language Data</a> · <a href="https://github.com/tomoshi-app/tomoshi-dict-data">Tomoshi Open Data</a> · <a href="https://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA 4.0</a></p></section><section class="card prose"><h2>内容状态</h2><p>原有 editorial alignment 继续作为人工推荐与排序信号；大型词汇池用于 discovery，不把社区估计表述成官方要求。</p></section><a class="button primary" href="/academic.html">返回选择学习目标</a>`;
}

const examDomains={vocabulary:'词汇',grammar:'语法',sentences:'句子与表达'};
const unitNames={sentence:'一句话',scenario:'情境',dialogue:'对话'};
const pageSize=24;
let examContext=null,detailOpener=null,overlayPushed=false,overlayRequest=0,examOverlayScroll=0;
const currentParams=()=>Object.fromEntries(new URLSearchParams(location.search));
const examUrl=(pageName,params)=>url(pageName,params);
function examCard(domain,a){
 const href=detail(domain,a.content_id,a.language);
 if(domain==='vocabulary'){
  return `<a class="vocab-row exam-card" data-detail="${esc(a.content_id)}" data-domain="vocabulary" href="${esc(href)}"><strong class="vocab-headword" lang="${a.language}">${esc(a.title)}${a.language==='ja'&&a.reading?`<span>（${esc(a.reading)}）</span>`:''}</strong><span class="vocab-pos">${esc(compactPos(a.language,a.part_of_speech))}</span><span class="vocab-meaning">${esc(a.meaning_zh)}</span><span class="vocab-arrow" aria-hidden="true">›</span></a>`;
 }
 if(domain==='grammar')return `<a class="card learner-card exam-card" data-detail="${esc(a.content_id)}" data-domain="grammar" href="${esc(href)}"><h2>${esc(a.title)}</h2><p class="form" lang="${a.language}">${esc(a.form_name)}</p><p class="meaning">${esc(a.purpose_zh)}</p><span class="text-link">查看详情 →</span></a>`;
 return `<a class="card learner-card exam-card" data-detail="${esc(a.content_id)}" data-domain="sentences" href="${esc(href)}"><div class="eyebrow">${esc(unitNames[a.unit_type]||'表达')}</div><h2>${esc(a.title)}</h2>${a.text?`<p class="expression-preview" lang="${a.language}">${esc(a.text)}</p>`:''}<span class="text-link">查看详情 →</span></a>`;
}
function ensureLessonDialog(){
 let dialog=$('#lesson-detail');
 if(dialog)return dialog;
 document.body.insertAdjacentHTML('beforeend','<dialog id="lesson-detail" class="lesson-sheet" aria-labelledby="lesson-detail-title"><div class="sheet-toolbar"><button class="sheet-close" type="button">← 返回内容列表</button></div><div class="sheet-body" aria-live="polite"></div></dialog>');
 dialog=$('#lesson-detail');
 $('.sheet-close',dialog).onclick=closeLesson;
 dialog.addEventListener('cancel',e=>{e.preventDefault();closeLesson();});
 dialog.addEventListener('click',e=>{const r=dialog.getBoundingClientRect();if(e.target===dialog&&(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom))closeLesson();});
 return dialog;
}
function closeLesson(){
 const dialog=$('#lesson-detail');
 if(!dialog?.open)return;
 if(overlayPushed){history.back();return;}
 const u=new URL(location.href);u.searchParams.delete('detail');u.searchParams.delete('detailType');history.replaceState(history.state,'',u);dialog.close();detailOpener?.focus();
}
const exampleHtml=(e,language)=>`<div class="example"><p class="reading" lang="${language}">${reading(e.text,e.readings)}</p>${e.translation_zh?`<p>${esc(e.translation_zh)}</p>`:''}${e.note_zh||e.explanation_zh?`<small>${esc(e.note_zh||e.explanation_zh)}</small>`:''}</div>`;
function overlayContent(domain,x,language){
 if(domain==='vocabulary')return `<div class="sheet-heading"><div class="eyebrow">${langName(x.language)} · 词汇</div><h2 id="lesson-detail-title" class="lexeme" lang="${x.language}">${esc(x.lemma)}</h2>${x.ipa||x.reading?`<p class="pronunciation">${esc(x.ipa?'/'+x.ipa+'/':x.reading)}</p>`:''}<p class="learner-meta">${esc(posNames[x.part_of_speech]||x.part_of_speech)} · ${esc(registerNames[x.register]||x.register)}</p></div>${section('意思与用法',x.senses.map(s=>`<article class="sense"><h3>${esc(s.meaning_zh)}</h3><p>${esc(s.usage_zh)}</p></article>`).join(''))}${section('常见搭配',x.examples.filter(e=>e.kind!=='example').map(e=>exampleHtml(e,x.language)).join(''))}${section('例句',x.examples.filter(e=>e.kind==='example').map(e=>exampleHtml(e,x.language)).join(''))}${section('相关词汇',relationCards(x.relations,'vocabulary'))}`;
 if(domain==='grammar')return `<div class="sheet-heading"><div class="eyebrow">${langName(x.language)} · 语法</div><h2 id="lesson-detail-title">${esc(x.title_zh)}</h2><p class="form" lang="${x.language}">${esc(x.form_name)}</p></div>${section('意思与功能',`<p>${esc(x.core_zh)}</p><p>${esc(x.purpose_zh)}</p>`)}${section('基本结构',`<div class="formula" lang="${x.language}">${esc(x.formula)}</div>`)}${section('什么时候使用',`<p>${esc(x.when_zh)}</p>`)}${section('例句',x.examples.map(e=>exampleHtml(e,x.language)).join(''))}${section('相关语法',relationCards(x.relations,'grammar'))}`;
 const expression=x.expressions.find(e=>e.language===language)||x.expressions[0];
 const body=expression?(x.unit_type==='dialogue'?expression.turns.map(t=>`<div class="turn"><span class="speaker">${esc(t.speaker)}</span><p class="expression-preview" lang="${expression.language}">${esc(t.text)}</p></div>`).join(''):`<p class="expression sheet-expression" lang="${expression.language}">${esc(expression.text)}</p>${expression.ipa?`<p class="pronunciation">${esc(expression.ipa)}</p>`:''}${expression.language==='ja'&&expression.readings?.length?`<p class="reading" lang="ja">${reading(expression.text,expression.readings)}</p>`:''}`):'';
 return `<div class="sheet-heading"><div class="eyebrow">${esc(unitNames[x.unit_type]||'表达')}</div><h2 id="lesson-detail-title">${esc(x.anchor_zh)}</h2></div>${x.context_zh?section('使用情境',`<p>${esc(x.context_zh)}</p>`):''}${section('完整表达',body)}${expression?section('词汇',`<div class="chips">${expression.vocabulary_links.map(l=>`<a class="button" href="${detail('vocabulary',l.item_id,expression.language)}">${esc(l.lemma)}</a>`).join('')||'<span class="muted">暂无标注</span>'}</div>`):''}${expression?section('语法',`<div class="chips">${expression.grammar_links.map(l=>`<a class="button" href="${detail('grammar',l.grammar_id,expression.language)}">${esc(l.title_zh)}</a>`).join('')||'<span class="muted">暂无标注</span>'}</div>`):''}`;
}
async function showLesson(domain,id,{push=false,opener=null}={}){
 const dialog=ensureLessonDialog(),body=$('.sheet-body',dialog),request=++overlayRequest;
 if(opener)detailOpener=opener;
 if(push){examOverlayScroll=scrollY;sessionStorage.setItem('exam-vocabulary-state',JSON.stringify({url:location.pathname+location.search,scroll:examOverlayScroll}));}
 body.innerHTML='<p class="status" role="status">正在加载详情…</p>';
 if(!dialog.open)dialog.showModal();
 if(push){const u=new URL(location.href);u.searchParams.set('detail',id);u.searchParams.set('detailType',domain);history.pushState({lesson:true},'',u);overlayPushed=true;}
 else overlayPushed=Boolean(history.state?.lesson);
 try{const x=(await api(domain+'/'+encodeURIComponent(id))).data;if(request!==overlayRequest)return;body.innerHTML=overlayContent(domain,x,examContext?.language||x.language);$('.sheet-close',dialog).textContent=`← 返回${examDomains[domain]}`;}
 catch(e){if(request!==overlayRequest)return;body.innerHTML=`<div class="error" role="alert"><h2 id="lesson-detail-title">详情暂时无法打开</h2><p>${esc(e.message)}</p></div>`;}
}
function bindExamCards(){document.querySelectorAll('.exam-card').forEach(a=>a.onclick=e=>{if(e.button!==0||e.metaKey||e.ctrlKey||e.shiftKey||e.altKey)return;e.preventDefault();showLesson(a.dataset.domain,a.dataset.detail,{push:true,opener:a});});}
function examFilters(domain,topics,key,target,language,browse=''){
 const hidden=`<input type="hidden" name="${key}" value="${esc(target)}"><input type="hidden" name="tab" value="${domain}">${browse?`<input type="hidden" name="browse" value="${esc(browse)}">`:''}`;
 const extra=domain==='vocabulary'?select('part_of_speech','词性',posTaxonomy[language]):domain==='sentences'?select('topic','主题',topics.map(t=>[t.id,topicName(t)]))+select('unit_type','表达类型',[['sentence','一句话'],['scenario','情境'],['dialogue','对话']]):'';
 return `<form class="filters exam-filters" method="get">${hidden}<div class="filter-row"><label class="search-label">搜索${examDomains[domain]}<input type="search" name="search" value="${esc(currentParams().search)}" placeholder="${domain==='vocabulary'?'输入词汇或中文意思':domain==='grammar'?'输入语法形式或功能':'输入中文意思或目标语言'}" maxlength="100"></label>${extra}<button class="primary" type="submit">搜索</button><a class="button" href="${esc(examUrl(page,{[key]:target,tab:domain}))}">清除</a></div></form>`;
}
async function exam(){
 if('scrollRestoration' in history)history.scrollRestoration='manual';
 const maxLoaded=500,state=currentParams(),framework=page==='ielts'?'IELTS':'JLPT',language=framework==='IELTS'?'en':'ja',targets=framework==='IELTS'?['5.0','5.5','6.0','6.5','7.0+']:['N5','N4','N3','N2','N1'],key=framework==='IELTS'?'target':'level',fallback=framework==='IELTS'?'6.5':'N4',target=targets.includes(state[key])?state[key]:fallback,domain=examDomains[state.tab]?state.tab:'vocabulary',shown=Math.max(pageSize,Math.min(maxLoaded,Number(state.shown)||pageSize));
 const browseGroups=language==='en'?'ABCDEFGHIJKLMNOPQRSTUVWXYZ#'.split(''):['あ行','か行','さ行','た行','な行','は行','ま行','や行','ら行','わ行','その他'],activeBrowse=domain==='vocabulary'&&!state.search&&browseGroups.includes(state.browse)?state.browse:'';
 const topics=domain==='sentences'?(await api('academic/topics')).data:[];
 const query={framework,target,domain};
 for(const k of ['search','part_of_speech','topic','unit_type'])if(state[k])query[k]=state[k];
 if(activeBrowse)query.browse=activeBrowse;
 const first={data:[],pagination:{limit:pageSize,offset:0,has_more:false,next_offset:null}};
 while(first.data.length<shown){const batch=await api('academic/alignments?'+new URLSearchParams({...query,limit:Math.min(100,shown-first.data.length),offset:first.data.length}));first.data.push(...batch.data);first.pagination=batch.pagination;first.pool=batch.pool;if(!batch.pagination.has_more||!batch.data.length)break;}
 examContext={framework,target,language,domain,key};
 const targetNav=`<nav class="pills target-nav" aria-label="${framework} 学习目标">${targets.map(t=>`<a class="${target===t?'active':''}" ${target===t?'aria-current="page"':''} href="${esc(examUrl(page,{[key]:t,tab:domain}))}">${framework==='IELTS'?'Band ':''}${esc(t)}</a>`).join('')}</nav>`;
 const tabs=`<nav class="tabs exam-tabs" aria-label="课程内容">${Object.entries(examDomains).map(([d,n])=>`<a class="${domain===d?'active':''}" role="tab" aria-selected="${domain===d}" href="${esc(examUrl(page,{[key]:target,tab:d}))}">${n}</a>`).join('')}</nav>`;
 const browseNav=domain==='vocabulary'?`<nav class="vocab-index-selector" aria-label="${language==='en'?'按英文字母浏览':'按五十音浏览'}">${browseGroups.map(g=>`<a class="${activeBrowse===g?'active':''}" ${activeBrowse===g?'aria-current="page"':''} href="${esc(examUrl(page,{[key]:target,tab:domain,...(state.part_of_speech?{part_of_speech:state.part_of_speech}:{}),browse:g}))}">${esc(g)}</a>`).join('')}</nav>`:'';
 const clear=examUrl(page,{[key]:target,tab:domain});
 const totalNote=Number.isInteger(first.pagination.total)?` / 共 ${first.pagination.total} 项`:'';
 $('#main').innerHTML=`<div class="breadcrumb"><a href="/academic.html">学术 / 考试</a> / ${framework}</div><header class="exam-heading"><div><div class="eyebrow">${language==='en'?'English':'日本語'}</div><h1>${framework} ${esc(target)}</h1></div><a class="about-link" href="/academic-about.html">关于考试目标</a></header>${targetNav}${tabs}${browseNav}${examFilters(domain,topics,key,target,language,activeBrowse)}${domain==='vocabulary'&&first.pool?.notice_zh?`<p class="results-note">${esc(first.pool.notice_zh)}</p>`:''}<p class="results-note" id="result-count" aria-live="polite">已显示 ${first.data.length}${totalNote}${first.pagination.has_more?'，可以继续加载':''}</p><div class="${domain==='vocabulary'?'vocab-index':'grid exam-grid'}" id="exam-results">${first.data.map(a=>examCard(domain,a)).join('')||`<div class="empty"><h2>还没有匹配的内容</h2><p>试试更换搜索或筛选条件。</p><a class="button" href="${esc(clear)}">清除筛选</a></div>`}</div>${first.pagination.has_more&&first.data.length<maxLoaded?'<div class="load-more-wrap"><button id="load-more" type="button">加载更多</button></div>':''}`;
 bindExamCards();
 const examForm=$('.exam-filters');examForm.addEventListener('submit',()=>{if(examForm.elements.search.value.trim())examForm.elements.browse?.remove();});
 if($('#load-more')){let offset=first.pagination.next_offset;$('#load-more').onclick=async()=>{const button=$('#load-more'),current=document.querySelectorAll('.exam-card').length;button.disabled=true;button.textContent='正在加载…';try{const more=await api('academic/alignments?'+new URLSearchParams({...query,limit:Math.min(pageSize,maxLoaded-current),offset}));$('#exam-results').insertAdjacentHTML('beforeend',more.data.map(a=>examCard(domain,a)).join(''));bindExamCards();offset=more.pagination.next_offset;const count=document.querySelectorAll('.exam-card').length,reached=count>=maxLoaded;button.hidden=!more.pagination.has_more||reached;button.textContent='加载更多';$('#result-count').textContent=`已显示 ${count}${Number.isInteger(more.pagination.total)?` / 共 ${more.pagination.total} 项`:''}${more.pagination.has_more&&!reached?'，可以继续加载':reached?'；请用索引、搜索或筛选继续定位':''}`;const u=new URL(location.href);u.searchParams.set('shown',String(count));history.replaceState(history.state,'',u);}catch(e){button.textContent='加载失败，点击重试';}finally{button.disabled=false;}};}
 const recommended=(await api('lessons/recommended?'+new URLSearchParams({framework,target}))).data;
 if(recommended.length)$('#main').insertAdjacentHTML('beforeend',`<section class="section exam-lessons"><div class="section-head"><div><div class="eyebrow">Recommended lessons</div><h2>相关站内课程</h2></div><span class="muted">根据当前学习目标推荐</span></div><div class="grid">${recommended.map(x=>`<a class="card" href="${url('lesson',{id:x.id,lang:x.language,stage:x.stage})}"><div class="eyebrow">${langName(x.language)} · Stage ${x.stage}</div><h3>${esc(x.title)}</h3><p>${esc(x.objective)}</p><span class="text-link">进入课程 →</span></a>`).join('')}</div></section>`);
 const detailId=state.detail,detailType=state.detailType;if(detailId&&examDomains[detailType])await showLesson(detailType,detailId);
}
const accuracy=value=>value==null?'—':value+'%';
const metricCard=(title,row)=>`<section class="card progress-metric"><div class="eyebrow">${title==='词汇'?'Vocabulary':'Grammar'}</div><h2>${title}</h2><dl><div><dt>已学习</dt><dd>${row.studied}</dd></div><div><dt>正确</dt><dd>${row.correct_count}</dd></div><div><dt>错误</dt><dd>${row.wrong_count}</dd></div><div><dt>正确率</dt><dd>${accuracy(row.accuracy)}</dd></div></dl></section>`;
const activityLink=item=>item.type==='lesson'?url('lesson',{id:item.id,lang:item.language}):detail(item.type,item.id,item.language);
async function progress(){
 const signedIn=await account();if(!signedIn.authenticated){$('#main').innerHTML=heading('Your learning, remembered','我的学习','登录后，词汇、语法与课程进度会分别安全保存。')+'<section class="card progress-empty"><h2>登录后查看学习记录</h2><p>未登录仍可浏览全部学习内容；只有真实答题和明确完成的课程会写入账户。</p><a class="button primary" href="/auth.html">邮箱验证码登录</a></section>';return;}
 const [summaryResponse,recentResponse,reviewResponse]=await Promise.all([privateApi('/api/progress/summary'),privateApi('/api/progress/recent?limit=8'),privateApi('/api/review/summary')]),s=summaryResponse.data,recent=recentResponse.data,review=reviewResponse.data,total=s.vocabulary.studied+s.grammar.studied+s.lessons.studied;
 if(!total){$('#main').innerHTML=heading('Your learning, remembered','我的学习','这里展示真实答题与课程完成记录。')+'<section class="card progress-empty"><h2>还没有学习记录，开始第一课吧。</h2><p>打开课程会记录为“进行中”；答题后才会产生正确或错误统计。</p><a class="button primary" href="/learn.html">开始第一课</a></section>';return;}
 const active=recent.find(item=>item.type==='lesson'&&item.status==='in_progress');
 const nextReview=review.next_review_at?new Date(review.next_review_at*1000).toLocaleString('zh-CN'):null;
 const reviewNote=review.total_due?`现在有 ${review.total_due} 项到期。` : nextReview?`下一次复习：${esc(nextReview)}`:review.has_learned?'现有记录将在下次答题后开始安排复习。':'还没有可复习的内容。';
 $('#main').innerHTML=heading('Your learning, remembered','我的学习',`今天已完成 ${s.today.attempts} 次真实答题。`)+`<section class="section callout review-dashboard"><div><div class="eyebrow">Spaced repetition</div><h2>待复习 <strong>${review.total_due}</strong></h2><p>词汇 ${review.vocabulary.due_count} · 语法 ${review.grammar.due_count}。${reviewNote}</p></div><a class="button primary" href="/review.html">${review.total_due?'开始复习':'查看复习计划'} →</a></section><div class="grid progress-summary">${metricCard('词汇',s.vocabulary)}${metricCard('语法',s.grammar)}<section class="card progress-metric"><div class="eyebrow">Lessons</div><h2>课程</h2><dl><div><dt>已完成</dt><dd>${s.lessons.completed}</dd></div><div><dt>进行中</dt><dd>${s.lessons.in_progress}</dd></div><div><dt>已打开</dt><dd>${s.lessons.studied}</dd></div></dl></section></div>${active?`<section class="section callout continue-learning"><div><div class="eyebrow">Continue learning</div><h2>${esc(active.title)}</h2><p>上次停在课程的“${esc(({overview:'概览',vocabulary:'词汇',grammar:'语法',expressions:'表达',scenario:'情境',practice:'练习'})[active.last_section_key]||'概览')}”。</p></div><a class="button primary" href="${esc(activityLink(active))}">继续学习 →</a></section>`:''}<section class="section"><div class="section-head"><h2>最近学习</h2><span class="muted">仅显示最近 ${recent.length} 项</span></div><div class="recent-activity">${recent.map(item=>`<a class="card" href="${esc(activityLink(item))}"><span>${item.type==='vocabulary'?'词汇':item.type==='grammar'?'语法':'课程'}</span><strong>${esc(item.title)}</strong><small>${item.result==='correct'?'回答正确':item.result==='wrong'?'回答错误':item.status==='completed'?'已完成':'进行中'} · ${new Date(item.activity_at*1000).toLocaleDateString('zh-CN')}</small></a>`).join('')}</div></section>`;
}

async function review(){
 const signedIn=await account();if(!signedIn.authenticated){$('#main').innerHTML=heading('Review what matters','到期复习','登录后查看属于你的词汇与语法复习队列。')+'<section class="card progress-empty"><h2>登录后开始复习</h2><a class="button primary" href="/auth.html">邮箱验证码登录</a></section>';return;}
 const [summaryResponse,queueResponse]=await Promise.all([privateApi('/api/review/summary'),privateApi('/api/review/queue?limit=20')]),summary=summaryResponse.data,items=queueResponse.data;
 if(!items.length){const noLearning=!summary.has_learned,message=noLearning?'还没有可复习的内容。先去学习一些词汇或语法吧。':'今天暂时没有到期复习内容。',next=summary.next_review_at?`<p>下一次复习：${esc(new Date(summary.next_review_at*1000).toLocaleString('zh-CN'))}</p>`:'';$('#main').innerHTML=heading('Review what matters','到期复习','按服务器时间安排，已经到期的内容会一直保留。')+`<section class="card progress-empty"><h2>${message}</h2>${next}<a class="button primary" href="${noLearning?'/learn.html':'/progress.html'}">${noLearning?'去学习':'返回我的学习'}</a></section>`;return;}
 let index=0;
 const render=()=>{const item=items[index],remaining=items.length-index;if(!item){$('#main').innerHTML=heading('Review complete','本轮复习完成','刚才答错的内容会在 10 分钟后重新到期，不会在本轮无限循环。')+'<section class="card review-complete"><h2>当前到期内容已复习完毕。</h2><p>你的下一次复习时间以服务器记录为准。</p><a class="button primary" href="/progress.html">返回我的学习</a></section>';return;}
  const prompt=item.type==='vocabulary'?`根据中文“${item.prompt}”，写出${langName(item.language)}词汇。`:`根据“${item.prompt}”，写出目标语法形式。`;
  $('#main').innerHTML=heading('Due review','到期复习',`本轮剩余 ${remaining} 项；队列只包含已经到期的学习记录。`)+`<section class="review-shell card" data-review-item><div class="review-meta"><span class="badge">${item.type==='vocabulary'?'词汇':'语法'}</span><span>${langName(item.language)}</span><span>第 ${index+1} / ${items.length} 项</span></div><h2>${esc(prompt)}</h2><form id="review-form"><label for="review-answer">你的答案</label><input id="review-answer" autocomplete="off" maxlength="200" required autofocus><button class="primary" type="submit">提交答案</button><p class="check-status" role="status" aria-live="polite"></p></form><button id="review-next" type="button" hidden>下一项 →</button></section>`;
  const form=$('#review-form'),status=$('.check-status',form),next=$('#review-next');let attemptId=null;
  form.onsubmit=async event=>{event.preventDefault();const answer=$('#review-answer',form).value.trim(),button=$('button',form);if(!answer)return;attemptId ||= crypto.randomUUID().replaceAll('-','');button.disabled=true;status.textContent='正在核对…';status.className='check-status';try{const result=(await privateApi('/api/learning/attempt',{method:'POST',body:JSON.stringify({attempt_id:attemptId,content_type:item.type,content_id:item.id,answer})})).data;status.classList.add(result.correct?'success':'wrong');status.textContent=result.correct?`回答正确。下一次复习将在 ${new Date(result.progress.next_review_at*1000).toLocaleString('zh-CN')}。`:`这次还不对。参考答案：${result.expected_answer}。10 分钟后再复习。`;form.querySelector('input').disabled=true;button.hidden=true;next.hidden=false;next.focus();}catch(error){status.classList.add('wrong');status.textContent=error.message+' 再次提交会安全重试，不会重复计数。';button.disabled=false;}};
  next.onclick=()=>{index++;render();};
 };render();
}
async function ai(){
 const stored=localStorage.getItem('yanjian.ai.language.v1'),language=['en','ja'].includes(p.lang)?p.lang:['en','ja'].includes(stored)?stored:'en';let context=null,label='',returnHref='';
 if(p.type||p.id){if(!['lesson','vocabulary','grammar','sentences'].includes(p.type)||!p.id||!['en','ja'].includes(p.lang))throw Error('Tutor 上下文无效，请从学习内容重新进入。');
  if(p.type==='lesson'){
   const lesson=(await api('lessons/'+encodeURIComponent(p.id))).data;if(lesson.language!==language)throw Error('Tutor 语言与课程不一致。');
   const focusType=['vocabulary','grammar','expression'].includes(p.focus_type)?p.focus_type:null,focusId=p.focus_id||null;if(Boolean(focusType)!==Boolean(focusId))throw Error('Tutor 课程焦点无效。');
   if(focusType){const items=focusType==='expression'?lesson.expressions:lesson[focusType],focus=items.find(x=>x.id===focusId);if(!focus)throw Error('Tutor 课程焦点无效。');label=`${langName(language)} · Stage ${lesson.stage} · ${lesson.title} · ${focusType==='vocabulary'?'Vocabulary: '+focus.lemma:focusType==='grammar'?'Grammar: '+focus.form_name:'Expression: '+focus.text}`;context={type:'lesson',id:p.id,focus_type:focusType,focus_id:focusId};}
   else{label=`${langName(language)} · Stage ${lesson.stage} · ${lesson.title}`;context={type:'lesson',id:p.id};}returnHref=url('lesson',{id:lesson.id,lang:language,stage:lesson.stage});
  }else{
   const item=(await api(p.type+'/'+encodeURIComponent(p.id))).data;if(p.type!=='sentences'&&item.language!==language)throw Error('Tutor 语言与内容不一致。');if(p.type==='sentences'&&!item.expressions.some(e=>e.language===language))throw Error('此内容没有所选语言表达。');context={type:p.type,id:p.id};label=p.type==='vocabulary'?`Vocabulary: ${item.lemma}`:p.type==='grammar'?`Grammar: ${item.form_name}`:`Expression: ${item.anchor_zh}`;returnHref=detail(p.type,p.id,language);
  }
 }
 renderTutor({language,context,label,returnHref});
}
window.addEventListener('popstate',()=>{
 if(!['ielts','jlpt'].includes(page))return;
 const state=currentParams(),dialog=$('#lesson-detail');
 if(state.detail&&examDomains[state.detailType])showLesson(state.detailType,state.detail);
 else if(dialog?.open){overlayPushed=false;dialog.close();setTimeout(()=>{scrollTo(0,examOverlayScroll);detailOpener?.focus();},0);}
});
load(()=>page==='index'?home():['vocabulary','grammar','sentences'].includes(page)?library(page):page==='vocabulary-detail'?detailPage('vocabulary'):page==='grammar-detail'?detailPage('grammar'):page==='sentence'?detailPage('sentences'):page==='academic'?academicHub():page==='academic-about'?academicAbout():['ielts','jlpt'].includes(page)?exam():page==='progress'?progress():page==='review'?review():ai());

