import {$,esc,url,detail,langName,badge,heading,reading,api,shell,section,account,privateApi} from './shared.js';
import {dynamicExamplesPanel,bindDynamicExamples} from './ai-examples.js';

const page=document.body.dataset.page,p=Object.fromEntries(new URLSearchParams(location.search));
const lang=p.lang==='ja'?'ja':'en',stage=/^[1-6]$/.test(p.stage||'')?Number(p.stage):1;
shell('learn');
const returnKey='yanjian.lesson-path.return.v1';
const steps=[['overview','概览'],['vocabulary','词汇'],['grammar','语法'],['expressions','表达'],['scenario','情境'],['practice','练习']];
const languageNav=()=>`<div class="pills" aria-label="学习语言">${['en','ja'].map(l=>`<a class="${lang===l?'active':''}" href="${url('learn',{lang:l,stage:1})}">${langName(l)}</a>`).join('')}</div>`;
const stageNav=()=>`<nav class="stage-path" aria-label="学习阶段">${[1,2,3,4,5,6].map(n=>`<a class="${stage===n?'active':''}" ${stage===n?'aria-current="page"':''} href="${url('learn',{lang,stage:n})}"><small>Stage</small><strong>${n}</strong></a>`).join('')}</nav>`;

async function list(){
 const result=await api(`lessons?language=${lang}&stage=${stage}`);
 document.title=`${langName(lang)} Stage ${stage} · 学习路径`;
 $('#main').innerHTML=heading('Learning path','逐课学习，逐步表达',`${langName(lang)} 有独立的课程顺序。每课约 10–20 分钟，从词汇和结构走向真实表达。`)+languageNav()+stageNav()+`<div class="section-head lesson-list-head"><div><div class="eyebrow">${langName(lang)} · Stage ${stage}</div><h2>本阶段课程</h2></div><a class="button" href="/vocabulary.html?lang=${lang}">Library / 自由探索</a></div><div class="lesson-grid">${result.data.map((x,i)=>`<a class="card lesson-card" data-lesson data-lesson-id="${esc(x.id)}" href="${url('lesson',{id:x.id,lang,stage})}"><div class="lesson-number">${String(i+1).padStart(2,'0')}</div><div><div class="eyebrow">${esc(x.topic)}</div><h2>${esc(x.title)}</h2><p>${esc(x.objective)}</p><div class="lesson-size"><span>约 ${x.estimated_minutes} 分钟</span><span>${x.vocabulary_count} 词汇</span><span>${x.grammar_count} 语法</span><span>${x.expression_count} 表达</span><span data-lesson-progress></span></div></div><span class="lesson-arrow" aria-hidden="true">→</span></a>`).join('')}</div><section class="section library-strip"><div><div class="eyebrow">Library / Explore</div><h2>想自由查阅？内容库仍然保留</h2><p>按阶段、主题或关键词探索词汇、语法与表达，不影响课程路径。</p></div><div class="actions"><a class="button" href="/vocabulary.html?lang=${lang}">词汇</a><a class="button" href="/grammar.html?lang=${lang}">语法</a><a class="button" href="/sentences.html?lang=${lang}">表达</a></div></section>`;
 document.querySelectorAll('[data-lesson]').forEach(a=>a.addEventListener('click',()=>sessionStorage.setItem(returnKey,JSON.stringify({url:location.pathname+location.search,scrollY}))));
 decorateLessonList(result.data.map(x=>x.id));
 try{const saved=JSON.parse(sessionStorage.getItem(returnKey)||'null');if(saved?.url===location.pathname+location.search){requestAnimationFrame(()=>scrollTo(0,Number(saved.scrollY)||0));sessionStorage.removeItem(returnKey);}}catch{}
}

async function decorateLessonList(ids){
 if(!(await account()).authenticated)return;
 try{const response=await privateApi('/api/progress/lessons?ids='+encodeURIComponent(ids.join(','))),byId=new Map(response.data.map(row=>[row.id,row]));for(const card of document.querySelectorAll('[data-lesson-id]')){const row=byId.get(card.dataset.lessonId),slot=$('[data-lesson-progress]',card);if(row)slot.innerHTML=`<span class="progress-pill ${row.status}">${row.status==='completed'?'已完成':'进行中'}</span>`;}}catch{}
}

const role=x=>x.role==='required'?badge('本课重点','lesson-required'):badge(x.role==='exposure'?'接触了解':'辅助理解','lesson-support');
const itemButton=(type,x,body)=>`<div class="lesson-item-row"><button class="lesson-item" data-type="${type}" data-id="${esc(x.id)}" type="button">${body}<span>${role(x)} <span aria-hidden="true">↗</span></span></button><a class="button lesson-ask-ai" href="${url('ai',{type:'lesson',id:p.id,lang,focus_type:type,focus_id:x.id})}">问 AI</a></div>`;
const vocabulary=items=>items.map(x=>itemButton('vocabulary',x,`<span><strong lang="${x.language}">${esc(x.lemma)}</strong><small>${esc(x.ipa?'/'+x.ipa+'/':x.reading||'')} · ${esc(x.meaning_zh)}</small></span>`)).join('');
const grammar=items=>items.map(x=>itemButton('grammar',x,`<span><strong>${esc(x.title_zh)}</strong><small lang="${x.language}">${esc(x.form_name)}</small></span>`)).join('');
const expressionCard=x=>itemButton('expression',x,`<span><strong>${esc(x.anchor_zh)}</strong><small lang="${x.language}">${reading(x.text,x.readings)}</small></span>`);
const panel=(id,body,active)=>`<section class="lesson-panel" role="tabpanel" data-panel="${id}" ${id===active?'':'hidden'}>${body}</section>`;

async function lesson(){
 if(!/^(en|ja)-s[1-6]-l[1-9]$/.test(p.id||''))throw Error('课程编号无效。');
 const x=(await api('lessons/'+encodeURIComponent(p.id))).data,scenarios=x.expressions.filter(e=>e.unit_type!=='sentence'),plain=x.expressions.filter(e=>e.unit_type==='sentence'),signedIn=await account();
 let remote=null;if(signedIn.authenticated){try{remote=(await privateApi(`/api/lessons/${encodeURIComponent(x.id)}/start`,{method:'POST',body:'{}'})).data;}catch{}}
 let saved=null;try{saved=JSON.parse(sessionStorage.getItem(`yanjian.lesson.${x.id}`)||'null');}catch{}const preferred=remote?.last_section_key||saved?.step,initial=steps.some(([id])=>id===preferred)?preferred:'overview';
 const listUrl=url('learn',{lang:x.language,stage:x.stage});document.title=x.title+' · 言间';
 $('#main').innerHTML=`<div class="breadcrumb"><a href="/">首页</a><span>/</span><a data-return-list href="${listUrl}">${langName(x.language)} Stage ${x.stage}</a><span>/</span><span>Lesson ${x.sequence}</span></div><header class="lesson-hero"><div><div class="eyebrow">${langName(x.language)} · Stage ${x.stage} · Lesson ${x.sequence}</div><h1>${esc(x.title)}</h1><p><strong>学完你能：</strong>${esc(x.objective)}</p></div><div class="lesson-estimate"><strong>${x.estimated_minutes}</strong><span>分钟核心学习</span></div></header><nav class="lesson-stepper" aria-label="课程步骤" role="tablist">${steps.map(([id,n],i)=>`<button type="button" role="tab" data-step="${id}" aria-selected="${id===initial}" tabindex="${id===initial?'0':'-1'}"><span>${i+1}</span>${n}</button>`).join('')}</nav><div class="lesson-panels">${panel('overview',overview(x),initial)}${panel('vocabulary',`<div class="section-intro"><h2>本课词汇</h2><p>先抓住沟通目标需要的核心词；“辅助理解”无需现在强记。</p></div><div class="lesson-items">${vocabulary(x.vocabulary)}</div>`,initial)}${panel('grammar',`<div class="section-intro"><h2>本课语法</h2><p>这些结构来自本课表达。点击查看核心感觉和真实例句。</p></div><div class="lesson-items">${grammar(x.grammar)}</div>`,initial)}${panel('expressions',`<div class="section-intro"><h2>自然表达</h2><p>把词汇和结构放回真正会说的话里。</p></div><div class="lesson-items">${plain.map(expressionCard).join('')||'<p class="muted">本课表达集中在情境环节。</p>'}</div>`,initial)}${panel('scenario',`<div class="section-intro"><h2>情境与对话</h2><p>留意人物、目的和语气，不必把每个附带结构都当成重点。</p></div>${scenarios.map(scenario).join('')||'<div class="empty compact"><h2>情境练习</h2><p>本课使用短句组合练习，独立对话将在后续课程出现。</p></div>'}`,initial)}${panel('practice',practice(x),initial)}</div><div class="lesson-controls"><button id="previous-step" type="button">← 上一步</button><span id="step-status" class="muted" aria-live="polite"></span><button id="next-step" class="primary" type="button">下一步 →</button></div><nav class="lesson-neighbors" aria-label="相邻课程">${x.previous?`<a class="button" href="${url('lesson',{id:x.previous.id,lang:x.language,stage:x.previous.stage})}">← ${esc(x.previous.title)}</a>`:'<span></span>'}${x.next?`<a class="button" href="${url('lesson',{id:x.next.id,lang:x.language,stage:x.next.stage})}">${esc(x.next.title)} →</a>`:`<a class="button" href="${listUrl}">返回课程列表</a>`}</nav>`;
 let active=steps.findIndex(([id])=>id===initial),completed=remote?.status==='completed';
 const show=(i,scroll=true)=>{active=Math.max(0,Math.min(steps.length-1,i));document.querySelectorAll('[data-step]').forEach((b,n)=>{b.setAttribute('aria-selected',String(n===active));b.tabIndex=n===active?0:-1;});document.querySelectorAll('[data-panel]').forEach((el,n)=>el.hidden=n!==active);$('#previous-step').disabled=active===0;$('#next-step').textContent=active===steps.length-1?(completed?'已完成 · 返回课程列表':'完成课程 ✓'):'下一步 →';$('#step-status').textContent=`${active+1} / ${steps.length} · ${steps[active][1]}`;sessionStorage.setItem(`yanjian.lesson.${x.id}`,JSON.stringify({step:steps[active][0]}));if(scroll){if(signedIn.authenticated&&!completed)privateApi(`/api/lessons/${encodeURIComponent(x.id)}/position`,{method:'POST',body:JSON.stringify({section_key:steps[active][0]})}).catch(()=>{});scrollTo({top:Math.max(0,document.querySelector('.lesson-stepper').offsetTop-12),behavior:'smooth'});}};
 document.querySelectorAll('[data-step]').forEach((b,i)=>{b.onclick=()=>show(i);b.onkeydown=e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();const n=e.key==='Home'?0:e.key==='End'?steps.length-1:e.key==='ArrowLeft'?(i+steps.length-1)%steps.length:(i+1)%steps.length;show(n);document.querySelectorAll('[data-step]')[n].focus();}};});
 $('#previous-step').onclick=()=>show(active-1);$('#next-step').onclick=async()=>{if(active!==steps.length-1){show(active+1);return;}if(!signedIn.authenticated||completed){location.assign(listUrl);return;}const button=$('#next-step');button.disabled=true;button.textContent='正在完成…';try{remote=(await privateApi(`/api/lessons/${encodeURIComponent(x.id)}/complete`,{method:'POST',body:'{}'})).data;completed=remote.status==='completed';show(active,false);$('#step-status').textContent='课程已完成，学习记录已保存。';}catch(error){$('#step-status').textContent=error.message;button.textContent='重试完成课程';}finally{button.disabled=false;}};
 document.querySelectorAll('.lesson-item,.practice-grid button').forEach(b=>b.onclick=()=>openItem(b.dataset.type,b.dataset.id,x));show(active,false);
}

const overview=x=>`<div class="overview-grid"><section class="card"><div class="eyebrow">What you'll learn</div><h2>${esc(x.objective)}</h2><p>围绕“${esc(x.topic)}”完成一段可实际使用的交流。</p></section><section class="card lesson-map"><h2>本课路线</h2><ol><li>${x.vocabulary_count} 个词汇</li><li>${x.grammar_count} 个语法点</li><li>${x.expression_count} 个表达</li><li>${x.scenario_count?x.scenario_count+' 个情境 / 对话':'短句情境练习'}</li><li>复习入口</li></ol></section></div><p class="notice">“本课重点”建议掌握；“辅助理解 / 接触了解”用于保持表达自然，不要求本课立即掌握。</p>`;
function scenario(x){const body=x.dialogue?.length?`<div class="dialogue">${x.dialogue.map(t=>`<div class="turn"><strong>${esc(t.speaker)}</strong><p lang="${x.language}">${reading(t.text,t.readings)}</p></div>`).join('')}</div>`:`<p class="scenario-expression" lang="${x.language}">${reading(x.text,x.readings)}</p>`;return `<article class="card scenario-card"><div class="eyebrow">${x.unit_type==='dialogue'?'Dialogue':'Scenario'}</div><h2>${esc(x.anchor_zh)}</h2>${x.context_zh?`<p>${esc(x.context_zh)}</p>`:''}${body}</article>`;}
function practice(x){const v=x.vocabulary[0],g=x.grammar[0],e=x.expressions[0];return `<div class="section-intro"><h2>练习与复习</h2><p>回看本课重点，也可以带着整课上下文询问 AI Tutor。</p></div><div class="practice-grid"><button class="card" data-type="vocabulary" data-id="${esc(v?.id)}" ${v?'':'disabled'}><strong>词义识别</strong><span>回看核心词及例句</span></button><button class="card" data-type="grammar" data-id="${esc(g?.id)}" ${g?'':'disabled'}><strong>结构选择</strong><span>理解功能与常见错误</span></button><button class="card" data-type="expression" data-id="${esc(e?.id)}" ${e?'':'disabled'}><strong>表达识别</strong><span>从中文目标回忆表达</span></button><a class="card" href="${url('ai',{type:'lesson',id:x.id,lang:x.language})}"><strong>问 AI Tutor</strong><span>带入本课词汇、语法与表达</span></a></div><p class="notice">完成课程需要点击下方“完成课程”。这里的回看按钮不虚构答题结果，AI Tutor 也不会写入学习进度。</p>`;}

async function openItem(type,id,lesson){
 if(!id)return;const d=$('#preview'),body=$('#preview-body');body.innerHTML='<p role="status">正在加载详情…</p>';d.showModal();
 try{if(type==='expression'){const x=lesson.expressions.find(e=>e.id===id);body.innerHTML=`<div class="eyebrow">本课表达 · ${esc(x.unit_type)}</div><h2 id="preview-title">${esc(x.anchor_zh)}</h2><p class="expression" lang="${x.language}">${reading(x.text,x.readings)}</p>${x.context_zh?section('使用情境',`<p>${esc(x.context_zh)}</p>`):''}<a class="button" href="${detail('sentences',x.unit_id,x.language)}">查看完整表达详情</a>`;}else{const x=(await api(type+'/'+encodeURIComponent(id))).data;body.innerHTML=type==='vocabulary'?`<div class="eyebrow">本课词汇</div><h2 id="preview-title" lang="${x.language}">${esc(x.lemma)}</h2><p>${esc(x.ipa?'/'+x.ipa+'/':x.reading||'')}</p>${section('意思与用法',x.senses.map(s=>`<article class="sense"><h3>${esc(s.meaning_zh)}</h3><p>${esc(s.usage_zh)}</p></article>`).join(''))}${section('例句',x.examples.slice(0,4).map(e=>`<div class="example"><p lang="${x.language}">${reading(e.text,e.readings)}</p><p>${esc(e.translation_zh)}</p></div>`).join(''))}<a class="button" href="${detail(type,id,x.language)}">查看完整词汇详情</a>`:`<div class="eyebrow">本课语法</div><h2 id="preview-title">${esc(x.title_zh)}</h2><p lang="${x.language}">${esc(x.form_name)}</p>${section('核心感觉',`<p>${esc(x.core_zh)}</p><p>${esc(x.purpose_zh)}</p>`)}${section('基本结构',`<div class="formula">${esc(x.formula)}</div>`)}${section('正式例句',x.examples.slice(0,4).map(e=>`<div class="example"><p lang="${x.language}">${reading(e.text,e.readings)}</p><p>${esc(e.translation_zh)}</p></div>`).join(''))}${dynamicExamplesPanel(x.id,lesson.id)}<a class="button" href="${url('grammar-detail',{id,lang:x.language,lesson:lesson.id})}">查看完整语法详情</a>`;}bindDynamicExamples(body);}catch(e){body.innerHTML=`<div class="error"><h2 id="preview-title">详情暂时无法打开</h2><p>${esc(e.message)}</p></div>`;}
}

$('#preview .close').onclick=()=>$('#preview').close();$('#preview').addEventListener('click',e=>{if(e.target===$('#preview'))$('#preview').close();});
async function load(fn){try{await fn();}catch(e){$('#main').innerHTML=`<div class="error" role="alert"><h1>暂时无法打开</h1><p>${esc(e.message)}</p><button id="retry">重新加载</button></div>`;$('#retry').onclick=()=>location.reload();}}
load(page==='lesson'?lesson:list);
