import {$,esc,heading,shell,account,privateApi,url,authHref} from './shared.js';

shell('practice');
const params=new URLSearchParams(location.search),source=params.get('source')==='weakness'?'weakness':'standard',context=params.get('context')==='lesson'?'lesson':'standalone',lessonId=params.get('lesson_id')||'',type=['vocabulary','grammar','mixed'].includes(params.get('type'))?params.get('type'):'mixed',mode=['mixed','recognition','selection','recall'].includes(params.get('mode'))?params.get('mode'):'mixed',contentId=params.get('content_id')||'';let language=['en','ja'].includes(params.get('language'))?params.get('language'):context==='lesson'&&lessonId.startsWith('ja-')?'ja':null;
const labels={vocabulary_recognition:'词义识别',vocabulary_meaning_to_word:'反向选择',vocabulary_typed_recall:'拼写回忆',grammar_form_selection:'语法形式选择',grammar_controlled_completion:'句子补全',grammar_form_recall:'语法形式回忆'};
let exercises=[],index=0,correct=0,wrong=0,attemptId=null,answered=false,meta=null;
const languageNav=()=>context==='lesson'||source==='weakness'?'':`<nav class="pills" aria-label="练习语言">${[['en','English'],['ja','日本語']].map(([key,label])=>`<a ${language===key?'class="active" aria-current="page"':''} href="${esc(url('practice',{type,mode,language:key}))}">${label}</a>`).join('')}</nav>`;

const choiceForm=item=>`<fieldset><legend class="sr-only">请选择一个答案</legend><div class="practice-choices">${item.choices.map((choice,i)=>`<label><input type="radio" name="answer" value="${esc(choice)}"><span><b>${String.fromCharCode(65+i)}</b>${esc(choice)}</span></label>`).join('')}</div></fieldset>`;
const typedForm=item=>`<label for="practice-answer">你的答案</label><input id="practice-answer" name="answer" autocomplete="off" autocapitalize="none" spellcheck="false" maxlength="200" required>`;

function renderQuestion(){
 const item=exercises[index];answered=false;attemptId=null;
 if(!item){renderSummary();return;}
 $('#main').innerHTML=heading('Focused practice',meta?.lesson?.title||'专注练习',`第 ${index+1} / ${exercises.length} 题 · 每次作答都会进入同一项学习记录与复习计划。`)+languageNav()+`<section class="card practice-shell"><div class="practice-top"><span class="badge">${esc(labels[item.exercise_type]||item.exercise_type)}</span><span class="muted">${item.content_type==='vocabulary'?'词汇':'语法'}</span></div><h2>${esc(item.prompt)}</h2>${item.detail?`<p class="muted">${esc(item.detail)}</p>`:''}<form id="practice-form">${item.choices?choiceForm(item):typedForm(item)}<div class="practice-submit"><button class="primary" type="submit">提交答案</button></div><div id="practice-feedback" class="practice-feedback" role="status" aria-live="polite"></div></form><button id="practice-next" class="primary" type="button" hidden>下一题 →</button></section>`;
 const form=$('#practice-form'),feedback=$('#practice-feedback'),next=$('#practice-next');
 form.onsubmit=async event=>{event.preventDefault();if(answered)return;const data=new FormData(form),answer=String(data.get('answer')||'').trim();if(!answer){feedback.className='practice-feedback wrong';feedback.textContent='请选择或填写一个答案。';return;}const button=$('button[type="submit"]',form);attemptId||=crypto.randomUUID().replaceAll('-','');button.disabled=true;feedback.className='practice-feedback';feedback.textContent='正在核对…';
  try{const result=(await privateApi('/api/learning/attempt',{method:'POST',body:JSON.stringify({attempt_id:attemptId,exercise_token:item.exercise_id,answer})})).data;answered=true;if(result.correct)correct++;else wrong++;feedback.className=`practice-feedback ${result.correct?'success':'wrong'}`;const resultLanguage=result.language||language||(result.content_id.startsWith('ja-')?'ja':'en');let aiAction='';if(result.remediation_token){const resumeId=crypto.randomUUID().replaceAll('-',''),returnPath=url('practice',{resume:resumeId});aiAction=`<a id="explain-wrong" class="button" href="${esc(url('ai',{remediation:result.remediation_token,lang:resultLanguage,return:returnPath}))}">让 AI 解释</a>`;queueMicrotask(()=>{$('#explain-wrong').onclick=()=>sessionStorage.setItem('yanjian.remediation.resume.'+resumeId,JSON.stringify({exercises,index:index+1,correct,wrong,meta}));});}else aiAction=`<a class="button" href="${esc(url('ai',{type:result.content_type,id:result.content_id,lang:resultLanguage}))}">让 AI 解释</a>`;feedback.innerHTML=result.correct?`<strong>回答正确。</strong><p>${esc(result.feedback)}</p>`:`<strong>这次还不对。</strong><p>你的答案：${esc(result.submitted_answer)}</p><p>参考答案：<b>${esc(result.expected_answer)}</b></p><p>${esc(result.feedback)}</p>${aiAction}`;form.querySelectorAll('input').forEach(input=>input.disabled=true);button.hidden=true;next.hidden=false;next.textContent=index===exercises.length-1?'查看总结':'下一题 →';next.focus();}
  catch(error){feedback.className='practice-feedback wrong';feedback.textContent=error.message+' 再次提交会安全重试，不会重复计数。';button.disabled=false;}
 };
 next.onclick=()=>{index++;renderQuestion();};
}

function renderSummary(){const total=correct+wrong,accuracy=total?Math.round(correct/total*100):0,lessonHref=context==='lesson'?url('lesson',{id:lessonId,lang:lessonId.startsWith('ja-')?'ja':'en',stage:lessonId.match(/-s([1-6])-/)?.[1]||1}):'/progress.html';$('#main').innerHTML=heading('Session complete','本轮练习完成','这里只汇报真实提交结果，不换算成掌握度或 XP。')+`<section class="card practice-summary"><h2>${total} 题已完成</h2><dl><div><dt>正确</dt><dd>${correct}</dd></div><div><dt>错误</dt><dd>${wrong}</dd></div><div><dt>正确率</dt><dd>${accuracy}%</dd></div></dl><div class="actions"><a class="button primary" href="${esc(lessonHref)}">${context==='lesson'?'返回课程并完成':'返回我的学习'}</a><a class="button" href="${esc(location.pathname+location.search)}">再练一轮</a></div></section>`;}

async function start(){if(!(await account()).authenticated){$('#main').innerHTML=heading('Focused practice','专注练习','登录后作答会进入你的学习记录与复习计划。')+`<section class="card"><a class="button primary" href="${esc(authHref())}">邮箱验证码登录</a></section>`;return;}const resumeId=params.get('resume');if(resumeId&&/^[A-Za-z0-9_-]{16,64}$/.test(resumeId)){const key='yanjian.remediation.resume.'+resumeId;try{const saved=JSON.parse(sessionStorage.getItem(key)||'null');sessionStorage.removeItem(key);if(saved&&Array.isArray(saved.exercises)&&Number.isInteger(saved.index)){exercises=saved.exercises;index=saved.index;correct=Number(saved.correct)||0;wrong=Number(saved.wrong)||0;meta=saved.meta;renderQuestion();return;}}catch{sessionStorage.removeItem(key);}}
 if(!language&&source!=='weakness'){try{language=(await privateApi('/api/settings')).data.preferred_learning_language||'en';}catch{language='en';}}
 const query=new URLSearchParams({source,type,mode,limit:contentId?'1':source==='weakness'?'5':'10',context,...(context==='lesson'?{lesson_id:lessonId}:{}),...(contentId?{content_id:contentId}:{}),...(language?{language}:{})});const response=await privateApi('/api/practice/session?'+query);exercises=response.data;meta=response.meta;if(!exercises.length)throw Error(source==='weakness'?'当前没有可用于专项练习的薄弱项。':'当前范围没有足够且无歧义的练习内容。');renderQuestion();}
start().catch(error=>{$('#main').innerHTML=`<div class="error" role="alert"><h1>练习暂时无法开始</h1><p>${esc(error.message)}</p><a class="button" href="/learn.html">返回学习路径</a></div>`;});
