import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {estimate,nextQuestion,recommend} from '../src/engine.js';
const content=JSON.parse(fs.readFileSync('tests/phase3-content-inventory.json','utf8'));
const catalog=content.map(c=>({...c,en:{difficulty:c.enLevel},ja:{difficulty:c.jaLevel}}));
const pool=catalog.map(c=>({...c,difficulty:c.en.difficulty}));
function simulate(answer,seed='test'){let h=[];while(!estimate(h).done){const q=nextQuestion(pool,h,seed);assert(q);h.push({...q,correct:answer(q,h)});assert(h.length<=18);}return {history:h,...estimate(h)};}
test('placement calibrates Levels 1–6, starts at 3, needs repeated evidence',()=>{for(let ability=0;ability<=6;ability++){const r=simulate(q=>q.difficulty<=ability);assert.equal(r.level,Math.max(1,ability));assert.equal(r.history[0].difficulty,3);assert(r.history.length>=8&&r.history.length<=18);assert(new Set(r.history.map(q=>q.id)).size===r.history.length);}assert(!estimate([{difficulty:6,correct:true}]).done);assert(!estimate([{difficulty:3,correct:false}]).done);});
test('mixed, consecutive mistakes/successes and uncertain boundaries respect hard maximum',()=>{for(const answer of [(q,h)=>h.length%2===0,(q,h)=>h.length>4,(q,h)=>h.length<4,(q,h)=>q.difficulty<3||(q.difficulty===3&&h.length%2===0)]){const r=simulate(answer);assert(r.history.length<=18&&r.history.length>=8);}assert(estimate(Array.from({length:18},(_,i)=>({difficulty:i%6+1,correct:i%2===0}))).done);});
test('early stopping, deterministic seed, varied sequence and language independence',()=>{assert(simulate(()=>true).history.length<15);assert(simulate(()=>false).history.length<15);assert.deepEqual(simulate(q=>q.difficulty<=4),simulate(q=>q.difficulty<=4));assert.notDeepEqual(simulate(()=>true,'a').history.map(q=>q.id),simulate(()=>true,'b').history.map(q=>q.id));const en=simulate(q=>q.difficulty<=5);simulate(q=>q.difficulty<=2);assert.deepEqual(en,simulate(q=>q.difficulty<=5));});
test('fresh Levels 1,4,6 produce different nearby content and topic variety',()=>{const outputs=[1,4,6].map(level=>recommend(catalog,{lang:'en',level}).items);for(const [i,items] of outputs.entries()){assert.equal(items.length,6);assert(new Set(items.map(c=>c.topic)).size>=3);assert(items.filter(c=>Math.abs(c.en.difficulty-[1,4,6][i])<=1).length>=5);}assert.notDeepEqual(outputs[0].map(c=>c.id),outputs[1].map(c=>c.id));assert.notDeepEqual(outputs[1].map(c=>c.id),outputs[2].map(c=>c.id));});
test('independent EN5/JA2, review and checkpoint weaknesses, recent and mastery',()=>{const en=recommend(catalog,{lang:'en',level:5}),ja=recommend(catalog,{lang:'ja',level:2});assert.notDeepEqual(en.items.map(c=>c.id),ja.items.map(c=>c.id));const id=en.items[0].id;assert(!recommend(catalog,{lang:'en',level:5,mastery:{[id]:'learned'}}).items.some(c=>c.id===id));assert(recommend(catalog,{lang:'en',level:5,mastery:{[id]:'review'},weak:[id]}).items.some(c=>c.id===id));assert.notEqual(recommend(catalog,{lang:'en',level:5,recent:[id]}).items[0].id,id);assert.equal(recommend(catalog,{lang:'en'}).level,1);});
test('partial topic, many review items, empty catalogs and manual topic filter',()=>{const mastery=Object.fromEntries(catalog.slice(0,70).map((c,i)=>[c.id,i<4?'learned':'review']));const r=recommend(catalog,{lang:'en',level:4,mastery,last:catalog[4].id});assert.equal(r.items.length,6);assert(new Set(r.items.map(c=>c.topic)).size>=3);assert(recommend(catalog,{lang:'ja',level:2,topic:'plans'}).items.every(c=>c.topic==='plans'));assert.deepEqual(recommend([],{lang:'en'}).items,[]);});
test('fresh intermediate queue includes consolidation and stretch',()=>{for(const lang of ['en','ja']){const r=recommend(catalog,{lang,level:4});assert(r.items.some(c=>c[lang].difficulty===3));assert(r.items.some(c=>c[lang].difficulty===5));}});
test('700 seeded simulations preserve level calibration independently',()=>{for(const lang of ['en','ja'])for(let ability=0;ability<=6;ability++)for(let seed=0;seed<50;seed++){const p=catalog.map(c=>({...c,difficulty:c[lang].difficulty}));let h=[];while(!estimate(h).done){const q=nextQuestion(p,h,String(seed));h.push({...q,correct:q.difficulty<=ability});assert(h.length<=18);}assert.equal(estimate(h).level,Math.max(1,ability));}});
