const assert=require('node:assert/strict');
const {chromium}=require('playwright');
const base=process.env.BASE_URL||'http://127.0.0.1:8816';
const account={authenticated:true,user:{id:'user-browser',email:'learner@example.com'}};
const summary={data:{server_time:2_000_000_000,vocabulary:{has_learned:true,scheduled_count:1,due_count:1,next_upcoming_at:null},grammar:{has_learned:true,scheduled_count:1,due_count:1,next_upcoming_at:null},total_due:2,has_learned:true,total_scheduled:2,next_review_at:null}};
const queue={data:[{type:'vocabulary',id:'en-choice',language:'en',prompt:'选择',next_review_at:1_999_999_000,overdue_seconds:1000,progress:{attempts:2,correct_count:1,wrong_count:1,correct_streak:0,review_stage:0,review_count:2,lapse_count:1,current_interval_seconds:600}},{type:'grammar',id:'en-present-perfect',language:'en',prompt:'现在完成时',next_review_at:2_000_000_000,overdue_seconds:0,progress:{attempts:2,correct_count:2,wrong_count:0,correct_streak:2,review_stage:2,review_count:2,lapse_count:0,current_interval_seconds:259200}}],meta:{server_time:2_000_000_000,type:'all',limit:20,returned:2}};
const fulfillJson=(route,body,status=200)=>route.fulfill({status,contentType:'application/json',body:JSON.stringify(body)});

(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH||'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'});try{
 for(const width of [360,390,430,768,1440]){const page=await browser.newPage({viewport:{width,height:900}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('**/api/me',r=>fulfillJson(r,account));await page.route('**/api/review/summary',r=>fulfillJson(r,summary));await page.route('**/api/review/queue?limit=20',r=>fulfillJson(r,queue));await page.route('**/api/learning/attempt',r=>fulfillJson(r,{data:{correct:true,expected_answer:'Choice',idempotent:false,progress:{next_review_at:2_000_086_400}}}));await page.goto(base+'/review.html');await page.getByRole('heading',{name:'到期复习'}).waitFor();await page.getByLabel('你的答案').fill('choice');await page.getByRole('button',{name:'提交答案'}).click();await page.getByText(/回答正确/).waitFor();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,`review overflow at ${width}px`);assert.deepEqual(errors,[]);await page.close();}
 const flow=await browser.newPage({viewport:{width:390,height:844}});let submitted;await flow.route('**/api/me',r=>fulfillJson(r,account));await flow.route('**/api/review/summary',r=>fulfillJson(r,summary));await flow.route('**/api/review/queue?limit=20',r=>fulfillJson(r,queue));await flow.route('**/api/learning/attempt',r=>{submitted=r.request().postDataJSON();return fulfillJson(r,{data:{correct:false,expected_answer:'Choice',idempotent:false,progress:{next_review_at:2_000_000_600}}});});await flow.goto(base+'/review.html');await flow.getByLabel('你的答案').fill('wrong');await flow.getByRole('button',{name:'提交答案'}).click();await flow.getByText(/10 分钟后/).waitFor();assert.deepEqual(Object.keys(submitted).sort(),['answer','attempt_id','content_id','content_type']);assert(!('user_id' in submitted));assert(!('next_review_at' in submitted));await flow.getByRole('button',{name:/下一项/}).click();assert.equal(await flow.getByText('第 2 / 2 项').isVisible(),true);await flow.close();
 for(const state of [{summary:{...summary.data,total_due:0,has_learned:false,total_scheduled:0,next_review_at:null},text:'还没有可复习的内容'},{summary:{...summary.data,total_due:0,has_learned:true,total_scheduled:2,next_review_at:2_000_086_400},text:'今天暂时没有到期复习内容'}]){const page=await browser.newPage({viewport:{width:430,height:844}});await page.route('**/api/me',r=>fulfillJson(r,account));await page.route('**/api/review/summary',r=>fulfillJson(r,{data:state.summary}));await page.route('**/api/review/queue?limit=20',r=>fulfillJson(r,{data:[],meta:{}}));await page.goto(base+'/review.html');await page.getByText(new RegExp(state.text)).waitFor();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.close();}
 console.log(JSON.stringify({passed:true,widths:[360,390,430,768,1440],cases:['due review layout','authoritative answer payload','correct feedback','wrong 10-minute feedback','next-item flow','empty account','learned-not-due state']}));
}finally{await browser.close();}})().catch(error=>{console.error(error);process.exitCode=1;});
