const assert=require('node:assert/strict');
const {chromium}=require('playwright');
const base=process.env.BASE_URL||'http://127.0.0.1:8816';
const account={authenticated:true,user:{id:'browser-user',email:'learner@example.com'}};
const exercises={data:[
 {exercise_id:'opaque-token-one',content_type:'vocabulary',exercise_type:'vocabulary_recognition',prompt:'选择“expect”的意思。',choices:['计划','期待','离开','帮助'],context:{type:'standalone'}},
 {exercise_id:'opaque-token-two',content_type:'grammar',exercise_type:'grammar_form_recall',prompt:'根据“现在完成时”，写出目标语法形式。',detail:'连接过去与现在。',context:{type:'standalone'}}
],meta:{type:'mixed',mode:'mixed',context:'standalone',limit:10,returned:2,maximum:20}};
const fulfill=(route,body,status=200)=>route.fulfill({status,contentType:'application/json',body:JSON.stringify(body)});
async function practiceRoutes(page,capture=[]){
 await page.route('**/api/me',route=>fulfill(route,account));
 await page.route('**/api/practice/session?*',route=>fulfill(route,exercises));
 await page.route('**/api/learning/attempt',route=>{const body=route.request().postDataJSON();capture.push(body);const correct=body.answer==='期待';return fulfill(route,{data:{correct,expected_answer:correct?'期待':'have + past participle',submitted_answer:body.answer,content_type:correct?'vocabulary':'grammar',content_id:correct?'en-expect':'en-present-perfect',exercise_type:correct?'vocabulary_recognition':'grammar_form_recall',feedback:correct?'回答正确。':'答案不匹配，请对照参考答案再试一次。',progress:{attempts:1,correct_count:correct?1:0},idempotent:false}});});
}

(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH||'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'});try{
 for(const width of [360,390,430,768,1440]){
  const page=await browser.newPage({viewport:{width,height:900}}),errors=[];page.setDefaultTimeout(5000);page.on('pageerror',error=>errors.push(error.message));await practiceRoutes(page);await page.goto(base+'/practice.html?type=mixed&mode=mixed');await page.getByRole('heading',{name:'专注练习'}).waitFor();
  assert.equal(await page.locator('fieldset').count(),1);assert.equal(await page.locator('[aria-live="polite"]').count(),1);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,`practice overflow at ${width}px`);if(width<=430)assert((await page.locator('.practice-choices span').first().boundingBox()).height>=56);assert.deepEqual(errors,[]);await page.close();
 }
 const flow=await browser.newPage({viewport:{width:390,height:844}}),submitted=[];flow.setDefaultTimeout(5000);await practiceRoutes(flow,submitted);await flow.goto(base+'/practice.html');await flow.locator('.practice-choices label').filter({hasText:'期待'}).click();await flow.getByRole('button',{name:'提交答案'}).click();await flow.getByText('回答正确。',{exact:true}).first().waitFor();assert.equal(await flow.getByRole('button',{name:/下一题/}).evaluate(el=>el===document.activeElement),true);await flow.getByRole('button',{name:/下一题/}).click();await flow.getByLabel('你的答案').fill('wrong answer');await flow.getByRole('button',{name:'提交答案'}).click();await flow.getByText('参考答案：').waitFor();assert(await flow.getByRole('link',{name:'让 AI 解释'}).isVisible());await flow.getByRole('button',{name:'查看总结'}).click();await flow.getByRole('heading',{name:'本轮练习完成'}).waitFor();await flow.getByText('50%').waitFor();assert.deepEqual(submitted.map(x=>Object.keys(x).sort()),[['answer','attempt_id','exercise_token'],['answer','attempt_id','exercise_token']]);await flow.close();

 const detail=await browser.newPage({viewport:{width:430,height:844}});await detail.route('**/api/me',route=>fulfill(route,account));await detail.route('**/api/v2/vocabulary/en-expect',route=>fulfill(route,{data:{id:'en-expect',language:'en',lemma:'expect',stage:3,part_of_speech:'verb',register:'neutral',ipa:'',reading:null,senses:[{meaning_zh:'期待',usage_zh:'预期某事发生。'}],examples:[],relations:[],sentences:{data:[],pagination:{has_more:false}}}}));await detail.goto(base+'/vocabulary-detail.html?id=en-expect&lang=en');const launch=detail.getByRole('link',{name:'开始练习'});await launch.waitFor();assert.match(await launch.getAttribute('href'),/practice\.html.*content_id=en-expect/);assert.equal(await detail.getByLabel('你的答案').count(),0);await detail.close();

 const lesson=await browser.newPage({viewport:{width:390,height:844}});await lesson.route('**/api/me',route=>fulfill(route,account));await lesson.route('**/api/v2/lessons/en-s1-l1',route=>fulfill(route,{data:{id:'en-s1-l1',language:'en',stage:1,sequence:1,title:'第一课',objective:'完成真实练习。',topic:'聊天',estimated_minutes:15,vocabulary_count:1,grammar_count:1,expression_count:0,scenario_count:0,previous:null,next:null,vocabulary:[{id:'en-expect',language:'en',lemma:'expect',meaning_zh:'期待',role:'required'}],grammar:[{id:'en-present-perfect',language:'en',title_zh:'现在完成时',form_name:'have + past participle',role:'required'}],expressions:[]}}));await lesson.route('**/api/lessons/en-s1-l1/start',route=>fulfill(route,{data:{id:'en-s1-l1',status:'in_progress',started_at:1,completed_at:null,last_activity_at:1,last_section_key:'overview',changed:true}}));await lesson.route('**/api/lessons/en-s1-l1/position',route=>fulfill(route,{data:{id:'en-s1-l1',status:'in_progress',started_at:1,completed_at:null,last_activity_at:2,last_section_key:route.request().postDataJSON().section_key,changed:true}}));await lesson.route('**/api/lessons/en-s1-l1/complete',route=>fulfill(route,{error:{code:'LESSON_PRACTICE_REQUIRED',message:'还需完成 2 项本课练习后才能完成课程。',evidence:{remaining_items:2}}},409));await lesson.goto(base+'/lesson.html?id=en-s1-l1&lang=en&stage=1');await lesson.getByRole('tab',{name:/练习/}).click();const lessonLaunch=lesson.getByRole('link',{name:/开始本课练习/});await lessonLaunch.waitFor();assert.match(await lessonLaunch.getAttribute('href'),/context=lesson.*lesson_id=en-s1-l1/);await lesson.getByRole('button',{name:'完成课程 ✓'}).click();await lesson.getByText(/还需完成 2 项/).waitFor();assert.equal(await lesson.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await lesson.close();
 console.log(JSON.stringify({passed:true,widths:[360,390,430,768,1440],cases:['choice and typed layouts','semantic controls','keyboard focus','correct and wrong feedback','session summary','opaque submission payload','detail-page migration','lesson practice link','completion-gate feedback','no horizontal overflow']}));
}finally{await browser.close();}})().catch(error=>{console.error(error);process.exitCode=1;});
