const assert=require('node:assert/strict'),fs=require('node:fs'),{chromium}=require('playwright'),vm=require('node:vm');
const base=process.env.BASE_URL||'http://127.0.0.1:8787',label=process.env.TEST_LABEL||'local',dir=`tests/phase3-${label}-screenshots`;
const baseline=vm.runInNewContext(fs.readFileSync('tests/fixtures/phase1-data.cjs','utf8')+';({placementQuestions})');
const supplemental=JSON.parse(fs.readFileSync('tests/phase3-supplement-keys.json','utf8'));
const key=q=>supplemental[q.id]?supplemental[q.id].key:q.id.startsWith('p3-')?(Number(q.id.split('-').at(-1))+(q.id.includes('-en-')?1:2)+(q.id.includes('-checkpoint-')?1:0))%4:baseline.placementQuestions[q.id.split('-')[0]][Number(q.id.split('-')[1])-1][3];
(async()=>{fs.mkdirSync(dir,{recursive:true});const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH||'C:/Program Files/Google/Chrome/Application/chrome.exe'});const context=await browser.newContext(),p=await context.newPage(),errors=[],checks=[];p.on('pageerror',e=>errors.push(e.message));
 const go=async path=>{assert.equal((await p.goto(base+'/'+path)).status(),200);assert(await p.evaluate(()=>appReady));if(path.startsWith('learn'))await p.locator('#concept-select').waitFor();};
 const overflow=async()=>{await p.evaluate(()=>document.fonts.ready);const offenders=await p.evaluate(()=>[...document.querySelectorAll('main *')].filter(e=>e.getBoundingClientRect().right>innerWidth+1).map(e=>({tag:e.tagName,cls:e.className,width:e.getBoundingClientRect().width,text:e.textContent.slice(0,70)})));assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,JSON.stringify(offenders));};
 try{
 await go('index.html');await p.evaluate(()=>{localStorage.clear();localStorage.setItem('kotoba.phase1.v1',JSON.stringify({levels:{en:{level:5,score:10,date:'old'},ja:{level:2,score:4,date:'old'}},mastery:{en:{8:'learned',2:'review'},ja:{8:'review'}},last:8,activity:{old:true}}));});await go('index.html');const old=await p.evaluate(()=>localStorage.getItem(LEGACY_KEY));let s=await p.evaluate(()=>state);assert.equal(s.mastery.en[8],'learned');assert.equal(s.mastery.ja[8],'review');assert.equal(s.lastByLang.en,8);assert.equal(s.levels.en.level,5);assert.equal(s.levels.ja.level,2);assert.equal(s.activity.old,true);assert(await p.evaluate(()=>!!localStorage.getItem(KEY)));checks.push('Phase 1/2 migration retains independent levels, mastery, position, activity and untouched legacy recovery key');
 const enLinks=await p.locator('#recommendations .en .queue-preview a').allTextContents(),jaLinks=await p.locator('#recommendations .ja .queue-preview a').allTextContents();assert.notDeepEqual(enLinks,jaLinks);await p.locator('.begin-queue[data-lang="ja"]').click();await p.locator('#concept-select').waitFor();assert.equal(await p.locator('.language-name').first().textContent(),'日本語');assert((await p.locator('main').textContent()).includes('今日日本語'));await p.locator('[data-mark="learned"][data-lang="ja"]').click();await p.locator('#next').click();await p.locator('#concept-select').waitFor();checks.push('EN5/JA2 recommendations differ; language-specific queue advances and records only selected mastery');
 await go('learn.html?id=8');await p.locator('#hiragana-toggle').check();assert(await p.locator('#hiragana-view').isVisible());await p.locator('.grammar[data-lang="en"]').click();assert(await p.locator('dialog').isVisible());await p.locator('.close-bottom').click();await p.locator('#comparison').click();assert(await p.locator('dialog .drawer-text').textContent());await p.keyboard.press('Escape');await p.locator('details.ipa summary').click();assert(await p.locator('details.ipa p').isVisible());assert.equal(await p.evaluate(()=>localStorage.getItem(LEGACY_KEY)),old);checks.push('Original card IPA, kana toggle, touch grammar drawer, comparison, escape and legacy preservation');
 await go('placement.html');await p.locator('.start-test[data-lang="en"]').click();await p.locator('#next-question').waitFor();assert(await p.locator('#next-question').isDisabled());let count=0;while(await p.locator('#next-question').count()){const q=await p.evaluate(()=>session.question);await p.locator(`input[value="${key(q)}"]`).check();await p.locator('#next-question').click();await p.waitForFunction(id=>session.complete||session.question.id!==id,q.id);count++;assert(count<=18);}assert(count>=8);assert.equal(await p.evaluate(()=>state.levels.en.level),6);assert.equal(await p.evaluate(()=>state.levels.ja.level),2);checks.push('Browser adaptive completion with independent retest and useful results');
 await go('checkpoint.html?topic=food&lang=ja');await p.locator('#start-checkpoint').click();await p.locator('#next-question').waitFor();for(let i=0;i<8;i++){const q=await p.evaluate(()=>session.question);await p.locator(`input[value="${i===0?(key(q)+1)%4:key(q)}"]`).check();await p.locator('#next-question').click();await p.waitForFunction(id=>session.complete||session.question.id!==id,q.id);}assert.equal((await p.evaluate(()=>state.checkpoints.ja.food)).weakConcepts.length,1);assert.equal(await p.evaluate(()=>Object.keys(state.checkpoints.en).length),0);assert.equal(await p.locator('.review-list a').count(),1);checks.push('Checkpoint result identifies weak Concept and updates Japanese only');
 for(const width of [360,390,430,1440]){await p.setViewportSize({width,height:920});for(const [name,path] of [['home','index.html'],['progress','progress.html'],['placement','placement.html'],['checkpoint','checkpoint.html?topic=plans&lang=ja'],['sentence','learn.html?id=8'],['vocabulary','learn.html?id=178'],['phrase','learn.html?id=182'],['pattern','learn.html?id=180'],['scenario','learn.html?id=181'],['dialogue','learn.html?id=183']]){await go(path);await overflow();await p.screenshot({path:`${dir}/${name}-${width}.png`,fullPage:true});}await go('placement.html');await p.locator('.start-test').first().click();await p.locator('#next-question').waitFor();await overflow();await p.screenshot({path:`${dir}/question-${width}.png`,fullPage:true});}
 checks.push('360/390/430/1440 layouts: Home, Progress, Placement, Checkpoint, six card types, long Level 6 dialogue and question; zero horizontal overflow');
 // Lost answer response must be recoverable without double scoring.
 let intercepted=false;await p.route('**/api/placement/answer',async route=>{if(!intercepted){intercepted=true;await route.fetch();await route.abort();}else await route.continue();});let q=await p.evaluate(()=>session.question);await p.locator(`input[value="${key(q)}"]`).check();await p.locator('#next-question').click();await p.locator('#answer-error').filter({hasText:'答案仍保留'}).waitFor();assert.equal(await p.evaluate(()=>session.version),0);await p.locator('#next-question').click();await p.waitForFunction(()=>session.version===1);await p.unroute('**/api/placement/answer');checks.push('Lost committed answer response retries idempotently');
 await p.route('**/api/concepts',r=>r.abort());await p.goto(base+'/index.html');await p.locator('#api-retry').waitFor();await p.unroute('**/api/concepts');await p.locator('#api-retry').click();await p.locator('.begin-queue').first().waitFor();checks.push('Content failure/retry recovery');
 await p.route('**/api/recommendations',r=>r.abort());await go('index.html');await p.locator('#retry-recommendations').waitFor();assert.equal(await p.locator('.topic-card').count(),14);await p.unroute('**/api/recommendations');await p.locator('#retry-recommendations').click();await p.locator('.begin-queue').first().waitFor();checks.push('Recommendation error leaves manual learning accessible and retries');
 const blocked=await browser.newContext();await blocked.addInitScript(()=>{Storage.prototype.setItem=function(){throw Error('blocked');};});const bp=await blocked.newPage();await bp.goto(base+'/learn.html?id=8');await bp.locator('#concept-select').waitFor();assert(await bp.locator('#storage-warning').isVisible());await blocked.close();checks.push('Blocked storage does not prevent learning');
 assert.deepEqual(errors,[]);fs.writeFileSync(`tests/phase3-browser-${label}.json`,JSON.stringify({base,passed:true,checks,errors},null,2));console.log(checks.join('\n'));
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
