const assert=require('node:assert/strict');
const {chromium}=require('playwright');
const base=process.env.BASE_URL||'http://127.0.0.1:8814';
(async()=>{
 const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH||'C:/Program Files/Google/Chrome/Application/chrome.exe'});
 for(const width of [360,390,430,768,1440]){
  const page=await browser.newPage({viewport:{width,height:900}}),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400&&!r.url().endsWith('/favicon.ico'))errors.push(`${r.status()} ${r.url()}`);});
  await page.goto(base+'/vocabulary.html?lang=en&browse=C');await page.locator('.vocab-row').first().waitFor();assert((await page.locator('.vocab-row').count())<=40);assert.equal(await page.locator('.vocab-row .pronunciation,.vocab-row .chips,.vocab-row .example').count(),0);assert.equal(await page.locator('.vocab-index-selector a').count(),27);for(const h of await page.locator('.vocab-index-selector a').evaluateAll(es=>es.map(e=>e.getBoundingClientRect().height)))assert(h>=44);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'overflow '+width);
  const targetRow=page.locator('.vocab-row').nth(Math.min(4,(await page.locator('.vocab-row').count())-1));const y=await targetRow.evaluate(e=>{e.scrollIntoView();return scrollY;});await targetRow.click();await page.locator('#preview[open] #preview-title').waitFor();assert(new URL(page.url()).searchParams.has('detail'));await page.locator('#preview .close').click();await page.waitForFunction(()=>!new URL(location.href).searchParams.has('detail'));assert(Math.abs((await page.evaluate(()=>scrollY))-y)<10);assert.deepEqual(errors,[]);await page.close();
 }
 const page=await browser.newPage({viewport:{width:390,height:900}});
 await page.goto(base+'/ielts.html?target=6.5&tab=vocabulary');await page.locator('select[name=part_of_speech]').waitFor();const ielts=await page.locator('select[name=part_of_speech] option').allTextContents();assert(!ielts.some(x=>/な形容|い形容|助数詞/.test(x)));assert((await page.locator('.vocab-row').count())>=20);assert.equal(await page.locator('.vocab-row .pronunciation,.vocab-row .learner-meta,.vocab-row .example').count(),0);assert.equal(await page.locator('.vocab-index-selector a').count(),27);const ipaRow=page.locator('.vocab-row').filter({hasText:'evaluate'});await ipaRow.click();await page.locator('#lesson-detail[open] .pronunciation').waitFor();await page.locator('#lesson-detail .sheet-close').click();await page.waitForFunction(()=>!new URL(location.href).searchParams.has('detail'));
 await page.getByRole('link',{name:'A',exact:true}).click();await page.waitForLoadState('networkidle');await page.locator('.vocab-row').first().waitFor();assert((await page.locator('.vocab-row .vocab-headword').allTextContents()).every(x=>/^a/i.test(x)));const examUrlBefore=page.url(),examY=await page.locator('.vocab-row').first().evaluate(e=>{e.scrollIntoView();return scrollY;});await page.locator('.vocab-row').first().dispatchEvent('click');await page.locator('#lesson-detail[open] #lesson-detail-title').waitFor();assert(await page.locator('#lesson-detail .sense').count());assert(await page.locator('#lesson-detail .example').count());await page.locator('#lesson-detail .sheet-close').click();await page.waitForFunction(()=>!new URL(location.href).searchParams.has('detail'));await page.waitForFunction(y=>Math.abs(scrollY-y)<10,examY);assert.equal(page.url(),examUrlBefore);
 await page.goto(base+'/jlpt.html?level=N3&tab=vocabulary');await page.getByRole('heading',{name:'JLPT N3'}).waitFor();await page.locator('select[name=part_of_speech]').waitFor();const jlpt=await page.locator('select[name=part_of_speech] option').allTextContents();assert(jlpt.includes('な形容詞')&&jlpt.includes('い形容詞'));assert(!jlpt.some(x=>/短语动词|介词短语/.test(x)));assert.equal(await page.locator('.vocab-index-selector a').count(),11);assert.equal(await page.locator('.vocab-row .pronunciation').count(),0);await page.getByRole('link',{name:'か行',exact:true}).click();await page.locator('.vocab-row').first().waitFor();assert((await page.locator('.vocab-row').allTextContents()).some(x=>x.includes('確認する')));
 await page.goto(base+'/jlpt.html?level=N4&tab=vocabulary&browse=さ行');await page.locator('.vocab-row').first().waitFor();assert((await page.locator('.vocab-row').allTextContents()).some(x=>x.includes('サイズ')));await page.getByRole('link',{name:'や行',exact:true}).click();await page.locator('.vocab-row').first().waitFor();assert((await page.locator('.vocab-row').allTextContents()).some(x=>x.includes('予定')));
 await page.goto(base+'/vocabulary.html?lang=ja&browse=や行');await page.locator('.vocab-index-selector').waitFor();assert.equal(await page.locator('.vocab-index-selector a').count(),11);assert(await page.locator('.vocab-row').first().textContent());assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 const scale=await browser.newPage({viewport:{width:390,height:900}}),total=5000;
 await scale.route('**/api/v2/vocabulary?**',route=>{const u=new URL(route.request().url()),limit=Number(u.searchParams.get('limit')),offset=Number(u.searchParams.get('offset'));const data=Array.from({length:Math.max(0,Math.min(limit,total-offset))},(_,i)=>({id:'scale-'+(offset+i),language:'en',lemma:'choice'+String(offset+i).padStart(4,'0'),type:'word',stage:2,ipa:'tʃɔɪs',reading:null,part_of_speech:'noun',register:'neutral',sort_order:offset+i,meaning_zh:'选择'}));route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({data,pagination:{limit,offset,has_more:offset+limit<total,next_offset:offset+limit<total?offset+limit:null}})});});
 await scale.goto(base+'/vocabulary.html?lang=en&browse=C');await scale.locator('.vocab-row').first().waitFor();assert.equal(await scale.locator('.vocab-row').count(),40);await scale.getByRole('button',{name:'加载更多'}).click();await scale.waitForFunction(()=>document.querySelectorAll('.vocab-row').length===80);assert.equal(await scale.locator('.vocab-row').count(),80);assert.equal(new URL(scale.url()).searchParams.get('shown'),'80');assert.equal(await scale.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await scale.close();
 await browser.close();console.log('Phase 3.5E.1C vocabulary UX passed at 360, 390, 430, 768 and 1440px.');
})().catch(e=>{console.error(e);process.exit(1);});
