import assert from 'node:assert/strict';
import fs from 'node:fs';
import test from 'node:test';
import {DatabaseSync} from 'node:sqlite';
import {lessons,lessonPracticeCurriculum,publishedLessonCurriculum} from '../src/lessons-35d.js';
import {practiceSession,resolvePracticeExercise} from '../src/practice-4e.js';
import {lessonRecommendations,recommendationPolicy} from '../src/recommendations-4d.js';
import {grammarContentCorrections,isCurrentGrammarId,isPracticeEligibleGrammarId} from '../src/content-quality-03.js';
import {authoritativeHashes,buildStage6Bundle,bundleId,datasetMarker,excludedStage6Ids,expectedDensity,finalStage6Ids,loadStage6Expansion,newLessonIds,prerequisiteChains,schemaVersion,slotLessonIds} from '../scripts/stage6-expansion-03.js';

const root=new URL('..',import.meta.url).pathname.replace(/^\/(.:)/,'$1'),loaded=loadStage6Expansion(root),{base,bundle,payload,matrix}=loaded;
const migration=fs.readdirSync(`${root}/migrations-stage6-expansion-03`).filter(name=>name.endsWith('.sql')).sort().map(name=>fs.readFileSync(`${root}/migrations-stage6-expansion-03/${name}`,'utf8')).join('\n'),authSigningFixture='stage6-expansion-03-test-signing-fixture-40';
const itemKey=item=>`${item[0]}\0${item[1]}\0${item[2]}`;

function canonicalDatabase({stage6=true}={}){
 const db=new DatabaseSync(':memory:');
 for(const directory of ['migrations-35d','migrations-35e1a','migrations-35e1a2','migrations-35e1b','migrations-35e1c'])for(const file of fs.readdirSync(`${root}/${directory}`).filter(name=>name.endsWith('.sql')).sort())db.exec(fs.readFileSync(`${root}/${directory}/${file}`,'utf8'));
 db.exec('CREATE TABLE IF NOT EXISTS v2_grammar_example_target_audits(example_id TEXT PRIMARY KEY,grammar_id TEXT,rationale_zh TEXT)');
 for(const file of ['migrations-content-quality-01/0001_content_quality_hotfix_01.sql','migrations-content-quality-02/0001_content_quality_hotfix_02.sql','migrations-content-quality-03/0001_content_quality_hotfix_03.sql','migrations-curriculum-expansion-01/0001_curriculum_expansion_01a_bundle.sql'])db.exec(fs.readFileSync(`${root}/${file}`,'utf8'));
 for(const file of fs.readdirSync(`${root}/migrations-stage5-expansion-02`).filter(name=>name.endsWith('.sql')).sort())db.exec(fs.readFileSync(`${root}/migrations-stage5-expansion-02/${file}`,'utf8'));
 if(stage6)db.exec(migration);
 return db;
}
function d1(sqlite){
 const wrap=(sql,values=[])=>({bind:(...next)=>wrap(sql,next),async first(){return sqlite.prepare(sql).get(...values)||null;},async all(){return {results:sqlite.prepare(sql).all(...values)};},async run(){const result=sqlite.prepare(sql).run(...values);return {success:true,meta:{changes:Number(result.changes)}};}});
 return {prepare:sql=>wrap(sql)};
}

test('frozen 03A/03B inputs pass hash, final approval, authorization, and agreement gates',()=>{
 assert.deepEqual(loaded.hashes,authoritativeHashes);assert.equal(matrix.relationships.length,177);assert.equal(payload.relationship_authority.length,177);
 const unauthorized=structuredClone(payload);unauthorized.grammar_examples[0].implementation_authorized=false;assert.throws(()=>buildStage6Bundle(base,unauthorized,matrix,fs.readFileSync(`${root}/docs/STAGE-6-EDITORIAL-APPROVAL-03B.md`,'utf8')),/implementation_authorized/);
 const disagreement=structuredClone(payload);disagreement.relationship_authority[0].instructional_role='SUPPORT';assert.throws(()=>buildStage6Bundle(base,disagreement,matrix,fs.readFileSync(`${root}/docs/STAGE-6-EDITORIAL-APPROVAL-03B.md`,'utf8')),/disagree/);
 const wrongCount=structuredClone(payload);wrongCount.relationship_authority.pop();assert.throws(()=>buildStage6Bundle(base,wrongCount,matrix,fs.readFileSync(`${root}/docs/STAGE-6-EDITORIAL-APPROVAL-03B.md`,'utf8')),/cardinality/);
});

test('immutable bundle has exact 76/74 graph, 177 Stage 6 relationships, roles, density, and source-derived delta',()=>{
 assert.equal(bundle.v,schemaVersion);assert.equal(bundle.u.length,76);assert.equal(bundle.p.length,74);assert.equal(bundle.i.length,1130);assert.deepEqual(newLessonIds,['en-s6-03-synthesis','en-s6-04-accountability','ja-s6-03-reporting','ja-s6-04-accountability']);
 const stage6=bundle.i.filter(item=>finalStage6Ids.includes(item[0])),totals=index=>Object.fromEntries([...new Set(stage6.map(item=>item[index]))].sort().map(value=>[value,stage6.filter(item=>item[index]===value).length]));
 assert.equal(stage6.length,177);assert.equal(new Set(stage6.map(itemKey)).size,177);assert.deepEqual(totals(1),{expression:47,grammar:35,vocabulary:95});assert.deepEqual(totals(6),{NEW:66,REVIEW:61,SUPPORT:50});
 assert.deepEqual(Object.fromEntries(['en','ja'].map(language=>[language,stage6.filter(item=>item[0].startsWith(language)).length])),{en:88,ja:89});for(const id of excludedStage6Ids)assert.equal(stage6.some(item=>item[2]===id),false,id);
 for(const row of payload.relationship_authority.filter(entry=>entry.instructional_role==='REVIEW')){assert(row.prior_review_source,`${row.slot_id}:${row.canonical_id}:missing review source`);assert(base.i.some(item=>item[0]===row.prior_review_source&&item[1]===row.content_type&&item[2]===row.canonical_id),`${row.slot_id}:${row.canonical_id}:invalid review source`);}
 for(const [slot,[v,g,e,assessable]] of Object.entries(expectedDensity)){const rows=stage6.filter(item=>item[0]===slotLessonIds[slot]);assert.deepEqual([rows.filter(x=>x[1]==='vocabulary').length,rows.filter(x=>x[1]==='grammar').length,rows.filter(x=>x[1]==='expression').length,rows.filter(x=>x[1]!=='expression'&&(x[1]!=='grammar'||isPracticeEligibleGrammarId(x[2]))).length],[v,g,e,assessable],slot);}
 assert.deepEqual(loaded.delta,{raw:{retained:35,added:142,removed:88,net:54},runtime:{retained:35,added:142,removed:87,net:55}});assert.deepEqual(loaded.counts,{raw:1130,runtime_active:1126,old_stage6_raw:123,old_stage6_active:122});
 const archived=base.i.filter(item=>item[0].startsWith('en-s6-')&&item[1]==='grammar'&&!isCurrentGrammarId(item[2]));assert.deepEqual(archived.map(item=>item[2]),['en-greeting']);assert.equal(stage6.some(item=>item[2]==='en-greeting'),false);
 const units=new Map(bundle.u.map(unit=>[unit[0],unit])),parents=new Map(bundle.p.map(edge=>edge));assert.equal([...parents.values()].filter(Boolean).length,74);
 for(const chain of Object.values(prerequisiteChains))for(let index=1;index<chain.length;index++)assert.equal(parents.get(chain[index]),chain[index-1]);
 assert.equal(parents.get('ja-s6-l4'),'ja-s6-04-accountability');assert.equal(parents.get('ja-s6-l3'),'ja-s6-l4');
 for(const language of ['en','ja']){const languageUnits=bundle.u.filter(unit=>unit[1]===language),roots=languageUnits.filter(unit=>!parents.has(unit[0]));assert.deepEqual(roots.map(unit=>unit[0]),[`${language}-s1-l1`]);for(const unit of languageUnits){let current=unit[0];const seen=new Set();while(parents.has(current)){assert(!seen.has(current));seen.add(current);const next=parents.get(current);assert.equal(units.get(next)[1],language);current=next;}assert.equal(current,roots[0][0]);}}
 const terminals=bundle.u.filter(unit=>!bundle.p.some(edge=>edge[1]===unit[0]));assert.deepEqual(terminals.map(unit=>unit[0]),['en-s6-l4','ja-s6-l3']);
});

test('migration inserts exact editorial delta once and preserves canonical identities and learner/SRS tables',()=>{
 const before=canonicalDatabase({stage6:false}),identityBefore={vocabulary:before.prepare("SELECT language,COUNT(*) n FROM v2_vocabulary_items GROUP BY language ORDER BY language").all(),grammar:before.prepare("SELECT language,COUNT(*) n,SUM(publication_state='published') p FROM v2_grammar_points GROUP BY language ORDER BY language").all(),expressions:before.prepare('SELECT COUNT(*) n FROM v2_sentence_expressions').get().n};before.close();
 const db=canonicalDatabase(),semantic=()=>({vocabulary_examples:db.prepare("SELECT COUNT(*) n FROM v2_vocabulary_examples WHERE id LIKE 'stage6-03-ve-%'").get().n,grammar_examples:db.prepare("SELECT COUNT(*) n FROM v2_grammar_examples WHERE id LIKE 's6-03b-%'").get().n,reviews:db.prepare('SELECT COUNT(*) n FROM v2_grammar_example_completion_reviews WHERE dataset_marker=?').get(datasetMarker).n,authority:db.prepare('SELECT COUNT(*) n FROM v2_grammar_example_completion_authority WHERE dataset_marker=?').get(datasetMarker).n,contexts:db.prepare('SELECT COUNT(*) n FROM v2_expression_context_details WHERE dataset_marker=?').get(datasetMarker).n,bundles:db.prepare('SELECT COUNT(*) n FROM lesson_bundles WHERE id=?').get(bundleId).n,lessons:db.prepare('SELECT COUNT(*) n FROM lesson_units').get().n,edges:db.prepare('SELECT COUNT(*) n FROM lesson_prerequisites').get().n});
 assert.deepEqual(semantic(),{vocabulary_examples:40,grammar_examples:60,reviews:60,authority:38,contexts:9,bundles:1,lessons:76,edges:74});db.exec(migration);assert.deepEqual(semantic(),{vocabulary_examples:40,grammar_examples:60,reviews:60,authority:38,contexts:9,bundles:1,lessons:76,edges:74});
 assert.deepEqual(db.prepare("SELECT language,COUNT(*) n FROM v2_vocabulary_items GROUP BY language ORDER BY language").all(),identityBefore.vocabulary);assert.deepEqual(db.prepare("SELECT language,COUNT(*) n,SUM(publication_state='published') p FROM v2_grammar_points GROUP BY language ORDER BY language").all(),identityBefore.grammar);assert.equal(db.prepare('SELECT COUNT(*) n FROM v2_sentence_expressions').get().n,identityBefore.expressions);
 assert.deepEqual(identityBefore.grammar.map(row=>[row.language,row.n,row.p]),[['en',83,82],['ja',98,97]]);assert.equal(identityBefore.expressions,713);
 assert.deepEqual(db.prepare('SELECT lesson_id,prerequisite_lesson_id FROM lesson_prerequisites ORDER BY lesson_id').all().map(row=>({...row})),bundle.p.map(([lesson_id,prerequisite_lesson_id])=>({lesson_id,prerequisite_lesson_id})).sort((a,b)=>a.lesson_id.localeCompare(b.lesson_id)));
 for(const row of payload.vocabulary_examples){const actual=db.prepare("SELECT text,translation_zh FROM v2_vocabulary_examples WHERE item_id=? AND id LIKE 'stage6-03-ve-%'").get(row.canonical_id);assert.deepEqual({...actual},{text:row.final_sentence,translation_zh:row.translation_zh});}
 for(const row of payload.grammar_examples){const actual=db.prepare('SELECT text,translation_zh FROM v2_grammar_examples WHERE id=?').get(row.example_id);assert.deepEqual({...actual},{text:row.text,translation_zh:row.translation_zh});}
 for(const row of payload.expression_contexts){const actual=db.prepare('SELECT canonical_text,scenario,speaker_relationship,intended_pragmatic_function,register_constraint FROM v2_expression_context_details WHERE canonical_id=? AND dataset_marker=?').get(row.canonical_id,datasetMarker);assert.deepEqual({...actual},{canonical_text:row.canonical_text,scenario:row.scenario,speaker_relationship:row.speaker_relationship,intended_pragmatic_function:row.intended_pragmatic_function,register_constraint:row.register_constraint});}
 assert.deepEqual(JSON.parse(db.prepare('SELECT payload_json FROM lesson_bundles WHERE id=?').get(bundleId).payload_json),bundle);db.close();
 const statements=migration.replace(/^--.*$/gm,'');assert.doesNotMatch(statements,/\b(?:INSERT|UPDATE|DELETE)\s+(?:INTO\s+)?(?:lesson_progress|learning_attempts|vocabulary_progress|grammar_progress|srs_items|user_settings)/i);assert.doesNotMatch(statements,/\bDELETE\b/i);
});

test('38 CC SAFE examples alone authorize controlled completion; all 22 unsafe and en-if-request remain non-authoritative',async()=>{
 const sqlite=canonicalDatabase(),DB=d1(sqlite),reviews=sqlite.prepare('SELECT * FROM v2_grammar_example_completion_reviews WHERE dataset_marker=? ORDER BY example_id').all(datasetMarker),authority=sqlite.prepare('SELECT * FROM v2_grammar_example_completion_authority WHERE dataset_marker=? ORDER BY example_id').all(datasetMarker);
 assert.equal(reviews.filter(row=>row.cc_safety==='CC SAFE').length,38);assert.equal(reviews.filter(row=>row.cc_safety==='NOT FOR CC').length,22);assert.equal(authority.length,38);assert(authority.every(row=>row.cc_safety==='CC SAFE'));
 for(const row of authority){const example=sqlite.prepare('SELECT text FROM v2_grammar_examples WHERE id=?').get(row.example_id);assert.equal(example.text.slice(row.answer_start,row.answer_start+row.answer.length),row.answer);}
 const unsafe=new Set(reviews.filter(row=>row.cc_safety==='NOT FOR CC').map(row=>row.example_id));assert.equal(authority.some(row=>unsafe.has(row.example_id)),false);assert.equal(reviews.filter(row=>row.grammar_id==='en-if-request').length,3);assert.equal(authority.some(row=>row.grammar_id==='en-if-request'),false);
 let result=await practiceSession(new URL('https://test/api/practice/session?type=grammar&mode=selection&content_id=en-if-request&limit=1'),{DB,CONTENT_DB:DB,AUTH_SECRET:authSigningFixture},{user_id:'unsafe-boundary'});assert.equal(result.data[0].exercise_type,'grammar_form_selection');
 result=await practiceSession(new URL('https://test/api/practice/session?type=grammar&mode=selection&content_id=en-inversion&limit=1'),{DB,CONTENT_DB:DB,AUTH_SECRET:authSigningFixture},{user_id:'safe-boundary'});assert.equal(result.data[0].exercise_type,'grammar_controlled_completion');const spec=await resolvePracticeExercise(result.data[0].exercise_id,{DB,CONTENT_DB:DB,AUTH_SECRET:authSigningFixture},{user_id:'safe-boundary'});assert(authority.some(row=>row.example_id===spec.authority_example_id&&row.answer===spec.answer));
 assert.deepEqual(Object.fromEntries(Object.entries(expectedDensity).map(([slot,row])=>[slot,row[4]])),{EN1:33,EN2:33,EN3:31,EN4:32,EN5:29,EN6:33,JA1:33,JA2:30,JA3:33,JA4:33,JA5:33,JA6:33});sqlite.close();
});

test('lesson APIs select Stage 6, expose exact public assets/roles, keep private metadata hidden, and remain zero-write',async()=>{
 const sqlite=canonicalDatabase();sqlite.exec('CREATE TABLE IF NOT EXISTS lesson_progress(user_id TEXT,lesson_id TEXT,status TEXT,last_activity_at INTEGER,last_section_key TEXT)');const DB=d1(sqlite),before=sqlite.prepare('SELECT total_changes() n').get().n;
 let response=await lessons(new Request('https://test/api/v2/lessons?language=ja&stage=6'),DB,DB),body=await response.json();assert.equal(response.status,200);assert.deepEqual(body.data.map(row=>row.id),prerequisiteChains.ja.slice(1));
 for(const id of finalStage6Ids){response=await lessons(new Request(`https://test/api/v2/lessons/${id}`),DB,DB);body=await response.json();assert.equal(response.status,200,id);const expected=bundle.i.filter(item=>item[0]===id);assert.equal(body.data.vocabulary.length+body.data.grammar.length+body.data.expressions.length,expected.length,id);assert(body.data.vocabulary.concat(body.data.grammar,body.data.expressions).every(row=>['NEW','REVIEW','SUPPORT'].includes(row.instructional_role)));assert.doesNotMatch(JSON.stringify(body),/implementation_authorized|human_approval_status|cc_answer|answer_start|prior_review_source|semantic_register_rationale/);}
 response=await lessons(new Request('https://test/api/v2/lessons/ja-s6-04-accountability'),DB,DB);body=await response.json();const dialogue=body.data.lesson_assets.find(asset=>asset.kind==='dialogue');assert.equal(dialogue.turns.length,6);assert.equal(dialogue.turns[4].text.split('\n').length,2);assert.match(dialogue.turns[4].text,/報告いたします/);assert.doesNotMatch(JSON.stringify(dialogue),/ja-c-827|demonstrated_canonical_ids|non_authoritative/);assert.equal(bundle.i.some(item=>item[0]==='ja-s6-04-accountability'&&item[2]==='ja-c-827'),false);assert.equal(bundle.i.some(item=>item[0]==='ja-s6-l4'&&item[2]==='ja-c-827'),true);
 assert.deepEqual(Object.fromEntries(['dialogue','reuse_prompt','scenario'].map(kind=>[kind,bundle.a.filter(asset=>asset.asset_id?.startsWith(datasetMarker)&&asset.kind===kind).length])),{dialogue:4,reuse_prompt:5,scenario:3});
 await practiceSession(new URL('https://test/api/practice/session?context=lesson&lesson_id=en-s6-03-synthesis&type=mixed&mode=mixed&limit=10'),{DB,CONTENT_DB:DB,AUTH_SECRET:authSigningFixture},{user_id:'zero-write'});await lessonRecommendations(DB,'zero-write','en');assert.equal(sqlite.prepare('SELECT total_changes() n').get().n,before);assert.equal((await publishedLessonCurriculum(DB)).lessons.length,76);assert.equal((await lessonPracticeCurriculum(DB,'ja-s6-l2')).items.length,10);sqlite.close();
});

test('grandfathering fixtures preserve progress, active lessons, JA reorder evidence, and prior course completion',async()=>{
 const sqlite=new DatabaseSync(':memory:');sqlite.exec('CREATE TABLE lesson_bundles(id TEXT PRIMARY KEY,schema_version TEXT,payload_json TEXT,published_at TEXT);CREATE TABLE lesson_progress(user_id TEXT,lesson_id TEXT,status TEXT,last_activity_at INTEGER,last_section_key TEXT);');sqlite.prepare('INSERT INTO lesson_bundles VALUES(?,?,?,?)').run(bundleId,schemaVersion,JSON.stringify(bundle),'2026-09-16');
 const DB=d1(sqlite),insert=(user,id,status='completed',time=1)=>sqlite.prepare('INSERT INTO lesson_progress VALUES(?,?,?,?,?)').run(user,id,status,time,status==='completed'?'practice':'grammar'),prior=bundle.g.previous_lesson_ids_by_language,preStage6=language=>prior[language].filter(id=>!id.includes('-s6-')),oldStage6=language=>prior[language].filter(id=>id.includes('-s6-'));
 for(const id of preStage6('en'))insert('A-no-stage6',id);let result=await lessonRecommendations(DB,'A-no-stage6','en');assert.equal(result.paths.en.next.id,'en-s6-l1');assert.equal(result.paths.en.grandfathered_complete,false);
 for(const id of [...preStage6('en'),'en-s6-l1'])insert('B-l1',id);result=await lessonRecommendations(DB,'B-l1','en');assert.equal(result.paths.en.next.id,'en-s6-l2');
 for(const id of [...preStage6('en'),'en-s6-l1','en-s6-l2'])insert('C-l2',id);result=await lessonRecommendations(DB,'C-l2','en');assert.equal(result.paths.en.next.id,'en-s6-03-synthesis');
 for(const id of [...preStage6('en'),'en-s6-l1','en-s6-l2'])insert('D-active-en',id);insert('D-active-en','en-s6-l3','in_progress',50);result=await lessonRecommendations(DB,'D-active-en','en');assert.equal(result.continue.id,'en-s6-l3');assert.equal(result.next,null);
 for(const id of [...preStage6('ja'),'ja-s6-l1','ja-s6-l2'])insert('D-active-ja',id);insert('D-active-ja','ja-s6-l3','in_progress',50);result=await lessonRecommendations(DB,'D-active-ja','ja');assert.equal(result.continue.id,'ja-s6-l3');
 for(const id of [...preStage6('ja'),'ja-s6-l1','ja-s6-l2','ja-s6-l3'])insert('E-ja-l3',id);result=await lessonRecommendations(DB,'E-ja-l3','ja');assert.equal(result.paths.ja.next.id,'ja-s6-03-reporting');assert.equal(result.paths.ja.complete,false);
 for(const id of [...preStage6('ja'),'ja-s6-l1','ja-s6-l2','ja-s6-l4'])insert('F-ja-l4',id);result=await lessonRecommendations(DB,'F-ja-l4','ja');assert.equal(result.paths.ja.next.id,'ja-s6-03-reporting');assert.equal(result.paths.ja.complete,false);
 for(const id of prior.ja)insert('G-old-four',id);result=await lessonRecommendations(DB,'G-old-four','ja');assert.equal(result.paths.ja.next,null);assert.equal(result.paths.ja.complete,true);assert.equal(result.paths.ja.grandfathered_complete,true);
 for(const language of ['en','ja'])for(const id of prior[language])insert('H-course-complete',id);result=await lessonRecommendations(DB,'H-course-complete','en');assert.equal(result.all_complete,true);assert.equal(result.next,null);assert.equal(result.paths.en.grandfathered_complete,true);assert.equal(result.paths.ja.grandfathered_complete,true);
 assert.deepEqual(recommendationPolicy.priority,['review_due','continue_lesson','start_next_lesson','all_lessons_complete']);assert.equal(sqlite.prepare("SELECT COUNT(*) n FROM lesson_progress WHERE status='in_progress'").get().n,2);assert.equal(sqlite.prepare("SELECT COUNT(*) n FROM lesson_progress WHERE status='completed'").get().n,345);sqlite.close();
});

test('Hotfix 01-03 boundaries, Stage 6 examples, SRS identity, and deployment policy remain bounded',()=>{
 const db=canonicalDatabase();for(const correction of grammarContentCorrections){const actual=db.prepare('SELECT form_name,formula FROM v2_grammar_points WHERE id=?').get(correction.id);assert.deepEqual({...actual},{form_name:correction.form_name,formula:correction.formula});}assert.equal(db.prepare("SELECT form_name FROM v2_grammar_points WHERE id='ja-kamoshirenai'").get().form_name,'〜かもしれない');
 assert.equal(db.prepare("SELECT COUNT(*) n FROM v2_vocabulary_examples WHERE item_id IN ('ja-c-859','ja-c-871') AND id LIKE 'stage6-03-ve-%'").get().n,2);assert.equal(bundle.i.filter(item=>['ja-c-859','ja-c-871'].includes(item[2])).every(item=>item[0]==='ja-s6-04-accountability'),true);
 const nonStage6Before=base.i.filter(item=>!item[0].includes('-s6-')).map(itemKey),nonStage6After=bundle.i.filter(item=>!item[0].includes('-s6-')).map(itemKey);assert.deepEqual(nonStage6After,nonStage6Before);assert.equal(new Set(bundle.i.filter(item=>item[1]!=='expression').map(item=>item[2])).size,new Set(bundle.i.filter(item=>item[1]!=='expression').map(item=>item[2])).size);db.close();
 const policy=JSON.parse(fs.readFileSync(`${root}/config/staging-data-policy.json`,'utf8')),lessonsPolicy=policy.datasets.find(row=>row.name==='lessons');assert.deepEqual([policy.datasets.find(row=>row.name==='en_vocabulary').row_count,policy.datasets.find(row=>row.name==='ja_vocabulary').row_count],[10000,8235]);assert.deepEqual([lessonsPolicy.version,lessonsPolicy.row_count,lessonsPolicy.checksum,lessonsPolicy.update_migration_config],[datasetMarker,76,`bundle:${bundleId}`,'wrangler.stage6-expansion-03.jsonc']);
 const local=fs.readFileSync(`${root}/wrangler.stage6-expansion-03.local.jsonc`,'utf8'),deployment=JSON.parse(fs.readFileSync(`${root}/package.json`,'utf8')).scripts['deploy:stage6-expansion-03'];assert.match(local,/migrations-stage6-expansion-03/);assert.doesNotMatch(local,/--remote|bootstrap/);assert.match(deployment,/not authorized/);
});
