import {$,esc,url,detail,names,langName,badge,heading,domains,languages,pagination,empty,load,api,shell,section,reading,aiLink,relationCards,reverseCards,legacyState,posNames,registerNames,preview} from './shared.js';
const page=document.body.dataset.page,p=Object.fromEntries(new URLSearchParams(location.search));
const lang=p.lang==='ja'?'ja':'en';
shell(['index'].includes(page)?'home':['academic','academic-about','ielts','jlpt'].includes(page)?'academic':['ai','progress'].includes(page)?page:'learn');
const domainCards=()=>`<div class="grid">${[['vocabulary','字','词汇库','Vocabulary','把词义、搭配与容易混淆的用法分清楚。','Stage 1–6 · 独立词汇阶段'],['grammar','式','语法库','Grammar','理解结构的核心感觉，再回到真实表达。','Level 1–6 · 建议学习路径'],['sentences','句','句子与表达','Sentences & Expressions','从想说的中文意思出发，学习自然用法。','生活主题 · 三维难度']].map(([k,i,n,en,d,m])=>`<a class="card domain-card ${k}" href="${url(k)}"><span class="domain-icon">${i}</span><div><div class="eyebrow">${en}</div><h3>${n}</h3></div><p>${d}</p><div class="end"><span>${m}</span><span aria-hidden="true">↗</span></div></a>`).join('')}</div>`;
function profile(l,expanded=false){const s=legacyState(),level=s.levels?.[l]?.level;const count=Object.values(s.mastery?.[l]||{}).filter(x=>x==='learned').length;return `<section class="card"><div class="profile"><div><h3>${langName(l)}</h3><p class="muted">${Number.isInteger(level)&&level>=1&&level<=6?'原版定位 Level '+level:'原版尚未定位'}${count?' · 已学 '+count+' 项':''}</p></div>${badge('领域档案预览','preview')}</div><div class="progress-domains">${['词汇阶段','语法水平','表达能力'].map(n=>`<div><strong>${n}</strong><span>尚未独立评估</span></div>`).join('')}</div>${expanded?`<p class="notice">以上领域尚无独立掌握度。原版定位与学习记录继续保留，不换算为词汇或语法分数。</p><a class="text-link" href="/legacy/progress.html">旧版学习（兼容） · 查看进度 →</a>`:''}</section>`;}
async function home(){
 const sample=(await api('sentences/not-eaten')).data;
 $('#main').innerHTML=`<section class="hero"><div class="hero-copy"><div class="eyebrow">A little understanding, a little further.</div><h1>先理解，<br>再说出你的世界。</h1><p>学会一个词，读懂一个结构，连成一句自然的表达。<br>从中文意思出发，分别建立英语与日语的理解。</p><div class="actions"><a class="button primary" href="/sentences.html">从一句话开始 ↗</a><a class="button" href="/vocabulary.html">探索词汇库</a></div></div><div class="hero-art" aria-label="中文理解与独立双语表达示例"><div class="eyebrow">今天，从这句话开始</div><div class="line"><small>想表达的意思</small>${esc(sample.anchor_zh)}</div><div class="line" lang="en"><small>ENGLISH</small>${esc(sample.expressions.find(e=>e.language==='en').text)}</div><div class="line" lang="ja"><small>日本語</small>${reading(sample.expressions.find(e=>e.language==='ja').text,sample.expressions.find(e=>e.language==='ja').readings)}</div><a class="text-link" href="/sentence.html?id=not-eaten">看看这句话用了哪些词与语法 →</a></div></section><section class="section"><div class="section-head"><h2>三个入口，一起走向表达</h2><span class="muted">双语分阶段课程</span></div>${domainCards()}</section><section class="section"><div class="section-head"><h2>你的两条学习路径</h2><a class="text-link" href="/progress.html">我的学习 →</a></div><div class="grid two">${profile('en')}${profile('ja')}</div></section><section class="section grid two"><a class="callout" href="/academic.html"><div class="eyebrow">A focused direction</div><h2>给学习一个考试目标</h2><p>IELTS 5.0–7.0+ · JLPT N5–N1<br>选择目标，开始学习词汇、语法与表达。</p><span class="text-link">探索学术 / 考试 →</span></a><a class="card" href="/ai.html"><div class="eyebrow">Practice, in context</div><h2>把理解变成自己的句子</h2><p>造句、情境回答、表达优化、词汇与语法问答。</p>${badge('AI 学习预览 · 尚未连接 AI','preview')}<p class="text-link">体验练习界面 →</p></a></section>`;
}
const options=(items,value)=>items.map(([v,n])=>`<option value="${esc(v)}" ${String(value??'')===String(v)?'selected':''}>${esc(n)}</option>`).join('');
const select=(key,label,items)=>`<label>${label}<select name="${key}" aria-label="${label}">${options([['','不限'],...items],p[key])}</select></label>`;
const nums=Array.from({length:6},(_,i)=>[String(i+1),String(i+1)]);
const stageDescriptions=['基础生活词汇','常见日常表达','更广泛的生活交流','细致的词义与搭配','正式与专业场景','进阶词义辨析'];
const grammarDescriptions={en:['基础句子结构','日常动作与时间','可能性与连接表达','复杂时间与背景说明','细致的逻辑关系','语境与结构的进阶运用'],ja:['基础句型与判断','常用变化与日常表达','状态、推测与意图','背景说明与复杂连接','细致的语气区分','语境与结构的进阶运用']};
const topicName=t=>({body:'身体 / 身体部位',health:'健康 / 身体状态'})[t.id]||t.name_zh;
async function library(kind){
 const topics=(await api('academic/topics')).data;
 const query={language:lang,limit:12,offset:p.offset||'0'};
 for(const k of ['stage','level','type','part_of_speech','register','topic','search','unit_type','overall_difficulty','vocabulary_difficulty','grammar_difficulty'])if(p[k])query[k]=p[k];
 const response=await api(kind+'?'+new URLSearchParams(query));
 const n=names[kind],isV=kind==='vocabulary',isG=kind==='grammar',band=isV?'stage':'level';
 const initial=kind==='sentences'?select('topic','生活主题',topics.map(t=>[t.id,topicName(t)])):'';
 const advanced=isV?select('type','词汇类型',[['word','单词'],['fixed_expression','固定表达']])+select('part_of_speech','词性',Object.entries(posNames))+select('register','语域',Object.entries(registerNames))+select('topic','主题',topics.map(t=>[t.id,topicName(t)])):isG?'':select('unit_type','表达类型',[['sentence','句子'],['scenario','情境'],['dialogue','对话']])+select('overall_difficulty','综合难度',nums)+select('vocabulary_difficulty','词汇难度',nums)+select('grammar_difficulty','语法难度',nums);
 const levelNav=kind==='sentences'?`<div class="pills" aria-label="生活主题">${topics.map(t=>`<a class="${p.topic===t.id?'active':''}" href="${esc(url(kind,{lang,topic:t.id}))}">${esc(topicName(t))}</a>`).join('')}</div>`:`<div class="pills" aria-label="${isV?'词汇阶段':'语法水平'}">${nums.map(([v])=>`<a class="${p[band]===v?'active':''}" href="${esc(url(kind,{lang,[band]:v}))}">${isV?'Stage':'Level'} ${v}</a>`).join('')}</div><p class="results-note">${p[band]?(isV?stageDescriptions:grammarDescriptions[lang])[Number(p[band])-1]||'请选择 1–6':''}</p>`;
 $('#main').innerHTML=heading(isV?'Build your vocabulary':isG?'Understand the structure':'Say what you mean',n+'，从理解开始',isV?'一个词可以有多个意思。把义项、搭配与真实用法一起学。':isG?'两种语言，两套独立的语法库。按水平探索，也可以自由跳转。':'先想清楚想说什么，再看看英语和日语各自怎么表达。')+domains(kind)+languages({...p,lang},kind)+levelNav+`<form class="filters" method="get"><input type="hidden" name="lang" value="${lang}">${kind!=='sentences'&&p[band]?`<input type="hidden" name="${band}" value="${esc(p[band])}">`:''}<div class="filter-row">${initial}<label class="search-label">${kind==='sentences'?'搜索中文意思':'搜索中文或目标语言'}<input name="search" value="${esc(p.search)}" placeholder="${isV?'试试：期待 / expect':isG?'试试：现在完成 / ている':'试试：吃饭'}" maxlength="100"></label><button class="primary" type="submit">搜索</button><a class="button" href="${url(kind,{lang})}">清除</a></div>${advanced?`<details ${Object.keys(p).some(k=>['type','register','part_of_speech','unit_type','overall_difficulty','grammar_difficulty','vocabulary_difficulty'].includes(k))?'open':''}><summary>更多筛选</summary><div class="filter-row">${advanced}<button type="submit">应用筛选</button></div></details>`:''}</form><p class="results-note">课程内容 · 当前显示 ${response.data.length} 项；可按阶段、主题与难度继续筛选。</p><div class="grid">${response.data.map(x=>listCard(kind,x)).join('')||empty()}</div>${pagination(response.pagination,kind,{...p,lang})}`;
}
function listCard(kind,x){return `<a class="card list-card" href="${detail(kind,x.id,lang)}">${kind==='vocabulary'?`<h2 class="lexeme" lang="${x.language}">${esc(x.lemma)}</h2><div class="pronunciation">${esc(x.ipa?'/'+x.ipa+'/':x.reading)}</div><p class="meaning">${esc(x.meaning_zh)}</p><p class="muted">${esc(posNames[x.part_of_speech]||x.part_of_speech)}</p><div class="chips">${badge('Stage '+x.stage)}${badge(x.type==='fixed_expression'?'固定表达':'单词')}</div>`:kind==='grammar'?`<h2>${esc(x.title_zh)}</h2><p lang="${x.language}">${esc(x.form_name)}</p><p class="muted">${esc(x.purpose_zh)}</p><div class="chips">${badge('Level '+x.level)}${badge('自由学习')}</div>`:`<div class="eyebrow">${esc(({sentence:'一句话',scenario:'生活情境',dialogue:'简短对话'})[x.unit_type])}</div><h2>${esc(x.anchor_zh)}</h2><p class="muted">探索${langName(lang)}的词汇与语法用法</p><div class="chips">${badge('查看语言独立难度')}<span aria-hidden="true">→</span></div>`}</a>`;}
async function detailPage(kind){
 const x=(await api(kind+'/'+encodeURIComponent(p.id||''))).data;
 if(kind==='sentences')return sentencePage(x);
 const isV=kind==='vocabulary',title=isV?x.lemma:x.title_zh;
 document.title=title+' · 言间';
 const examples=x.examples.map(e=>`<div class="example"><p class="reading" lang="${x.language}">${reading(e.text,e.readings)}</p><p>${esc(e.translation_zh)}</p>${e.note_zh||e.explanation_zh?`<small>${esc(e.note_zh||e.explanation_zh)}</small>`:''}</div>`);
 const content=isV?section('意思与用法',x.senses.map((s,i)=>`<article class="sense"><div class="sense-number">义项 ${i+1}</div><h3>${esc(s.meaning_zh)}</h3><p>${esc(s.usage_zh)}</p>${s.register_note?`<p class="muted">${esc(s.register_note)}</p>`:''}</article>`).join(''))+section('常见搭配与结构',examples.filter((e,i)=>x.examples[i].kind!=='example').join(''))+section('在例句中理解',examples.filter((e,i)=>x.examples[i].kind==='example').join(''))+section('相关与容易混淆的词',relationCards(x.relations,'vocabulary')):section('核心感觉',`<p>${esc(x.core_zh)}</p><p class="muted">${esc(x.purpose_zh)}</p>`)+section('基本结构',`<div class="formula" lang="${x.language}">${esc(x.formula)}</div>`)+section('什么时候使用',`<p>${esc(x.when_zh)}</p>`)+section('例句',examples.join(''))+section('常见错误',x.mistakes_zh?`<p>${esc(x.mistakes_zh)}</p>`:'')+section('细微差别',x.nuance_zh?`<p>${esc(x.nuance_zh)}</p>`:'')+section('建议先了解',x.prerequisites.length?'<p class="muted">只是学习建议，可以直接学习当前语法。</p>'+relationCards(x.prerequisites,'grammar'):'')+section('相关语法与对比',relationCards(x.relations,'grammar'))+section('接下来可以探索',relationCards(x.recommended_for,'grammar'));
 $('#main').innerHTML=`<div class="breadcrumb"><a href="/">首页</a> / <a href="${url(kind,{lang:x.language})}">${names[kind]}库</a> / ${esc(title)}</div><div class="page-heading"><div class="eyebrow">${langName(x.language)} · ${names[kind]}</div><h1 lang="${isV?x.language:'zh-CN'}">${esc(title)}</h1>${isV?`<p class="pronunciation">${esc(x.ipa?'/'+x.ipa+'/':x.reading)}</p>`:`<p lang="${x.language}">${esc(x.form_name)}</p>`}<div class="chips">${badge((isV?'Stage ':'Level ')+(x.stage||x.level))}${isV?badge(posNames[x.part_of_speech]||x.part_of_speech):''}${badge(registerNames[x.register]||x.register)}</div></div><div class="detail-layout"><div class="detail-main">${content}${section('在这些表达中出现',x.sentences.data.length?reverseCards(x.sentences.data)+`<div id="reverse-more"></div>${x.sentences.pagination.has_more?'<button id="load-reverse">加载更多表达</button>':''}`:'<p class="muted">暂时没有关联表达。</p>')}</div><aside class="detail-aside">${section('从理解到使用',`<p class="muted">带着当前${names[kind]}打开练习预览。</p>${aiLink(kind,x.id,x.language)}`)}<div class="card"><h2>继续探索</h2><a class="text-link" href="${url(kind,{lang:x.language})}">返回${names[kind]}库 →</a></div></aside></div>`;
 if($('#load-reverse')){let offset=x.sentences.pagination.next_offset;$('#load-reverse').onclick=async()=>{const b=$('#load-reverse');b.disabled=true;try{const r=await api(`${kind}/${x.id}/sentences?limit=10&offset=${offset}`);$('#reverse-more').insertAdjacentHTML('beforeend',reverseCards(r.data));offset=r.pagination.next_offset;b.hidden=!r.pagination.has_more;}catch{b.textContent='加载失败，点击重试';}finally{b.disabled=false;}};}
}
const difficulty=e=>`<div class="difficulty"><span>词汇 ${e.vocabulary_difficulty} / 6</span><span>语法 ${e.grammar_difficulty} / 6</span><span>综合 ${e.overall_difficulty} / 6</span></div><details><summary>理解这些难度</summary><p class="muted">${esc(e.difficulty_note_zh)} 各语言独立评定，不是你的能力分数。</p></details>`;
let chunkActions=[];
function chunkButton(text,links,language){const index=chunkActions.push({links,language})-1;return `<button class="chunk" data-chunk="${index}" aria-label="查看 ${esc(text)} 的词汇或语法">${esc(text)}</button>`;}
function interactiveText(text,e,turnId=null){
 const links=[...e.vocabulary_links.map(l=>({...l,domain:'vocabulary',target:l.item_id})),...e.grammar_links.map(l=>({...l,domain:'grammar',target:l.grammar_id}))].filter(l=>l.turn_id===turnId);
 const spans=links.map(l=>{let start=-1;for(let i=0;i<l.occurrence;i++){start=text.indexOf(l.displayed_form,start<0?0:start+l.displayed_form.length);if(start<0)return null;}return {start,end:start+l.displayed_form.length,links:[l]};}).filter(Boolean).sort((a,b)=>a.start-b.start||b.end-a.end);
 const merged=[];for(const s of spans){const last=merged.at(-1);if(last&&s.start<last.end){last.end=Math.max(last.end,s.end);last.links.push(...s.links);}else merged.push(s);}
 let at=0,result='';for(const s of merged){result+=esc(text.slice(at,s.start))+chunkButton(text.slice(s.start,s.end),s.links,e.language);at=s.end;}return result+esc(text.slice(at));
}
async function sentencePage(x){
 chunkActions=[];const related=(await api('sentences?topic='+encodeURIComponent(x.topic_id)+'&language='+lang+'&limit=6')).data.filter(s=>s.id!==x.id);
 $('#main').innerHTML=`<div class="breadcrumb"><a href="/sentences.html">句子与表达</a> / ${esc(x.anchor_zh)}</div>${heading('Meaning first',x.anchor_zh,'同一个中文意思，两种语言各自自然表达。')}${x.context_zh?`<div class="context"><strong>情境</strong><p>${esc(x.context_zh)}</p></div>`:''}<div class="grid two">${x.expressions.map(e=>`<section class="card"><div class="section-head"><h2>${langName(e.language)}</h2>${badge(e.is_primary?'主要表达':'另一种说法')}</div>${x.unit_type==='dialogue'?e.turns.map(t=>`<div class="turn"><span class="speaker">${esc(t.speaker)}</span><div><div class="expression" lang="${e.language}">${interactiveText(t.text,e,t.id)}</div>${e.language==='ja'?`<details><summary>查看读音</summary><p class="reading" lang="ja">${reading(t.text,t.readings)}</p></details>`:''}</div></div>`).join(''):`<div class="expression" lang="${e.language}">${interactiveText(e.text,e)}</div>${e.ipa?`<p class="pronunciation">${esc(e.ipa)}</p>`:''}${e.language==='ja'?`<details><summary>查看读音 / 振假名</summary><p class="reading" lang="ja">${reading(e.text,e.readings)}</p></details>`:''}`}${difficulty(e)}<p class="muted">${esc(registerNames[e.register]||e.register)}${e.note_zh?' · '+esc(e.note_zh):''}</p><div class="link-group"><h3>用到的词汇</h3><div class="chips">${e.vocabulary_links.map(l=>{const i=chunkActions.push({links:[{...l,domain:'vocabulary',target:l.item_id}],language:e.language})-1;return `<button data-chunk="${i}">${esc(l.lemma)}</button>`;}).join('')||'<span class="muted">暂无标注</span>'}</div></div><div class="link-group"><h3>用到的语法</h3><div class="chips">${e.grammar_links.map(l=>{const i=chunkActions.push({links:[{...l,domain:'grammar',target:l.grammar_id}],language:e.language})-1;return `<button data-chunk="${i}">${esc(l.title_zh)}</button>`;}).join('')||'<span class="muted">暂无标注</span>'}</div></div><div class="section">${aiLink('sentences',x.id,e.language)}</div></section>`).join('')}</div><div class="section">${section('英语 × 日语：表达的区别',`<p>${esc(x.comparison_zh||'从交际意图理解，不把两种语言逐词对齐。')}</p>`)}</div><section class="section"><h2>同一主题，再看一句</h2><div class="grid">${related.map(s=>listCard('sentences',s)).join('')||'<p class="muted">当前主题暂无其他示例。</p>'}</div></section>`;
 document.querySelectorAll('[data-chunk]').forEach(b=>b.onclick=()=>{const action=chunkActions[Number(b.dataset.chunk)];preview(`<h2 id="preview-title">这段表达怎么理解</h2>${action.links.map(l=>`<article class="sense">${badge(names[l.domain])}<h3>${esc(l.lemma||l.title_zh||l.displayed_form)}</h3><p>${esc(l.meaning_zh||l.note_zh||'在当前表达中使用这个结构。')}</p><p class="muted">原文：${esc(l.displayed_form)}</p><a class="button primary" href="${detail(l.domain,l.target,action.language)}">查看${names[l.domain]}详情 →</a></article>`).join('')}`);});
}
async function academicHub(){
 const targetLinks=(pageName,key,targets,prefix='')=>`<div class="target-links">${targets.map(t=>`<a class="button" href="${esc(url(pageName,{[key]:t}))}">${prefix}${esc(t)}</a>`).join('')}</div>`;
 $('#main').innerHTML=heading('Choose your goal','学术与考试','选择学习目标，直接开始学习。')+`<div class="grid two academic-goals"><section class="goal-hero"><div class="eyebrow">English</div><h2>IELTS</h2><p>选择目标分数</p>${targetLinks('ielts','target',['5.0','5.5','6.0','6.5','7.0+'])}</section><section class="goal-hero"><div class="eyebrow">日本語</div><h2>JLPT</h2><p>选择目标等级</p>${targetLinks('jlpt','level',['N5','N4','N3','N2','N1'])}</section></div><a class="about-link" href="/academic-about.html">关于考试目标</a>`;
}
async function academicAbout(){
 $('#main').innerHTML=`<div class="breadcrumb"><a href="/academic.html">学术 / 考试</a> / 关于考试目标</div>${heading('About these learning tracks','关于考试目标','了解课程范围与内容审校方式。')}<section class="card prose"><h2>课程范围</h2><p>IELTS 与 JLPT 目标用于组织适合当前学习方向的内容，不是官方完整词汇或语法清单，也不构成成绩保证。</p><p>词汇 Stage、语法 Level 与表达难度仍各自独立，不与考试目标互相换算。</p></section><section class="card prose"><h2>内容状态</h2><p>考试目标对齐目前保持 draft，供课程编排参考并等待独立审校。学习内容本身仍来自现有课程库。</p></section><a class="button primary" href="/academic.html">返回选择学习目标</a>`;
}

const examDomains={vocabulary:'词汇',grammar:'语法',sentences:'句子与表达'};
const unitNames={sentence:'一句话',scenario:'情境',dialogue:'对话'};
const pageSize=24;
let examContext=null,detailOpener=null,overlayPushed=false,overlayRequest=0;
const currentParams=()=>Object.fromEntries(new URLSearchParams(location.search));
const examUrl=(pageName,params)=>url(pageName,params);
function examCard(domain,a){
 const href=detail(domain,a.content_id,a.language);
 if(domain==='vocabulary'){
  const focus=(a.tags||[]).filter(t=>!['Usage','Vocabulary'].includes(t)).slice(0,2).join(' · ');
  return `<a class="card learner-card exam-card" data-detail="${esc(a.content_id)}" data-domain="vocabulary" href="${esc(href)}"><h2 class="lexeme" lang="${a.language}">${esc(a.title)}</h2>${a.ipa||a.reading?`<div class="pronunciation">${esc(a.ipa?'/'+a.ipa+'/':a.reading)}</div>`:''}<p class="meaning">${esc(a.meaning_zh)}</p><div class="learner-meta">${esc(posNames[a.part_of_speech]||a.part_of_speech||'')}${focus?`<span>${esc(focus)}</span>`:''}</div><span class="text-link">查看详情 →</span></a>`;
 }
 if(domain==='grammar')return `<a class="card learner-card exam-card" data-detail="${esc(a.content_id)}" data-domain="grammar" href="${esc(href)}"><h2>${esc(a.title)}</h2><p class="form" lang="${a.language}">${esc(a.form_name)}</p><p class="meaning">${esc(a.purpose_zh)}</p><span class="text-link">查看详情 →</span></a>`;
 return `<a class="card learner-card exam-card" data-detail="${esc(a.content_id)}" data-domain="sentences" href="${esc(href)}"><div class="eyebrow">${esc(unitNames[a.unit_type]||'表达')}</div><h2>${esc(a.title)}</h2>${a.text?`<p class="expression-preview" lang="${a.language}">${esc(a.text)}</p>`:''}<span class="text-link">查看详情 →</span></a>`;
}
function ensureLessonDialog(){
 let dialog=$('#lesson-detail');
 if(dialog)return dialog;
 document.body.insertAdjacentHTML('beforeend','<dialog id="lesson-detail" class="lesson-sheet" aria-labelledby="lesson-detail-title"><div class="sheet-toolbar"><button class="sheet-close" type="button">← 返回内容列表</button></div><div class="sheet-body" aria-live="polite"></div></dialog>');
 dialog=$('#lesson-detail');
 $('.sheet-close',dialog).onclick=closeLesson;
 dialog.addEventListener('cancel',e=>{e.preventDefault();closeLesson();});
 dialog.addEventListener('click',e=>{const r=dialog.getBoundingClientRect();if(e.target===dialog&&(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom))closeLesson();});
 return dialog;
}
function closeLesson(){
 const dialog=$('#lesson-detail');
 if(!dialog?.open)return;
 if(overlayPushed){history.back();return;}
 const u=new URL(location.href);u.searchParams.delete('detail');u.searchParams.delete('detailType');history.replaceState(history.state,'',u);dialog.close();detailOpener?.focus();
}
const exampleHtml=(e,language)=>`<div class="example"><p class="reading" lang="${language}">${reading(e.text,e.readings)}</p>${e.translation_zh?`<p>${esc(e.translation_zh)}</p>`:''}${e.note_zh||e.explanation_zh?`<small>${esc(e.note_zh||e.explanation_zh)}</small>`:''}</div>`;
function overlayContent(domain,x,language){
 if(domain==='vocabulary')return `<div class="sheet-heading"><div class="eyebrow">${langName(x.language)} · 词汇</div><h2 id="lesson-detail-title" class="lexeme" lang="${x.language}">${esc(x.lemma)}</h2>${x.ipa||x.reading?`<p class="pronunciation">${esc(x.ipa?'/'+x.ipa+'/':x.reading)}</p>`:''}<p class="learner-meta">${esc(posNames[x.part_of_speech]||x.part_of_speech)} · ${esc(registerNames[x.register]||x.register)}</p></div>${section('意思与用法',x.senses.map(s=>`<article class="sense"><h3>${esc(s.meaning_zh)}</h3><p>${esc(s.usage_zh)}</p></article>`).join(''))}${section('常见搭配',x.examples.filter(e=>e.kind!=='example').map(e=>exampleHtml(e,x.language)).join(''))}${section('例句',x.examples.filter(e=>e.kind==='example').map(e=>exampleHtml(e,x.language)).join(''))}${section('相关词汇',relationCards(x.relations,'vocabulary'))}`;
 if(domain==='grammar')return `<div class="sheet-heading"><div class="eyebrow">${langName(x.language)} · 语法</div><h2 id="lesson-detail-title">${esc(x.title_zh)}</h2><p class="form" lang="${x.language}">${esc(x.form_name)}</p></div>${section('意思与功能',`<p>${esc(x.core_zh)}</p><p>${esc(x.purpose_zh)}</p>`)}${section('基本结构',`<div class="formula" lang="${x.language}">${esc(x.formula)}</div>`)}${section('什么时候使用',`<p>${esc(x.when_zh)}</p>`)}${section('例句',x.examples.map(e=>exampleHtml(e,x.language)).join(''))}${section('相关语法',relationCards(x.relations,'grammar'))}`;
 const expression=x.expressions.find(e=>e.language===language)||x.expressions[0];
 const body=expression?(x.unit_type==='dialogue'?expression.turns.map(t=>`<div class="turn"><span class="speaker">${esc(t.speaker)}</span><p class="expression-preview" lang="${expression.language}">${esc(t.text)}</p></div>`).join(''):`<p class="expression sheet-expression" lang="${expression.language}">${esc(expression.text)}</p>${expression.ipa?`<p class="pronunciation">${esc(expression.ipa)}</p>`:''}${expression.language==='ja'&&expression.readings?.length?`<p class="reading" lang="ja">${reading(expression.text,expression.readings)}</p>`:''}`):'';
 return `<div class="sheet-heading"><div class="eyebrow">${esc(unitNames[x.unit_type]||'表达')}</div><h2 id="lesson-detail-title">${esc(x.anchor_zh)}</h2></div>${x.context_zh?section('使用情境',`<p>${esc(x.context_zh)}</p>`):''}${section('完整表达',body)}${expression?section('词汇',`<div class="chips">${expression.vocabulary_links.map(l=>`<a class="button" href="${detail('vocabulary',l.item_id,expression.language)}">${esc(l.lemma)}</a>`).join('')||'<span class="muted">暂无标注</span>'}</div>`):''}${expression?section('语法',`<div class="chips">${expression.grammar_links.map(l=>`<a class="button" href="${detail('grammar',l.grammar_id,expression.language)}">${esc(l.title_zh)}</a>`).join('')||'<span class="muted">暂无标注</span>'}</div>`):''}`;
}
async function showLesson(domain,id,{push=false,opener=null}={}){
 const dialog=ensureLessonDialog(),body=$('.sheet-body',dialog),request=++overlayRequest;
 if(opener)detailOpener=opener;
 body.innerHTML='<p class="status" role="status">正在加载详情…</p>';
 if(!dialog.open)dialog.showModal();
 if(push){const u=new URL(location.href);u.searchParams.set('detail',id);u.searchParams.set('detailType',domain);history.pushState({lesson:true},'',u);overlayPushed=true;}
 else overlayPushed=Boolean(history.state?.lesson);
 try{const x=(await api(domain+'/'+encodeURIComponent(id))).data;if(request!==overlayRequest)return;body.innerHTML=overlayContent(domain,x,examContext?.language||x.language);$('.sheet-close',dialog).textContent=`← 返回${examDomains[domain]}`;}
 catch(e){if(request!==overlayRequest)return;body.innerHTML=`<div class="error" role="alert"><h2 id="lesson-detail-title">详情暂时无法打开</h2><p>${esc(e.message)}</p></div>`;}
}
function bindExamCards(){document.querySelectorAll('.exam-card').forEach(a=>a.onclick=e=>{if(e.button!==0||e.metaKey||e.ctrlKey||e.shiftKey||e.altKey)return;e.preventDefault();showLesson(a.dataset.domain,a.dataset.detail,{push:true,opener:a});});}
function examFilters(domain,topics,key,target){
 const hidden=`<input type="hidden" name="${key}" value="${esc(target)}"><input type="hidden" name="tab" value="${domain}">`;
 const extra=domain==='vocabulary'?select('part_of_speech','词性',Object.entries(posNames)):domain==='sentences'?select('topic','主题',topics.map(t=>[t.id,topicName(t)]))+select('unit_type','表达类型',[['sentence','一句话'],['scenario','情境'],['dialogue','对话']]):'';
 return `<form class="filters exam-filters" method="get">${hidden}<div class="filter-row"><label class="search-label">搜索${examDomains[domain]}<input type="search" name="search" value="${esc(currentParams().search)}" placeholder="${domain==='vocabulary'?'输入词汇或中文意思':domain==='grammar'?'输入语法形式或功能':'输入中文意思或目标语言'}" maxlength="100"></label>${extra}<button class="primary" type="submit">搜索</button><a class="button" href="${esc(examUrl(page,{[key]:target,tab:domain}))}">清除</a></div></form>`;
}
async function exam(){
 const state=currentParams(),framework=page==='ielts'?'IELTS':'JLPT',language=framework==='IELTS'?'en':'ja',targets=framework==='IELTS'?['5.0','5.5','6.0','6.5','7.0+']:['N5','N4','N3','N2','N1'],key=framework==='IELTS'?'target':'level',fallback=framework==='IELTS'?'6.5':'N4',target=targets.includes(state[key])?state[key]:fallback,domain=examDomains[state.tab]?state.tab:'vocabulary',shown=Math.max(pageSize,Math.min(2400,Number(state.shown)||pageSize));
 const topics=domain==='sentences'?(await api('academic/topics')).data:[];
 const query={framework,target,domain};
 for(const k of ['search','part_of_speech','topic','unit_type'])if(state[k])query[k]=state[k];
 const first={data:[],pagination:{limit:pageSize,offset:0,has_more:false,next_offset:null}};
 while(first.data.length<shown){const batch=await api('academic/alignments?'+new URLSearchParams({...query,limit:Math.min(100,shown-first.data.length),offset:first.data.length}));first.data.push(...batch.data);first.pagination=batch.pagination;if(!batch.pagination.has_more||!batch.data.length)break;}
 examContext={framework,target,language,domain,key};
 const targetNav=`<nav class="pills target-nav" aria-label="${framework} 学习目标">${targets.map(t=>`<a class="${target===t?'active':''}" ${target===t?'aria-current="page"':''} href="${esc(examUrl(page,{[key]:t,tab:domain}))}">${framework==='IELTS'?'Band ':''}${esc(t)}</a>`).join('')}</nav>`;
 const tabs=`<nav class="tabs exam-tabs" aria-label="课程内容">${Object.entries(examDomains).map(([d,n])=>`<a class="${domain===d?'active':''}" role="tab" aria-selected="${domain===d}" href="${esc(examUrl(page,{[key]:target,tab:d}))}">${n}</a>`).join('')}</nav>`;
 const clear=examUrl(page,{[key]:target,tab:domain});
 $('#main').innerHTML=`<div class="breadcrumb"><a href="/academic.html">学术 / 考试</a> / ${framework}</div><header class="exam-heading"><div><div class="eyebrow">${language==='en'?'English':'日本語'}</div><h1>${framework} ${esc(target)}</h1></div><a class="about-link" href="/academic-about.html">关于考试目标</a></header>${targetNav}${tabs}${examFilters(domain,topics,key,target)}<p class="results-note" id="result-count" aria-live="polite">已显示 ${first.data.length} 项${first.pagination.has_more?'，可以继续加载':''}</p><div class="grid exam-grid" id="exam-results">${first.data.map(a=>examCard(domain,a)).join('')||`<div class="empty"><h2>还没有匹配的内容</h2><p>试试更换搜索或筛选条件。</p><a class="button" href="${esc(clear)}">清除筛选</a></div>`}</div>${first.pagination.has_more?'<div class="load-more-wrap"><button id="load-more" type="button">加载更多</button></div>':''}`;
 bindExamCards();
 if($('#load-more')){let offset=first.pagination.next_offset;$('#load-more').onclick=async()=>{const button=$('#load-more');button.disabled=true;button.textContent='正在加载…';try{const more=await api('academic/alignments?'+new URLSearchParams({...query,limit:pageSize,offset}));$('#exam-results').insertAdjacentHTML('beforeend',more.data.map(a=>examCard(domain,a)).join(''));bindExamCards();offset=more.pagination.next_offset;button.hidden=!more.pagination.has_more;button.textContent='加载更多';const count=document.querySelectorAll('.exam-card').length;$('#result-count').textContent=`已显示 ${count} 项${more.pagination.has_more?'，可以继续加载':''}`;const u=new URL(location.href);u.searchParams.set('shown',String(count));history.replaceState(history.state,'',u);}catch(e){button.textContent='加载失败，点击重试';}finally{button.disabled=false;}};}
 const detailId=state.detail,detailType=state.detailType;if(detailId&&examDomains[detailType])await showLesson(detailType,detailId);
}
async function progress(){
 $('#main').innerHTML=heading('Your learning, in perspective','我的学习','英语与日语分开记录。新领域档案正在准备，现有学习记录继续可用。')+`<div class="grid two">${profile('en',true)}${profile('ja',true)}</div><section class="section card"><h2>原版学习记录</h2><p>继续使用已有定位、推荐与主题检查；这里不会把原版掌握度推算成新领域成绩。</p><div class="actions"><a class="button primary" href="/legacy/progress.html">旧版学习（兼容） · 查看进度</a><a class="button" href="/legacy/placement.html">旧版学习（兼容） · 能力定位</a><a class="button" href="/legacy/learn.html">旧版学习（兼容）</a></div></section><section class="section"><h2>想给下一步一个方向？</h2><div class="grid two"><a class="card" href="/ielts.html"><h3>English · IELTS 目标</h3><p class="muted">尚未设置目标</p></a><a class="card" href="/jlpt.html"><h3>日本語 · JLPT 目标</h3><p class="muted">尚未设置目标</p></a></div></section>`;
}
async function ai(){
 let context=null;if(p.type||p.id){if(!names[p.type]||!p.id||!['en','ja'].includes(p.lang))throw Error('练习上下文无效，请从内容详情重新进入。');context=(await api(p.type+'/'+encodeURIComponent(p.id))).data;if(p.type!=='sentences'&&context.language!==p.lang)throw Error('练习语言与内容不一致。');if(p.type==='sentences'&&!context.expressions.some(e=>e.language===p.lang))throw Error('此内容没有所选语言表达。');}
 const label=context?(context.lemma||context.title_zh||context.anchor_zh):'选择一个想练习的方向';
 const modes=[['自由造句','把学到的内容用出来'],['情境回答','换一个真实场景'],['表达优化','让语气更自然'],['词汇 / 语法问答','把不明白的地方问清楚']];
 const prompts=p.type==='vocabulary'?['用这个词造句','区别近义词','学术表达练习']:p.type==='grammar'?['造句','改错','情境练习','问这个语法']:p.type==='sentences'?['自己翻译','换一种说法','情境回答','解释表达差异']:['写一句今天想说的话','尝试一个生活情境'];
 $('#main').innerHTML=heading('Practice with understanding','给表达，留一个练习空间','先体验练习方式。当前尚未连接 AI，不会发送你的文字，也不会评分。')+badge('Preview · 尚未连接 AI','preview')+`<div class="mode-grid" aria-label="练习方式">${modes.map(([n,d],i)=>`<button data-mode="${i}" aria-pressed="${i===0}"><strong>${n}</strong><small>${d}</small></button>`).join('')}</div><div class="ai-workspace"><section class="card"><div class="context-pill">${context?badge(names[p.type]+' · '+langName(p.lang)):badge('自由练习')}<h2>${esc(label)}</h2>${context?`<a class="text-link" href="${detail(p.type,p.id,p.lang)}">返回学习内容 →</a>`:''}</div><div class="chips">${prompts.map(n=>`<button class="prompt">${n}</button>`).join('')}</div><form id="ai-form"><label for="practice-input"><h3 id="input-title">试着写一句话</h3></label><textarea id="practice-input" maxlength="2000" placeholder="这里只是界面预览。输入内容不会提交给 AI，也不会保存。"></textarea><p class="muted">演示反馈是固定样例，与输入无关。</p><button class="primary" type="submit">查看固定反馈示例</button></form></section><section class="card" id="feedback" aria-live="polite"><h2>反馈会在这里展开</h2>${badge('固定样例 · 非实时反馈','preview')}<p class="muted">你可以查看反馈组件示例，了解未来的练习方式。</p><div id="feedback-content" hidden><p>示例输入：I very like this idea.</p>${[['意思','示例：意思可理解'],['语法','示例：副词位置可调整'],['自然度','示例：改用 really like'],['语域','示例：日常交流'],['词汇','示例：really 表示程度']].map(([n,v])=>`<div class="feedback-row"><strong>${n}</strong><span>${v}</span></div>`).join('')}<div class="example"><h3>建议表达 · 固定演示</h3><p lang="en">I really like this idea.</p><p>说明：英语一般不直接用 very 修饰 like。这是展示组件的预写示例，不是对你输入的评判。</p></div></div></section></div>`;
 document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-mode]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));$('#input-title').textContent=['试着写一句话','你会怎样回应这个情境？','写下想优化的表达','写下你的词汇或语法问题'][Number(b.dataset.mode)];});
 document.querySelectorAll('.prompt').forEach(b=>b.onclick=()=>{$('#input-title').textContent=b.textContent;$('#practice-input').focus();});
 $('#ai-form').onsubmit=e=>{e.preventDefault();$('#feedback-content').hidden=false;$('#feedback').scrollIntoView({behavior:'smooth',block:'nearest'});};
}
window.addEventListener('popstate',()=>{
 if(!['ielts','jlpt'].includes(page))return;
 const state=currentParams(),dialog=$('#lesson-detail');
 if(state.detail&&examDomains[state.detailType])showLesson(state.detailType,state.detail);
 else if(dialog?.open){overlayPushed=false;dialog.close();detailOpener?.focus();}
});
load(()=>page==='index'?home():['vocabulary','grammar','sentences'].includes(page)?library(page):page==='vocabulary-detail'?detailPage('vocabulary'):page==='grammar-detail'?detailPage('grammar'):page==='sentence'?detailPage('sentences'):page==='academic'?academicHub():page==='academic-about'?academicAbout():['ielts','jlpt'].includes(page)?exam():page==='progress'?progress():ai());

