-- Additional practical sentence completion, original-Concept checkpoint coverage, vocabulary metadata.
INSERT INTO placement_questions (id,language,difficulty,concept_id,type,prompt,target_text,sort_order,purpose) VALUES ('p3-completion-en-1','en',1,2,'句子补全','你刚醒来，向朋友说明自己的状态。','I just ___ up.',1000,'placement');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-completion-en-1',0,'wake');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-completion-en-1',1,'woke');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-completion-en-1',2,'waking');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-completion-en-1',3,'will wake');
INSERT INTO placement_answer_keys (question_id,correct_option) VALUES ('p3-completion-en-1',1);
INSERT INTO placement_questions (id,language,difficulty,concept_id,type,prompt,target_text,sort_order,purpose) VALUES ('p3-completion-en-2','en',1,16,'句子补全','第一次见面，说自己的名字。','My ___ is Mei.',1001,'placement');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-completion-en-2',0,'time');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-completion-en-2',1,'way');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-completion-en-2',2,'name');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-completion-en-2',3,'turn');
INSERT INTO placement_answer_keys (question_id,correct_option) VALUES ('p3-completion-en-2',2);
INSERT INTO placement_questions (id,language,difficulty,concept_id,type,prompt,target_text,sort_order,purpose) VALUES ('p3-completion-en-3','en',2,42,'句子补全','同事问任务进度，你正在处理它。','I''m working ___ it.',1002,'placement');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-completion-en-3',0,'on');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-completion-en-3',1,'from');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-completion-en-3',2,'by');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-completion-en-3',3,'with');
INSERT INTO placement_answer_keys (question_id,correct_option) VALUES ('p3-completion-en-3',0);
INSERT INTO placement_questions (id,language,difficulty,concept_id,type,prompt,target_text,sort_order,purpose) VALUES ('p3-completion-en-4','en',2,78,'句子补全','问店员同款有没有更小的尺码。','Do you have this ___ a smaller size?',1003,'placement');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-completion-en-4',0,'at');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-completion-en-4',1,'for');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-completion-en-4',2,'by');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-completion-en-4',3,'in');
INSERT INTO placement_answer_keys (question_id,correct_option) VALUES ('p3-completion-en-4',3);
INSERT INTO placement_questions (id,language,difficulty,concept_id,type,prompt,target_text,sort_order,purpose) VALUES ('p3-completion-en-5','en',3,44,'句子补全','同事问报告是否完成，你还没写完。','I haven''t finished it ___.',1004,'placement');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-completion-en-5',0,'already');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-completion-en-5',1,'yet');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-completion-en-5',2,'ever');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-completion-en-5',3,'before');
INSERT INTO placement_answer_keys (question_id,correct_option) VALUES ('p3-completion-en-5',1);
INSERT INTO placement_questions (id,language,difficulty,concept_id,type,prompt,target_text,sort_order,purpose) VALUES ('p3-completion-en-6','en',3,92,'句子补全','告诉朋友从这里去车站需要半小时。','It ___ half an hour to get there.',1005,'placement');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-completion-en-6',0,'makes');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-completion-en-6',1,'keeps');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-completion-en-6',2,'takes');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-completion-en-6',3,'has');
INSERT INTO placement_answer_keys (question_id,correct_option) VALUES ('p3-completion-en-6',2);
INSERT INTO placement_questions (id,language,difficulty,concept_id,type,prompt,target_text,sort_order,purpose) VALUES ('p3-completion-en-7','en',4,71,'句子补全','你差一点错过末班车，最后赶上了。','I made it just ___ time for the last train.',1006,'placement');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-completion-en-7',0,'in');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-completion-en-7',1,'on');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-completion-en-7',2,'at');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-completion-en-7',3,'by');
INSERT INTO placement_answer_keys (question_id,correct_option) VALUES ('p3-completion-en-7',0);
INSERT INTO placement_questions (id,language,difficulty,concept_id,type,prompt,target_text,sort_order,purpose) VALUES ('p3-completion-en-8','en',4,179,'句子补全','结果和你的预想不同。','It turned ___ differently than I expected.',1007,'placement');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-completion-en-8',0,'over');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-completion-en-8',1,'off');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-completion-en-8',2,'in');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-completion-en-8',3,'out');
INSERT INTO placement_answer_keys (question_id,correct_option) VALUES ('p3-completion-en-8',3);
INSERT INTO placement_questions (id,language,difficulty,concept_id,type,prompt,target_text,sort_order,purpose) VALUES ('p3-completion-en-9','en',5,178,'句子补全','你很高兴下周能见到朋友。','I''m looking forward to ___ you.',1008,'placement');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-completion-en-9',0,'see');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-completion-en-9',1,'seeing');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-completion-en-9',2,'saw');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-completion-en-9',3,'seen');
INSERT INTO placement_answer_keys (question_id,correct_option) VALUES ('p3-completion-en-9',1);
INSERT INTO placement_questions (id,language,difficulty,concept_id,type,prompt,target_text,sort_order,purpose) VALUES ('p3-completion-en-10','en',5,180,'句子补全','解释过去未能参加，因为当时需要工作。','I ___ joined you, but I had to work.',1009,'placement');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-completion-en-10',0,'will have');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-completion-en-10',1,'am going to');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-completion-en-10',2,'would have');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-completion-en-10',3,'have to');
INSERT INTO placement_answer_keys (question_id,correct_option) VALUES ('p3-completion-en-10',2);
INSERT INTO placement_questions (id,language,difficulty,concept_id,type,prompt,target_text,sort_order,purpose) VALUES ('p3-completion-en-11','en',6,38,'句子补全','描述这种味道需要适应后才会欣赏。','It''s ___ taste.',1010,'placement');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-completion-en-11',0,'an acquired');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-completion-en-11',1,'a required');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-completion-en-11',2,'an expected');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-completion-en-11',3,'a requested');
INSERT INTO placement_answer_keys (question_id,correct_option) VALUES ('p3-completion-en-11',0);
INSERT INTO placement_questions (id,language,difficulty,concept_id,type,prompt,target_text,sort_order,purpose) VALUES ('p3-completion-en-12','en',6,182,'句子补全','事后回顾，你觉得当时应该多等一会儿。','In hindsight, I ___ waited.',1011,'placement');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-completion-en-12',0,'must wait');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-completion-en-12',1,'will have');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-completion-en-12',2,'was waiting');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-completion-en-12',3,'should have');
INSERT INTO placement_answer_keys (question_id,correct_option) VALUES ('p3-completion-en-12',3);
INSERT INTO placement_questions (id,language,difficulty,concept_id,type,prompt,target_text,sort_order,purpose) VALUES ('p3-original-en-1','en',2,1,'自然表达选择','要表达「你在干嘛？」，哪项最合适？',NULL,1012,'checkpoint');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-en-1',0,'I just woke up.');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-en-1',1,'What are you doing?');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-en-1',2,'I’m a little tired.');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-en-1',3,'I don’t know.');
INSERT INTO placement_answer_keys (question_id,correct_option) VALUES ('p3-original-en-1',1);
INSERT INTO placement_questions (id,language,difficulty,concept_id,type,prompt,target_text,sort_order,purpose) VALUES ('p3-original-en-2','en',2,2,'自然表达选择','要表达「我刚起床。」，哪项最合适？',NULL,1013,'checkpoint');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-en-2',0,'What are you doing?');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-en-2',1,'I’m a little tired.');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-en-2',2,'I just woke up.');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-en-2',3,'I don’t know.');
INSERT INTO placement_answer_keys (question_id,correct_option) VALUES ('p3-original-en-2',2);
INSERT INTO placement_questions (id,language,difficulty,concept_id,type,prompt,target_text,sort_order,purpose) VALUES ('p3-original-en-3','en',1,3,'自然表达选择','要表达「我有点累。」，哪项最合适？',NULL,1014,'checkpoint');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-en-3',0,'What are you doing?');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-en-3',1,'I just woke up.');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-en-3',2,'I don’t know.');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-en-3',3,'I’m a little tired.');
INSERT INTO placement_answer_keys (question_id,correct_option) VALUES ('p3-original-en-3',3);
INSERT INTO placement_questions (id,language,difficulty,concept_id,type,prompt,target_text,sort_order,purpose) VALUES ('p3-original-en-4','en',1,4,'自然表达选择','要表达「我不知道。」，哪项最合适？',NULL,1015,'checkpoint');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-en-4',0,'I don’t know.');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-en-4',1,'What are you doing?');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-en-4',2,'I just woke up.');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-en-4',3,'I’m a little tired.');
INSERT INTO placement_answer_keys (question_id,correct_option) VALUES ('p3-original-en-4',0);
INSERT INTO placement_questions (id,language,difficulty,concept_id,type,prompt,target_text,sort_order,purpose) VALUES ('p3-original-en-5','en',1,5,'自然表达选择','要表达「等一下。」，哪项最合适？',NULL,1016,'checkpoint');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-en-5',0,'What are you doing?');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-en-5',1,'Wait a second.');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-en-5',2,'I just woke up.');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-en-5',3,'I’m a little tired.');
INSERT INTO placement_answer_keys (question_id,correct_option) VALUES ('p3-original-en-5',1);
INSERT INTO placement_questions (id,language,difficulty,concept_id,type,prompt,target_text,sort_order,purpose) VALUES ('p3-original-en-6','en',1,6,'自然表达选择','要表达「我饿了。」，哪项最合适？',NULL,1017,'checkpoint');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-en-6',0,'What do you want to eat?');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-en-6',1,'I haven’t eaten yet.');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-en-6',2,'I’m hungry.');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-en-6',3,'Is this spicy?');
INSERT INTO placement_answer_keys (question_id,correct_option) VALUES ('p3-original-en-6',2);
INSERT INTO placement_questions (id,language,difficulty,concept_id,type,prompt,target_text,sort_order,purpose) VALUES ('p3-original-en-7','en',2,7,'自然表达选择','要表达「你想吃什么？」，哪项最合适？',NULL,1018,'checkpoint');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-en-7',0,'I’m hungry.');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-en-7',1,'I haven’t eaten yet.');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-en-7',2,'Is this spicy?');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-en-7',3,'What do you want to eat?');
INSERT INTO placement_answer_keys (question_id,correct_option) VALUES ('p3-original-en-7',3);
INSERT INTO placement_questions (id,language,difficulty,concept_id,type,prompt,target_text,sort_order,purpose) VALUES ('p3-original-en-8','en',3,8,'自然表达选择','要表达「我还没吃饭。」，哪项最合适？',NULL,1019,'checkpoint');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-en-8',0,'I haven’t eaten yet.');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-en-8',1,'I’m hungry.');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-en-8',2,'What do you want to eat?');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-en-8',3,'Is this spicy?');
INSERT INTO placement_answer_keys (question_id,correct_option) VALUES ('p3-original-en-8',0);
INSERT INTO placement_questions (id,language,difficulty,concept_id,type,prompt,target_text,sort_order,purpose) VALUES ('p3-original-en-9','en',1,9,'自然表达选择','要表达「这个辣吗？」，哪项最合适？',NULL,1020,'checkpoint');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-en-9',0,'I’m hungry.');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-en-9',1,'Is this spicy?');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-en-9',2,'What do you want to eat?');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-en-9',3,'I haven’t eaten yet.');
INSERT INTO placement_answer_keys (question_id,correct_option) VALUES ('p3-original-en-9',1);
INSERT INTO placement_questions (id,language,difficulty,concept_id,type,prompt,target_text,sort_order,purpose) VALUES ('p3-original-en-10','en',1,10,'自然表达选择','要表达「我吃饱了。」，哪项最合适？',NULL,1021,'checkpoint');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-en-10',0,'I’m hungry.');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-en-10',1,'What do you want to eat?');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-en-10',2,'I’m full.');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-en-10',3,'I haven’t eaten yet.');
INSERT INTO placement_answer_keys (question_id,correct_option) VALUES ('p3-original-en-10',2);
INSERT INTO placement_questions (id,language,difficulty,concept_id,type,prompt,target_text,sort_order,purpose) VALUES ('p3-original-en-11','en',2,11,'自然表达选择','要表达「今天有课吗？」，哪项最合适？',NULL,1022,'checkpoint');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-en-11',0,'I’m late.');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-en-11',1,'I don’t understand what you’re saying.');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-en-11',2,'When is it due?');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-en-11',3,'Do we have class today?');
INSERT INTO placement_answer_keys (question_id,correct_option) VALUES ('p3-original-en-11',3);
INSERT INTO placement_questions (id,language,difficulty,concept_id,type,prompt,target_text,sort_order,purpose) VALUES ('p3-original-en-12','en',1,12,'自然表达选择','要表达「我迟到了。」，哪项最合适？',NULL,1023,'checkpoint');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-en-12',0,'I’m late.');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-en-12',1,'Do we have class today?');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-en-12',2,'I don’t understand what you’re saying.');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-en-12',3,'When is it due?');
INSERT INTO placement_answer_keys (question_id,correct_option) VALUES ('p3-original-en-12',0);
INSERT INTO placement_questions (id,language,difficulty,concept_id,type,prompt,target_text,sort_order,purpose) VALUES ('p3-original-en-13','en',3,13,'自然表达选择','要表达「我听不懂。」，哪项最合适？',NULL,1024,'checkpoint');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-en-13',0,'Do we have class today?');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-en-13',1,'I don’t understand what you’re saying.');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-en-13',2,'I’m late.');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-en-13',3,'When is it due?');
INSERT INTO placement_answer_keys (question_id,correct_option) VALUES ('p3-original-en-13',1);
INSERT INTO placement_questions (id,language,difficulty,concept_id,type,prompt,target_text,sort_order,purpose) VALUES ('p3-original-en-14','en',2,14,'自然表达选择','要表达「什么时候截止？」，哪项最合适？',NULL,1025,'checkpoint');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-en-14',0,'Do we have class today?');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-en-14',1,'I’m late.');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-en-14',2,'When is it due?');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-en-14',3,'I don’t understand what you’re saying.');
INSERT INTO placement_answer_keys (question_id,correct_option) VALUES ('p3-original-en-14',2);
INSERT INTO placement_questions (id,language,difficulty,concept_id,type,prompt,target_text,sort_order,purpose) VALUES ('p3-original-en-15','en',3,15,'自然表达选择','要表达「我还没写作业。」，哪项最合适？',NULL,1026,'checkpoint');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-en-15',0,'Do we have class today?');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-en-15',1,'I’m late.');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-en-15',2,'I don’t understand what you’re saying.');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-en-15',3,'I haven’t done my homework yet.');
INSERT INTO placement_answer_keys (question_id,correct_option) VALUES ('p3-original-en-15',3);
INSERT INTO placement_questions (id,language,difficulty,concept_id,type,prompt,target_text,sort_order,purpose) VALUES ('p3-completion-ja-1','ja',1,16,'句子补全','初次见面，说自己叫梅。','名前___メイです。',1027,'placement');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-completion-ja-1',0,'を');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-completion-ja-1',1,'は');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-completion-ja-1',2,'に');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-completion-ja-1',3,'で');
INSERT INTO placement_answer_keys (question_id,correct_option) VALUES ('p3-completion-ja-1',1);
INSERT INTO placement_questions (id,language,difficulty,concept_id,type,prompt,target_text,sort_order,purpose) VALUES ('p3-completion-ja-2','ja',1,114,'句子补全','告诉朋友自己有点头疼。','少し頭___痛いです。',1028,'placement');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-completion-ja-2',0,'を');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-completion-ja-2',1,'に');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-completion-ja-2',2,'が');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-completion-ja-2',3,'で');
INSERT INTO placement_answer_keys (question_id,correct_option) VALUES ('p3-completion-ja-2',2);
INSERT INTO placement_questions (id,language,difficulty,concept_id,type,prompt,target_text,sort_order,purpose) VALUES ('p3-completion-ja-3','ja',2,78,'句子补全','在店里问有没有小一点的尺码。','小さいサイズは___か。',1029,'placement');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-completion-ja-3',0,'あります');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-completion-ja-3',1,'います');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-completion-ja-3',2,'なります');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-completion-ja-3',3,'します');
INSERT INTO placement_answer_keys (question_id,correct_option) VALUES ('p3-completion-ja-3',0);
INSERT INTO placement_questions (id,language,difficulty,concept_id,type,prompt,target_text,sort_order,purpose) VALUES ('p3-completion-ja-4','ja',2,174,'句子补全','明天打算在家做饭。','明日は料理をする___です。',1030,'placement');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-completion-ja-4',0,'ところでした');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-completion-ja-4',1,'はずでした');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-completion-ja-4',2,'わけでした');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-completion-ja-4',3,'つもり');
INSERT INTO placement_answer_keys (question_id,correct_option) VALUES ('p3-completion-ja-4',3);
INSERT INTO placement_questions (id,language,difficulty,concept_id,type,prompt,target_text,sort_order,purpose) VALUES ('p3-completion-ja-5','ja',3,176,'句子补全','问对方是否有过露营经历。','キャンプを___ことがありますか。',1031,'placement');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-completion-ja-5',0,'するつもりの');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-completion-ja-5',1,'した');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-completion-ja-5',2,'している間の');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-completion-ja-5',3,'してからの');
INSERT INTO placement_answer_keys (question_id,correct_option) VALUES ('p3-completion-ja-5',1);
INSERT INTO placement_questions (id,language,difficulty,concept_id,type,prompt,target_text,sort_order,purpose) VALUES ('p3-completion-ja-6','ja',3,44,'句子补全','向同事说明报告还没写完。','まだ報告書を書き終えて___。',1032,'placement');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-completion-ja-6',0,'いました');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-completion-ja-6',1,'おきました');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-completion-ja-6',2,'いません');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-completion-ja-6',3,'しまいました');
INSERT INTO placement_answer_keys (question_id,correct_option) VALUES ('p3-completion-ja-6',2);
INSERT INTO placement_questions (id,language,difficulty,concept_id,type,prompt,target_text,sort_order,purpose) VALUES ('p3-completion-ja-7','ja',4,177,'句子补全','原本想出门，后来自己决定留在家里。','家で過ごすこと___した。',1033,'placement');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-completion-ja-7',0,'に');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-completion-ja-7',1,'が');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-completion-ja-7',2,'を');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-completion-ja-7',3,'で');
INSERT INTO placement_answer_keys (question_id,correct_option) VALUES ('p3-completion-ja-7',0);
INSERT INTO placement_questions (id,language,difficulty,concept_id,type,prompt,target_text,sort_order,purpose) VALUES ('p3-completion-ja-8','ja',4,71,'句子补全','差一点没赶上，但最终赶上了末班车。','終電に___間に合いました。',1034,'placement');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-completion-ja-8',0,'そろそろ');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-completion-ja-8',1,'とっくに');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-completion-ja-8',2,'ゆっくり');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-completion-ja-8',3,'ぎりぎり');
INSERT INTO placement_answer_keys (question_id,correct_option) VALUES ('p3-completion-ja-8',3);
INSERT INTO placement_questions (id,language,difficulty,concept_id,type,prompt,target_text,sort_order,purpose) VALUES ('p3-completion-ja-9','ja',5,178,'句子补全','期待将来见到对方，请补全自然说法。','会えるのを楽しみ___しています。',1035,'placement');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-completion-ja-9',0,'を');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-completion-ja-9',1,'に');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-completion-ja-9',2,'が');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-completion-ja-9',3,'で');
INSERT INTO placement_answer_keys (question_id,correct_option) VALUES ('p3-completion-ja-9',1);
INSERT INTO placement_questions (id,language,difficulty,concept_id,type,prompt,target_text,sort_order,purpose) VALUES ('p3-completion-ja-10','ja',5,144,'句子补全','越练习越觉得有趣。','練習すればする___、楽しくなります。',1036,'placement');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-completion-ja-10',0,'だけでなく');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-completion-ja-10',1,'わけで');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-completion-ja-10',2,'ほど');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-completion-ja-10',3,'つもりで');
INSERT INTO placement_answer_keys (question_id,correct_option) VALUES ('p3-completion-ja-10',2);
INSERT INTO placement_questions (id,language,difficulty,concept_id,type,prompt,target_text,sort_order,purpose) VALUES ('p3-completion-ja-11','ja',6,182,'句子补全','回头看，觉得当时应该等一下。','今思えば、待てば___です。',1037,'placement');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-completion-ja-11',0,'よかった');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-completion-ja-11',1,'いいつもり');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-completion-ja-11',2,'よくなる予定');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-completion-ja-11',3,'いいはずがない');
INSERT INTO placement_answer_keys (question_id,correct_option) VALUES ('p3-completion-ja-11',0);
INSERT INTO placement_questions (id,language,difficulty,concept_id,type,prompt,target_text,sort_order,purpose) VALUES ('p3-completion-ja-12','ja',6,170,'句子补全','礼貌表示不想让对方因为自己的请求添麻烦。','ご迷惑を___したくないので。',1038,'placement');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-completion-ja-12',0,'お持ち');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-completion-ja-12',1,'お越し');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-completion-ja-12',2,'お見え');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-completion-ja-12',3,'おかけ');
INSERT INTO placement_answer_keys (question_id,correct_option) VALUES ('p3-completion-ja-12',3);
INSERT INTO placement_questions (id,language,difficulty,concept_id,type,prompt,target_text,sort_order,purpose) VALUES ('p3-original-ja-1','ja',2,1,'自然表达选择','要表达「你在干嘛？」，哪项最合适？',NULL,1039,'checkpoint');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-ja-1',0,'今起きたところ。');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-ja-1',1,'ちょっと疲れた。');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-ja-1',2,'何をしているの？');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-ja-1',3,'わからない。');
INSERT INTO placement_answer_keys (question_id,correct_option) VALUES ('p3-original-ja-1',2);
INSERT INTO placement_questions (id,language,difficulty,concept_id,type,prompt,target_text,sort_order,purpose) VALUES ('p3-original-ja-2','ja',3,2,'自然表达选择','要表达「我刚起床。」，哪项最合适？',NULL,1040,'checkpoint');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-ja-2',0,'何をしているの？');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-ja-2',1,'ちょっと疲れた。');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-ja-2',2,'わからない。');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-ja-2',3,'今起きたところ。');
INSERT INTO placement_answer_keys (question_id,correct_option) VALUES ('p3-original-ja-2',3);
INSERT INTO placement_questions (id,language,difficulty,concept_id,type,prompt,target_text,sort_order,purpose) VALUES ('p3-original-ja-3','ja',2,3,'自然表达选择','要表达「我有点累。」，哪项最合适？',NULL,1041,'checkpoint');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-ja-3',0,'ちょっと疲れた。');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-ja-3',1,'何をしているの？');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-ja-3',2,'今起きたところ。');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-ja-3',3,'わからない。');
INSERT INTO placement_answer_keys (question_id,correct_option) VALUES ('p3-original-ja-3',0);
INSERT INTO placement_questions (id,language,difficulty,concept_id,type,prompt,target_text,sort_order,purpose) VALUES ('p3-original-ja-4','ja',1,4,'自然表达选择','要表达「我不知道。」，哪项最合适？',NULL,1042,'checkpoint');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-ja-4',0,'何をしているの？');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-ja-4',1,'わからない。');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-ja-4',2,'今起きたところ。');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-ja-4',3,'ちょっと疲れた。');
INSERT INTO placement_answer_keys (question_id,correct_option) VALUES ('p3-original-ja-4',1);
INSERT INTO placement_questions (id,language,difficulty,concept_id,type,prompt,target_text,sort_order,purpose) VALUES ('p3-original-ja-5','ja',2,5,'自然表达选择','要表达「等一下。」，哪项最合适？',NULL,1043,'checkpoint');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-ja-5',0,'何をしているの？');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-ja-5',1,'今起きたところ。');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-ja-5',2,'ちょっと待って。');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-ja-5',3,'ちょっと疲れた。');
INSERT INTO placement_answer_keys (question_id,correct_option) VALUES ('p3-original-ja-5',2);
INSERT INTO placement_questions (id,language,difficulty,concept_id,type,prompt,target_text,sort_order,purpose) VALUES ('p3-original-ja-6','ja',2,6,'自然表达选择','要表达「我饿了。」，哪项最合适？',NULL,1044,'checkpoint');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-ja-6',0,'何が食べたい？');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-ja-6',1,'まだ食べていません。');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-ja-6',2,'これは辛いですか？');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-ja-6',3,'お腹がすいた。');
INSERT INTO placement_answer_keys (question_id,correct_option) VALUES ('p3-original-ja-6',3);
INSERT INTO placement_questions (id,language,difficulty,concept_id,type,prompt,target_text,sort_order,purpose) VALUES ('p3-original-ja-7','ja',2,7,'自然表达选择','要表达「你想吃什么？」，哪项最合适？',NULL,1045,'checkpoint');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-ja-7',0,'何が食べたい？');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-ja-7',1,'お腹がすいた。');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-ja-7',2,'まだ食べていません。');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-ja-7',3,'これは辛いですか？');
INSERT INTO placement_answer_keys (question_id,correct_option) VALUES ('p3-original-ja-7',0);
INSERT INTO placement_questions (id,language,difficulty,concept_id,type,prompt,target_text,sort_order,purpose) VALUES ('p3-original-ja-8','ja',3,8,'自然表达选择','要表达「我还没吃饭。」，哪项最合适？',NULL,1046,'checkpoint');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-ja-8',0,'お腹がすいた。');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-ja-8',1,'まだ食べていません。');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-ja-8',2,'何が食べたい？');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-ja-8',3,'これは辛いですか？');
INSERT INTO placement_answer_keys (question_id,correct_option) VALUES ('p3-original-ja-8',1);
INSERT INTO placement_questions (id,language,difficulty,concept_id,type,prompt,target_text,sort_order,purpose) VALUES ('p3-original-ja-9','ja',1,9,'自然表达选择','要表达「这个辣吗？」，哪项最合适？',NULL,1047,'checkpoint');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-ja-9',0,'お腹がすいた。');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-ja-9',1,'何が食べたい？');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-ja-9',2,'これは辛いですか？');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-ja-9',3,'まだ食べていません。');
INSERT INTO placement_answer_keys (question_id,correct_option) VALUES ('p3-original-ja-9',2);
INSERT INTO placement_questions (id,language,difficulty,concept_id,type,prompt,target_text,sort_order,purpose) VALUES ('p3-original-ja-10','ja',1,10,'自然表达选择','要表达「我吃饱了。」，哪项最合适？',NULL,1048,'checkpoint');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-ja-10',0,'お腹がすいた。');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-ja-10',1,'何が食べたい？');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-ja-10',2,'まだ食べていません。');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-ja-10',3,'お腹がいっぱい。');
INSERT INTO placement_answer_keys (question_id,correct_option) VALUES ('p3-original-ja-10',3);
INSERT INTO placement_questions (id,language,difficulty,concept_id,type,prompt,target_text,sort_order,purpose) VALUES ('p3-original-ja-11','ja',2,11,'自然表达选择','要表达「今天有课吗？」，哪项最合适？',NULL,1049,'checkpoint');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-ja-11',0,'今日は授業がありますか？');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-ja-11',1,'遅れました。');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-ja-11',2,'言っていることがわかりません。');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-ja-11',3,'締め切りはいつですか？');
INSERT INTO placement_answer_keys (question_id,correct_option) VALUES ('p3-original-ja-11',0);
INSERT INTO placement_questions (id,language,difficulty,concept_id,type,prompt,target_text,sort_order,purpose) VALUES ('p3-original-ja-12','ja',2,12,'自然表达选择','要表达「我迟到了。」，哪项最合适？',NULL,1050,'checkpoint');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-ja-12',0,'今日は授業がありますか？');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-ja-12',1,'遅れました。');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-ja-12',2,'言っていることがわかりません。');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-ja-12',3,'締め切りはいつですか？');
INSERT INTO placement_answer_keys (question_id,correct_option) VALUES ('p3-original-ja-12',1);
INSERT INTO placement_questions (id,language,difficulty,concept_id,type,prompt,target_text,sort_order,purpose) VALUES ('p3-original-ja-13','ja',3,13,'自然表达选择','要表达「我听不懂。」，哪项最合适？',NULL,1051,'checkpoint');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-ja-13',0,'今日は授業がありますか？');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-ja-13',1,'遅れました。');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-ja-13',2,'言っていることがわかりません。');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-ja-13',3,'締め切りはいつですか？');
INSERT INTO placement_answer_keys (question_id,correct_option) VALUES ('p3-original-ja-13',2);
INSERT INTO placement_questions (id,language,difficulty,concept_id,type,prompt,target_text,sort_order,purpose) VALUES ('p3-original-ja-14','ja',2,14,'自然表达选择','要表达「什么时候截止？」，哪项最合适？',NULL,1052,'checkpoint');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-ja-14',0,'今日は授業がありますか？');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-ja-14',1,'遅れました。');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-ja-14',2,'言っていることがわかりません。');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-ja-14',3,'締め切りはいつですか？');
INSERT INTO placement_answer_keys (question_id,correct_option) VALUES ('p3-original-ja-14',3);
INSERT INTO placement_questions (id,language,difficulty,concept_id,type,prompt,target_text,sort_order,purpose) VALUES ('p3-original-ja-15','ja',3,15,'自然表达选择','要表达「我还没写作业。」，哪项最合适？',NULL,1053,'checkpoint');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-ja-15',0,'まだ宿題をしていません。');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-ja-15',1,'今日は授業がありますか？');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-ja-15',2,'遅れました。');
INSERT INTO placement_options (question_id,option_id,text) VALUES ('p3-original-ja-15',3,'言っていることがわかりません。');
INSERT INTO placement_answer_keys (question_id,correct_option) VALUES ('p3-original-ja-15',0);
UPDATE expressions SET metadata_json=json_set(metadata_json,'$.partOfSpeech','名词／名词短语') WHERE concept_id=16 AND language='en';
UPDATE expressions SET metadata_json=json_set(metadata_json,'$.partOfSpeech','名词／名词短语') WHERE concept_id=22 AND language='en';
UPDATE expressions SET metadata_json=json_set(metadata_json,'$.partOfSpeech','名词／名词短语') WHERE concept_id=28 AND language='en';
UPDATE expressions SET metadata_json=json_set(metadata_json,'$.partOfSpeech','形容词') WHERE concept_id=34 AND language='en';
UPDATE expressions SET metadata_json=json_set(metadata_json,'$.partOfSpeech','名词／名词短语') WHERE concept_id=40 AND language='en';
UPDATE expressions SET metadata_json=json_set(metadata_json,'$.partOfSpeech','名词／名词短语') WHERE concept_id=46 AND language='en';
UPDATE expressions SET metadata_json=json_set(metadata_json,'$.partOfSpeech','名词／名词短语') WHERE concept_id=52 AND language='en';
UPDATE expressions SET metadata_json=json_set(metadata_json,'$.partOfSpeech','名词／名词短语') WHERE concept_id=58 AND language='en';
UPDATE expressions SET metadata_json=json_set(metadata_json,'$.partOfSpeech','名词／名词短语') WHERE concept_id=64 AND language='en';
UPDATE expressions SET metadata_json=json_set(metadata_json,'$.partOfSpeech','名词／名词短语') WHERE concept_id=70 AND language='en';
UPDATE expressions SET metadata_json=json_set(metadata_json,'$.partOfSpeech','名词／名词短语') WHERE concept_id=76 AND language='en';
UPDATE expressions SET metadata_json=json_set(metadata_json,'$.partOfSpeech','名词／名词短语') WHERE concept_id=82 AND language='en';
UPDATE expressions SET metadata_json=json_set(metadata_json,'$.partOfSpeech','名词／名词短语') WHERE concept_id=88 AND language='en';
UPDATE expressions SET metadata_json=json_set(metadata_json,'$.partOfSpeech','名词／名词短语') WHERE concept_id=94 AND language='en';
UPDATE expressions SET metadata_json=json_set(metadata_json,'$.partOfSpeech','名词／名词短语') WHERE concept_id=100 AND language='en';
UPDATE expressions SET metadata_json=json_set(metadata_json,'$.partOfSpeech','形容词') WHERE concept_id=106 AND language='en';
UPDATE expressions SET metadata_json=json_set(metadata_json,'$.partOfSpeech','形容词') WHERE concept_id=112 AND language='en';
UPDATE expressions SET metadata_json=json_set(metadata_json,'$.partOfSpeech','形容词') WHERE concept_id=118 AND language='en';
UPDATE expressions SET metadata_json=json_set(metadata_json,'$.partOfSpeech','形容词') WHERE concept_id=124 AND language='en';
UPDATE expressions SET metadata_json=json_set(metadata_json,'$.partOfSpeech','形容词') WHERE concept_id=130 AND language='en';
UPDATE expressions SET metadata_json=json_set(metadata_json,'$.partOfSpeech','名词／名词短语') WHERE concept_id=136 AND language='en';
UPDATE expressions SET metadata_json=json_set(metadata_json,'$.partOfSpeech','动词短语') WHERE concept_id=142 AND language='en';
UPDATE expressions SET metadata_json=json_set(metadata_json,'$.partOfSpeech','名词／名词短语') WHERE concept_id=148 AND language='en';
UPDATE expressions SET metadata_json=json_set(metadata_json,'$.partOfSpeech','形容词') WHERE concept_id=154 AND language='en';
UPDATE expressions SET metadata_json=json_set(metadata_json,'$.partOfSpeech','名词／名词短语') WHERE concept_id=160 AND language='en';
UPDATE expressions SET metadata_json=json_set(metadata_json,'$.partOfSpeech','名词／名词短语') WHERE concept_id=166 AND language='en';
UPDATE expressions SET metadata_json=json_set(metadata_json,'$.partOfSpeech','名词／名词短语') WHERE concept_id=172 AND language='en';
UPDATE expressions SET metadata_json=json_set(metadata_json,'$.partOfSpeech','动词短语') WHERE concept_id=178 AND language='en';
UPDATE topics SET name='学校 / 工作', description='学习、协作与工作中的日常沟通' WHERE id='school';
