const KEY='kotoba.phase1.v1';
const fresh=()=>({levels:{en:null,ja:null},mastery:{en:{},ja:{}},last:1,activity:{}});
let state=fresh();
function restoreState(){try {const s=JSON.parse(localStorage.getItem(KEY));if(s&&typeof s==='object'){for(const l of ['en','ja']){const result=s.levels?.[l];if(Number.isInteger(result?.level)&&result.level>=1&&result.level<=6&&Number.isInteger(result.score)&&result.score>=0&&result.score<=12)state.levels[l]={level:result.level,score:result.score,date:typeof result.date==='string'?result.date:''};for(const c of concepts)if(['learned','review'].includes(s.mastery?.[l]?.[c.id]))state.mastery[l][c.id]=s.mastery[l][c.id];}if(concepts.some(c=>c.id===s.last))state.last=s.last;if(s.activity&&typeof s.activity==='object')state.activity=s.activity;}}catch{}}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));}catch{document.querySelector('#storage-warning').hidden=false;}}
function percent(lang,list=concepts){return Math.round(list.filter(c=>state.mastery[lang][c.id]==='learned').length/list.length*100);}
function level(lang){return state.levels[lang]?`Level ${state.levels[lang].level}`:'尚未定位';}
function ruby(tokens){return tokens.map(t=>t.reading?`<ruby>${escapeHtml(t.text)}<rt>${escapeHtml(t.reading)}</rt></ruby>`:escapeHtml(t.text)).join('');}
const page=document.body.dataset.page;
document.querySelector('#shell').innerHTML=`<header class="site-header"><a class="brand" href="index.html"><span class="brand-symbol">言</span>言间 <small>两种语言，一起学</small></a><nav aria-label="主导航">${[['home','index.html','首页'],['placement','placement.html','能力定位'],['learn','learn.html','学习'],['progress','progress.html','学习进度']].map(([p,url,t])=>`<a href="${url}" ${p===page?'aria-current="page"':''}>${t}</a>`).join('')}</nav></header><div id="storage-warning" class="notice" role="alert" hidden>浏览器无法保存进度。请允许此网站使用本地存储；当前页面仍可学习。</div>`;
document.querySelector('#footer').innerHTML='言间 · 从生活出发，让表达自然发生。<span>本地体验版 · 进度保存在此浏览器</span>';
function languageCard(lang){const name=lang==='en'?'English':'日本語';return `<div class="level-card ${lang}"><span class="eyebrow">${name}</span><strong>${level(lang)}</strong><span>${state.levels[lang]?'按自己的节奏，继续向前':'先了解你的起点'}</span></div>`;}
function home(){const c=concepts.find(c=>c.id===state.last);const recommended=concepts.find(c=>['en','ja'].some(l=>state.mastery[l][c.id]==='review'))||concepts.find(c=>['en','ja'].some(l=>state.mastery[l][c.id]!=='learned'))||concepts[0];document.querySelector('main').innerHTML=`<section class="intro"><div class="eyebrow">每一天，都多会说一点</div><h1>从熟悉的生活，<br>走进两种语言。</h1><p>以中文理解意思，用英语与日语，把同一份想法说自然。</p></section>${(!state.levels.en||!state.levels.ja)?'<a class="notice placement-prompt" href="placement.html"><div><strong>找到你的起点</strong><p>英语和日语分别定位，不必从同一个水平开始。</p></div><span>开始能力定位 →</span></a>':''}<section class="home-grid"><a class="continue-card" href="learn.html?id=${c.id}"><span class="eyebrow">${Object.keys(state.mastery.en).length+Object.keys(state.mastery.ja).length?'继续学习':'你的第一段对话'}</span><span class="topic-label">${escapeHtml(topics.find(t=>t.id===c.topic).name)} · ${String(c.id).padStart(2,'0')} / 15</span><h2>${escapeHtml(c.zh)}</h2><p>${escapeHtml(c.en)}</p><p lang="ja">${escapeHtml(c.ja)}</p><span class="primary link-button">进入学习 <span>↗</span></span></a><div class="level-stack">${languageCard('en')}${languageCard('ja')}</div></section><section class="recommendation"><span class="small-icon">✧</span><div><strong>今日推荐 · ${escapeHtml(recommended.zh)}</strong><p>${concepts.every(x=>state.mastery.en[x.id]==='learned'&&state.mastery.ja[x.id]==='learned')?'15 个情境都已学过。回到熟悉的表达，再比较一次两种语言的习惯。':'读一句表达，点开一个语法片段，再分别记录两种语言的掌握程度。'}</p><a class="text-link" href="learn.html?id=${recommended.id}">学习这句 →</a></div></section><section><div class="section-heading"><h2>把生活变成课堂</h2><span>3 个主题 · 15 个真实情境</span></div><div class="topic-grid">${topics.map(t=>`<a class="topic-card" href="learn.html?topic=${t.id}"><span class="topic-icon">${escapeHtml(t.icon)}</span><h3>${escapeHtml(t.name)} <span>↗</span></h3><p>${escapeHtml(t.description)}</p><div class="topic-foot">5 个情境 <span>英 ${percent('en',concepts.filter(c=>c.topic===t.id))}% · 日 ${percent('ja',concepts.filter(c=>c.topic===t.id))}%</span></div></a>`).join('')}</div></section>`;}
function progress(){document.querySelector('main').innerHTML=`<section class="page-intro"><span class="eyebrow">每一步，都算数</span><h1>看见自己的进步</h1><p>两种语言，各有节奏。「学会了」计入掌握进度，「不太会」留待复习。</p></section><div class="progress-grid">${['en','ja'].map(l=>`<section class="panel ${l}"><span class="eyebrow">${l==='en'?'English':'日本語'}</span><div class="section-heading"><h2>${level(l)}</h2><a href="placement.html?lang=${l}">${state.levels[l]?'重新定位':'开始定位'} ↗</a></div><strong class="big-number">${percent(l)}<small>%</small></strong><div class="meter"><span style="width:${percent(l)}%"></span></div><p>${concepts.filter(c=>state.mastery[l][c.id]==='learned').length} / 15 已掌握 · ${concepts.filter(c=>state.mastery[l][c.id]==='review').length} 待复习</p></section>`).join('')}</div><section><div class="section-heading"><h2>每个主题的足迹</h2><a href="learn.html">继续学习 →</a></div><div class="topic-grid">${topics.map(t=>`<div class="topic-card"><h3>${escapeHtml(t.name)}</h3>${['en','ja'].map(l=>`<div class="topic-progress ${l}"><div>${l==='en'?'English':'日本語'}<strong>${percent(l,concepts.filter(c=>c.topic===t.id))}%</strong></div><div class="meter"><span style="width:${percent(l,concepts.filter(c=>c.topic===t.id))}%"></span></div></div>`).join('')}<a class="text-link" href="learn.html?topic=${t.id}">学习这个主题 →</a></div>`).join('')}</div></section><section class="panel review-section"><h2>再熟悉一点</h2><p>只要有一种语言标记为「不太会」，这个情境就会留在这里。</p><div class="review-list">${concepts.filter(c=>['en','ja'].some(l=>state.mastery[l][c.id]==='review')).map(c=>`<a href="learn.html?id=${c.id}"><span>${escapeHtml(c.zh)}</span><small>${state.mastery.en[c.id]==='review'?'英语待复习 ':''}${state.mastery.ja[c.id]==='review'?'日语待复习':''} →</small></a>`).join('')||'<p>目前没有待复习的情境。去学一句，把自己的感受记录下来。</p><a class="text-link" href="learn.html">进入学习 →</a>'}</div></section>`;}
loading();
const appReady=loadContent().then(()=>{restoreState();if(page==='home')home();if(page==='progress')progress();return true;}).catch(error=>{contentError(error);return false;});

