let testLang=null,questionIndex=0,answers=[];
function placementLanding(){document.querySelector('main').innerHTML=`<section class="page-intro"><span class="eyebrow">找到适合自己的起点</span><h1>两种语言，分别出发</h1><p>每种语言 12 道生活情境题。按第一感觉选择，不确定也没关系。</p></section><div class="notice">这是体验版的简易定位，不是考试或正式能力认证。两种语言独立计分；重新完成一种语言的测试，不会改变另一种语言的结果。</div><div class="progress-grid">${['en','ja'].map(l=>`<section class="panel ${l}"><span class="eyebrow">${l==='en'?'English':'日本語'}</span><h2>${level(l)}</h2><p>${state.levels[l]?levelDescriptions[state.levels[l].level-1]:'用熟悉的日常情境，了解目前的理解程度。'}</p>${state.levels[l]?`<p class="result-score">${state.levels[l].score} / 12 题正确 · ${Math.round(state.levels[l].score/12*100)}%</p><p>推荐起点：难度 ${state.levels[l].level}。${state.levels[l].level>3?'本期内容为难度 1–3，可用于巩固自然表达。':'可以从本期相近难度的表达开始。'}</p>`:'<p>约 3 分钟 · 12 道题 · 可返回修改答案</p>'}<button class="primary start-test" data-lang="${l}">${state.levels[l]?'重新定位':'开始定位'} ${l==='en'?'英语':'日语'} →</button></section>`).join('')}</div>${state.levels.en&&state.levels.ja?'<div class="result-note"><h2>起点可以不同，学习可以一起</h2><p>在同一个情境中，分别记录英语和日语的掌握情况。</p><a class="primary link-button" href="learn.html">开始学习 →</a></div>':''}`;document.querySelectorAll('.start-test').forEach(b=>b.onclick=()=>startTest(b.dataset.lang));}
function renderQuestion(){const q=placementQuestions[testLang][questionIndex];document.querySelector('main').innerHTML=`<section class="test-wrap"><div class="section-heading"><span class="eyebrow">${testLang==='en'?'English · 英语定位':'日本語 · 日语定位'}</span><button id="exit-test" class="subtle">退出本次测试</button></div><div class="test-count">第 ${questionIndex+1} / 12 题<span>${escapeHtml(q.type)}</span></div><div class="meter"><span style="width:${(questionIndex+1)/12*100}%"></span></div><h1>${escapeHtml(q.prompt)}</h1><fieldset><legend class="sr-only">选择最合适的答案</legend>${q.options.map((a,index)=>`<label class="answer ${answers[questionIndex]===a.id?'chosen':''}"><input type="radio" name="answer" value="${a.id}" ${answers[questionIndex]===a.id?'checked':''}><span class="answer-letter">${String.fromCharCode(65+index)}</span><span>${escapeHtml(a.text)}</span></label>`).join('')}</fieldset><p class="test-hint">不确定时也可以选择最接近的答案。结果只用来帮助你开始。</p><div class="section-heading"><button id="back-question" class="secondary" ${questionIndex===0?'disabled':''}>← 上一题</button><button id="next-question" class="primary" ${answers[questionIndex]===null?'disabled':''}>${questionIndex===11?'完成并查看结果':'下一题 →'}</button></div><p class="muted">完成 12 题后保存结果。退出将放弃本次答案，保留之前的定位。</p></section>`;
document.querySelectorAll('[name="answer"]').forEach(r=>r.onchange=()=>{answers[questionIndex]=Number(r.value);document.querySelectorAll('.answer').forEach(l=>l.classList.toggle('chosen',l.contains(r)));document.querySelector('#next-question').disabled=false;});
document.querySelector('#back-question').onclick=()=>{questionIndex--;renderQuestion();};document.querySelector('#exit-test').onclick=()=>{testLang=null;placementLanding();};document.querySelector('#next-question').onclick=async()=>{if(answers[questionIndex]===null)return;if(questionIndex<11){questionIndex++;renderQuestion();}else{await submitAnswers();}window.scrollTo(0,0);};}
appReady.then(ready=>{if(!ready)return;placementLanding();
const requested=new URLSearchParams(location.search).get('lang');if(['en','ja'].includes(requested))document.querySelector(`[data-lang="${requested}"]`).focus();

}).catch(error=>contentError(error));

async function startTest(lang){
 testLang=lang;loading('正在加载测试题目…');
 try {const questions=await api('/placement/questions?lang='+lang);if(!Array.isArray(questions)||questions.length!==12)throw Error('测试内容暂不可用，请重试。');placementQuestions[lang]=questions;questionIndex=0;answers=Array(questions.length).fill(null);renderQuestion();}
 catch(error){contentError(error,()=>startTest(lang));const back=document.createElement('button');back.className='secondary';back.textContent='返回能力定位';back.onclick=placementLanding;document.querySelector('main .panel').append(back);}
}
async function submitAnswers(){
 const controls=[...document.querySelectorAll('.test-wrap button,.test-wrap input')];controls.forEach(c=>c.disabled=true);
 document.querySelector('#next-question').textContent='正在计算结果…';
 try {const result=await api('/placement/score',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({lang:testLang,answers:placementQuestions[testLang].map((q,i)=>({questionId:q.id,optionId:answers[i]}))})});
 if(result.lang!==testLang||!Number.isInteger(result.level)||result.level<1||result.level>6||!Number.isInteger(result.score)||result.score<0||result.score>12)throw Error('结果返回异常，请重试。');
 state.levels[testLang]={score:result.score,level:result.level,date:new Date().toISOString()};save();testLang=null;placementLanding();
 }catch(error){renderQuestion();const message=document.createElement('p');message.className='notice';message.setAttribute('role','alert');message.textContent=error.message+' 你的答案仍然保留，请再次点击完成。';document.querySelector('.test-wrap').prepend(message);}
}
