// Phase 3.5E.1C editorial source. Topic-grouped order reflects P0/P1 task value.
// Vocabulary tuples: lemma, reading/null, POS, zh, example, example zh, stage, topic.
const E=(lemma,pos,zh,example,translation,stage,topic)=>({lemma,reading:null,pos,zh,example,translation,stage,topic});
const J=(lemma,reading,pos,zh,example,translation,stage,topic)=>({lemma,reading,pos,zh,example,translation,stage,topic});

export const enVocabularyCandidates=[
 E('allergy','noun','过敏','I have a peanut allergy.','我对花生过敏。',2,'health'),
 E('dietary restriction','noun phrase','饮食限制','Please let us know about any dietary restrictions.','如有任何饮食限制，请告诉我们。',3,'food'),
 E('ingredient','noun','原料；配料','Does this sauce contain any dairy ingredients?','这个酱汁含乳制品配料吗？',2,'food'),
 E('vegetarian','adjective','素食的','Is there a vegetarian option?','有素食选项吗？',2,'food'),
 E('bill','noun','账单','Could we have the bill, please?','请给我们账单好吗？',2,'food'),
 E('refill','noun','续杯；补充','Could I get a refill of water?','可以再给我加些水吗？',3,'food'),
 E('refund','noun','退款','I would like a refund, please.','我想申请退款。',3,'shopping'),
 E('exchange','noun','换货','Can I exchange this for a larger size?','我可以把这个换成大一号的吗？',3,'shopping'),
 E('aisle','noun','货架通道','The rice is in aisle five.','米在第五条通道。',2,'shopping'),
 E('checkout counter','noun phrase','结账台','Please pay at the checkout counter.','请在结账台付款。',2,'shopping'),
 E('contactless payment','noun phrase','非接触式支付','Do you accept contactless payment?','你们接受非接触式支付吗？',3,'shopping'),
 E('receipt','noun','收据','Please keep your receipt.','请保留收据。',2,'shopping'),
 E('faulty','adjective','有故障的','The charger is faulty.','这个充电器有故障。',3,'shopping'),
 E('warranty','noun','保修','Is this repair covered by the warranty?','这次维修在保修范围内吗？',4,'shopping'),
 E('return policy','noun phrase','退货政策','What is your return policy?','你们的退货政策是什么？',3,'shopping'),
 E('original packaging','noun phrase','原包装','The item must be in its original packaging.','商品必须保留原包装。',3,'shopping'),
 E('store credit','noun phrase','商店代金余额','We can offer store credit instead of a cash refund.','我们可以提供商店代金余额，而不是现金退款。',4,'shopping'),
 E('out of stock','adjective phrase','缺货','That model is currently out of stock.','那个型号目前缺货。',2,'shopping'),
 E('fever','noun','发烧','I have had a fever since last night.','我从昨晚开始发烧。',2,'health'),
 E('cough','noun','咳嗽','I have a dry cough.','我干咳。',2,'health'),
 E('dizzy','adjective','头晕的','I feel dizzy when I stand up.','我站起来时会头晕。',3,'health'),
 E('pharmacy','noun','药房','Is there a pharmacy nearby?','附近有药房吗？',2,'health'),
 E('prescription','noun','处方','You need a prescription for this medicine.','这种药需要处方。',3,'health'),
 E('symptom','noun','症状','When did the symptoms start?','症状什么时候开始的？',2,'health'),
 E('sore throat','noun phrase','喉咙痛','I have a sore throat and a cough.','我喉咙痛，还有咳嗽。',2,'health'),
 E('painkiller','noun','止痛药','Take one painkiller after food.','饭后服一片止痛药。',2,'health'),
 E('dosage','noun','剂量','Please follow the dosage on the label.','请按标签上的剂量服用。',3,'health'),
 E('side effect','noun','副作用','This medicine may cause a mild side effect.','这种药可能会引起轻微副作用。',3,'health'),
 E('swelling','noun','肿胀','There is some swelling around my ankle.','我的脚踝周围有些肿。',3,'health'),
 E('rash','noun','皮疹','The rash appeared this morning.','皮疹今天早上出现了。',3,'health'),
 E('time slot','noun phrase','可预约时段','Is there an afternoon time slot available?','下午有可预约时段吗？',2,'time'),
 E('appointment','noun','预约','I need to make a dental appointment.','我需要预约牙医。',2,'time'),
 E('reschedule','verb','改期','Could we reschedule the appointment for Friday?','我们可以把预约改到周五吗？',3,'time'),
 E('cancel','verb','取消','I need to cancel tomorrow’s appointment.','我需要取消明天的预约。',2,'time'),
 E('availability','noun','可用时间','Could you check the doctor’s availability?','你能查一下医生有空的时间吗？',3,'time'),
 E('confirmation','noun','确认信息','You will receive a confirmation by email.','你会通过邮件收到确认信息。',3,'time'),
 E('notice','noun','提前通知','Please give us 24 hours’ notice if you cancel.','如需取消，请提前24小时通知我们。',3,'time'),
 E('fully booked','adjective phrase','预约已满','We are fully booked on Monday.','我们周一已经约满了。',2,'time'),
 E('landlord','noun','房东','I reported the leak to my landlord.','我把漏水问题告诉了房东。',3,'home'),
 E('tenant','noun','租客','The tenant is responsible for keeping the room clean.','租客负责保持房间整洁。',3,'home'),
 E('rent','noun','房租','The rent is due on the first of each month.','房租每月一号到期。',3,'home'),
 E('deposit','noun','押金','The deposit is equal to four weeks’ rent.','押金相当于四周房租。',4,'home'),
 E('lease','noun','租约','Please read the lease before signing it.','签字前请阅读租约。',4,'home'),
 E('maintenance','noun','维修保养','I submitted a maintenance request.','我提交了维修申请。',3,'home'),
 E('leak','noun','漏水','There is a leak under the kitchen sink.','厨房水槽下面漏水。',2,'home'),
 E('heating','noun','供暖','The heating is not working.','暖气坏了。',2,'home'),
 E('repair request','noun phrase','报修申请','The repair request has been approved.','报修申请已经批准。',3,'home'),
 E('inspection','noun','检查；房屋检查','The landlord arranged an inspection for Tuesday.','房东安排周二检查房屋。',4,'home'),
 E('utility bill','noun phrase','水电燃气账单','Electricity is not included in the utility bill.','这张公共事业账单不含电费。',3,'home'),
 E('furnished','adjective','带家具的','We are looking for a furnished apartment.','我们在找一套带家具的公寓。',3,'home'),
 E('bank transfer','noun phrase','银行转账','I paid the rent by bank transfer.','我通过银行转账付了房租。',3,'shopping'),
 E('account balance','noun phrase','账户余额','Please check your account balance before paying.','付款前请查看账户余额。',3,'shopping'),
 E('service fee','noun phrase','服务费','The service fee is already included.','服务费已经包含在内。',3,'shopping'),
 E('PIN','noun','个人识别码；密码','Please enter your PIN.','请输入密码。',2,'shopping'),
 E('charger','noun','充电器','Can I borrow a phone charger?','我可以借一个手机充电器吗？',2,'help'),
 E('Wi-Fi','noun','无线网络','The hotel Wi-Fi keeps disconnecting.','酒店无线网络总是断开。',2,'help'),
 E('password','noun','密码','The Wi-Fi password is on the key card.','无线网络密码在房卡上。',2,'help'),
 E('signal','noun','信号','There is no phone signal in this room.','这个房间里没有手机信号。',3,'help'),
 E('connection','noun','连接','The internet connection is very slow.','网络连接很慢。',3,'help'),
 E('restart','verb','重新启动','Try restarting the router.','试着重启路由器。',2,'help'),
 E('router','noun','路由器','The green light on the router is flashing.','路由器上的绿灯在闪。',2,'help'),
 E('mobile data','noun phrase','移动数据','Turn on mobile data and try again.','打开移动数据再试一次。',3,'help'),
 E('airplane mode','noun phrase','飞行模式','Make sure airplane mode is off.','请确认飞行模式已关闭。',2,'help'),
 E('network','noun','网络','My laptop cannot find the network.','我的笔记本电脑找不到这个网络。',2,'help'),
 E('disconnect','verb','断开连接','The call disconnects after a few minutes.','通话几分钟后就会断开。',3,'help'),
 E('update','noun','更新','The app needs a software update.','这个应用需要软件更新。',3,'help'),
 E('platform','noun','站台','Which platform does the train leave from?','火车从哪个站台发车？',2,'travel'),
 E('delay','noun','延误','The flight has a two-hour delay.','航班延误两小时。',2,'travel'),
 E('traffic jam','noun phrase','交通堵塞','We were late because of a traffic jam.','我们因为堵车迟到了。',2,'travel'),
 E('seat belt','noun phrase','安全带','Please fasten your seat belt.','请系好安全带。',2,'travel'),
 E('parking','noun','停车；停车位','Is parking included in the room rate?','房价包含停车费吗？',2,'travel'),
 E('check-in','noun','入住登记','Hotel check-in starts at three.','酒店三点开始办理入住。',3,'travel'),
 E('key card','noun phrase','房卡','My key card does not open the door.','我的房卡打不开门。',2,'travel'),
 E('accommodation','noun','住宿','The course fee includes accommodation.','课程费用包含住宿。',4,'travel'),
 E('reservation','noun','预订','I have a reservation under the name Chen.','我用陈这个名字订了房。',2,'travel'),
 E('reception desk','noun phrase','前台','Please leave your luggage at the reception desk.','请把行李寄存在前台。',2,'travel'),
 E('vacancy','noun','空房','Do you have any vacancies tonight?','你们今晚有空房吗？',3,'travel'),
 E('room rate','noun phrase','房价','Does the room rate include breakfast?','房价包含早餐吗？',3,'travel'),
 E('late checkout','noun phrase','延迟退房','Is late checkout available?','可以延迟退房吗？',3,'travel'),
 E('colleague','noun','同事','I asked a colleague to cover my shift.','我请一位同事替我的班。',2,'school'),
 E('shift','noun','班次','My evening shift starts at four.','我的晚班四点开始。',3,'school'),
 E('salary','noun','工资','The salary is paid monthly.','工资按月发放。',3,'school'),
 E('interview','noun','面试','I have a job interview on Monday.','我周一有工作面试。',3,'school'),
 E('performance review','noun phrase','绩效评估','My performance review is next week.','我的绩效评估在下周。',3,'school'),
 E('deadline','noun','截止日期','We need to meet Friday’s deadline.','我们需要赶上周五的截止日期。',2,'school'),
 E('workload','noun','工作量','My workload is heavier this month.','我这个月的工作量更大。',3,'school'),
 E('handover','noun','工作交接','Please include the open tasks in your handover.','请把未完成的任务写进交接记录。',4,'school'),
 E('supervisor','noun','主管','Please check the change with your supervisor.','请和你的主管确认这项变更。',3,'school'),
 E('task update','noun phrase','任务进展更新','Could you send me a task update by noon?','你能在中午前发给我任务进展吗？',3,'school'),
 E('cover a shift','verb phrase','替班','Can you cover my shift on Saturday?','你周六能替我的班吗？',3,'school'),
 E('feedback','noun','反馈','Thank you for the helpful feedback.','谢谢你提供有帮助的反馈。',3,'school'),
 E('priority','noun','优先事项','The customer request is our first priority.','客户请求是我们的首要事项。',3,'school'),
 E('follow up','phrasal verb','跟进','I will follow up with the supplier tomorrow.','我明天会跟供应商跟进。',3,'school'),
 E('take responsibility','verb phrase','承担责任','I will take responsibility for the final check.','我会负责最后检查。',3,'school'),
 E('clinic','noun','诊所','The clinic opens at eight thirty.','诊所八点半开门。',2,'health'),
 E('receptionist','noun','前台接待员','The receptionist checked my appointment.','前台接待员核对了我的预约。',2,'health'),
 E('follow-up appointment','noun phrase','复诊预约','The doctor arranged a follow-up appointment.','医生安排了复诊预约。',3,'health'),
 E('emergency contact','noun phrase','紧急联系人','Please write down an emergency contact.','请写下一位紧急联系人。',3,'health')
];

export const jaVocabularyCandidates=[
 J('アレルギー','あれるぎー','noun','过敏','卵のアレルギーがあります。','我对鸡蛋过敏。',2,'health'),
 J('食事制限','しょくじせいげん','noun','饮食限制','食事制限はありますか。','您有饮食限制吗？',3,'food'),
 J('原材料','げんざいりょう','noun','原料；配料','原材料を確認していただけますか。','能请您确认一下配料吗？',3,'food'),
 J('ベジタリアン','べじたりあん','noun','素食者；素食的','ベジタリアン向けの料理はありますか。','有适合素食者的菜吗？',2,'food'),
 J('会計','かいけい','noun','结账','会計をお願いします。','请结账。',2,'food'),
 J('おかわり','おかわり','noun','再来一份；续杯','ご飯のおかわりをお願いします。','请再来一份米饭。',2,'food'),
 J('注文','ちゅうもん','noun','点餐；订单','注文を変更できますか。','可以更改订单吗？',2,'food'),
 J('乳製品','にゅうせいひん','noun','乳制品','このスープに乳製品は入っていますか。','这道汤里有乳制品吗？',3,'food'),
 J('抜き','ぬき','noun','不加；去掉','ねぎ抜きでお願いします。','请不要加葱。',2,'food'),
 J('別々','べつべつ','adverb','分别地','会計は別々でお願いします。','请分开结账。',2,'food'),
 J('返品','へんぴん','noun','退货','この商品を返品したいのですが。','我想退这件商品。',3,'shopping'),
 J('交換','こうかん','noun','换货','別のサイズに交換できますか。','可以换成别的尺码吗？',3,'shopping'),
 J('通路','つうろ','noun','通道','飲み物は三番通路にあります。','饮料在第三条通道。',2,'shopping'),
 J('レジ','れじ','noun','收银台','レジはどこですか。','收银台在哪里？',1,'shopping'),
 J('タッチ決済','たっちけっさい','noun','非接触式支付','タッチ決済は使えますか。','可以使用非接触式支付吗？',3,'shopping'),
 J('レシート','れしーと','noun','收据','返品にはレシートが必要です。','退货需要收据。',2,'shopping'),
 J('不良品','ふりょうひん','noun','次品；故障品','これは不良品だと思います。','我觉得这是次品。',3,'shopping'),
 J('保証','ほしょう','noun','保修；保证','この修理は保証の対象です。','这次维修在保修范围内。',4,'shopping'),
 J('返金','へんきん','noun','退款','返金はカードに戻されます。','退款会退回卡中。',3,'shopping'),
 J('在庫','ざいこ','noun','库存','この色は在庫がありますか。','这个颜色有库存吗？',2,'shopping'),
 J('発熱','はつねつ','noun','发烧','昨夜から発熱があります。','从昨晚开始发烧。',2,'health'),
 J('咳','せき','noun','咳嗽','乾いた咳が出ます。','我会干咳。',2,'health'),
 J('めまい','めまい','noun','头晕','立つとめまいがします。','站起来时会头晕。',3,'health'),
 J('薬局','やっきょく','noun','药房','近くに薬局はありますか。','附近有药房吗？',2,'health'),
 J('処方箋','しょほうせん','noun','处方','この薬には処方箋が必要です。','这种药需要处方。',3,'health'),
 J('診察','しんさつ','noun','诊察','午後に診察を受けます。','我下午接受诊察。',3,'health'),
 J('症状','しょうじょう','noun','症状','症状はいつ始まりましたか。','症状什么时候开始的？',2,'health'),
 J('喉の痛み','のどのいたみ','noun phrase','喉咙痛','喉の痛みが三日続いています。','喉咙痛持续三天了。',2,'health'),
 J('痛み止め','いたみどめ','noun','止痛药','食後に痛み止めを飲んでください。','请饭后服用止痛药。',2,'health'),
 J('用量','ようりょう','noun','用量','決められた用量を守ってください。','请遵守规定用量。',3,'health'),
 J('副作用','ふくさよう','noun','副作用','眠気はこの薬の副作用です。','困倦是这种药的副作用。',3,'health'),
 J('腫れ','はれ','noun','肿胀','足首に少し腫れがあります。','脚踝有些肿。',3,'health'),
 J('発疹','ほっしん','noun','皮疹','今朝、腕に発疹が出ました。','今天早上手臂出现了皮疹。',3,'health'),
 J('予約枠','よやくわく','noun','可预约时段','午後の予約枠は空いていますか。','下午的预约时段有空吗？',3,'time'),
 J('予約','よやく','noun','预约','歯医者の予約を取りたいです。','我想预约牙医。',2,'time'),
 J('変更','へんこう','noun','变更','予約を金曜日に変更できますか。','可以把预约改到周五吗？',2,'time'),
 J('キャンセル','きゃんせる','noun','取消','明日の予約をキャンセルしたいです。','我想取消明天的预约。',2,'time'),
 J('空き','あき','noun','空位；空档','午前中に空きはありますか。','上午有空档吗？',2,'time'),
 J('確認メール','かくにんめーる','noun phrase','确认邮件','確認メールをお送りします。','我们会发送确认邮件。',3,'time'),
 J('大家','おおや','noun','房东','水漏れを大家さんに連絡しました。','我把漏水问题联系了房东。',3,'home'),
 J('借主','かりぬし','noun','承租人','借主は部屋をきれいに使う必要があります。','承租人需要爱护房间。',4,'home'),
 J('家賃','やちん','noun','房租','家賃は毎月一日に払います。','房租每月一号支付。',3,'home'),
 J('敷金','しききん','noun','押金','敷金は家賃一か月分です。','押金是一个月房租。',4,'home'),
 J('賃貸契約','ちんたいけいやく','noun','租赁合同','署名する前に賃貸契約を確認してください。','签字前请确认租赁合同。',4,'home'),
 J('修理','しゅうり','noun','维修','エアコンの修理をお願いしたいです。','我想请人修空调。',2,'home'),
 J('水漏れ','みずもれ','noun','漏水','台所で水漏れしています。','厨房正在漏水。',2,'home'),
 J('暖房','だんぼう','noun','暖气','暖房がつきません。','暖气打不开。',2,'home'),
 J('管理会社','かんりがいしゃ','noun','物业管理公司','管理会社に修理を依頼しました。','我向物业管理公司报修了。',3,'home'),
 J('点検','てんけん','noun','检查','火曜日に設備の点検があります。','周二有设备检查。',3,'home'),
 J('光熱費','こうねつひ','noun','水电燃气费','家賃に光熱費は含まれていません。','房租不包含水电燃气费。',3,'home'),
 J('家具付き','かぐつき','noun','带家具','家具付きの部屋を探しています。','我在找带家具的房间。',3,'home'),
 J('振込','ふりこみ','noun','转账','家賃は銀行振込で払います。','房租通过银行转账支付。',3,'shopping'),
 J('残高','ざんだか','noun','余额','支払う前に残高を確認します。','付款前确认余额。',3,'shopping'),
 J('手数料','てすうりょう','noun','手续费','振込手数料がかかります。','转账需要手续费。',3,'shopping'),
 J('暗証番号','あんしょうばんごう','noun','密码；个人识别码','暗証番号を入力してください。','请输入密码。',2,'shopping'),
 J('充電器','じゅうでんき','noun','充电器','充電器を借りてもいいですか。','可以借充电器吗？',2,'help'),
 J('Wi-Fi','わいふぁい','noun','无线网络','ホテルのWi-Fiが切れます。','酒店无线网络会断开。',2,'help'),
 J('パスワード','ぱすわーど','noun','密码','Wi-Fiのパスワードを教えてください。','请告诉我无线网络密码。',2,'help'),
 J('電波','でんぱ','noun','信号','この部屋は電波が弱いです。','这个房间信号很弱。',3,'help'),
 J('接続','せつぞく','noun','连接','インターネットの接続が不安定です。','网络连接不稳定。',3,'help'),
 J('再起動','さいきどう','noun','重新启动','ルーターを再起動してみてください。','请试着重启路由器。',3,'help'),
 J('ルーター','るーたー','noun','路由器','ルーターのランプが点滅しています。','路由器的灯在闪烁。',2,'help'),
 J('モバイルデータ','もばいるでーた','noun','移动数据','モバイルデータをオンにしてください。','请打开移动数据。',3,'help'),
 J('機内モード','きないもーど','noun','飞行模式','機内モードをオフにしました。','我关掉了飞行模式。',2,'help'),
 J('ネットワーク','ねっとわーく','noun','网络','パソコンがネットワークを見つけません。','电脑找不到网络。',2,'help'),
 J('切断','せつだん','noun','断开连接','通話が何度も切断されます。','通话多次断开。',3,'help'),
 J('更新','こうしん','noun','更新','アプリを更新する必要があります。','需要更新应用。',3,'help'),
 J('ホーム','ほーむ','noun','站台','電車は三番ホームから出ます。','电车从三号站台出发。',2,'travel'),
 J('遅延','ちえん','noun','延误','電車に二十分の遅延が出ています。','电车延误二十分钟。',3,'travel'),
 J('渋滞','じゅうたい','noun','堵车','渋滞で到着が遅れました。','因为堵车到晚了。',3,'travel'),
 J('シートベルト','しーとべると','noun','安全带','シートベルトを締めてください。','请系好安全带。',2,'travel'),
 J('駐車','ちゅうしゃ','noun','停车','ここに駐車してもいいですか。','可以在这里停车吗？',2,'travel'),
 J('チェックイン','ちぇっくいん','noun','入住登记','三時からチェックインできます。','三点起可以办理入住。',3,'travel'),
 J('カードキー','かーどきー','noun','房卡','カードキーでドアが開きません。','用房卡打不开门。',2,'travel'),
 J('宿泊','しゅくはく','noun','住宿','二泊の宿泊を予約しました。','我预订了两晚住宿。',3,'travel'),
 J('宿泊予約','しゅくはくよやく','noun phrase','住宿预订','田中の名前で宿泊予約があります。','以田中的名字有住宿预订。',3,'travel'),
 J('フロント','ふろんと','noun','前台','荷物をフロントに預けました。','我把行李寄存在前台了。',2,'travel'),
 J('空室','くうしつ','noun','空房','今夜、空室はありますか。','今晚有空房吗？',3,'travel'),
 J('宿泊料金','しゅくはくりょうきん','noun phrase','住宿费','宿泊料金に朝食は含まれますか。','住宿费包含早餐吗？',3,'travel'),
 J('延長','えんちょう','noun','延长','チェックアウトの延長はできますか。','可以延迟退房吗？',3,'travel'),
 J('同僚','どうりょう','noun','同事','同僚にシフトを代わってもらいました。','我请同事替了班。',3,'school'),
 J('シフト','しふと','noun','班次','夕方のシフトは四時からです。','晚班四点开始。',3,'school'),
 J('給料','きゅうりょう','noun','工资','給料は毎月振り込まれます。','工资每月转账发放。',2,'school'),
 J('面接','めんせつ','noun','面试','月曜日に面接があります。','周一有面试。',3,'school'),
 J('フィードバック','ふぃーどばっく','noun','反馈','具体的なフィードバックをいただきました。','我收到了具体的反馈。',3,'school'),
 J('締め切り','しめきり','noun','截止日期','金曜日の締め切りに間に合わせます。','我要赶上周五的截止日期。',2,'school'),
 J('業務量','ぎょうむりょう','noun','工作量','今月は業務量が多いです。','这个月工作量很大。',3,'school'),
 J('引き継ぎ','ひきつぎ','noun','工作交接','未完了の仕事を引き継ぎに入れてください。','请把未完成的工作写进交接。',4,'school'),
 J('上司','じょうし','noun','上司','変更について上司に確認します。','我会向上司确认变更。',2,'school'),
 J('進捗','しんちょく','noun','进展','午後に進捗を報告します。','我下午汇报进展。',3,'school'),
 J('代わる','かわる','verb','替代；替班','土曜日のシフトを代わってもらえますか。','能请你替我周六的班吗？',3,'school'),
 J('優先事項','ゆうせんじこう','noun','优先事项','安全確認が最優先事項です。','安全确认是首要事项。',3,'school'),
 J('報告','ほうこく','noun','汇报','問題があればすぐに報告してください。','如有问题请立即汇报。',2,'school'),
 J('連絡','れんらく','noun','联络','遅れる場合は担当者に連絡します。','迟到时会联系负责人。',2,'school'),
 J('相談','そうだん','noun','商量；咨询','勤務時間について相談したいです。','我想商量工作时间。',2,'school'),
 J('担当者','たんとうしゃ','noun','负责人','担当者に確認してから返事します。','向负责人确认后再回复。',3,'school'),
 J('休暇申請','きゅうかしんせい','noun phrase','请假申请','休暇申請を昨日提出しました。','我昨天提交了请假申请。',3,'school'),
 J('勤務時間','きんむじかん','noun phrase','工作时间','勤務時間は九時から五時までです。','工作时间是九点到五点。',2,'school'),
 J('研修','けんしゅう','noun','培训','来週、新人研修に参加します。','下周参加新人培训。',3,'school'),
 J('備品','びひん','noun','办公用品；设备','必要な備品を注文しました。','我订购了需要的办公用品。',3,'school'),
 J('共有','きょうゆう','noun','共享；分享','会議のメモをチームで共有します。','在团队内共享会议记录。',3,'school'),
 J('確認事項','かくにんじこう','noun','待确认事项','確認事項をメールで送ります。','我会邮件发送待确认事项。',3,'school'),
 J('担当','たんとう','noun','负责；分工','私は受付を担当します。','我负责接待。',2,'school'),
 J('欠勤','けっきん','noun','缺勤','体調不良で欠勤する場合は連絡してください。','因身体不适缺勤时请联系。',3,'school'),
 J('早退','そうたい','noun','早退','今日は通院のため早退します。','今天因为去医院要早退。',3,'school'),
 J('勤務表','きんむひょう','noun','排班表','新しい勤務表を確認しました。','我确认了新的排班表。',3,'school')
];

const G=(id,language,level,title,form,core,purpose,formula,when,mistakes,nuance,examples)=>({id,language,level,title,form,core,purpose,formula,when,mistakes,nuance,examples});
export const grammarCandidates=[
 G('35e1c-en-negation-short-answers','en',1,'一般现在时否定与简短回答','do/does not; Yes, ... do. / No, ... do not.','用 do/does 承担一般现在时的否定和问答。','否定事实、习惯或需要，并作自然简答。','subject + do/does not + base verb; Do/Does ...?','谈论现在的习惯、事实或需要时。','第三人称否定后动词不用 -s；简答不能只机械重复主句。','be 动词不用 do；回答常用缩略形式。',[['I do not need a receipt.','我不需要收据。'],['She does not work on Fridays.','她周五不上班。'],['Do you accept cards? Yes, we do.','你们收卡吗？是的，收。'],['Does this contain milk? No, it does not.','这个含牛奶吗？不含。']]),
 G('35e1c-en-past-questions-negatives','en',2,'一般过去时问句与否定','Did ...? / did not + base verb','did 标记过去后，实义动词回到原形。','询问或否定已经结束的事情。','Did + subject + base verb?; subject + did not + base verb','核实过去发生的预约、付款或故障。','不要写 did went / did not received。','be 动词过去式使用 was/were，不使用 did。',[['Did you book the room online?','你是在网上订房的吗？'],['I did not receive a confirmation email.','我没有收到确认邮件。'],['Did the heating stop last night?','暖气昨晚停了吗？'],['No, it did not stop completely.','没有，它没有完全停。']]),
 G('35e1c-en-article-system','en',1,'冠词系统：a/an、the 与零冠词','a/an; the; zero article','冠词表示名词是否可数、是否首次出现以及双方是否能识别。','自然引入和再次指称人物或事物。','a/an + singular count noun; the + identifiable noun','介绍一个新对象、回指或谈论类别时。','单数可数名词通常不能裸用；不可数名词不随意加 a。','零冠词常用于复数/不可数的泛指。',[['I need a charger.','我需要一个充电器。'],['The charger is in my room.','那个充电器在我房间。'],['Breakfast is included.','早餐包含在内。'],['The breakfast we ordered was cold.','我们点的那份早餐凉了。']]),
 G('35e1c-en-some-any','en',2,'some / any 与可数性','some / any + plural or non-count noun','some 常用于肯定与主动提供，any 常用于疑问和否定。','谈论不确定数量。','some/any + plural count noun or non-count noun','购物、点餐和询问库存时。','不要把不可数名词机械变复数。','期待肯定回答的礼貌请求中常用 some。',[['We need some batteries.','我们需要一些电池。'],['Do you have any vegetarian dishes?','你们有素食菜吗？'],['There is not any milk left.','一点牛奶也没剩。'],['Could I have some water?','可以给我一些水吗？']]),
 G('35e1c-en-should-advice','en',2,'should / should not 表建议','should (not) + base verb','should 给出建议，不等于强制命令。','提供或询问适度建议。','subject + should/should not + base verb','健康、出行和处理问题时。','should 后不用 to，也不随人称变化。','语气通常比 must 柔和。',[['You should rest today.','你今天应该休息。'],['You should not drive if you feel dizzy.','如果头晕，你不应该开车。'],['Should I take this with food?','我应该随餐服用这个吗？'],['We should call the landlord first.','我们应该先联系房东。']]),
 G('35e1c-en-obligation-contrast','en',3,'must / have to / do not have to 对比','must; have to; do not have to','区分说话者强调的义务、外部规定和没有必要。','说明规则、职责与可选事项。','must/have to + base verb; do not have to + base verb','工作、租房、旅行规定中。','do not have to 表示“不必”，不是“禁止”。','must not 表禁止；have to 更常指外部要求。',[['Visitors must show identification.','访客必须出示身份证明。'],['I have to submit the form today.','我今天必须提交表格。'],['You do not have to pay in advance.','你不必提前付款。'],['You must not share your PIN.','你绝不能透露密码。']]),
 G('35e1c-en-first-conditional','en',3,'第一条件句','If + present, will/can/imperative','用现实可能的条件连接未来结果或行动。','讨论可行的安排与后果。','if + present simple, will/can + base verb','预约、行程和排障时。','if 从句中通常不用 will 表普通未来。','主句可用 will、can 或祈使句。',[['If Friday is full, I will come on Monday.','如果周五约满，我周一来。'],['If the light stays red, restart the router.','如果灯一直红着，就重启路由器。'],['We can refund you if you have the receipt.','如果你有收据，我们可以退款。'],['If the train is delayed, I will call you.','如果火车晚点，我会给你打电话。']]),
 G('35e1c-en-future-arrangements','en',3,'现在进行时表示已安排的将来','be + V-ing + future time','现在进行时可表示已经约定或落实的近期安排。','说明日程中已确定的未来活动。','subject + be + V-ing + future time','预约、面试、出行和工作排班。','需要未来时间语境；不要和正在发生混淆。','通常比 be going to 更强调已有安排。',[['I am seeing the doctor at three.','我三点去看医生。'],['We are checking in on Friday.','我们周五办理入住。'],['Are you working this weekend?','你这周末上班吗？'],['She is not joining the meeting tomorrow.','她明天不参加会议。']]),
 G('35e1c-en-perfect-vs-past','en',4,'现在完成时与一般过去时对比','have + participle vs past form','现在完成时连接现在；一般过去时把事件放在已结束的过去。','准确报告经历、结果或具体过去时间。','have/has + past participle; simple past','汇报进展、故障和旅行经历时。','带 yesterday/last week 等已结束时间通常不用现在完成时。','结果仍相关时常用现在完成时。',[['I have submitted the repair request.','我已经提交了报修申请。'],['I submitted it yesterday.','我是昨天提交的。'],['Have you ever stayed here before?','你以前住过这里吗？'],['We stayed here last summer.','我们去年夏天住过这里。']]),
 G('35e1c-en-reported-statements','en',4,'转述陈述与信息','said/told + (that) clause','用 said 或 told 转述他人的信息，并明确接收者。','在工作和服务场景中传递消息。','say (that) + clause; tell + person + (that) + clause','转达安排、说明或决定时。','tell 后通常要有人作宾语；不要写 said me。','时间明确且内容仍有效时不必机械回移时态。',[['The manager said that the shift starts at nine.','经理说班次九点开始。'],['She told me that the room was ready.','她告诉我房间准备好了。'],['I said that I could come on Friday.','我说我周五能来。'],['They told us the flight had been cancelled.','他们告诉我们航班已经取消。']]),
 G('35e1c-ja-movement-particles','ja',1,'移動の「に・へ」と動作場所の「で」','場所に／へ行く；場所で動作する','に・へ表示移动目的地，で表示动作发生处。','区分“去哪里”和“在哪里做什么”。','destination + に/へ + 移動動詞；place + で + 動作動詞','问路、交通和日常活动。','「駅で行きます」不能表示去车站。','へ偏方向，に偏到达点；很多移动语境可互换。',[['駅に行きます。','去车站。'],['駅へ向かっています。','正在往车站去。'],['駅で友達を待ちます。','在车站等朋友。'],['ホテルで朝食を食べました。','在酒店吃了早餐。']]),
 G('35e1c-ja-kara-made-range','ja',1,'起点と終点の「から・まで」','N から N まで','から标起点，まで标终点，可以只用其中之一。','表达时间或空间范围。','start + から；end + まで','营业时间、路线和工作时间。','まで不是“到达”的动词助词。','强调截止期限时也可用まで。',[['九時から働きます。','从九点开始工作。'],['店は五時までです。','店营业到五点。'],['駅からホテルまで歩きました。','从车站走到酒店。'],['金曜日までに提出してください。','请在周五之前提交。']]),
 G('35e1c-ja-adjective-tense','ja',2,'い形容詞・な形容詞の否定と過去','〜くない／〜かった；〜ではない／〜だった','两类形容词的否定和过去活用不同。','描述过去状态或否定性质。','い→くない/かった；な→ではない/だった','评价房间、食物、身体状态。','な形容词不能变成〜くない；いい的过去是よかった。','礼貌体可用〜くありません、〜ではありません。',[['部屋は広くないです。','房间不宽敞。'],['昨日は寒かったです。','昨天很冷。'],['この辺は静かではありません。','这一带不安静。'],['ホテルは便利でした。','酒店很方便。']]),
 G('35e1c-ja-plain-tense-system','ja',2,'普通形の肯定・否定・過去','辞書形／ない形／た形／なかった形','普通体用四个基本形式表达非过去/过去与肯定/否定。','在关系近的交流及从句中准确变化。','Vる・Vない・Vた・Vなかった','朋友会话以及と思う、ので等前面。','不要把ます和普通形词尾混合。','普通体不等于粗鲁，是否合适取决于关系和场景。',[['今日は行く。','今天去。'],['今日は行かない。','今天不去。'],['昨日は行った。','昨天去了。'],['昨日は行かなかった。','昨天没去。']]),
 G('35e1c-ja-te-sequence','ja',2,'て形で動作をつなぐ','Vて、V','て形按语境连接先后或并列动作。','简洁说明一连串日常行动。','verb て-form + clause','说明路线、手续和工作流程。','て形本身不总表示严格先后；需要时加それから。','同一主语的一连串动作尤其自然。',[['受付で名前を書いて、待ちます。','在前台写下名字，然后等候。'],['薬を飲んで、休みました。','吃了药，然后休息了。'],['カードを入れて、暗証番号を押してください。','请插卡后输入密码。'],['部屋を確認して、フロントに連絡します。','确认房间后联系前台。']]),
 G('35e1c-ja-permission-prohibition','ja',2,'〜てもいい・〜てはいけない','Vてもいい；Vてはいけない','一个表示许可，一个表示禁止。','询问许可或说明规则。','て-form + もいい／はいけない','住宿、职场和公共场所。','〜なくてもいい是“不必”，不要当成禁止。','口语禁止也常用〜てはだめ。',[['ここに座ってもいいですか。','可以坐这里吗？'],['この薬を食後に飲んでもいいです。','这种药可以饭后吃。'],['ここで写真を撮ってはいけません。','这里禁止拍照。'],['暗証番号を教えてはいけません。','不能告诉别人密码。']]),
 G('35e1c-ja-counter-system','ja',2,'助数詞：人・本・枚・個・つ','number + counter','根据人或物的形状/类别选择助数词，并注意读音变化。','在购物、餐厅和预约中准确计数。','人: ひとり/ふたり；本・枚・個・つ','购买、人数、份数和物品数量。','不要对所有东西都只用個。','不知道专用量词时，つ可数部分一般物品到十。',[['二人でお願いします。','两位。'],['水を二本ください。','请给两瓶水。'],['切符を三枚買いました。','买了三张票。'],['りんごを四つください。','请给四个苹果。']]),
 G('35e1c-ja-obligation-contrast','ja',3,'〜なければならない・〜なくてもいい','Vなければならない；Vなくてもいい','区分必须做和不必做。','说明义务、规则与可选事项。','ない形去い + ければならない／くてもいい','工作、手续、住宿和健康建议。','〜なくてもいい不是“不能做”。','口语中义务常缩略为〜なきゃ。',[['今日中に報告しなければなりません。','必须在今天内汇报。'],['受付で身分証を見せなければなりません。','必须在前台出示身份证明。'],['朝食は予約しなくてもいいです。','早餐不必预约。'],['制服を着なくてもいい日はありますか。','有不用穿制服的日子吗？']]),
 G('35e1c-ja-kara-node-contrast','ja',3,'理由の「から・ので」','plain/polite clause + から／ので','两者都说明理由；ので通常更柔和客观。','解释原因并为请求或变更铺垫。','clause + から／ので、result','请假、改期、拒绝与说明问题。','名词/な形容词接ので时用なので。','から较直接；在服务和职场请求中ので常更缓和。',[['熱があるので、今日は休みます。','因为发烧，今天休息。'],['電車が遅れたから、間に合いませんでした。','因为电车晚点，所以没赶上。'],['予約を変更したいのですが、予定が変わったので。','我想改预约，因为安排变了。'],['静かなので、この部屋が好きです。','因为安静，我喜欢这个房间。']]),
 G('35e1c-ja-comparison-system','ja',3,'〜より・〜ほうがで比べる','AよりBのほうが adjective','より标比较基准，ほうが标在该维度更突出的一方。','比较商品、时间和选择。','A より B のほうが + predicate','购物、建议和选择方案时。','不要把比较方向说反。','只说Bのほうが也可承接上文比较。',[['バスより電車のほうが速いです。','电车比公交车快。'],['午前より午後のほうが空いています。','下午比上午有空。'],['こちらの部屋のほうが静かです。','这间房更安静。'],['現金よりカードのほうが便利です。','卡比现金方便。']]),
 G('35e1c-ja-giving-receiving','ja',3,'あげる・くれる・もらう','giver が receiver に N/Vて + verb','根据叙述视点选择给予、为己方做或接受。','表达帮助、恩惠和物品往来。','AがBにあげる；Aが私にくれる；私はAにもらう','同事协作、朋友帮助和服务。','くれる的接受方通常是说话者一方。','て形组合能表达“为某人做某事”。',[['私は同僚に資料をあげました。','我把资料给了同事。'],['同僚がシフトを代わってくれました。','同事替我上了班。'],['先生に推薦状を書いてもらいました。','我请老师写了推荐信。'],['友達に駅まで送ってあげました。','我把朋友送到了车站。']]),
 G('35e1c-ja-condition-contrast','ja',4,'条件の「なら・たら・ば・と」','N/普通形なら；た形ら；ば形；辞書形と','根据前提来源、时序和结果性质选择条件形式。','协商方案、说明规则或自然结果。','なら/たら/ば/と + result','出行变更、排障、建议和规则。','命令、意志句通常不接表示自然结果的と。','なら承接话题；たら灵活；ば重条件；と表规律或自动结果。',[['金曜日なら空いています。','如果是周五，我有空。'],['着いたら連絡してください。','到了以后请联系。'],['早く予約すれば、安くなります。','早点预订的话会便宜。'],['このボタンを押すと、電源が入ります。','按这个按钮就会开机。']]),
 G('35e1c-ja-sentence-final-softeners','ja',3,'終助詞「ね・よ・かな」','clause + ね／よ／かな','句末助词管理共享信息、告知和自问语气。','让确认、提醒和犹豫更自然。','sentence + particle','日常确认、提出看法和思考选择时。','よ连续使用会显得强硬；かな不宜用于正式请求。','ね邀请对方确认；よ提供新信息；かな表示自问。',[['今日は寒いですね。','今天很冷啊。'],['この薬は食後ですよ。','这种药是饭后吃哦。'],['次の電車に間に合うかな。','不知道能不能赶上下一班车。'],['こちらでよろしいですね。','这样可以，对吧。']]),
 G('35e1c-ja-workplace-register','ja',4,'職場の敬体・尊敬語・謙譲語切り替え','です/ます；お/ご〜になる；お/ご〜する','根据行为主体与关系距离，区分普通礼貌、抬高对方和压低己方。','在汇报、联系、接待中选择合适语域。','polite / honorific / humble by actor','职场内部、客户接待和正式联络。','不是把所有动词都机械加お；先判断谁做动作。','同事内部通常以です/ます为基础，面对客户再用必要敬语。',[['部長はもうお帰りになりました。','部长已经回去了。'],['私が資料をご説明します。','由我来说明资料。'],['担当者に確認いたします。','我会向负责人确认。'],['少々お待ちください。','请稍等。']]),
 G('35e1c-ja-explanatory-nodesu','ja',3,'〜んです・〜んですがの説明と前置き','plain + んです／んですが','补充背景或温和地引出请求和问题。','解释情况、求助或开启协商。','V/い-adj plain + んです；N/な-adj + なんです','服务、医疗、租房和职场咨询。','不能把名词直接接んです，需用なんです。','んですが常把具体请求留给后句，语气更柔和。',[['予約を変更したいんですが。','我想改预约。'],['暖房がつかないんです。','暖气打不开。'],['明日は休みなんです。','明天休息。'],['少し相談したいことがあるんですが。','我有点事想商量。']]),
 G('35e1c-ja-experience-system','ja',3,'〜たことがあるで経験を話す','Vた + ことがある','表示截至现在曾有过某种经历。','询问或分享人生经验。','past plain verb + ことがある','旅行、工作和社交经历。','具体一次的过去事件通常直接用た形，不用ことがある。','否定是〜たことがない。',[['日本で働いたことがあります。','我曾在日本工作过。'],['このホテルに泊まったことがありますか。','你住过这家酒店吗？'],['まだ海外へ行ったことがありません。','我还没去过国外。'],['一度だけ返品したことがあります。','我只退过一次货。']])
];

export const dialogueCandidates=[
 {id:'35e1c-en-d-supermarket',language:'en',stage:2,topic:'shopping',anchor:'在超市找到商品并完成结账。',context:'顾客先询问商品位置，再在结账时确认支付方式和收据。',turns:[['A','Excuse me, where can I find the oat milk?'],['B','It is in aisle six, next to the cereal.'],['A','Thank you. Is this brand on sale today?'],['B','Yes. The discount will appear at the checkout.'],['A','Great. Can I pay by card and get a receipt?'],['B','Of course. Please tap your card here.']]},
 {id:'35e1c-en-d-connectivity',language:'en',stage:3,topic:'help',anchor:'说明网络故障并完成基本排障。',context:'住客说明 Wi-Fi 无法连接，工作人员逐步确认网络和路由器状态。',turns:[['A','The Wi-Fi keeps disconnecting in my room.'],['B','I’m sorry. Can you see the hotel network on your phone?'],['A','Yes, but it says the password is incorrect.'],['B','Please forget the network and enter this new password.'],['A','I’m connected now, but the signal is still weak.'],['B','I’ll restart the router. If that does not help, I can move you to another room.']]},
 {id:'35e1c-ja-d-supermarket',language:'ja',stage:2,topic:'shopping',anchor:'スーパーで商品を探して会計する。',context:'客が商品の場所を尋ね、レジで支払い方法とレシートを確認する。',turns:[['A','すみません。牛乳はどの通路にありますか。'],['B','三番通路の奥にあります。'],['A','ありがとうございます。この商品は今日、安くなっていますか。'],['B','はい。レジで二十円引きになります。'],['A','では、これを二本ください。カードで払えますか。'],['B','はい。こちらのレジでお支払いください。レシートもお渡しします。']]},
 {id:'35e1c-ja-d-connectivity',language:'ja',stage:3,topic:'help',anchor:'通信の問題を説明して基本的な対処を確認する。',context:'利用者が Wi-Fi 接続の問題を伝え、担当者と順番に対処する。',turns:[['A','部屋のWi-Fiが何度も切れるんですが。'],['B','ご不便をおかけして申し訳ありません。ネットワーク名は表示されていますか。'],['A','はい。でも、パスワードが違うと出ます。'],['B','一度接続を削除して、この新しいパスワードを入れてください。'],['A','つながりましたが、まだ電波が弱いです。'],['B','ルーターを再起動します。それでも直らなければ、別の部屋をご案内します。']]}
];

export const lessonBlueprints=[
 ['en-s2-l5','en',2,'shopping','在超市找货并结账','能询问商品位置、确认数量价格并完成支付。','35e1b-en-d-wrong-delivery-expr',['aisle','checkout counter','receipt','out of stock'],['35e1c-en-some-any','en-wh-question']],
 ['en-s3-l5','en',3,'shopping','退货与换货','能说明商品问题、提出退款或换货并确认处理条件。','35e1b-en-d-return-defect-expr',['refund','exchange','faulty','return policy','receipt'],['35e1c-en-past-questions-negatives','35e1c-en-first-conditional']],
 ['en-s3-l6','en',3,'health','在药房或诊所说明症状','能描述症状、持续时间和严重度并理解基本建议。','35e1b-en-d-medical-symptoms-expr',['fever','cough','dizzy','pharmacy','prescription'],['35e1c-en-should-advice','en-since-for']],
 ['en-s3-l7','en',3,'time','预约、取消与改期','能预约、确认、取消并协商替代时间。','35e1b-en-d-appointment-reschedule-expr',['appointment','reschedule','time slot','availability','confirmation'],['35e1c-en-future-arrangements','35e1c-en-first-conditional']],
 ['en-s3-l8','en',3,'help','处理手机与网络问题','能描述连接问题并执行、确认排障步骤。','35e1b-en-d-help-alternative-expr',['Wi-Fi','password','signal','connection','restart','router'],['35e1c-en-first-conditional','en-imperative']],
 ['en-s3-l9','en',3,'school','职场任务、排班与反馈','能汇报进展、协调班次并回应反馈。','35e1b-en-d-work-clarification-expr',['colleague','shift','deadline','feedback','supervisor'],['35e1c-en-obligation-contrast','35e1c-en-future-arrangements']],
 ['en-s4-l5','en',4,'home','租房、报修与房东沟通','能说明住房问题、请求维修并确认费用和时间。','35e1b-en-d-repair-leak-expr',['landlord','rent','maintenance','leak','repair request'],['35e1c-en-perfect-vs-past','35e1c-en-obligation-contrast']],
 ['en-s4-l6','en',4,'travel','入住酒店并处理住宿问题','能办理入住、询问设施并处理房间问题。','35e1b-en-d-hotel-room-expr',['check-in','key card','reservation','room rate','late checkout'],['35e1c-en-past-questions-negatives','35e1c-en-first-conditional']],
 ['ja-s2-l5','ja',2,'shopping','スーパーで商品を探して会計する','能询问位置、数量、价格并完成超市支付。','35e1b-ja-d-counter-service-expr',['通路','レジ','レシート','在庫'],['35e1c-ja-counter-system','ja-ka-question']],
 ['ja-s2-l6','ja',2,'food','店で注文し、希望を伝える','能点餐、说明饮食限制并结账。','35e1b-ja-d-restaurant-allergy-expr',['アレルギー','原材料','会計','抜き','別々'],['35e1c-ja-counter-system','ja-request-onegai']],
 ['ja-s3-l5','ja',3,'shopping','返品・交換を相談する','能说明商品问题并协商退换条件。','35e1b-ja-d-return-defect-expr',['返品','交換','レシート','不良品','返金'],['35e1c-ja-explanatory-nodesu','35e1c-ja-condition-contrast']],
 ['ja-s3-l6','ja',3,'health','薬局・病院で症状を説明する','能说明症状、程度与持续时间并理解建议。','35e1b-ja-d-medical-symptoms-expr',['発熱','咳','めまい','薬局','処方箋'],['35e1c-ja-kara-node-contrast','ja-hou-ga-ii']],
 ['ja-s3-l7','ja',3,'help','スマホ・通信の問題を伝える','能描述连接问题并确认排障步骤。','35e1b-ja-d-help-alternative-expr',['Wi-Fi','パスワード','電波','接続','再起動'],['35e1c-ja-te-sequence','35e1c-ja-condition-contrast']],
 ['ja-s3-l8','ja',3,'school','職場で報告・連絡・相談する','能汇报、联络和商量并保持合适礼貌度。','35e1b-ja-d-work-clarification-expr',['同僚','シフト','進捗','報告','相談'],['35e1c-ja-workplace-register','35e1c-ja-obligation-contrast']],
 ['ja-s4-l5','ja',4,'home','賃貸・修理について相談する','能向房东或管理方报修并确认费用与时间。','35e1b-ja-d-repair-leak-expr',['大家','家賃','修理','水漏れ','管理会社'],['35e1c-ja-explanatory-nodesu','35e1c-ja-obligation-contrast']],
 ['ja-s4-l6','ja',4,'travel','宿泊手続きと部屋の問題に対応する','能办理入住、询问设施并处理房间问题。','35e1b-ja-d-hotel-room-expr',['チェックイン','カードキー','宿泊予約','フロント','宿泊料金'],['35e1c-ja-workplace-register','35e1c-ja-condition-contrast']]
];

export const restructureItems=[
 ['en-s1-l4','35e1b-en-d-help-alternative-expr','exposure'],
 ['en-s4-l3','35e1b-en-d-restaurant-allergy-expr','required'],
 ['en-s5-l2','35e1b-en-d-flight-delay-expr','required'],
 ['en-s6-l3','35e1b-en-d-invitation-decline-expr','required'],
 ['en-s6-l4','35e1c-en-perfect-vs-past','support','grammar'],
 ['ja-s4-l1','35e1c-ja-kara-node-contrast','required','grammar'],
 ['ja-s5-l3','35e1b-ja-d-flight-delay-expr','required'],
 ['ja-s6-l4','35e1b-ja-d-invitation-condition-expr','required']
];

export const rejectedDrafts={duplicate:9,semantic_invalid:7};
