// Editorially curated source for Phase 3.5E.1B.
// Tuple fields: id, topic, stage, register, text, translation/anchor, context.
const S=(id,topic,stage,register,text,anchor,context)=>({id,topic,stage,register,text,anchor,context});
const D=(id,topic,stage,register,goal,context,turns)=>({id,topic,stage,register,goal,context,turns:turns.map((text,index)=>({speaker:index%2?'B':'A',text,role:['opening_request','response','clarification_follow_up','response_alternative','confirmation_follow_up','confirmation_closing'][Math.min(index,5)]}))});

export const rejectedDrafts=[
 {language:'en',type:'duplicate',text:'Can you help me?',reason:'与现有 canonical expression 完全重复。'},
 {language:'ja',type:'duplicate',text:'手伝ってください。',reason:'与现有 canonical dialogue turn 完全重复。'},
 {language:'en',type:'duplicate',text:'No worries.',reason:'与现有 canonical expression 完全重复。'},
 {language:'ja',type:'duplicate',text:'大丈夫です。',reason:'与现有 canonical expression 完全重复。'},
 {language:'en',type:'duplicate',text:'Does this train go to the airport?',reason:'与现有 canonical dialogue turn 完全重复。'},
 {language:'ja',type:'duplicate',text:'カードは使えますか。',reason:'与现有 canonical dialogue turn 完全重复。'},
 {language:'en',type:'duplicate',text:'How long is the wait?',reason:'与现有 canonical dialogue turn 完全重复。'},
 {language:'en',type:'semantic_invalid',text:'I have food problems.','reason':'饮食限制表达不具体，不能支持安全点餐任务。'},
 {language:'ja',type:'semantic_invalid',text:'食べ物がだめです。','reason':'范围与原因都含糊，不适合作为饮食限制核心表达。'},
 {language:'en',type:'semantic_invalid',text:'Give me another appointment.','reason':'服务场景语气不自然且过于命令式。'},
 {language:'ja',type:'semantic_invalid',text:'予約を別にしてください。','reason':'改期意图不清，可能被理解为另建预约。'},
 {language:'en',type:'semantic_invalid',text:'I disagree with you.','reason':'可用但教学价值不足，缺少立场缓和或理由衔接。'},
 {language:'ja',type:'semantic_invalid',text:'それは違います。','reason':'在目标分歧场景中过硬，缺少关系距离控制。'},
 {language:'en',type:'semantic_invalid',text:'My throat is bad.','reason':'症状描述不自然且不够具体。'},
 {language:'ja',type:'semantic_invalid',text:'喉が悪いです。','reason':'自然度不足，未准确描述症状。'},
 {language:'en',type:'semantic_invalid',text:'Return this for me.','reason':'退货意图和期望结果不清，register 不合适。'},
 {language:'ja',type:'semantic_invalid',text:'これを返します。','reason':'可能表示归还而非商品退货，语义范围不清。'},
 {language:'en',type:'semantic_invalid',text:'Where is somewhere else?',reason:'替代路线追问不自然。'}
];

export const enExpressions=[
 S('clarify-mean','chat',2,'neutral','What do you mean by that?','你那句话是什么意思？','没有听懂对方刚才的意思，请对方解释。'),
 S('clarify-specific','chat',2,'neutral','Could you be more specific?','你能说得具体一点吗？','需要对方补充具体信息。'),
 S('clarify-say-again','help',1,'polite','Could you say that again, please?','可以请你再说一遍吗？','在服务场景中没有听清。'),
 S('clarify-slower','help',1,'polite','Could you speak a little more slowly?','你可以说慢一点吗？','请对方降低语速。'),
 S('clarify-spell','help',2,'polite','How do you spell that?','那个怎么拼？','确认姓名或生词的拼写。'),
 S('clarify-last-part','chat',2,'neutral','I didn’t catch the last part.','我没听清最后一部分。','指出具体没有听清的位置。'),
 S('clarify-confirm-heard','chat',3,'neutral','Did you say fifteen or fifty?','你说的是十五还是五十？','核对容易听错的数字。'),
 S('clarify-refer','chat',3,'neutral','Which one are you referring to?','你指的是哪一个？','指代不清时要求明确。'),
 S('clarify-example','school',3,'polite','Could you give me an example?','你能举个例子吗？','在课堂或讨论中请求例子。'),
 S('clarify-understand','school',3,'neutral','Let me check that I understand correctly.','我确认一下自己是否理解正确。','复述前先标明确认意图。'),
 S('clarify-in-other-words','chat',4,'neutral','So, in other words, we need to start over?','也就是说，我们需要重新开始吗？','用改述检查理解。'),
 S('clarify-correct-me','school',3,'neutral','Please correct me if I’m wrong.','如果我理解错了，请纠正我。','在提出暂定理解前邀请纠正。'),
 S('follow-what-next','chat',1,'neutral','What should we do next?','我们下一步该做什么？','完成一步后询问下一步。'),
 S('follow-anything-else','shopping',1,'polite','Is there anything else you need?','你还需要别的吗？','服务人员确认是否还有需求。'),
 S('follow-how-long','time',2,'neutral','How long will that take?','那需要多长时间？','追问预计耗时。'),
 S('follow-when-hear','time',3,'polite','When can I expect to hear back?','我大概什么时候能收到回复？','正式跟进回复时间。'),
 S('follow-what-happened','chat',2,'neutral','What happened after that?','后来发生了什么？','听故事时自然追问。'),
 S('follow-how-go','plans',2,'neutral','How did it go?','事情进行得怎么样？','跟进之前提过的活动。'),
 S('follow-need-bring','travel',2,'polite','Do I need to bring anything?','我需要带什么东西吗？','预约或活动前确认准备事项。'),
 S('follow-who-contact','help',3,'polite','Who should I contact about this?','这件事我应该联系谁？','找到正确负责人。'),
 S('follow-other-options','shopping',3,'neutral','What other options do I have?','我还有哪些其他选择？','当前方案不可行时追问替代方案。'),
 S('follow-check-later','time',2,'neutral','Can I check back later today?','我今天晚些时候再来确认可以吗？','约定稍后再次联系。'),
 S('confirm-right','chat',1,'neutral','That’s right.','对，就是这样。','确认对方的理解。'),
 S('confirm-understood','chat',2,'neutral','Got it. Thanks for explaining.','明白了，谢谢你的解释。','表示已经理解并结束澄清。'),
 S('confirm-plan','plans',2,'neutral','So we’re meeting at six, right?','所以我们六点见，对吧？','复核时间安排。'),
 S('confirm-booked','time',2,'polite','Could you confirm that it’s booked?','可以确认一下已经预约成功了吗？','要求服务方确认预约状态。'),
 S('confirm-email','school',2,'polite','Could you send me a confirmation email?','可以给我发一封确认邮件吗？','请求书面确认。'),
 S('confirm-repeat-order','food',2,'polite','Let me repeat your order.','我来复述一下您的订单。','服务人员核对点单内容。'),
 S('confirm-if-changes','plans',3,'neutral','I’ll let you know if anything changes.','如果有变化，我会告诉你。','确认后说明变更沟通方式。'),
 S('confirm-works','time',2,'neutral','That time works for me.','那个时间我可以。','接受提议的时间。'),
 S('confirm-agreed','school',3,'neutral','All right, we have a plan.','好，我们有方案了。','讨论结束时总结达成一致。'),
 S('confirm-double-check','travel',3,'neutral','I’ll double-check before we leave.','出发前我会再确认一次。','说明最终核对动作。'),
 S('refuse-sorry-cant','social',1,'polite','I’m sorry, but I can’t make it.','抱歉，我去不了。','礼貌拒绝邀请。'),
 S('refuse-not-today','help',2,'neutral','I can help, but not today.','我可以帮忙，但今天不行。','带条件地接受请求。'),
 S('refuse-not-comfortable','social',3,'neutral','I’m not comfortable with that.','我对此不太自在。','明确但不过度强硬地设界限。'),
 S('refuse-appreciate-offer','social',3,'polite','I appreciate the offer, but I’ll pass.','谢谢你的好意，不过这次不用了。','礼貌拒绝提议。'),
 S('refuse-unable-refund','shopping',3,'polite','I’m afraid we can’t offer a cash refund.','很抱歉，我们不能提供现金退款。','服务方说明限制。'),
 S('alternative-tomorrow','time',1,'neutral','How about tomorrow instead?','改成明天怎么样？','原时间不可行时提出替代。'),
 S('alternative-different-table','food',2,'polite','Would a table outside be okay?','室外的桌子可以吗？','餐厅无原座位时提供替代。'),
 S('alternative-store-credit','shopping',3,'polite','We can offer store credit instead.','我们可以改为提供店内余额。','退款不可行时提供替代方案。'),
 S('alternative-split-work','school',2,'neutral','Why don’t we split the work?','我们分工怎么样？','小组任务中提出分工。'),
 S('alternative-call','help',2,'neutral','If now isn’t a good time, I can call back.','如果现在不方便，我可以再打来。','发现时机不合适时提供替代。'),
 S('alternative-route','travel',3,'neutral','There’s another route, but it takes longer.','还有一条路线，不过时间更长。','说明替代路线及代价。'),
 S('alternative-repair','home',3,'polite','If it can’t be fixed today, could you lend me a heater?','如果今天修不好，可以借我一台暖气吗？','维修延迟时请求临时方案。'),
 S('alternative-online','time',2,'polite','Could we do it online instead?','我们可以改为线上进行吗？','改变会面方式。'),
 S('repair-wrong-word','chat',2,'neutral','Sorry, that’s not what I meant.','抱歉，我不是那个意思。','发现表达造成误解时修正。'),
 S('repair-start-again','chat',2,'neutral','Let me start again.','我重新说一遍。','表达混乱后重新组织。'),
 S('repair-rephrase','chat',3,'neutral','Let me put that another way.','我换一种说法。','用不同措辞修复理解。'),
 S('repair-correction','chat',2,'neutral','Actually, I meant Thursday, not Tuesday.','其实我说的是星期四，不是星期二。','更正关键信息。'),
 S('repair-misunderstanding','social',3,'neutral','I think there’s been a misunderstanding.','我想这里有些误会。','温和指出双方理解不一致。'),
 S('repair-not-blaming','social',4,'neutral','I’m not blaming you; I’m trying to understand what happened.','我不是在责怪你，我只是想弄清发生了什么。','缓和可能被听成指责的话。'),
 S('repair-tone','school',4,'neutral','That came out more strongly than I intended.','刚才的语气比我本意更强烈。','意识到语气过重后修复。'),
 S('repair-name','social',1,'polite','Sorry, I got your name wrong.','抱歉，我把你的名字叫错了。','纠正称呼错误。'),
 S('repair-order','food',2,'polite','Sorry, I ordered the soup, not the salad.','不好意思，我点的是汤，不是沙拉。','餐厅中纠正上错的餐点。'),
 S('repair-which-bus','travel',2,'neutral','Sorry, I meant the number fifteen bus.','抱歉，我指的是十五路公交车。','更正交通信息。'),
 S('food-ready-order','food',1,'polite','We’re ready to order.','我们可以点餐了。','向服务员表示可以点单。'),
 S('food-recommend','food',2,'polite','What would you recommend?','你有什么推荐吗？','请服务员推荐菜品。'),
 S('food-allergy','food',2,'polite','I’m allergic to peanuts.','我对花生过敏。','明确说明食物过敏。'),
 S('food-contain','food',2,'polite','Does this contain dairy?','这个含乳制品吗？','确认饮食限制。'),
 S('food-without','food',2,'polite','Could I have this without onions?','这个可以不放洋葱吗？','请求调整菜品。'),
 S('food-side','food',2,'polite','Could we get the sauce on the side?','酱汁可以另外放吗？','请求酱汁分开放。'),
 S('food-bill','food',1,'polite','Could we have the bill, please?','请给我们账单。','用餐结束后结账。'),
 S('food-split-bill','food',2,'polite','Could we split the bill?','我们可以分开结账吗？','询问能否分账。'),
 S('appt-make','time',2,'polite','I’d like to make an appointment.','我想预约。','开始预约流程。'),
 S('appt-available','time',2,'polite','Do you have anything available on Friday?','星期五有空档吗？','询问可预约时间。'),
 S('appt-reschedule','time',2,'polite','I need to reschedule my appointment.','我需要改期。','主动提出更改预约。'),
 S('appt-cancel','time',2,'polite','I’m calling to cancel my appointment.','我打电话来取消预约。','说明来电目的。'),
 S('appt-earlier','time',2,'polite','Is there anything earlier?','有更早的时间吗？','追问更早空档。'),
 S('appt-name','time',1,'polite','The appointment is under Lee.','预约登记的名字是 Lee。','提供预约姓名。'),
 S('appt-arrive','time',2,'polite','How early should I arrive?','我应该提前多久到？','询问到场时间。'),
 S('appt-confirm-day','time',2,'neutral','Just to confirm, that’s next Monday.','再确认一下，是下周一。','复核日期。'),
 S('return-wrong-size','shopping',2,'polite','I’d like to exchange this for a different size.','我想换一个尺码。','说明换货需求。'),
 S('return-receipt','shopping',2,'polite','Do you need the receipt?','需要收据吗？','确认退换货材料。'),
 S('return-defective','shopping',2,'polite','It stopped working after two days.','用了两天后它就坏了。','说明商品故障。'),
 S('return-refund-card','shopping',3,'polite','Will the refund go back to my card?','退款会退回我的卡吗？','确认退款方式。'),
 S('return-policy','shopping',2,'polite','What is your return policy?','你们的退货政策是什么？','购买前或退货时询问规则。'),
 S('return-original','shopping',3,'polite','It’s still in the original packaging.','它还在原包装里。','说明商品状态。'),
 S('direction-get-station','travel',1,'polite','How do I get to the station?','去车站怎么走？','问路。'),
 S('direction-right-way','travel',1,'neutral','Am I going the right way?','我走对方向了吗？','途中确认方向。'),
 S('direction-stop','travel',2,'polite','Which stop should I get off at?','我应该在哪一站下车？','确认下车站。'),
 S('direction-transfer','travel',2,'polite','Do I need to change trains?','我需要换乘吗？','确认交通换乘。'),
 S('direction-platform','travel',1,'polite','Which platform does it leave from?','它从哪个站台出发？','确认出发站台。'),
 S('direction-delay','travel',2,'polite','Is the train running on time?','火车准点吗？','确认交通延误。'),
 S('medical-symptom','health',2,'polite','I’ve had a sore throat since yesterday.','我从昨天开始喉咙痛。','向医护人员描述症状和持续时间。'),
 S('medical-worse','health',2,'neutral','It gets worse at night.','晚上会更严重。','补充症状变化。'),
 S('hotel-quiet-room','travel',2,'polite','Could I have a quieter room?','可以给我一间更安静的房间吗？','住宿中请求换房。'),
 S('hotel-checkout','travel',2,'polite','What time is check-out?','几点退房？','确认住宿退房时间。'),
 S('direction-show-map','travel',2,'polite','Could you show me where that is on the map?','可以在地图上给我指出来吗？','听完路线后请求视觉确认。')
];

export const jaExpressions=[
 S('clarify-mean','chat',2,'neutral','それはどういう意味ですか。','那是什么意思？','没有理解对方刚才的意思，请对方解释。'),
 S('clarify-specific','chat',2,'polite','もう少し具体的に教えていただけますか。','可以再具体说明一点吗？','礼貌请求补充具体信息。'),
 S('clarify-say-again','help',1,'polite','もう一度言っていただけますか。','可以请您再说一遍吗？','在服务场景中没有听清。'),
 S('clarify-slower','help',1,'polite','もう少しゆっくり話していただけますか。','可以请您说慢一点吗？','礼貌请求降低语速。'),
 S('clarify-reading','help',2,'polite','これは何と読みますか。','这个怎么读？','询问汉字或词语读法。'),
 S('clarify-last-part','chat',2,'neutral','最後のところが聞き取れませんでした。','最后那部分我没听清。','指出具体没有听清的位置。'),
 S('clarify-confirm-heard','chat',3,'neutral','十五日ですか、五十日ですか。','是十五天还是五十天？','核对容易听错的数字。'),
 S('clarify-refer','chat',3,'neutral','どちらのことを言っていますか。','你指的是哪一个？','指代不清时要求明确。'),
 S('clarify-example','school',3,'polite','例を挙げていただけますか。','可以举个例子吗？','在课堂或讨论中请求例子。'),
 S('clarify-understand','school',3,'neutral','念のため、私の理解を確認させてください。','请让我确认一下自己的理解。','复述前先标明确认意图。'),
 S('clarify-in-other-words','chat',4,'neutral','つまり、最初からやり直すということですか。','也就是说，要从头再来吗？','用改述检查理解。'),
 S('clarify-correct-me','school',3,'neutral','間違っていたら、直してください。','如果我理解错了，请纠正我。','在提出暂定理解前邀请纠正。'),
 S('follow-what-next','chat',1,'neutral','次は何をすればいいですか。','下一步该做什么？','完成一步后询问下一步。'),
 S('follow-anything-else','shopping',1,'polite','ほかに何かございますか。','您还需要别的吗？','服务人员确认是否还有需求。'),
 S('follow-how-long','time',2,'neutral','どのくらいかかりますか。','需要多长时间？','追问预计耗时。'),
 S('follow-when-hear','time',3,'polite','いつごろお返事をいただけますか。','大概什么时候能收到回复？','正式跟进回复时间。'),
 S('follow-what-happened','chat',2,'neutral','それから、どうなったの？','后来怎么样了？','听故事时自然追问。'),
 S('follow-how-go','plans',2,'neutral','どうだった？','事情怎么样？','跟进之前提过的活动。'),
 S('follow-need-bring','travel',2,'polite','何か持っていくものはありますか。','需要带什么东西吗？','预约或活动前确认准备事项。'),
 S('follow-who-contact','help',3,'polite','この件は、どなたに連絡すればいいですか。','这件事该联系哪位？','找到正确负责人。'),
 S('follow-other-options','shopping',3,'neutral','ほかにどんな方法がありますか。','还有什么其他办法？','当前方案不可行时追问替代。'),
 S('follow-check-later','time',2,'neutral','今日、また後で確認してもいいですか。','今天晚些时候再确认可以吗？','约定稍后再次联系。'),
 S('confirm-right','chat',1,'neutral','はい、そのとおりです。','对，就是这样。','确认对方的理解。'),
 S('confirm-understood','chat',2,'neutral','わかりました。説明してくれてありがとう。','明白了，谢谢你的解释。','表示理解并结束澄清。'),
 S('confirm-plan','plans',2,'neutral','では、六時に会うということでいいですね。','那么，六点见对吧？','复核时间安排。'),
 S('confirm-booked','time',2,'polite','予約できているか確認していただけますか。','可以确认一下预约成功了吗？','要求服务方确认预约状态。'),
 S('confirm-email','school',2,'polite','確認のメールを送っていただけますか。','可以发一封确认邮件吗？','请求书面确认。'),
 S('confirm-repeat-order','food',2,'polite','ご注文を確認いたします。','我确认一下您的点单。','服务人员核对点单内容。'),
 S('confirm-if-changes','plans',3,'neutral','何か変わったら連絡します。','如果有变化，我会联系你。','确认后说明变更沟通方式。'),
 S('confirm-works','time',2,'neutral','その時間で大丈夫です。','那个时间可以。','接受提议的时间。'),
 S('confirm-agreed','school',3,'neutral','では、この方針で進めましょう。','那么，就按这个方案进行吧。','讨论结束时总结一致。'),
 S('confirm-double-check','travel',3,'neutral','出発する前に、もう一度確認します。','出发前我会再确认一次。','说明最终核对动作。'),
 S('refuse-sorry-cant','social',1,'polite','すみませんが、今回は行けません。','抱歉，这次去不了。','礼貌拒绝邀请。'),
 S('refuse-not-today','help',2,'neutral','手伝えるけど、今日は難しい。','可以帮忙，不过今天不行。','带条件地接受请求。'),
 S('refuse-not-comfortable','social',3,'neutral','それはちょっと困ります。','那样我有点为难。','委婉但明确地设界限。'),
 S('refuse-appreciate-offer','social',3,'polite','お心遣いはありがたいのですが、今回は遠慮します。','谢谢您的好意，不过这次不用了。','正式礼貌拒绝。'),
 S('refuse-unable-refund','shopping',3,'polite','申し訳ありませんが、現金での返金はできません。','很抱歉，不能现金退款。','服务方说明限制。'),
 S('alternative-tomorrow','time',1,'neutral','代わりに、明日はどうですか。','改成明天怎么样？','原时间不可行时提出替代。'),
 S('alternative-different-table','food',2,'polite','外の席でもよろしいですか。','室外座位可以吗？','餐厅无原座位时提供替代。'),
 S('alternative-store-credit','shopping',3,'polite','代わりに、店内で使える商品券をお渡しできます。','可以改为提供店内使用的商品券。','退款不可行时提供替代。'),
 S('alternative-split-work','school',2,'neutral','作業を分担しませんか。','我们分工怎么样？','小组任务中提出分工。'),
 S('alternative-call','help',2,'neutral','今お忙しければ、後でかけ直します。','如果现在忙，我稍后再打。','发现时机不合适时提供替代。'),
 S('alternative-route','travel',3,'neutral','別の行き方もありますが、少し時間がかかります。','还有别的路线，不过更费时间。','说明替代路线及代价。'),
 S('alternative-repair','home',3,'polite','今日直らない場合は、暖房器具を貸していただけますか。','如果今天修不好，可以借我取暖设备吗？','维修延迟时请求临时方案。'),
 S('alternative-online','time',2,'polite','代わりに、オンラインでもよろしいですか。','改为线上可以吗？','改变会面方式。'),
 S('repair-wrong-word','chat',2,'neutral','すみません、そういう意味ではありません。','抱歉，我不是那个意思。','发现表达造成误解时修正。'),
 S('repair-start-again','chat',2,'neutral','最初から言い直します。','我从头再说一遍。','表达混乱后重新组织。'),
 S('repair-rephrase','chat',3,'neutral','別の言い方をしますね。','我换一种说法。','用不同措辞修复理解。'),
 S('repair-correction','chat',2,'neutral','すみません、火曜日ではなく木曜日です。','抱歉，不是星期二，是星期四。','更正关键信息。'),
 S('repair-misunderstanding','social',3,'neutral','何か誤解があるようです。','好像有些误会。','温和指出理解不一致。'),
 S('repair-not-blaming','social',4,'neutral','責めているのではなく、何があったのか知りたいんです。','我不是在责怪你，只是想知道发生了什么。','缓和可能被听成指责的话。'),
 S('repair-tone','school',4,'neutral','少し強い言い方になってしまいました。','刚才说得有点重了。','意识到语气过重后修复。'),
 S('repair-name','social',1,'polite','すみません、お名前を間違えました。','抱歉，我把您的名字叫错了。','纠正称呼错误。'),
 S('repair-order','food',2,'polite','すみません、注文したのはサラダではなくスープです。','不好意思，我点的不是沙拉，是汤。','纠正上错的餐点。'),
 S('repair-which-bus','travel',2,'neutral','すみません、十五番のバスのことです。','抱歉，我指的是十五路公交车。','更正交通信息。'),
 S('food-ready-order','food',1,'polite','注文をお願いします。','请帮我们点餐。','向服务员表示可以点单。'),
 S('food-recommend','food',2,'polite','おすすめは何ですか。','有什么推荐？','请服务员推荐菜品。'),
 S('food-allergy','food',2,'polite','ピーナッツアレルギーがあります。','我对花生过敏。','明确说明食物过敏。'),
 S('food-contain','food',2,'polite','これは乳製品が入っていますか。','这个含乳制品吗？','确认饮食限制。'),
 S('food-without','food',2,'polite','玉ねぎ抜きにできますか。','可以不放洋葱吗？','请求调整菜品。'),
 S('food-side','food',2,'polite','ソースは別にしていただけますか。','酱汁可以另外放吗？','请求酱汁分开放。'),
 S('food-bill','food',1,'polite','お会計をお願いします。','请结账。','用餐结束后结账。'),
 S('food-split-bill','food',2,'polite','別々に払えますか。','可以分开付款吗？','询问能否分账。'),
 S('appt-make','time',2,'polite','予約を取りたいのですが。','我想预约。','开始预约流程。'),
 S('appt-available','time',2,'polite','金曜日に空いている時間はありますか。','星期五有空档吗？','询问可预约时间。'),
 S('appt-reschedule','time',2,'polite','予約の日を変更したいのですが。','我想更改预约日期。','主动提出改期。'),
 S('appt-cancel','time',2,'polite','予約をキャンセルしたくて、お電話しました。','我打电话来取消预约。','说明来电目的。'),
 S('appt-earlier','time',2,'polite','もう少し早い時間はありますか。','有更早的时间吗？','追问更早空档。'),
 S('appt-name','time',1,'polite','李の名前で予約しています。','预约登记的是李。','提供预约姓名。'),
 S('appt-arrive','time',2,'polite','何分前に行けばいいですか。','应该提前几分钟到？','询问到场时间。'),
 S('appt-confirm-day','time',2,'neutral','確認ですが、来週の月曜日ですね。','确认一下，是下周一。','复核日期。'),
 S('return-wrong-size','shopping',2,'polite','違うサイズに交換したいのですが。','我想换一个尺码。','说明换货需求。'),
 S('return-receipt','shopping',2,'polite','レシートは必要ですか。','需要收据吗？','确认退换货材料。'),
 S('return-defective','shopping',2,'polite','二日使ったら動かなくなりました。','用了两天后就不工作了。','说明商品故障。'),
 S('return-refund-card','shopping',3,'polite','返金はカードに戻りますか。','退款会退回卡里吗？','确认退款方式。'),
 S('return-policy','shopping',2,'polite','返品の条件を教えてください。','请告诉我退货条件。','询问退货规则。'),
 S('return-original','shopping',3,'polite','まだ元の箱に入っています。','还在原来的盒子里。','说明商品状态。'),
 S('direction-get-station','travel',1,'polite','駅へはどう行けばいいですか。','去车站怎么走？','问路。'),
 S('direction-right-way','travel',1,'neutral','この道で合っていますか。','走这条路对吗？','途中确认方向。'),
 S('direction-stop','travel',2,'polite','どの停留所で降りればいいですか。','应该在哪一站下车？','确认下车站。'),
 S('direction-transfer','travel',2,'polite','乗り換えは必要ですか。','需要换乘吗？','确认交通换乘。'),
 S('direction-platform','travel',1,'polite','何番線から出ますか。','从几号站台出发？','确认出发站台。'),
 S('direction-delay','travel',2,'polite','電車は時間どおりに動いていますか。','电车准点运行吗？','确认交通延误。'),
 S('medical-symptom','health',2,'polite','昨日から喉が痛いです。','从昨天开始喉咙痛。','向医护人员描述症状和持续时间。'),
 S('medical-worse','health',2,'neutral','夜になると、もっとひどくなります。','到晚上会更严重。','补充症状变化。'),
 S('hotel-quiet-room','travel',2,'polite','もう少し静かな部屋に替えていただけますか。','可以换到更安静的房间吗？','住宿中请求换房。'),
 S('hotel-checkout','travel',2,'polite','チェックアウトは何時ですか。','几点退房？','确认退房时间。'),
 S('service-onegaishimasu','shopping',1,'polite','こちらでお願いします。','请用这个。','付款或选择时指明对象。'),
 S('service-kekkou','shopping',2,'polite','袋は結構です。','不用袋子。','在商店礼貌拒绝购物袋。'),
 S('service-mochikaeri','food',1,'polite','こちらは持ち帰りでお願いします。','这个请做成外带。','点餐时说明外带。'),
 S('service-ryoushuusho','shopping',2,'polite','領収書をいただけますか。','可以给我收据吗？','正式请求收据。'),
 S('home-tachiai','home',3,'polite','修理のときは立ち会いが必要ですか。','维修时需要在场吗？','确认维修到访条件。'),
 S('medical-kusuri','health',2,'polite','この薬は食後に飲めばいいですか。','这个药饭后吃就可以吗？','向药师确认服药时间。'),
 S('direction-show-map','travel',2,'polite','地図で場所を教えていただけますか。','可以在地图上指出位置吗？','听完路线后请求视觉确认。')
];

export const enDialogues=[
 D('restaurant-allergy','food',2,'polite','确认过敏原后安全点餐。','顾客在餐厅确认菜品是否含花生，并完成替换点单。',["Hi. Are you ready to order?","Almost. Does the curry contain peanuts?","The sauce does, but the tomato soup doesn’t.","Thanks. I’ll have the soup, then.","Certainly. I’ll note that you have a peanut allergy.","Thank you. I appreciate that."]),
 D('restaurant-bill','food',2,'polite','核对账单错误并完成结账。','顾客发现账单上多了一项，服务员核对并更正。',["Excuse me, could we have the bill?","Of course. I’ll bring it over.","I think there’s an extra dessert on here.","You’re right. I’m sorry about that.","Could you remove it and let us pay separately?","Certainly. I’ll bring two corrected bills."]),
 D('appointment-reschedule','time',2,'polite','完成预约改期与最终确认。','来电者把周二预约改到周四。',["Good morning. I need to reschedule my appointment.","Certainly. What day is it booked for?","It’s under Lee for Tuesday at ten.","I have Thursday at eleven or Friday at nine.","Thursday at eleven works for me.","All right. Your appointment is now Thursday at eleven."]),
 D('appointment-cancel','time',2,'polite','取消预约并确认是否收费。','来电者因生病取消预约。',["I’m calling to cancel my appointment tomorrow.","May I have the name on the booking?","It’s Morgan Chen.","Thank you. There’s no cancellation fee this time.","Great. Could you email me a confirmation?","Yes, I’ll send it right away."]),
 D('help-alternative','help',2,'neutral','拒绝部分请求并提供可行替代。','同学请求当晚帮忙搬家。',["Could you help me move tonight?","I can’t tonight, but I’m free tomorrow morning.","Would nine o’clock work?","I have class at nine. How about ten thirty?","Ten thirty is perfect. Thanks for offering another time.","No problem. Send me the address."]),
 D('return-exchange','shopping',2,'polite','凭收据完成尺码换货。','顾客退回尺码不合适且未穿过的鞋。',["Hi. I’d like to exchange these shoes.","Is there anything wrong with them?","No, they’re just too small. I haven’t worn them outside.","Do you have the receipt?","Yes. Could I try the next size up?","Of course. I’ll get that for you."]),
 D('return-defect','shopping',3,'polite','说明故障并协商退款方式。','顾客退回使用两天即故障的水壶。',["This kettle stopped working after two days.","I’m sorry to hear that. Do you have the receipt?","Yes. I’d prefer a refund rather than a replacement.","That’s fine. The refund will go back to your card.","How long will that take?","Usually three to five business days."]),
 D('directions-repair','travel',2,'polite','在误解目的地后修正问路。','旅客问去中央车站的路，对方先听成公交总站。',["Excuse me, how do I get to Central Station?","The bus terminal is two blocks that way.","Sorry, I meant the train station.","Oh, I see. Take the next left and walk past the bank.","Is it far from there?","No, it’s about a five-minute walk."]),
 D('train-transfer','travel',2,'polite','确认换乘、站台与时间。','旅客询问前往机场的列车。',["Excuse me, is this the right train for the airport?","Not directly. You need to change at Central.","Which platform do I need there?","Platform six. The signs are easy to follow.","Will I have enough time to change?","Yes. You’ll have about twelve minutes."]),
 D('group-work','school',2,'neutral','分工并确认交付时间。','学生为小组展示分配工作。',["How should we split the presentation?","I can do the introduction and the first two slides.","Could you also find one example for slide two?","Sure. Can you check the figures in the last section?","Yes. Let’s send everything to each other by Friday.","Agreed. Then we can practise on Monday."]),
 D('group-disagree','school',4,'neutral','表达不同意见并达成折中。','小组对报告重点意见不同。',["I think we should focus on the survey results.","I see your point, but the interviews explain why the results changed.","Are you suggesting we include both?","Yes, but we could shorten the background section.","That sounds reasonable. Let’s keep one paragraph of background.","Great. I’ll revise the outline."]),
 D('repair-heating','home',3,'polite','报修暖气并确认临时方案。','租客报告暖气不工作。',["Hello. The heater in my flat isn’t working.","I’m sorry about that. Is it showing an error code?","Yes, it says E3, and the room is getting cold.","A technician can come tomorrow afternoon.","If it can’t be fixed then, could I borrow a portable heater?","Yes. We can leave one at reception today."]),
 D('repair-leak','home',3,'polite','报告漏水并说明紧急程度。','租客发现水槽下漏水。',["There’s water leaking under the kitchen sink.","Is it a slow drip or a steady flow?","It’s a steady flow, so I’ve turned the water off.","Good. I’ll send someone within an hour.","Do I need to stay home?","Yes, please. The plumber will call before arriving."]),
 D('medical-symptoms','health',3,'polite','描述症状、持续时间与严重程度。','患者因喉咙痛和发烧看诊。',["What seems to be the problem?","I’ve had a sore throat since Monday, and I had a fever last night.","Are you having any trouble breathing?","No, but it hurts when I swallow.","All right. I’ll examine your throat first.","Okay. Thank you."]),
 D('pharmacy-medicine','health',2,'polite','确认药物用法和注意事项。','顾客向药师询问止痛药。',["Could you tell me how to take this medicine?","Take one tablet after food, up to three times a day.","Can I take it with my allergy medicine?","Let me check. What’s the name of that medicine?","It’s written on this box.","Thanks. These two are safe to take together."]),
 D('invitation-decline','social',2,'neutral','礼貌拒绝邀请并提出另约。','朋友邀请周五吃饭。',["Would you like to have dinner on Friday?","I’d love to, but I already have plans that evening.","No problem. Are you free over the weekend?","Sunday afternoon should work.","How about coffee at three?","Perfect. I’ll see you then."]),
 D('invitation-condition','social',2,'neutral','带条件接受邀请并确认细节。','朋友邀请参加野餐。',["We’re having a picnic on Saturday. Want to come?","Maybe. What time are you starting?","Around noon, at Riverside Park.","I can come if I finish work by eleven.","That’s fine. Just text me when you know.","Will do. Thanks for inviting me."]),
 D('misunderstanding-time','time',2,'neutral','修正时间误会并重新确认。','两人对会议时间理解不同。',["I thought the meeting started at two.","It was moved to three yesterday.","Oh, I must have missed that message.","No worries. Can you still make it?","Yes. Just to confirm, it’s in Room 4 at three.","That’s right. See you there."]),
 D('misunderstanding-tone','social',4,'neutral','解释语气并修复关系。','同事觉得一句反馈太尖锐。',["Your comment in the meeting sounded quite critical.","I’m sorry. I was questioning the schedule, not your work.","Thanks for explaining. I thought you were blaming me.","I can see why it sounded that way.","Could we talk about the schedule again tomorrow?","Of course. I’ll be clearer next time."]),
 D('hotel-room','travel',2,'polite','报告房间问题并完成换房。','住客因街道噪声请求换房。',["Hello. My room is very noisy at night.","I’m sorry. Is the noise coming from the street?","Yes. Do you have a quieter room available?","We have one on the sixth floor, but it has two single beds.","That’s fine. Can I move tonight?","Certainly. I’ll prepare the new key."]),
 D('hotel-booking','travel',2,'polite','查找预订并确认早餐。','住客办理入住时预订记录不易找到。',["Hi. I have a booking under Patel.","I’m not seeing it yet. Could it be under another name?","Try Priya Patel. I booked it online last month.","Found it. You’re staying for three nights, correct?","Yes. Is breakfast included?","It is. Breakfast starts at seven."]),
 D('taxi-destination','travel',2,'polite','确认目的地、路线和支付方式。','乘客乘出租车去酒店。',["Could you take me to the Riverside Hotel, please?","Certainly. Do you mean the one on King Street?","Yes, that’s the one. How long will it take?","About twenty minutes if traffic is light.","Can I pay by card?","Yes, you can."]),
 D('bus-wrong-stop','travel',2,'neutral','发现坐错方向后获得补救路线。','乘客担心错过下车站。',["Does this bus stop near City Hospital?","No, this bus is going in the other direction.","Oh no. Where should I get off?","Get off at the next stop and take the 24 back.","Does the 24 stop outside the hospital?","Yes, right by the main entrance."]),
 D('order-unavailable','food',2,'polite','菜品售罄后选择替代。','餐厅告知顾客所点菜品卖完。',["I’d like the grilled fish, please.","I’m sorry, we’ve sold out of the fish.","What would you recommend instead?","The chicken is similar, or we have a vegetable pasta.","I’ll try the pasta. Could I have it without cheese?","Of course."]),
 D('dietary-clarify','food',3,'polite','澄清素食需求并确认配料。','顾客确认汤是否真正适合素食者。',["Is the vegetable soup suitable for vegetarians?","Yes, it doesn’t contain any meat.","What about the stock? Is that vegetable stock too?","Let me check with the kitchen.","Thanks. I need to avoid chicken stock as well.","Understood. I’ll make sure before you order."]),
 D('school-deadline','school',3,'polite','请求延期并协商新截止时间。','学生因生病请求作业延期。',["Could I ask about the assignment deadline?","Of course. What’s the issue?","I’ve been ill, and I’m not going to finish by Thursday.","I can give you until Monday, but no later.","Monday would really help. Do I need to provide a medical note?","Not this time. Please email me the work by noon."]),
 D('work-clarification','school',3,'neutral','澄清任务范围并确认优先级。','同事收到含糊的资料整理请求。',["Could you update the client file today?","Which part would you like me to update?","The contact details and the notes from yesterday’s call.","Should I leave the payment section unchanged?","Yes. Please focus on the contact information first.","Got it. I’ll send it to you by four."]),
 D('neighbour-noise','home',3,'polite','提出噪声问题并协商解决。','邻居深夜音乐过大。',["Hi. I’m sorry to bother you, but the music is coming through the wall.","Oh, I didn’t realize it was that loud.","Would you mind turning it down after ten?","Of course. We’re finishing soon anyway.","Thanks. I really appreciate it.","No problem, and sorry again."]),
 D('wrong-delivery','shopping',3,'polite','说明送错商品并安排补发。','网购顾客收到错误颜色。',["I received the wrong item in my order.","I’m sorry about that. What did you order?","A black jacket, but this one is blue.","I can send the correct one today.","Do I need to return this one first?","No. We’ll include a prepaid return label."]),
 D('opinion-disagree','chat',3,'neutral','礼貌表达不同意见并追问理由。','朋友对城市禁车提议看法不同。',["I think cars should be banned from the city centre.","I’m not sure I agree. Some people need to drive to work.","That’s true, but public transport could be improved.","Would you support a ban if buses ran more often?","Maybe during the busiest hours.","That sounds like a reasonable compromise."]),
 D('lost-reservation','time',3,'polite','预订未显示时提供证据并取得替代安排。','餐厅找不到顾客预订。',["Hi. We have a reservation for four at seven.","I’m sorry, I can’t find it. What name is it under?","Taylor. I have the confirmation email here.","Thank you. It looks like it was entered for tomorrow.","We need a table tonight. Is anything available?","Yes, but there’ll be a fifteen-minute wait."]),
 D('flight-delay','travel',3,'polite','航班延误后确认转机替代方案。','旅客因延误可能错过转机。',["My flight is delayed, and I may miss my connection.","What is your final destination?","Wellington, via Sydney.","There’s a later flight from Sydney at eight.","Could you move me to that flight now?","Yes. I’ll rebook you and print a new boarding pass."])
];

export const jaDialogues=[
 D('restaurant-allergy','food',2,'polite','确认过敏原后安全点餐。','顾客在餐厅确认菜品是否含花生，并完成替换点单。',['ご注文はお決まりですか。','もう少しです。このカレーにピーナッツは入っていますか。','ソースには入っていますが、トマトスープには入っていません。','では、スープをお願いします。','かしこまりました。ピーナッツアレルギーがあることも伝えます。','ありがとうございます。助かります。']),
 D('restaurant-bill','food',2,'polite','核对账单错误并完成结账。','顾客发现账单上多了一项，服务员核对并更正。',['すみません、お会計をお願いします。','かしこまりました。すぐにお持ちします。','このデザートは注文していないと思います。','申し訳ありません。こちらの間違いです。','これを外して、別々に払えますか。','はい。訂正した伝票を二枚お持ちします。']),
 D('appointment-reschedule','time',2,'polite','完成预约改期与最终确认。','来电者把周二预约改到周四。',['予約の日を変更したいのですが。','かしこまりました。現在は何曜日のご予約ですか。','李の名前で、火曜日の十時です。','木曜日の十一時か、金曜日の九時が空いています。','木曜日の十一時でお願いします。','では、木曜日の十一時に変更いたします。']),
 D('appointment-cancel','time',2,'polite','取消预约并确认是否收费。','来电者因病取消预约。',['明日の予約をキャンセルしたいのですが。','ご予約のお名前をお願いします。','モーガン・チェンです。','ありがとうございます。今回はキャンセル料はかかりません。','確認のメールを送っていただけますか。','はい、すぐにお送りします。']),
 D('help-alternative','help',2,'neutral','拒绝部分请求并提供可行替代。','同学请求当晚帮忙搬家。',['今夜、引っ越しを手伝ってくれない？','今夜は無理だけど、明日の朝なら空いてるよ。','九時はどう？','九時は授業があるんだ。十時半ならどう？','十時半で大丈夫。別の時間を考えてくれてありがとう。','うん。住所を送って。']),
 D('return-exchange','shopping',2,'polite','凭收据完成尺码换货。','顾客退回尺码不合适且未穿过的鞋。',['この靴を交換したいのですが。','何か問題がございましたか。','いいえ、少し小さいだけです。外では履いていません。','レシートはお持ちですか。','はい。一つ上のサイズを試せますか。','もちろんです。お持ちします。']),
 D('return-defect','shopping',3,'polite','说明故障并协商退款方式。','顾客退回使用两天即故障的水壶。',['この電気ケトルが、二日で動かなくなりました。','申し訳ありません。レシートはお持ちですか。','はい。交換ではなく、返金をお願いします。','かしこまりました。カードに返金いたします。','返金までどのくらいかかりますか。','通常は三日から五営業日です。']),
 D('directions-repair','travel',2,'polite','在误解目的地后修正问路。','旅客问去中央车站的路，对方先听成公交总站。',['すみません、中央駅へはどう行けばいいですか。','バスターミナルなら、あちらへ二ブロックです。','すみません、バスではなく電車の駅です。','ああ、わかりました。次の角を左に曲がって、銀行を通り過ぎてください。','そこから遠いですか。','いいえ、歩いて五分くらいです。']),
 D('train-transfer','travel',2,'polite','确认换乘、站台与时间。','旅客询问前往机场的电车。',['すみません、空港へ行くならこの電車で合っていますか。','直接は行きません。中央駅で乗り換えてください。','中央駅では何番線ですか。','六番線です。案内表示があります。','乗り換える時間は十分ありますか。','はい、十二分ほどあります。']),
 D('group-work','school',2,'neutral','分工并确认交付时间。','学生为小组展示分配工作。',['発表の作業をどう分けようか。','私は導入と最初の二枚のスライドを担当するよ。','二枚目に入れる例も一つ探してくれる？','いいよ。最後の数字を確認してもらえる？','うん。金曜日までにお互いに送ろう。','わかった。月曜日に練習できるね。']),
 D('group-disagree','school',4,'neutral','表达不同意见并达成折中。','小组对报告重点意见不同。',['アンケートの結果を中心にしたほうがいいと思います。','言いたいことはわかりますが、インタビューが変化の理由を説明しています。','両方入れるということですか。','はい。ただ、背景の部分は短くできます。','それならよさそうです。背景は一段落だけ残しましょう。','では、私が構成を直します。']),
 D('repair-heating','home',3,'polite','报修暖气并确认临时方案。','租客报告暖气不工作。',['部屋の暖房が動かないのですが。','申し訳ありません。エラー番号は出ていますか。','はい、E3と出ています。部屋も寒くなってきました。','明日の午後なら修理の者が伺えます。','明日直らなかった場合、暖房器具を借りられますか。','はい。今日、受付にご用意します。']),
 D('repair-leak','home',3,'polite','报告漏水并说明紧急程度。','租客发现水槽下漏水。',['台所の流しの下から水が漏れています。','少しずつですか。それとも、ずっと流れていますか。','ずっと流れていたので、水を止めました。','ありがとうございます。一時間以内に修理の者を向かわせます。','家で待っている必要がありますか。','はい。到着前に担当者から電話します。']),
 D('medical-symptoms','health',3,'polite','描述症状、持续时间与严重程度。','患者因喉咙痛和发烧看诊。',['今日はどうされましたか。','月曜日から喉が痛くて、昨夜は熱もありました。','息苦しさはありますか。','いいえ。でも、飲み込むと痛いです。','わかりました。まず喉を診ますね。','わかりました。ありがとうございます。']),
 D('pharmacy-medicine','health',2,'polite','确认药物用法和注意事项。','顾客向药师询问止痛药。',['この薬の飲み方を教えていただけますか。','食後に一錠、一日三回まで飲んでください。','アレルギーの薬と一緒に飲んでも大丈夫ですか。','確認します。その薬の名前は何ですか。','この箱に書いてあります。','ありがとうございます。この二つは一緒に飲んでも大丈夫です。']),
 D('invitation-decline','social',2,'neutral','礼貌拒绝邀请并提出另约。','朋友邀请周五吃饭。',['金曜日、一緒に夕飯を食べない？','行きたいけど、その夜はもう予定があるんだ。','そっか。週末は空いてる？','日曜日の午後なら大丈夫だよ。','三時にコーヒーはどう？','いいね。じゃあ、そのときに。']),
 D('invitation-condition','social',2,'neutral','带条件接受邀请并确认细节。','朋友邀请参加野餐。',['土曜日にピクニックをするんだけど、来ない？','行けるかも。何時から？','十二時ごろ、リバーサイド公園で。','十一時までに仕事が終わったら行けるよ。','大丈夫。わかったらメッセージして。','そうするね。誘ってくれてありがとう。']),
 D('misunderstanding-time','time',2,'neutral','修正时间误会并重新确认。','两人对会议时间理解不同。',['会議は二時からだと思っていました。','昨日、三時に変更になりました。','そのメッセージを見落としたようです。','大丈夫です。三時でも来られますか。','はい。確認ですが、三時に四号室ですね。','そのとおりです。では、後で。']),
 D('misunderstanding-tone','social',4,'neutral','解释语气并修复关系。','同事觉得一句反馈太尖锐。',['会議でのコメントが、かなり厳しく聞こえました。','すみません。仕事ではなく、日程について確認したかったんです。','説明してくれてありがとう。責められたのかと思いました。','そう聞こえた理由はわかります。','明日、もう一度日程について話せますか。','もちろんです。今度はもっとはっきり説明します。']),
 D('hotel-room','travel',2,'polite','报告房间问题并完成换房。','住客因街道噪声请求换房。',['すみません、夜になると部屋がとても騒がしいです。','申し訳ありません。外の道路の音ですか。','はい。もう少し静かな部屋はありますか。','六階にございますが、シングルベッドが二台の部屋です。','それで大丈夫です。今夜移れますか。','はい。新しい鍵をご用意します。']),
 D('hotel-booking','travel',2,'polite','查找预订并确认早餐。','住客办理入住时预订记录不易找到。',['パテルの名前で予約しています。','まだ見つかりません。別のお名前でしょうか。','プリヤ・パテルで探してください。先月、オンラインで予約しました。','ございました。三泊のご予定ですね。','はい。朝食は含まれていますか。','はい。朝食は七時からです。']),
 D('taxi-destination','travel',2,'polite','确认目的地、路线和支付方式。','乘客乘出租车去酒店。',['リバーサイドホテルまでお願いします。','かしこまりました。キング通りのホテルですね。','はい、そこです。どのくらいかかりますか。','道が空いていれば、二十分くらいです。','カードで払えますか。','はい、使えます。']),
 D('bus-wrong-stop','travel',2,'neutral','发现坐错方向后获得补救路线。','乘客担心错过下车站。',['このバスは市立病院の近くに止まりますか。','いいえ、このバスは反対方向に向かっています。','そうですか。どこで降りればいいですか。','次で降りて、反対側から二十四番に乗ってください。','二十四番は病院の前に止まりますか。','はい、正面入口のすぐ前です。']),
 D('order-unavailable','food',2,'polite','菜品售罄后选择替代。','餐厅告知顾客所点菜品卖完。',['焼き魚をお願いします。','申し訳ありません。焼き魚は売り切れております。','代わりに、何がおすすめですか。','鶏肉料理が似ています。野菜のパスタもございます。','では、パスタにします。チーズ抜きにできますか。','もちろんです。']),
 D('dietary-clarify','food',3,'polite','澄清素食需求并确认配料。','顾客确认汤是否真正适合素食者。',['野菜スープはベジタリアン向けですか。','はい、肉は入っていません。','だしも野菜だけですか。','厨房に確認してまいります。','ありがとうございます。鶏のだしも避けたいんです。','承知しました。ご注文の前に必ず確認します。']),
 D('school-deadline','school',3,'polite','请求延期并协商新截止时间。','学生因病请求作业延期。',['課題の締め切りについて相談してもいいですか。','もちろんです。どうしましたか。','体調を崩して、木曜日までに終わりそうにありません。','月曜日までなら延ばせますが、それより後は難しいです。','月曜日なら助かります。診断書は必要ですか。','今回は必要ありません。正午までにメールで送ってください。']),
 D('work-clarification','school',3,'neutral','澄清任务范围并确认优先级。','同事收到含糊的资料整理请求。',['今日中に顧客ファイルを更新してもらえますか。','どの部分を更新すればいいですか。','連絡先と昨日の電話のメモです。','支払いの部分はそのままでいいですか。','はい。まず連絡先を優先してください。','わかりました。四時までに送ります。']),
 D('neighbour-noise','home',3,'polite','提出噪声问题并协商解决。','邻居深夜音乐过大。',['すみません。音楽が壁越しにかなり聞こえるのですが。','そんなに大きいとは気づきませんでした。','十時を過ぎたら、音を小さくしてもらえますか。','もちろんです。もうすぐ終わるところです。','ありがとうございます。本当に助かります。','こちらこそ、すみませんでした。']),
 D('wrong-delivery','shopping',3,'polite','说明送错商品并安排补发。','网购顾客收到错误颜色。',['注文と違う商品が届きました。','申し訳ありません。何をご注文になりましたか。','黒いジャケットを注文しましたが、青いものが届きました。','本日、正しい商品を発送できます。','先にこちらを返す必要がありますか。','いいえ。返送用の伝票を同封します。']),
 D('opinion-disagree','chat',3,'neutral','礼貌表达不同意见并追问理由。','朋友对市中心禁车提议看法不同。',['市の中心部への車の乗り入れは禁止したほうがいいと思う。','私は少し違う意見かな。通勤に車が必要な人もいるよ。','確かに。でも、公共交通をもっと便利にできると思う。','バスの本数が増えたら、禁止に賛成する？','混む時間だけなら賛成するかも。','それなら、いい妥協案になりそうだね。']),
 D('lost-reservation','time',3,'polite','预订未显示时提供证据并取得替代安排。','餐厅找不到顾客预订。',['七時に四名で予約しています。','申し訳ありません。お名前を教えていただけますか。','テイラーです。確認メールもあります。','ありがとうございます。明日の予約として入っています。','今夜、席が必要なのですが、空いていませんか。','十五分ほどお待ちいただければ、ご用意できます。']),
 D('flight-delay','travel',3,'polite','航班延误后确认转机替代方案。','旅客因延误可能错过转机。',['飛行機が遅れて、乗り継ぎに間に合わないかもしれません。','最終目的地はどちらですか。','シドニー経由でウェリントンです。','シドニーを八時に出る便ならあります。','今、その便に変更できますか。','はい。予約を変更して、新しい搭乗券をお渡しします。']),
 D('counter-service','shopping',2,'polite','在柜台确认包装与收据。','顾客购买礼物并请求包装。',['こちらを贈り物にしたいのですが。','無料の包装と有料の箱がございます。','無料の包装でお願いします。','かしこまりました。値札は外しますか。','はい。領収書もいただけますか。','もちろんです。商品とは別にお渡しします。']),
 D('clinic-reception','health',2,'polite','在诊所前台确认就诊与候诊。','患者没有预约但症状加重。',['予約はないのですが、診てもらえますか。','症状を簡単に教えてください。','昨日から熱があり、今朝ひどくなりました。','少しお待ちいただければ、医師に確認します。','待ち時間はどのくらいですか。','今のところ、三十分ほどです。']),
 D('delivery-time','home',2,'polite','协调送货时间并确认在场。','配送人员提出工作日下午送货。',['家具のお届け時間についてご連絡しました。','ありがとうございます。何時ごろになりますか。','木曜日の二時から四時の間です。','その時間は不在です。金曜日の午前中はどうですか。','金曜日なら九時から十一時が空いています。','では、その時間でお願いします。']),
 D('lost-property','travel',3,'polite','描述失物并留下联系方式。','旅客在车站寻找遗失的包。',['電車にかばんを忘れたかもしれません。','どの電車に乗りましたか。','十時十五分発の空港行きです。','かばんの色と形を教えてください。','黒い小さなリュックです。中に名前が書いてあります。','見つかったら、こちらの番号にご連絡します。'])
];
