// One-time migration from the frozen, non-public Phase 1 fixture. Never loaded at runtime.
import fs from 'node:fs';
import vm from 'node:vm';
const source=fs.readFileSync(new URL('../tests/fixtures/phase1-data.cjs',import.meta.url),'utf8');
const data=vm.runInNewContext(source+';({topics,concepts,placementQuestions})');
const quote=v=>v==null?'NULL':typeof v==='number'?String(v):"'"+String(v).replaceAll("'","''")+"'";
let sql='-- Approved Phase 1 content, preserved verbatim. Generated by scripts/generate-seed.js.\n';
function insert(table,record){sql+=`INSERT INTO ${table} (${Object.keys(record).join(', ')}) VALUES (${Object.values(record).map(quote).join(', ')});\n`;}
function tokens(text){let result=[],end=0;for(const m of text.matchAll(/\{([^:}]+):([^}]+)\}/g)){if(m.index>end)result.push({text:text.slice(end,m.index)});result.push({text:m[1],reading:m[2]});end=m.index+m[0].length;}if(end<text.length)result.push({text:text.slice(end)});return result;}
data.topics.forEach((t,i)=>insert('topics',{...t,slug:t.id,sort_order:i+1}));
for(const c of data.concepts){
 insert('concepts',{id:c.id,slug:'concept-'+c.id,topic_id:c.topic,zh:c.zh,sort_order:c.id});
 insert('comparisons',{concept_id:c.id,explanation:c.comparison});
 for(const [i,lang] of ['en','ja'].entries()){
  const id=c.id*2-1+i,g=c[lang+'Grammar'];
  insert('grammar_points',{id,language:lang,title:g.title,explanation:g.text,example:g.example});
  insert('expressions',{id,concept_id:c.id,language:lang,text:c[lang],ipa:lang==='en'?c.ipa:null,hiragana:lang==='ja'?c.hiragana:null,difficulty:c[lang+'Difficulty'],grammar_point_id:id});
  c[lang+'Chunks'].forEach((chunk,j)=>{const readings=lang==='ja'?tokens(chunk):[];insert('expression_chunks',{id:id*100+j,expression_id:id,language:lang,grammar_point_id:id,text:lang==='en'?chunk:readings.map(t=>t.text).join(''),readings_json:JSON.stringify(readings),sort_order:j});});
  if(lang==='ja')tokens(c.jaChunks.join('')+c.ja.slice(-1)).forEach((r,j)=>insert('expression_readings',{expression_id:id,sort_order:j,text:r.text,reading:r.reading}));
 }
}
for(const lang of ['en','ja'])data.placementQuestions[lang].forEach((q,i)=>{
 const id=lang+'-'+(i+1);insert('placement_questions',{id,language:lang,type:q[0],prompt:q[1],difficulty:Math.floor(i/2)+1,sort_order:i+1});
 q[2].forEach((text,option_id)=>insert('placement_options',{question_id:id,option_id,text}));
 insert('placement_answer_keys',{question_id:id,correct_option:q[3]});
});
fs.writeFileSync(new URL('../migrations/0002_seed.sql',import.meta.url),sql);
