function percent(lang,list=concepts){return list.length?Math.round(list.reduce((n,c)=>n+(state.mastery[lang][c.id]==='learned'?1:state.mastery[lang][c.id]==='learning'?.35:0),0)/list.length*100):0;}
function level(lang){return state.levels[lang]?`Level ${state.levels[lang].level}`:'尚未定位';}
function ruby(tokens){return tokens.map(t=>t.reading?`<ruby>${escapeHtml(t.text)}<rt>${escapeHtml(t.reading)}</rt></ruby>`:escapeHtml(t.text)).join('');}
const page=document.body.dataset.page;
document.querySelector('#shell').innerHTML=`<header class="site-header"><a class="brand" href="index.html"><span class="brand-symbol">言</span>言间 <small>两种语言，一起学</small></a><nav aria-label="主导航">${[['home','index.html','首页'],['placement','placement.html','能力定位'],['learn','learn.html','学习'],['progress','progress.html','学习进度']].map(([p,url,t])=>`<a href="${url}" ${p===page?'aria-current="page"':''}>${t}</a>`).join('')}</nav></header><div id="storage-warning" class="notice" role="alert" hidden>浏览器无法保存进度。请允许此网站使用本地存储；当前页面仍可学习。</div>`;
document.querySelector('#footer').innerHTML='言间 · 从生活出发，让表达自然发生。<span>本地体验版 · 进度保存在此浏览器</span>';
function languageCard(lang){const name=lang==='en'?'English':'日本語';return `<div class="level-card ${lang}"><span class="eyebrow">${name}</span><strong>${level(lang)}</strong><span>${state.levels[lang]?'按自己的节奏，继续向前':'先了解你的起点'}</span></div>`;}
const topicName=id=>topics.find(t=>t.id===id)?.name||id;
function topicCards(){return topics.map(t=>{const list=concepts.filter(c=>c.topic===t.id);return `<article class="topic-card"><span class="topic-icon">${escapeHtml(t.icon)}</span><h3>${escapeHtml(t.name)}</h3><p>${escapeHtml(t.description)}</p><p>${list.length} 个学习项</p>${['en','ja'].map(l=>`<div class="topic-progress ${l}"><div>${l==='en'?'English':'日本語'}<strong>${percent(l,list)}%</strong></div><div class="meter"><span style="width:${percent(l,list)}%"></span></div><small>${list.filter(c=>state.mastery[l][c.id]==='learned').length} 已掌握 · ${list.filter(c=>state.mastery[l][c.id]==='learning').length} 学习中 · ${list.filter(c=>state.mastery[l][c.id]==='review').length} 待复习</small><div class="topic-actions"><a href="learn.html?topic=${t.id}&lang=${l}">自由学习 →</a><a href="checkpoint.html?topic=${t.id}&lang=${l}">主题小测${state.checkpoints[l][t.id]?` · 上次 ${state.checkpoints[l][t.id].percentage}%`:''} ↗</a></div></div>`).join('')}</article>`;}).join('');}
async function home(){
 document.querySelector('main').innerHTML=`<section class="intro"><div class="eyebrow">每一天，都多会说一点</div><h1>从熟悉的生活，<br>走进两种语言。</h1><p>以中文理解意思，用英语与日语，把同一份想法说自然。</p></section>${!state.levels.en||!state.levels.ja?'<a class="notice placement-prompt" href="placement.html"><div><strong>找到你的起点</strong><p>英语和日语分别定位，题目会随表现调整。</p></div><span>开始能力定位 →</span></a>':''}<section><div class="section-heading"><h2>今日推荐</h2><span>各有起点，各有节奏</span></div><div id="recommendations" class="progress-grid" role="status">正在匹配学习项…</div></section><section><div class="section-heading"><h2>把生活变成课堂</h2><span>${topics.length} 个主题 · ${concepts.length} 个学习项</span></div><p>推荐是起点，不是限制。所有难度都可以自由学习。</p><div class="topic-grid">${topicCards()}</div></section>`;
 async function fill(){try{
  const recs=await Promise.all(['en','ja'].map(l=>post('/recommendations',learnerProfile(l))));
  document.querySelector('#recommendations').innerHTML=recs.map(r=>`<article class="panel ${r.lang}"><span class="eyebrow">${r.lang==='en'?'English':'日本語'}</span><h2>${level(r.lang)}</h2><p>${escapeHtml(state.levels[r.lang]?.summary||'还没有定位，先从基础表达开始，也可以自由选择难度。')}</p><p>${r.items.length} 个学习项 · 推荐难度 ${r.level}</p><ol class="queue-preview">${r.items.map(c=>`<li><a href="learn.html?id=${c.id}&lang=${r.lang}">${escapeHtml(c.zh)}</a><small>${escapeHtml(c.reason)} · ${typeNames[c.conceptType]} · ${topicName(c.topic)}</small></li>`).join('')}</ol><button class="primary begin-queue" data-lang="${r.lang}">开始${r.lang==='en'?'英语':'日语'}学习 →</button>${state.lastByLang[r.lang]?`<a class="text-link" href="learn.html?id=${state.lastByLang[r.lang]}&lang=${r.lang}">回到上次学习 →</a>`:''}</article>`).join('');
  document.querySelectorAll('.begin-queue').forEach(b=>b.onclick=()=>{const r=recs.find(r=>r.lang===b.dataset.lang);state.queues[r.lang]=r.items.map(c=>c.id);save();location.href=`learn.html?id=${r.items[0].id}&lang=${r.lang}&queue=1`;});
 }catch(e){const container=document.querySelector('#recommendations');container.innerHTML=`<div class="notice" role="alert"><p>${escapeHtml(e.message)}</p><button id="retry-recommendations" class="secondary">重试推荐</button><p>也可以从下方主题自由学习。</p></div>`;document.querySelector('#retry-recommendations').onclick=fill;}}
 await fill();
}
function progress(){document.querySelector('main').innerHTML=`<section class="page-intro"><span class="eyebrow">每一步，都算数</span><h1>看见自己的进步</h1><p>英语与日语分别记录。掌握计为完整进度，学习中计为部分进度；待复习项不计为已掌握。小测不会一次判定整个主题已掌握。</p></section><div class="progress-grid">${['en','ja'].map(l=>`<section class="panel ${l}"><span class="eyebrow">${l==='en'?'English':'日本語'}</span><div class="section-heading"><h2>${level(l)}</h2><a href="placement.html?lang=${l}">重新定位 ↗</a></div><strong class="big-number">${percent(l)}<small>%</small></strong><div class="meter"><span style="width:${percent(l)}%"></span></div><p>${concepts.filter(c=>state.mastery[l][c.id]==='learned').length} / ${concepts.length} 已掌握 · ${concepts.filter(c=>state.mastery[l][c.id]==='review').length} 待复习</p></section>`).join('')}</div><section><h2>每个主题的足迹</h2><div class="topic-grid">${topicCards()}</div></section><section class="panel review-section"><h2>再熟悉一点</h2><div class="review-list">${concepts.filter(c=>['en','ja'].some(l=>state.mastery[l][c.id]==='review')).map(c=>`<div><strong>${escapeHtml(c.zh)}</strong>${['en','ja'].filter(l=>state.mastery[l][c.id]==='review').map(l=>`<a href="learn.html?id=${c.id}&lang=${l}">${l==='en'?'英语':'日语'}待复习 →</a>`).join('')}</div>`).join('')||'<p>目前没有待复习的学习项。</p>'}</div></section>`;}
loading();
const appReady=loadContent().then(async()=>{restoreState();if(page==='home')await home();if(page==='progress')progress();return true;}).catch(error=>{contentError(error);return false;});
