import {rows} from './assessments.js';
import auditedBundle from './lesson-bundle-35d.js';
import {isCurrentGrammarId,isPracticeEligibleGrammarId} from './content-quality-02.js';
const json=(data,status=200)=>Response.json(data,{status,headers:{'Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}}),fail=(message,status=400)=>json({error:{message}},status),validId=id=>/^(?:en|ja)-s[1-6]-l[1-9]$/.test(id),marks=n=>Array(n).fill('?').join(',');
const cols={u:['id','language','stage','topic_id','title','objective','sequence','status','estimated_minutes'],p:['lesson_id','prerequisite_lesson_id'],i:['lesson_id','content_type','content_id','role','sequence','required','instructional_role'],e:['framework_id','target','lesson_id','relevance']};
const records=(data,keys)=>data.map(values=>Object.fromEntries(keys.map((key,i)=>[key,values[i]])));
async function bundle(db){try{const exists=await db.prepare("SELECT 1 found FROM sqlite_master WHERE type='table' AND name='lesson_bundles' LIMIT 1").first();if(exists){const row=await db.prepare("SELECT payload_json FROM lesson_bundles WHERE id IN ('curriculum-expansion-01a-v1','phase-35e1c-v2','phase-35e1c-v1','phase-35d-v1') ORDER BY CASE id WHEN 'curriculum-expansion-01a-v1' THEN 0 WHEN 'phase-35e1c-v2' THEN 1 WHEN 'phase-35e1c-v1' THEN 2 ELSE 3 END LIMIT 1").first();if(row?.payload_json)return JSON.parse(row.payload_json);}}catch{}return auditedBundle;}
const decoded=b=>({units:records(b.u,cols.u),prerequisites:records(b.p,cols.p),items:records(b.i,cols.i).filter(x=>x.content_type!=='grammar'||isCurrentGrammarId(x.content_id)),exams:records(b.e,cols.e)});
export async function lessonPracticeCurriculum(db,id){
 const data=decoded(await bundle(db)),lesson=data.units.find(x=>x.id===id&&x.status==='published');
 if(!lesson)return null;
 return {lesson,items:data.items.filter(x=>x.lesson_id===id&&(x.content_type==='vocabulary'||x.content_type==='grammar'&&isPracticeEligibleGrammarId(x.content_id))).sort((a,b)=>a.content_type.localeCompare(b.content_type)||a.sequence-b.sequence||a.content_id.localeCompare(b.content_id))};
}
export async function publishedLessonCurriculum(db){
 const data=decoded(await bundle(db));
 const lessons=data.units.filter(x=>x.status==='published').sort((a,c)=>a.language.localeCompare(c.language)||a.stage-c.stage||a.sequence-c.sequence||a.id.localeCompare(c.id));
 const publishedIds=new Set(lessons.map(x=>x.id));
 return {lessons,prerequisites:data.prerequisites.filter(x=>publishedIds.has(x.lesson_id)&&publishedIds.has(x.prerequisite_lesson_id))};
}
async function addTopics(data,contentDb){if(!data.length)return data;const ids=[...new Set(data.map(x=>x.topic_id))],found=await rows(contentDb,`SELECT id,name_zh FROM v2_topics WHERE id IN (${marks(ids.length)})`,...ids),map=new Map(found.map(x=>[x.id,x.name_zh]));return data.map(x=>({...x,topic:map.get(x.topic_id)||x.topic_id}));}
async function canonical(db,table,columns,ids,extra='',idColumn='id'){if(!ids.length)return [];return rows(db,`SELECT ${columns} FROM ${table} WHERE ${idColumn} IN (${marks(ids.length)}) ${extra}`,...ids);}
const merge=(links,content)=>{const map=new Map(content.map(x=>[x.id,x]));return links.map(link=>({...map.get(link.content_id),role:link.role,required:link.required,sequence:link.sequence,instructional_role:link.instructional_role||null})).filter(x=>x.id);};
const counts=(x,items)=>({...x,vocabulary_count:items.filter(i=>i.lesson_id===x.id&&i.content_type==='vocabulary').length,grammar_count:items.filter(i=>i.lesson_id===x.id&&i.content_type==='grammar').length,expression_count:items.filter(i=>i.lesson_id===x.id&&i.content_type==='expression').length});

export async function lessons(request,lessonDb,contentDb){try{if(request.method!=='GET')return fail('请使用 GET。',405);const u=new URL(request.url),suffix=u.pathname.slice('/api/v2/lessons'.length);if(suffix==='/status')return status(lessonDb);if(suffix==='/recommended')return recommended(u,lessonDb,contentDb);if(suffix===''||suffix==='/')return list(u,lessonDb,contentDb);const id=decodeURIComponent(suffix.slice(1));if(suffix.includes('/',1)||!validId(id)||u.search)return fail('课程编号无效。');return detail(id,lessonDb,contentDb);}catch(e){console.error('Lesson API unavailable',e);return fail('课程路径暂时无法加载，请重试。',503);}}
async function status(db){const exists=await db.prepare("SELECT 1 found FROM sqlite_master WHERE type='table' AND name='lesson_bundles' LIMIT 1").first();if(!exists)return json({source:'audited-fallback',persisted:false});const row=await db.prepare("SELECT id,schema_version,published_at,length(payload_json) bytes,json_array_length(json_extract(payload_json,'$.u')) lessons,json_array_length(json_extract(payload_json,'$.i')) links FROM lesson_bundles WHERE id IN ('curriculum-expansion-01a-v1','phase-35e1c-v2','phase-35e1c-v1','phase-35d-v1') ORDER BY CASE id WHEN 'curriculum-expansion-01a-v1' THEN 0 WHEN 'phase-35e1c-v2' THEN 1 WHEN 'phase-35e1c-v1' THEN 2 ELSE 3 END LIMIT 1").first();return json({source:row?'d1':'audited-fallback',persisted:Boolean(row),bundle:row||null});}
async function list(u,lessonDb,contentDb){const allowed=['language','stage'];for(const [k,v] of u.searchParams)if(!allowed.includes(k)||u.searchParams.getAll(k).length!==1||!v)return fail('筛选条件无效。');const language=u.searchParams.get('language')||'en',stage=Number(u.searchParams.get('stage')||1);if(!['en','ja'].includes(language)||!Number.isInteger(stage)||stage<1||stage>6)return fail('请选择有效的语言和阶段。');const b=decoded(await bundle(lessonDb)),data=b.units.filter(x=>x.status==='published'&&x.language===language&&x.stage===stage).sort((a,c)=>a.sequence-c.sequence).slice(0,9).map(x=>counts(x,b.items));return json({data:await addTopics(data,contentDb),query:{language,stage},bounded:true});}
async function detail(id,lessonDb,contentDb){
 const b=decoded(await bundle(lessonDb)),base=b.units.find(x=>x.id===id&&x.status==='published');if(!base)return fail('没有找到这节课。',404);const lesson=(await addTopics([counts(base,b.items)],contentDb))[0],links=type=>b.items.filter(x=>x.lesson_id===id&&x.content_type===type).sort((a,c)=>a.sequence-c.sequence),vLinks=links('vocabulary').slice(0,10),gLinks=links('grammar').slice(0,3),eLinks=links('expression').slice(0,8);
 const [vocabularyRaw,grammarRaw,expressionsRaw]=await Promise.all([
  canonical(contentDb,'v2_vocabulary_items v',`v.id,v.language,v.lemma,v.stage,v.ipa,v.reading,v.part_of_speech,v.register,(SELECT meaning_zh FROM v2_vocabulary_senses s WHERE s.item_id=v.id ORDER BY s.sort_order,s.id LIMIT 1) meaning_zh`,vLinks.map(x=>x.content_id),"AND v.publication_state='published'"),
  canonical(contentDb,'v2_grammar_points g','g.id,g.language,g.title_zh,g.form_name,g.level,g.purpose_zh,g.register',gLinks.map(x=>x.content_id),"AND g.publication_state='published'"),
  canonical(contentDb,'v2_sentence_expressions e JOIN v2_sentence_units u ON u.id=e.unit_id',`e.id,e.language,e.text,e.readings_json,e.overall_difficulty,e.vocabulary_difficulty,e.grammar_difficulty,u.id unit_id,u.anchor_zh,u.context_zh,u.unit_type,(SELECT json_group_array(json_object('speaker',d.speaker,'text',d.text,'readings',json(d.readings_json),'sequence',d.sort_order)) FROM v2_dialogue_turns d WHERE d.expression_id=e.id ORDER BY d.sort_order) dialogue_json`,eLinks.map(x=>x.content_id),"AND e.publication_state='published' AND u.publication_state='published'",'e.id')
 ]);
 const expressions=merge(eLinks,expressionsRaw).map(({readings_json,dialogue_json,...e})=>({...e,readings:JSON.parse(readings_json),dialogue:dialogue_json?JSON.parse(dialogue_json):[]})),ordered=b.units.filter(x=>x.language===lesson.language&&x.status==='published').sort((a,c)=>a.stage-c.stage||a.sequence-c.sequence),index=ordered.findIndex(x=>x.id===id),prerequisites=b.prerequisites.filter(x=>x.lesson_id===id).map(x=>ordered.find(l=>l.id===x.prerequisite_lesson_id)).filter(Boolean);
 return json({data:{...lesson,scenario_count:expressions.filter(x=>x.unit_type!=='sentence').length,vocabulary:merge(vLinks,vocabularyRaw),grammar:merge(gLinks,grammarRaw),expressions,prerequisites,previous:ordered[index-1]||null,next:ordered[index+1]||null},bounded:true});
}
async function recommended(u,lessonDb,contentDb){const allowed=['framework','target'];for(const [k,v] of u.searchParams)if(!allowed.includes(k)||u.searchParams.getAll(k).length!==1||!v)return fail('考试目标无效。');const framework=u.searchParams.get('framework'),target=u.searchParams.get('target'),targets={IELTS:['5.0','5.5','6.0','6.5','7.0+'],JLPT:['N5','N4','N3','N2','N1']};if(!targets[framework]?.includes(target))return fail('考试目标无效。');const b=decoded(await bundle(lessonDb)),data=b.exams.filter(x=>x.framework_id===framework&&x.target===target).map(r=>({...counts(b.units.find(l=>l.id===r.lesson_id),b.items),relevance:r.relevance})).filter(x=>x.id).sort((a,c)=>c.relevance-a.relevance||a.stage-c.stage||a.sequence-c.sequence).slice(0,6);return json({data:await addTopics(data,contentDb),framework,target,note:'站内课程推荐'});}
