-- Phase 3.5E.1A: additive curated examples for existing core grammar only.
-- Generated from scripts/grammar-examples-35e1a.js; Dynamic AI output is not a source.
PRAGMA foreign_keys=ON;
INSERT INTO v2_grammar_examples(id,grammar_id,language,text,translation_zh,explanation_zh,ipa,readings_json,source_expression_id,sort_order) VALUES
('35e1a-ge-en-simple-present-01','en-simple-present','en','She walks to work every day.','她每天步行上班。','描述日常或事实；新增正式例句覆盖：canonical/basic usage。',NULL,'[]',NULL,'1'),
('35e1a-ge-en-simple-present-02','en-simple-present','en','We usually eat dinner at seven.','我们通常七点吃晚饭。','描述日常或事实；新增正式例句覆盖：natural daily-life context。',NULL,'[]',NULL,'2'),
('35e1a-ge-en-simple-present-03','en-simple-present','en','My brother does not drink coffee.','我哥哥不喝咖啡。','描述日常或事实；新增正式例句覆盖：negative / restriction。',NULL,'[]',NULL,'3'),
('35e1a-ge-en-simple-present-04','en-simple-present','en','The shop closes at six.','这家店六点关门。','描述日常或事实；新增正式例句覆盖：natural daily-life context。',NULL,'[]',NULL,'4'),
('35e1a-ge-en-simple-present-05','en-simple-present','en','Do they live near the station?','他们住在车站附近吗？','描述日常或事实；新增正式例句覆盖：question / interaction。',NULL,'[]',NULL,'5'),
('35e1a-ge-en-simple-present-06','en-simple-present','en','Water boils at one hundred degrees Celsius.','水在一百摄氏度时沸腾。','描述日常或事实；新增正式例句覆盖：natural daily-life context。',NULL,'[]',NULL,'6'),
('35e1a-ge-en-be-adjective-01','en-be-adjective','en','The soup is hot.','这汤很烫。','描述状态；新增正式例句覆盖：canonical/basic usage。',NULL,'[]',NULL,'1'),
('35e1a-ge-en-be-adjective-02','en-be-adjective','en','I am not busy this afternoon.','我今天下午不忙。','描述状态；新增正式例句覆盖：negative / restriction。',NULL,'[]',NULL,'2'),
('35e1a-ge-en-be-adjective-03','en-be-adjective','en','Are you ready to leave?','你准备好出发了吗？','描述状态；新增正式例句覆盖：question / interaction。',NULL,'[]',NULL,'3'),
('35e1a-ge-en-be-adjective-04','en-be-adjective','en','Her parents are teachers.','她的父母是老师。','描述状态；新增正式例句覆盖：natural daily-life context。',NULL,'[]',NULL,'4'),
('35e1a-ge-en-be-adjective-05','en-be-adjective','en','The keys are on the table.','钥匙在桌上。','描述状态；新增正式例句覆盖：natural daily-life context。',NULL,'[]',NULL,'5'),
('35e1a-ge-en-be-adjective-06','en-be-adjective','en','This room was quiet last night.','这个房间昨晚很安静。','描述状态；新增正式例句覆盖：natural daily-life context。',NULL,'[]',NULL,'6'),
('35e1a-ge-en-present-continuous-01','en-present-continuous','en','She is waiting outside.','她正在外面等。','正在进行的动作；新增正式例句覆盖：canonical/basic usage。',NULL,'[]',NULL,'1'),
('35e1a-ge-en-present-continuous-02','en-present-continuous','en','We are not using the meeting room.','我们现在没有使用会议室。','正在进行的动作；新增正式例句覆盖：negative / restriction。',NULL,'[]',NULL,'2'),
('35e1a-ge-en-present-continuous-03','en-present-continuous','en','Are you looking for the bus stop?','你在找公交车站吗？','正在进行的动作；新增正式例句覆盖：question / interaction。',NULL,'[]',NULL,'3'),
('35e1a-ge-en-present-continuous-04','en-present-continuous','en','The children are sleeping now.','孩子们现在正在睡觉。','正在进行的动作；新增正式例句覆盖：natural daily-life context。',NULL,'[]',NULL,'4'),
('35e1a-ge-en-present-continuous-05','en-present-continuous','en','I am staying with a friend this week.','我这周暂住在朋友家。','正在进行的动作；新增正式例句覆盖：natural daily-life context。',NULL,'[]',NULL,'5'),
('35e1a-ge-en-present-continuous-06','en-present-continuous','en','Why is the printer making that noise?','打印机为什么在发出那种声音？','正在进行的动作；新增正式例句覆盖：question / interaction。',NULL,'[]',NULL,'6'),
('35e1a-ge-en-do-question-01','en-do-question','en','Do you need a receipt?','你需要收据吗？','一般现在时问句；新增正式例句覆盖：question / interaction。',NULL,'[]',NULL,'1'),
('35e1a-ge-en-do-question-02','en-do-question','en','Does this bus stop at the airport?','这辆公交车在机场停吗？','一般现在时问句；新增正式例句覆盖：question / interaction。',NULL,'[]',NULL,'2'),
('35e1a-ge-en-do-question-03','en-do-question','en','Do your classes start at nine?','你的课九点开始吗？','一般现在时问句；新增正式例句覆盖：question / interaction。',NULL,'[]',NULL,'3'),
('35e1a-ge-en-do-question-04','en-do-question','en','Does Anna work on Saturdays?','安娜星期六上班吗？','一般现在时问句；新增正式例句覆盖：question / interaction。',NULL,'[]',NULL,'4'),
('35e1a-ge-en-do-question-05','en-do-question','en','Do we have enough time?','我们有足够的时间吗？','一般现在时问句；新增正式例句覆盖：question / interaction。',NULL,'[]',NULL,'5'),
('35e1a-ge-en-do-question-06','en-do-question','en','Does the price include breakfast?','这个价格包含早餐吗？','一般现在时问句；新增正式例句覆盖：question / interaction。',NULL,'[]',NULL,'6'),
('35e1a-ge-en-there-is-01','en-there-is','en','There is a pharmacy across the street.','街对面有一家药房。','说明存在；新增正式例句覆盖：canonical/basic usage。',NULL,'[]',NULL,'1'),
('35e1a-ge-en-there-is-02','en-there-is','en','There are two clean cups in the cupboard.','橱柜里有两个干净的杯子。','说明存在；新增正式例句覆盖：natural daily-life context。',NULL,'[]',NULL,'2'),
('35e1a-ge-en-there-is-03','en-there-is','en','There is not enough milk for breakfast.','早餐的牛奶不够。','说明存在；新增正式例句覆盖：negative / restriction。',NULL,'[]',NULL,'3'),
('35e1a-ge-en-there-is-04','en-there-is','en','Is there a lift in this building?','这栋楼里有电梯吗？','说明存在；新增正式例句覆盖：question / interaction。',NULL,'[]',NULL,'4'),
('35e1a-ge-en-there-is-05','en-there-is','en','Are there any seats near the window?','窗边还有座位吗？','说明存在；新增正式例句覆盖：question / interaction。',NULL,'[]',NULL,'5'),
('35e1a-ge-en-there-is-06','en-there-is','en','There was a delay on the train line this morning.','今天早上这条火车线路有延误。','说明存在；新增正式例句覆盖：natural daily-life context。',NULL,'[]',NULL,'6'),
('35e1a-ge-en-have-possession-01','en-have-possession','en','We have a spare key.','我们有一把备用钥匙。','拥有与身体感受；新增正式例句覆盖：canonical/basic usage。',NULL,'[]',NULL,'1'),
('35e1a-ge-en-have-possession-02','en-have-possession','en','He has a new phone.','他有一部新手机。','拥有与身体感受；新增正式例句覆盖：natural daily-life context。',NULL,'[]',NULL,'2'),
('35e1a-ge-en-have-possession-03','en-have-possession','en','I do not have any cash with me.','我身上没有现金。','拥有与身体感受；新增正式例句覆盖：negative / restriction。',NULL,'[]',NULL,'3'),
('35e1a-ge-en-have-possession-04','en-have-possession','en','Do you have a reservation?','你有预订吗？','拥有与身体感受；新增正式例句覆盖：question / interaction。',NULL,'[]',NULL,'4'),
('35e1a-ge-en-have-possession-05','en-have-possession','en','She has a sore throat today.','她今天喉咙痛。','拥有与身体感受；新增正式例句覆盖：natural daily-life context。',NULL,'[]',NULL,'5'),
('35e1a-ge-en-have-possession-06','en-have-possession','en','The apartment has a small balcony.','这套公寓有一个小阳台。','拥有与身体感受；新增正式例句覆盖：natural daily-life context。',NULL,'[]',NULL,'6'),
('35e1a-ge-en-wh-question-01','en-wh-question','en','What time does the library open?','图书馆几点开门？','询问信息；新增正式例句覆盖：question / interaction。',NULL,'[]',NULL,'1'),
('35e1a-ge-en-wh-question-02','en-wh-question','en','Where can I charge my phone?','我可以在哪里给手机充电？','询问信息；新增正式例句覆盖：question / interaction。',NULL,'[]',NULL,'2'),
('35e1a-ge-en-wh-question-03','en-wh-question','en','Why did you change the plan?','你为什么改变了计划？','询问信息；新增正式例句覆盖：question / interaction。',NULL,'[]',NULL,'3'),
('35e1a-ge-en-wh-question-04','en-wh-question','en','How much does this ticket cost?','这张票多少钱？','询问信息；新增正式例句覆盖：question / interaction。',NULL,'[]',NULL,'4');
INSERT INTO v2_grammar_examples(id,grammar_id,language,text,translation_zh,explanation_zh,ipa,readings_json,source_expression_id,sort_order) VALUES
('35e1a-ge-en-wh-question-05','en-wh-question','en','When are they arriving?','他们什么时候到？','询问信息；新增正式例句覆盖：question / interaction。',NULL,'[]',NULL,'5'),
('35e1a-ge-en-wh-question-06','en-wh-question','en','Which train goes to the city centre?','哪趟火车去市中心？','询问信息；新增正式例句覆盖：question / interaction。',NULL,'[]',NULL,'6'),
('35e1a-ge-en-imperative-01','en-imperative','en','Turn left at the next corner.','在下一个路口左转。','行动指示；新增正式例句覆盖：canonical/basic usage。',NULL,'[]',NULL,'1'),
('35e1a-ge-en-imperative-02','en-imperative','en','Please keep the receipt.','请保留收据。','行动指示；新增正式例句覆盖：natural daily-life context。',NULL,'[]',NULL,'2'),
('35e1a-ge-en-imperative-03','en-imperative','en','Do not touch that pan; it is hot.','不要碰那个锅，它很烫。','行动指示；新增正式例句覆盖：negative / restriction。',NULL,'[]',NULL,'3'),
('35e1a-ge-en-imperative-04','en-imperative','en','Take this medicine after dinner.','晚饭后服用这种药。','行动指示；新增正式例句覆盖：natural daily-life context。',NULL,'[]',NULL,'4'),
('35e1a-ge-en-imperative-05','en-imperative','en','Let me know when you arrive.','你到达时告诉我一声。','行动指示；新增正式例句覆盖：natural daily-life context。',NULL,'[]',NULL,'5'),
('35e1a-ge-en-imperative-06','en-imperative','en','Check the address before you send the form.','发送表格前请核对地址。','行动指示；新增正式例句覆盖：natural daily-life context。',NULL,'[]',NULL,'6'),
('35e1a-ge-en-want-to-01','en-want-to','en','We want to leave before the traffic gets busy.','我们想在交通繁忙前离开。','想做某事；新增正式例句覆盖：canonical/basic usage。',NULL,'[]',NULL,'1'),
('35e1a-ge-en-want-to-02','en-want-to','en','She does not want to eat outside tonight.','她今晚不想在外面吃。','想做某事；新增正式例句覆盖：negative / restriction。',NULL,'[]',NULL,'2'),
('35e1a-ge-en-want-to-03','en-want-to','en','Do you want to sit by the window?','你想坐在窗边吗？','想做某事；新增正式例句覆盖：question / interaction。',NULL,'[]',NULL,'3'),
('35e1a-ge-en-want-to-04','en-want-to','en','I want to learn how to cook this dish.','我想学会做这道菜。','想做某事；新增正式例句覆盖：natural daily-life context。',NULL,'[]',NULL,'4'),
('35e1a-ge-en-want-to-05','en-want-to','en','They wanted to change their booking.','他们想更改预订。','想做某事；新增正式例句覆盖：natural daily-life context。',NULL,'[]',NULL,'5'),
('35e1a-ge-en-want-to-06','en-want-to','en','What do you want to do this weekend?','这个周末你想做什么？','想做某事；新增正式例句覆盖：question / interaction。',NULL,'[]',NULL,'6'),
('35e1a-ge-en-possessive-01','en-possessive','en','Your bag is under the seat.','你的包在座位下面。','物品所属；新增正式例句覆盖：canonical/basic usage。',NULL,'[]',NULL,'1'),
('35e1a-ge-en-possessive-02','en-possessive','en','His appointment is on Thursday.','他的预约在星期四。','物品所属；新增正式例句覆盖：natural daily-life context。',NULL,'[]',NULL,'2'),
('35e1a-ge-en-possessive-03','en-possessive','en','Her train leaves at eight.','她的火车八点出发。','物品所属；新增正式例句覆盖：natural daily-life context。',NULL,'[]',NULL,'3'),
('35e1a-ge-en-possessive-04','en-possessive','en','Our room is on the third floor.','我们的房间在三楼。','物品所属；新增正式例句覆盖：natural daily-life context。',NULL,'[]',NULL,'4'),
('35e1a-ge-en-possessive-05','en-possessive','en','Their children go to this school.','他们的孩子在这所学校上学。','物品所属；新增正式例句覆盖：natural daily-life context。',NULL,'[]',NULL,'5'),
('35e1a-ge-en-possessive-06','en-possessive','en','Is this your card or mine?','这是你的卡还是我的？','物品所属；新增正式例句覆盖：question / interaction。',NULL,'[]',NULL,'6'),
('35e1a-ge-en-greeting-01','en-greeting','en','Good morning. How are you?','早上好。你好吗？','程式化社交回应；新增正式例句覆盖：question / interaction。',NULL,'[]',NULL,'1'),
('35e1a-ge-en-greeting-02','en-greeting','en','Nice to meet you.','很高兴认识你。','程式化社交回应；新增正式例句覆盖：natural daily-life context。',NULL,'[]',NULL,'2'),
('35e1a-ge-en-greeting-03','en-greeting','en','Thank you for your help.','谢谢你的帮助。','程式化社交回应；新增正式例句覆盖：natural daily-life context。',NULL,'[]',NULL,'3'),
('35e1a-ge-en-greeting-04','en-greeting','en','You are welcome.','不客气。','程式化社交回应；新增正式例句覆盖：natural daily-life context。',NULL,'[]',NULL,'4'),
('35e1a-ge-en-greeting-05','en-greeting','en','Take care on your way home.','回家路上保重。','程式化社交回应；新增正式例句覆盖：natural daily-life context。',NULL,'[]',NULL,'5'),
('35e1a-ge-en-greeting-06','en-greeting','en','Have a good weekend.','周末愉快。','程式化社交回应；新增正式例句覆盖：natural daily-life context。',NULL,'[]',NULL,'6'),
('35e1a-ge-en-noun-please-01','en-noun-please','en','A table for two, please.','请给我们一张两人桌。','简短礼貌回应；新增正式例句覆盖：canonical/basic usage。',NULL,'[]',NULL,'1'),
('35e1a-ge-en-noun-please-02','en-noun-please','en','The vegetarian option, please.','请给我素食那款。','简短礼貌回应；新增正式例句覆盖：natural daily-life context。',NULL,'[]',NULL,'2'),
('35e1a-ge-en-noun-please-03','en-noun-please','en','No sugar, thanks.','不要糖，谢谢。','简短礼貌回应；新增正式例句覆盖：negative / restriction。',NULL,'[]',NULL,'3'),
('35e1a-ge-en-noun-please-04','en-noun-please','en','Not today, thanks.','今天不用了，谢谢。','简短礼貌回应；新增正式例句覆盖：negative / restriction。',NULL,'[]',NULL,'4'),
('35e1a-ge-en-noun-please-05','en-noun-please','en','One more minute, please.','请再等一分钟。','简短礼貌回应；新增正式例句覆盖：natural daily-life context。',NULL,'[]',NULL,'5'),
('35e1a-ge-en-noun-please-06','en-noun-please','en','The receipt as well, please.','也请给我收据。','简短礼貌回应；新增正式例句覆盖：natural daily-life context。',NULL,'[]',NULL,'6'),
('35e1a-ge-en-simple-past-01','en-simple-past','en','We arrived ten minutes early.','我们提前十分钟到了。','讲述过去经历；新增正式例句覆盖：canonical/basic usage。',NULL,'[]',NULL,'1'),
('35e1a-ge-en-simple-past-02','en-simple-past','en','She did not feel well yesterday.','她昨天感觉不舒服。','讲述过去经历；新增正式例句覆盖：negative / restriction。',NULL,'[]',NULL,'2'),
('35e1a-ge-en-simple-past-03','en-simple-past','en','Did you call the hotel?','你给酒店打电话了吗？','讲述过去经历；新增正式例句覆盖：question / interaction。',NULL,'[]',NULL,'3'),
('35e1a-ge-en-simple-past-04','en-simple-past','en','I left my umbrella on the bus.','我把雨伞落在公交车上了。','讲述过去经历；新增正式例句覆盖：natural daily-life context。',NULL,'[]',NULL,'4'),
('35e1a-ge-en-simple-past-05','en-simple-past','en','They changed the meeting time last week.','他们上周更改了会议时间。','讲述过去经历；新增正式例句覆盖：natural daily-life context。',NULL,'[]',NULL,'5'),
('35e1a-ge-en-simple-past-06','en-simple-past','en','What did the doctor say?','医生说了什么？','讲述过去经历；新增正式例句覆盖：question / interaction。',NULL,'[]',NULL,'6'),
('35e1a-ge-en-plan-to-01','en-plan-to','en','We plan to move next month.','我们计划下个月搬家。','表达计划；新增正式例句覆盖：canonical/basic usage。',NULL,'[]',NULL,'1'),
('35e1a-ge-en-plan-to-02','en-plan-to','en','I do not plan to drive in the city.','我不打算在市区开车。','表达计划；新增正式例句覆盖：negative / restriction。',NULL,'[]',NULL,'2');
INSERT INTO v2_grammar_examples(id,grammar_id,language,text,translation_zh,explanation_zh,ipa,readings_json,source_expression_id,sort_order) VALUES
('35e1a-ge-en-plan-to-03','en-plan-to','en','Do you plan to stay for dinner?','你打算留下来吃晚饭吗？','表达计划；新增正式例句覆盖：question / interaction。',NULL,'[]',NULL,'3'),
('35e1a-ge-en-plan-to-04','en-plan-to','en','She plans to apply for the course.','她计划申请这门课程。','表达计划；新增正式例句覆盖：natural daily-life context。',NULL,'[]',NULL,'4'),
('35e1a-ge-en-plan-to-05','en-plan-to','en','They planned to meet at the station.','他们原计划在车站见面。','表达计划；新增正式例句覆盖：natural daily-life context。',NULL,'[]',NULL,'5'),
('35e1a-ge-en-plan-to-06','en-plan-to','en','When do you plan to finish the report?','你计划什么时候完成报告？','表达计划；新增正式例句覆盖：question / interaction。',NULL,'[]',NULL,'6'),
('35e1a-ge-en-can-request-01','en-can-request','en','Can you open the window?','你能打开窗户吗？','提出请求；新增正式例句覆盖：question / interaction。',NULL,'[]',NULL,'1'),
('35e1a-ge-en-can-request-02','en-can-request','en','Can you show me where the lift is?','你能告诉我电梯在哪里吗？','提出请求；新增正式例句覆盖：question / interaction。',NULL,'[]',NULL,'2'),
('35e1a-ge-en-can-request-03','en-can-request','en','Can you wait here for a moment?','你能在这里等一会儿吗？','提出请求；新增正式例句覆盖：question / interaction。',NULL,'[]',NULL,'3'),
('35e1a-ge-en-can-request-04','en-can-request','en','Can you speak a little more slowly?','你能说慢一点吗？','提出请求；新增正式例句覆盖：question / interaction。',NULL,'[]',NULL,'4'),
('35e1a-ge-en-can-request-05','en-can-request','en','Can you check this address for me?','你能帮我核对这个地址吗？','提出请求；新增正式例句覆盖：question / interaction。',NULL,'[]',NULL,'5'),
('35e1a-ge-en-can-request-06','en-can-request','en','Can you call me when you arrive?','你到的时候能给我打电话吗？','提出请求；新增正式例句覆盖：question / interaction。',NULL,'[]',NULL,'6'),
('35e1a-ge-en-can-ability-01','en-can-ability','en','My daughter can swim.','我女儿会游泳。','能力与许可；新增正式例句覆盖：canonical/basic usage。',NULL,'[]',NULL,'1'),
('35e1a-ge-en-can-ability-02','en-can-ability','en','I cannot hear you clearly.','我听不清你说话。','能力与许可；新增正式例句覆盖：negative / restriction。',NULL,'[]',NULL,'2'),
('35e1a-ge-en-can-ability-03','en-can-ability','en','Can he use this software?','他会使用这个软件吗？','能力与许可；新增正式例句覆盖：question / interaction。',NULL,'[]',NULL,'3'),
('35e1a-ge-en-can-ability-04','en-can-ability','en','We can finish the work today.','我们今天能完成这项工作。','能力与许可；新增正式例句覆盖：natural daily-life context。',NULL,'[]',NULL,'4'),
('35e1a-ge-en-can-ability-05','en-can-ability','en','This card can be used overseas.','这张卡可以在海外使用。','能力与许可；新增正式例句覆盖：natural daily-life context。',NULL,'[]',NULL,'5'),
('35e1a-ge-en-can-ability-06','en-can-ability','en','How many people can the room hold?','这个房间能容纳多少人？','能力与许可；新增正式例句覆盖：question / interaction。',NULL,'[]',NULL,'6'),
('35e1a-ge-en-could-request-01','en-could-request','en','Could you repeat the last part?','你能重复一下最后一部分吗？','委婉请求；新增正式例句覆盖：question / interaction。',NULL,'[]',NULL,'1'),
('35e1a-ge-en-could-request-02','en-could-request','en','Could you move your bag, please?','请你把包挪一下好吗？','委婉请求；新增正式例句覆盖：question / interaction。',NULL,'[]',NULL,'2'),
('35e1a-ge-en-could-request-03','en-could-request','en','Could you tell me the total price?','你能告诉我总价吗？','委婉请求；新增正式例句覆盖：question / interaction。',NULL,'[]',NULL,'3'),
('35e1a-ge-en-could-request-04','en-could-request','en','Could you send the file by Friday?','你能在星期五前发送文件吗？','委婉请求；新增正式例句覆盖：question / interaction。',NULL,'[]',NULL,'4'),
('35e1a-ge-en-could-request-05','en-could-request','en','Could you help me change this booking?','你能帮我更改这个预订吗？','委婉请求；新增正式例句覆盖：question / interaction。',NULL,'[]',NULL,'5'),
('35e1a-ge-en-could-request-06','en-could-request','en','Could you write that name down for me?','你能帮我写下那个名字吗？','委婉请求；新增正式例句覆盖：question / interaction。',NULL,'[]',NULL,'6'),
('35e1a-ge-en-going-to-01','en-going-to','en','We are going to visit my parents on Sunday.','我们打算星期天去看望我的父母。','已有意图；新增正式例句覆盖：canonical/basic usage。',NULL,'[]',NULL,'1'),
('35e1a-ge-en-going-to-02','en-going-to','en','I am not going to buy it today.','我今天不打算买它。','已有意图；新增正式例句覆盖：negative / restriction。',NULL,'[]',NULL,'2'),
('35e1a-ge-en-going-to-03','en-going-to','en','Are you going to take the train?','你打算坐火车吗？','已有意图；新增正式例句覆盖：question / interaction。',NULL,'[]',NULL,'3'),
('35e1a-ge-en-going-to-04','en-going-to','en','Look at those clouds; it is going to rain.','看那些云，要下雨了。','已有意图；新增正式例句覆盖：natural daily-life context。',NULL,'[]',NULL,'4'),
('35e1a-ge-en-going-to-05','en-going-to','en','She is going to start a new job next week.','她下周要开始一份新工作。','已有意图；新增正式例句覆盖：natural daily-life context。',NULL,'[]',NULL,'5'),
('35e1a-ge-en-going-to-06','en-going-to','en','What are you going to cook tonight?','你今晚打算做什么？','已有意图；新增正式例句覆盖：question / interaction。',NULL,'[]',NULL,'6'),
('35e1a-ge-en-will-01','en-will','en','I will carry that bag for you.','我来帮你拿那个包。','当场决定与承诺；新增正式例句覆盖：canonical/basic usage。',NULL,'[]',NULL,'1'),
('35e1a-ge-en-will-02','en-will','en','We will not be late.','我们不会迟到。','当场决定与承诺；新增正式例句覆盖：negative / restriction。',NULL,'[]',NULL,'2'),
('35e1a-ge-en-will-03','en-will','en','Will you be home this evening?','你今晚会在家吗？','当场决定与承诺；新增正式例句覆盖：question / interaction。',NULL,'[]',NULL,'3'),
('35e1a-ge-en-will-04','en-will','en','The meeting will start at ten.','会议将在十点开始。','当场决定与承诺；新增正式例句覆盖：natural daily-life context。',NULL,'[]',NULL,'4'),
('35e1a-ge-en-will-05','en-will','en','I think the weather will improve tomorrow.','我想明天天气会好转。','当场决定与承诺；新增正式例句覆盖：natural daily-life context。',NULL,'[]',NULL,'5'),
('35e1a-ge-en-will-06','en-will','en','Do not worry; I will call the landlord.','别担心，我会给房东打电话。','当场决定与承诺；新增正式例句覆盖：negative / restriction。',NULL,'[]',NULL,'6'),
('35e1a-ge-en-comparative-01','en-comparative','en','The bus is cheaper than the train.','公交车比火车便宜。','比较两者；新增正式例句覆盖：canonical/basic usage。',NULL,'[]',NULL,'1'),
('35e1a-ge-en-comparative-02','en-comparative','en','This route is not faster than the old one.','这条路线不比旧路线快。','比较两者；新增正式例句覆盖：negative / restriction。',NULL,'[]',NULL,'2'),
('35e1a-ge-en-comparative-03','en-comparative','en','Is the blue jacket warmer than the black one?','蓝色夹克比黑色夹克暖和吗？','比较两者；新增正式例句覆盖：question / interaction。',NULL,'[]',NULL,'3'),
('35e1a-ge-en-comparative-04','en-comparative','en','My new office is closer to home.','我的新办公室离家更近。','比较两者；新增正式例句覆盖：natural daily-life context。',NULL,'[]',NULL,'4'),
('35e1a-ge-en-comparative-05','en-comparative','en','Today is busier than yesterday.','今天比昨天更忙。','比较两者；新增正式例句覆盖：natural daily-life context。',NULL,'[]',NULL,'5'),
('35e1a-ge-en-comparative-06','en-comparative','en','Which option is more convenient for you?','哪个选项对你更方便？','比较两者；新增正式例句覆盖：question / interaction。',NULL,'[]',NULL,'6');
INSERT INTO v2_grammar_examples(id,grammar_id,language,text,translation_zh,explanation_zh,ipa,readings_json,source_expression_id,sort_order) VALUES
('35e1a-ge-en-would-like-01','en-would-like','en','I would like a glass of water, please.','我想要一杯水。','礼貌愿望与邀请；新增正式例句覆盖：canonical/basic usage。',NULL,'[]',NULL,'1'),
('35e1a-ge-en-would-like-02','en-would-like','en','We would like to check in now.','我们想现在办理入住。','礼貌愿望与邀请；新增正式例句覆盖：natural daily-life context。',NULL,'[]',NULL,'2'),
('35e1a-ge-en-would-like-03','en-would-like','en','Would you like some more rice?','你想再来一点米饭吗？','礼貌愿望与邀请；新增正式例句覆盖：question / interaction。',NULL,'[]',NULL,'3'),
('35e1a-ge-en-would-like-04','en-would-like','en','I would not like to discuss that at work.','我不想在工作场合讨论那件事。','礼貌愿望与邀请；新增正式例句覆盖：negative / restriction。',NULL,'[]',NULL,'4'),
('35e1a-ge-en-would-like-05','en-would-like','en','She would prefer a seat near the door.','她更想要靠门的座位。','礼貌愿望与邀请；新增正式例句覆盖：natural daily-life context。',NULL,'[]',NULL,'5'),
('35e1a-ge-en-would-like-06','en-would-like','en','Would they like us to call a taxi?','他们希望我们叫出租车吗？','礼貌愿望与邀请；新增正式例句覆盖：question / interaction。',NULL,'[]',NULL,'6'),
('35e1a-ge-en-let-us-01','en-let-us','en','Let''s check the timetable first.','我们先查看时刻表吧。','一起行动的建议；新增正式例句覆盖：canonical/basic usage。',NULL,'[]',NULL,'1'),
('35e1a-ge-en-let-us-02','en-let-us','en','Let''s not make a decision yet.','我们先别作决定。','一起行动的建议；新增正式例句覆盖：negative / restriction。',NULL,'[]',NULL,'2'),
('35e1a-ge-en-let-us-03','en-let-us','en','Let''s meet near the main entrance.','我们在正门附近见吧。','一起行动的建议；新增正式例句覆盖：natural daily-life context。',NULL,'[]',NULL,'3'),
('35e1a-ge-en-let-us-04','en-let-us','en','Let''s ask the staff for help.','我们请工作人员帮忙吧。','一起行动的建议；新增正式例句覆盖：natural daily-life context。',NULL,'[]',NULL,'4'),
('35e1a-ge-en-let-us-05','en-let-us','en','Let''s cook at home tonight.','我们今晚在家做饭吧。','一起行动的建议；新增正式例句覆盖：natural daily-life context。',NULL,'[]',NULL,'5'),
('35e1a-ge-en-let-us-06','en-let-us','en','Where shall we go? Let''s try the new café.','我们去哪里？去试试那家新咖啡馆吧。','一起行动的建议；新增正式例句覆盖：natural daily-life context。',NULL,'[]',NULL,'6'),
('35e1a-ge-en-before-after-01','en-before-after','en','Wash your hands before you cook.','做饭前要洗手。','动作先后；新增正式例句覆盖：canonical/basic usage。',NULL,'[]',NULL,'1'),
('35e1a-ge-en-before-after-02','en-before-after','en','We can talk after the meeting ends.','会议结束后我们可以谈谈。','动作先后；新增正式例句覆盖：natural daily-life context。',NULL,'[]',NULL,'2'),
('35e1a-ge-en-before-after-03','en-before-after','en','Do not leave before the doctor sees you.','医生看过你之前不要离开。','动作先后；新增正式例句覆盖：negative / restriction。',NULL,'[]',NULL,'3'),
('35e1a-ge-en-before-after-04','en-before-after','en','After she finishes work, she takes the bus home.','她下班后坐公交车回家。','动作先后；新增正式例句覆盖：natural daily-life context。',NULL,'[]',NULL,'4'),
('35e1a-ge-en-before-after-05','en-before-after','en','Please pay before you collect the order.','取餐前请付款。','动作先后；新增正式例句覆盖：natural daily-life context。',NULL,'[]',NULL,'5'),
('35e1a-ge-en-before-after-06','en-before-after','en','I checked the address after you called me.','你给我打电话后，我核对了地址。','动作先后；新增正式例句覆盖：natural daily-life context。',NULL,'[]',NULL,'6'),
('35e1a-ge-en-enjoy-ing-01','en-enjoy-ing','en','She enjoys reading on the train.','她喜欢在火车上看书。','喜欢某项活动；新增正式例句覆盖：canonical/basic usage。',NULL,'[]',NULL,'1'),
('35e1a-ge-en-enjoy-ing-02','en-enjoy-ing','en','We do not enjoy waiting in long lines.','我们不喜欢排长队等候。','喜欢某项活动；新增正式例句覆盖：negative / restriction。',NULL,'[]',NULL,'2'),
('35e1a-ge-en-enjoy-ing-03','en-enjoy-ing','en','Do you enjoy cooking for friends?','你喜欢给朋友做饭吗？','喜欢某项活动；新增正式例句覆盖：question / interaction。',NULL,'[]',NULL,'3'),
('35e1a-ge-en-enjoy-ing-04','en-enjoy-ing','en','He enjoyed working with the new team.','他很享受和新团队一起工作。','喜欢某项活动；新增正式例句覆盖：natural daily-life context。',NULL,'[]',NULL,'4'),
('35e1a-ge-en-enjoy-ing-05','en-enjoy-ing','en','I enjoy learning languages through conversation.','我喜欢通过对话学习语言。','喜欢某项活动；新增正式例句覆盖：natural daily-life context。',NULL,'[]',NULL,'5'),
('35e1a-ge-en-enjoy-ing-06','en-enjoy-ing','en','What do you enjoy doing after work?','你下班后喜欢做什么？','喜欢某项活动；新增正式例句覆盖：question / interaction。',NULL,'[]',NULL,'6'),
('35e1a-ge-en-take-time-01','en-take-time','en','It takes five minutes to walk to the station.','步行到车站需要五分钟。','需要多长时间；新增正式例句覆盖：canonical/basic usage。',NULL,'[]',NULL,'1'),
('35e1a-ge-en-take-time-02','en-take-time','en','It does not take long to complete the form.','填写这张表格花不了很久。','需要多长时间；新增正式例句覆盖：negative / restriction。',NULL,'[]',NULL,'2'),
('35e1a-ge-en-take-time-03','en-take-time','en','How long does it take to cook this rice?','煮这种米需要多长时间？','需要多长时间；新增正式例句覆盖：question / interaction。',NULL,'[]',NULL,'3'),
('35e1a-ge-en-take-time-04','en-take-time','en','It took us an hour to find the hotel.','我们花了一个小时才找到酒店。','需要多长时间；新增正式例句覆盖：natural daily-life context。',NULL,'[]',NULL,'4'),
('35e1a-ge-en-take-time-05','en-take-time','en','It will take two days to repair the phone.','修好这部手机需要两天。','需要多长时间；新增正式例句覆盖：natural daily-life context。',NULL,'[]',NULL,'5'),
('35e1a-ge-en-take-time-06','en-take-time','en','Does it take longer to travel during rush hour?','高峰期出行会花更长时间吗？','需要多长时间；新增正式例句覆盖：question / interaction。',NULL,'[]',NULL,'6'),
('35e1a-ge-en-shall-suggestion-01','en-shall-suggestion','en','Shall we order now?','我们现在点餐好吗？','共同提议问句；新增正式例句覆盖：question / interaction。',NULL,'[]',NULL,'1'),
('35e1a-ge-en-shall-suggestion-02','en-shall-suggestion','en','Shall we take a short break?','我们休息一会儿好吗？','共同提议问句；新增正式例句覆盖：question / interaction。',NULL,'[]',NULL,'2'),
('35e1a-ge-en-shall-suggestion-03','en-shall-suggestion','en','Shall we leave now rather than wait until tomorrow?','我们现在走，不等到明天好吗？','共同提议问句；新增正式例句覆盖：question / interaction。',NULL,'[]',NULL,'3'),
('35e1a-ge-en-shall-suggestion-04','en-shall-suggestion','en','Where shall we meet after class?','下课后我们在哪里见面？','共同提议问句；新增正式例句覆盖：question / interaction。',NULL,'[]',NULL,'4'),
('35e1a-ge-en-shall-suggestion-05','en-shall-suggestion','en','Shall we ask for a different room?','我们要求换一个房间好吗？','共同提议问句；新增正式例句覆盖：question / interaction。',NULL,'[]',NULL,'5'),
('35e1a-ge-en-shall-suggestion-06','en-shall-suggestion','en','What shall we do if the train is late?','如果火车晚点，我们怎么办？','共同提议问句；新增正式例句覆盖：question / interaction。',NULL,'[]',NULL,'6'),
('35e1a-ge-en-ellipsis-01','en-ellipsis','en','Are you ready? Not quite.','你准备好了吗？还没有完全准备好。','语境中的省略回应；新增正式例句覆盖：negative / restriction。',NULL,'[]',NULL,'1'),
('35e1a-ge-en-ellipsis-02','en-ellipsis','en','Would you like some tea? Yes, please.','你想喝点茶吗？好的，谢谢。','语境中的省略回应；新增正式例句覆盖：natural daily-life context。',NULL,'[]',NULL,'2'),
('35e1a-ge-en-ellipsis-03','en-ellipsis','en','Did she call? Not yet.','她打电话了吗？还没有。','语境中的省略回应；新增正式例句覆盖：negative / restriction。',NULL,'[]',NULL,'3'),
('35e1a-ge-en-ellipsis-04','en-ellipsis','en','Who needs a receipt? I do.','谁需要收据？我需要。','语境中的省略回应；新增正式例句覆盖：natural daily-life context。',NULL,'[]',NULL,'4');
INSERT INTO v2_grammar_examples(id,grammar_id,language,text,translation_zh,explanation_zh,ipa,readings_json,source_expression_id,sort_order) VALUES
('35e1a-ge-en-ellipsis-05','en-ellipsis','en','Can you come on Friday? I think so.','你星期五能来吗？我想可以。','语境中的省略回应；新增正式例句覆盖：natural daily-life context。',NULL,'[]',NULL,'5'),
('35e1a-ge-en-ellipsis-06','en-ellipsis','en','Is this seat free? It looks like it.','这个座位空着吗？看起来是的。','语境中的省略回应；新增正式例句覆盖：natural daily-life context。',NULL,'[]',NULL,'6'),
('35e1a-ge-en-may-01','en-may','en','The train may arrive a few minutes late.','火车可能会晚到几分钟。','表达不确定性；新增正式例句覆盖：canonical/basic usage。',NULL,'[]',NULL,'1'),
('35e1a-ge-en-may-02','en-may','en','She may not have enough time today.','她今天可能没有足够的时间。','表达不确定性；新增正式例句覆盖：negative / restriction。',NULL,'[]',NULL,'2'),
('35e1a-ge-en-may-03','en-may','en','The manager may join us later.','经理稍后可能会加入我们。','表达不确定性；新增正式例句覆盖：natural daily-life context。',NULL,'[]',NULL,'3'),
('35e1a-ge-en-may-04','en-may','en','We may need to change the schedule.','我们可能需要更改日程。','表达不确定性；新增正式例句覆盖：natural daily-life context。',NULL,'[]',NULL,'4'),
('35e1a-ge-en-may-05','en-may','en','This medicine may make you sleepy.','这种药可能会让你犯困。','表达不确定性；新增正式例句覆盖：natural daily-life context。',NULL,'[]',NULL,'5'),
('35e1a-ge-en-may-06','en-may','en','There may be a fee for changing the booking.','更改预订可能会收费。','表达不确定性；新增正式例句覆盖：natural daily-life context。',NULL,'[]',NULL,'6'),
('35e1a-ge-en-might-01','en-might','en','I might work from home tomorrow.','我明天可能在家工作。','表达不确定性；新增正式例句覆盖：canonical/basic usage。',NULL,'[]',NULL,'1'),
('35e1a-ge-en-might-02','en-might','en','They might not accept cash.','他们可能不收现金。','表达不确定性；新增正式例句覆盖：negative / restriction。',NULL,'[]',NULL,'2'),
('35e1a-ge-en-might-03','en-might','en','Do you think the road might be closed because of the snow?','你觉得这条路可能会因为下雪而关闭吗？','表达不确定性；新增正式例句覆盖：question / interaction。',NULL,'[]',NULL,'3'),
('35e1a-ge-en-might-04','en-might','en','We might need a larger table.','我们可能需要一张更大的桌子。','表达不确定性；新增正式例句覆盖：natural daily-life context。',NULL,'[]',NULL,'4'),
('35e1a-ge-en-might-05','en-might','en','She said she might arrive after eight.','她说她可能八点以后到。','表达不确定性；新增正式例句覆盖：natural daily-life context。',NULL,'[]',NULL,'5'),
('35e1a-ge-en-might-06','en-might','en','You might want to keep a copy of the form.','你或许最好留一份表格副本。','表达不确定性；新增正式例句覆盖：natural daily-life context。',NULL,'[]',NULL,'6'),
('35e1a-ge-en-indirect-question-01','en-indirect-question','en','Could you tell me when the shop closes?','你能告诉我商店几点关门吗？','嵌入式疑问；新增正式例句覆盖：question / interaction。',NULL,'[]',NULL,'1'),
('35e1a-ge-en-indirect-question-02','en-indirect-question','en','Do you know whether this seat is free?','你知道这个座位是否空着吗？','嵌入式疑问；新增正式例句覆盖：question / interaction。',NULL,'[]',NULL,'2'),
('35e1a-ge-en-indirect-question-03','en-indirect-question','en','I cannot remember where I put the key.','我想不起把钥匙放在哪里了。','嵌入式疑问；新增正式例句覆盖：negative / restriction。',NULL,'[]',NULL,'3'),
('35e1a-ge-en-indirect-question-04','en-indirect-question','en','Can you explain why the price changed?','你能解释价格为什么变了吗？','嵌入式疑问；新增正式例句覆盖：question / interaction。',NULL,'[]',NULL,'4'),
('35e1a-ge-en-indirect-question-05','en-indirect-question','en','She asked how long the repair would take.','她问维修需要多长时间。','嵌入式疑问；新增正式例句覆盖：natural daily-life context。',NULL,'[]',NULL,'5'),
('35e1a-ge-en-indirect-question-06','en-indirect-question','en','I wonder which bus goes to the hospital.','我想知道哪辆公交车去医院。','嵌入式疑问；新增正式例句覆盖：natural daily-life context。',NULL,'[]',NULL,'6'),
('35e1a-ge-en-since-for-01','en-since-for','en','We have lived here for three years.','我们在这里住了三年。','持续的起点与时长；新增正式例句覆盖：canonical/basic usage。',NULL,'[]',NULL,'1'),
('35e1a-ge-en-since-for-02','en-since-for','en','She has not eaten since breakfast.','她从早餐后一直没吃东西。','持续的起点与时长；新增正式例句覆盖：negative / restriction。',NULL,'[]',NULL,'2'),
('35e1a-ge-en-since-for-03','en-since-for','en','How long have you worked at this school?','你在这所学校工作多久了？','持续的起点与时长；新增正式例句覆盖：question / interaction。',NULL,'[]',NULL,'3'),
('35e1a-ge-en-since-for-04','en-since-for','en','I have known him since university.','我从大学起就认识他。','持续的起点与时长；新增正式例句覆盖：natural daily-life context。',NULL,'[]',NULL,'4'),
('35e1a-ge-en-since-for-05','en-since-for','en','The lift has been out of order for two days.','电梯已经坏了两天。','持续的起点与时长；新增正式例句覆盖：natural daily-life context。',NULL,'[]',NULL,'5'),
('35e1a-ge-en-since-for-06','en-since-for','en','Have you been waiting since nine o''clock?','你从九点起一直在等吗？','持续的起点与时长；新增正式例句覆盖：question / interaction。',NULL,'[]',NULL,'6'),
('35e1a-ge-en-as-long-as-01','en-as-long-as','en','You can borrow the car as long as you drive carefully.','只要你小心驾驶，就可以借这辆车。','只要这个条件成立；新增正式例句覆盖：canonical/basic usage。',NULL,'[]',NULL,'1'),
('35e1a-ge-en-as-long-as-02','en-as-long-as','en','I do not mind waiting as long as you let me know.','只要你告诉我，我不介意等。','只要这个条件成立；新增正式例句覆盖：negative / restriction。',NULL,'[]',NULL,'2'),
('35e1a-ge-en-as-long-as-03','en-as-long-as','en','Can we change the booking as long as we call today?','只要今天打电话，我们就能改预订吗？','只要这个条件成立；新增正式例句覆盖：question / interaction。',NULL,'[]',NULL,'3'),
('35e1a-ge-en-as-long-as-04','en-as-long-as','en','As long as the pain does not get worse, you can rest at home.','只要疼痛没有加重，你可以在家休息。','只要这个条件成立；新增正式例句覆盖：negative / restriction。',NULL,'[]',NULL,'4'),
('35e1a-ge-en-as-long-as-05','en-as-long-as','en','The plan will work as long as everyone arrives on time.','只要大家准时到，这个计划就可行。','只要这个条件成立；新增正式例句覆盖：natural daily-life context。',NULL,'[]',NULL,'5'),
('35e1a-ge-en-as-long-as-06','en-as-long-as','en','You may stay here as long as you keep the door closed.','只要你把门关着，就可以待在这里。','只要这个条件成立；新增正式例句覆盖：natural daily-life context。',NULL,'[]',NULL,'6'),
('35e1a-ge-en-would-rather-01','en-would-rather','en','I would rather take the train than drive.','我宁愿坐火车也不愿开车。','偏好某种行动；新增正式例句覆盖：canonical/basic usage。',NULL,'[]',NULL,'1'),
('35e1a-ge-en-would-rather-02','en-would-rather','en','She would rather not talk about it now.','她现在宁愿不谈这件事。','偏好某种行动；新增正式例句覆盖：negative / restriction。',NULL,'[]',NULL,'2'),
('35e1a-ge-en-would-rather-03','en-would-rather','en','Would you rather eat inside or outside?','你更愿意在室内还是室外吃？','偏好某种行动；新增正式例句覆盖：question / interaction。',NULL,'[]',NULL,'3'),
('35e1a-ge-en-would-rather-04','en-would-rather','en','We would rather wait for a quieter room.','我们宁愿等一个更安静的房间。','偏好某种行动；新增正式例句覆盖：natural daily-life context。',NULL,'[]',NULL,'4'),
('35e1a-ge-en-would-rather-05','en-would-rather','en','He said he would rather leave early.','他说他宁愿早点离开。','偏好某种行动；新增正式例句覆盖：natural daily-life context。',NULL,'[]',NULL,'5'),
('35e1a-ge-en-would-rather-06','en-would-rather','en','I would rather you called before visiting.','我希望你来访前先打电话。','偏好某种行动；新增正式例句覆盖：natural daily-life context。',NULL,'[]',NULL,'6'),
('35e1a-ge-en-what-if-01','en-what-if','en','What if the shop is already closed?','如果商店已经关门了怎么办？','提出假设问题；新增正式例句覆盖：question / interaction。',NULL,'[]',NULL,'1'),
('35e1a-ge-en-what-if-02','en-what-if','en','What if we cannot find a taxi?','如果我们找不到出租车怎么办？','提出假设问题；新增正式例句覆盖：negative question / interaction。',NULL,'[]',NULL,'2');
INSERT INTO v2_grammar_examples(id,grammar_id,language,text,translation_zh,explanation_zh,ipa,readings_json,source_expression_id,sort_order) VALUES
('35e1a-ge-en-what-if-03','en-what-if','en','What if she does not agree with the plan?','如果她不同意这个计划怎么办？','提出假设问题；新增正式例句覆盖：negative question / interaction。',NULL,'[]',NULL,'3'),
('35e1a-ge-en-what-if-04','en-what-if','en','What if I miss the last train?','如果我错过末班车怎么办？','提出假设问题；新增正式例句覆盖：question / interaction。',NULL,'[]',NULL,'4'),
('35e1a-ge-en-what-if-05','en-what-if','en','What if the medicine makes me feel worse?','如果这种药让我感觉更糟怎么办？','提出假设问题；新增正式例句覆盖：question / interaction。',NULL,'[]',NULL,'5'),
('35e1a-ge-en-what-if-06','en-what-if','en','What if we moved the meeting to Friday?','如果我们把会议改到星期五怎么样？','提出假设问题；新增正式例句覆盖：question / interaction。',NULL,'[]',NULL,'6'),
('35e1a-ge-en-ever-perfect-01','en-ever-perfect','en','Have you ever worked from home?','你曾经在家工作过吗？','到现在的经历；新增正式例句覆盖：question / interaction。',NULL,'[]',NULL,'1'),
('35e1a-ge-en-ever-perfect-02','en-ever-perfect','en','Has she ever tried Japanese food?','她吃过日本料理吗？','到现在的经历；新增正式例句覆盖：question / interaction。',NULL,'[]',NULL,'2'),
('35e1a-ge-en-ever-perfect-03','en-ever-perfect','en','I have never missed a flight.','我从未误过航班。','到现在的经历；新增正式例句覆盖：negative / restriction。',NULL,'[]',NULL,'3'),
('35e1a-ge-en-ever-perfect-04','en-ever-perfect','en','Have they ever stayed at this hotel?','他们住过这家酒店吗？','到现在的经历；新增正式例句覆盖：question / interaction。',NULL,'[]',NULL,'4'),
('35e1a-ge-en-ever-perfect-05','en-ever-perfect','en','What is the best book you have ever read?','你读过的最好的书是什么？','到现在的经历；新增正式例句覆盖：question / interaction。',NULL,'[]',NULL,'5'),
('35e1a-ge-en-ever-perfect-06','en-ever-perfect','en','He has only ever used this card online.','他一直只在网上用过这张卡。','到现在的经历；新增正式例句覆盖：natural daily-life context。',NULL,'[]',NULL,'6'),
('35e1a-ge-ja-plain-nonpast-01','ja-plain-nonpast','ja','毎朝、六時に起きる。','每天早上六点起床。','普通体非过去；新增正式例句覆盖：canonical/basic usage。',NULL,'[{"text":"毎朝、六時に起きる。","reading":"まいあさ、ろくじにおきる。"}]',NULL,'1'),
('35e1a-ge-ja-plain-nonpast-02','ja-plain-nonpast','ja','今日は家で仕事をする。','今天在家工作。','普通体非过去；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"今日は家で仕事をする。","reading":"きょうはいえでしごとをする。"}]',NULL,'2'),
('35e1a-ge-ja-plain-nonpast-03','ja-plain-nonpast','ja','この電車は空港まで行く。','这趟电车开往机场。','普通体非过去；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"この電車は空港まで行く。","reading":"このでんしゃはくうこうまでいく。"}]',NULL,'3'),
('35e1a-ge-ja-plain-nonpast-04','ja-plain-nonpast','ja','明日は学校に行かない。','明天不去学校。','普通体非过去；新增正式例句覆盖：negative / restriction。',NULL,'[{"text":"明日は学校に行かない。","reading":"あすはがっこうにいかない。"}]',NULL,'4'),
('35e1a-ge-ja-plain-nonpast-05','ja-plain-nonpast','ja','週末は友達と料理を作る。','周末和朋友一起做饭。','普通体非过去；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"週末は友達と料理を作る。","reading":"しゅうまつはともだちとりょうりをつくる。"}]',NULL,'5'),
('35e1a-ge-ja-plain-nonpast-06','ja-plain-nonpast','ja','何時に家を出る？','几点出门？','普通体非过去；新增正式例句覆盖：question / interaction。',NULL,'[{"text":"何時に家を出る？","reading":"なんじにいえをでる？"}]',NULL,'6'),
('35e1a-ge-ja-plain-nonpast-07','ja-plain-nonpast','ja','来月、新しい仕事を始める。','下个月开始新工作。','普通体非过去；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"来月、新しい仕事を始める。","reading":"らいげつ、あたらしいしごとをはじめる。"}]',NULL,'7'),
('35e1a-ge-ja-copula-01','ja-copula','ja','こちらが受付です。','这里是接待处。','描述状态；新增正式例句覆盖：canonical/basic usage。',NULL,'[{"text":"こちらが受付です。","reading":"こちらがうけつけです。"}]',NULL,'1'),
('35e1a-ge-ja-copula-02','ja-copula','ja','今日は休みではありません。','今天不是休息日。','描述状态；新增正式例句覆盖：negative / restriction。',NULL,'[{"text":"今日は休みではありません。","reading":"きょうはやすみではありません。"}]',NULL,'2'),
('35e1a-ge-ja-copula-03','ja-copula','ja','この部屋は静かですか。','这个房间安静吗？','描述状态；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"この部屋は静かですか。","reading":"このへやはしずかですか。"}]',NULL,'3'),
('35e1a-ge-ja-copula-04','ja-copula','ja','予約は明日の三時です。','预约是明天下午三点。','描述状态；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"予約は明日の三時です。","reading":"よやくはあすのさんじです。"}]',NULL,'4'),
('35e1a-ge-ja-copula-05','ja-copula','ja','妹は大学生です。','妹妹是大学生。','描述状态；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"妹は大学生です。","reading":"いもうとはだいがくせいです。"}]',NULL,'5'),
('35e1a-ge-ja-copula-06','ja-copula','ja','駅はあの建物の隣です。','车站在那栋楼旁边。','描述状态；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"駅はあの建物の隣です。","reading":"えきはあのたてもののとなりです。"}]',NULL,'6'),
('35e1a-ge-ja-copula-07','ja-copula','ja','昨日の担当は田中さんでした。','昨天的负责人是田中。','描述状态；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"昨日の担当は田中さんでした。","reading":"きのうのたんとうはたなかさんでした。"}]',NULL,'7'),
('35e1a-ge-ja-wa-topic-01','ja-wa-topic','ja','私は毎朝コーヒーを飲みます。','我每天早上喝咖啡。','提出话题；新增正式例句覆盖：canonical/basic usage。',NULL,'[{"text":"私は毎朝コーヒーを飲みます。","reading":"わたしはまいあさこーひーをのみます。"}]',NULL,'1'),
('35e1a-ge-ja-wa-topic-02','ja-wa-topic','ja','この店は日曜日も開いています。','这家店星期天也营业。','提出话题；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"この店は日曜日も開いています。","reading":"このみせはにちようびもあいています。"}]',NULL,'2'),
('35e1a-ge-ja-wa-topic-03','ja-wa-topic','ja','会議は十時からです。','会议从十点开始。','提出话题；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"会議は十時からです。","reading":"かいぎはじゅうじからです。"}]',NULL,'3'),
('35e1a-ge-ja-wa-topic-04','ja-wa-topic','ja','田中さんは今日は来ません。','田中今天不来。','提出话题；新增正式例句覆盖：negative / restriction。',NULL,'[{"text":"田中さんは今日は来ません。","reading":"たなかさんはきょうはきません。"}]',NULL,'4'),
('35e1a-ge-ja-wa-topic-05','ja-wa-topic','ja','この薬は食後に飲んでください。','这种药请在饭后服用。','提出话题；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"この薬は食後に飲んでください。","reading":"このくすりはしょくごにのんでください。"}]',NULL,'5'),
('35e1a-ge-ja-wa-topic-06','ja-wa-topic','ja','週末は何をしますか。','周末做什么？','提出话题；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"週末は何をしますか。","reading":"しゅうまつはなにをしますか。"}]',NULL,'6'),
('35e1a-ge-ja-wa-topic-07','ja-wa-topic','ja','値段は高いですが、品質はいいです。','价格虽高，但质量很好。','提出话题；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"値段は高いですが、品質はいいです。","reading":"ねだんはたかいですが、ひんしつはいいです。"}]',NULL,'7'),
('35e1a-ge-ja-ga-existence-01','ja-ga-existence','ja','机の上に鍵があります。','桌上有钥匙。','事物的存在；新增正式例句覆盖：canonical/basic usage。',NULL,'[{"text":"机の上に鍵があります。","reading":"つくえのうえにかぎがあります。"}]',NULL,'1'),
('35e1a-ge-ja-ga-existence-02','ja-ga-existence','ja','公園に子どもがいます。','公园里有孩子。','事物的存在；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"公園に子どもがいます。","reading":"こうえんにこどもがいます。"}]',NULL,'2'),
('35e1a-ge-ja-ga-existence-03','ja-ga-existence','ja','この近くに薬局はありません。','这附近没有药房。','事物的存在；新增正式例句覆盖：negative / restriction。',NULL,'[{"text":"この近くに薬局はありません。","reading":"このちかくにやっきょくはありません。"}]',NULL,'3'),
('35e1a-ge-ja-ga-existence-04','ja-ga-existence','ja','部屋に冷蔵庫がありますか。','房间里有冰箱吗？','事物的存在；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"部屋に冷蔵庫がありますか。","reading":"へやにれいぞうこがありますか。"}]',NULL,'4'),
('35e1a-ge-ja-ga-existence-05','ja-ga-existence','ja','駅の前に新しい店ができました。','车站前开了一家新店。','事物的存在；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"駅の前に新しい店ができました。","reading":"えきのまえにあたらしいみせができました。"}]',NULL,'5'),
('35e1a-ge-ja-ga-existence-06','ja-ga-existence','ja','会議室には誰もいません。','会议室里没有人。','事物的存在；新增正式例句覆盖：negative / restriction。',NULL,'[{"text":"会議室には誰もいません。","reading":"かいぎしつにはだれもいません。"}]',NULL,'6'),
('35e1a-ge-ja-ga-existence-07','ja-ga-existence','ja','明日の午後、予約があります。','明天下午有预约。','事物的存在；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"明日の午後、予約があります。","reading":"あすのごご、よやくがあります。"}]',NULL,'7'),
('35e1a-ge-ja-wo-object-01','ja-wo-object','ja','毎朝、新聞を読みます。','我每天早上看报纸。','动作对象；新增正式例句覆盖：canonical/basic usage。',NULL,'[{"text":"毎朝、新聞を読みます。","reading":"まいあさ、しんぶんをよみます。"}]',NULL,'1'),
('35e1a-ge-ja-wo-object-02','ja-wo-object','ja','駅で友達を待っています。','我正在车站等朋友。','动作对象；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"駅で友達を待っています。","reading":"えきでともだちをまっています。"}]',NULL,'2');
INSERT INTO v2_grammar_examples(id,grammar_id,language,text,translation_zh,explanation_zh,ipa,readings_json,source_expression_id,sort_order) VALUES
('35e1a-ge-ja-wo-object-03','ja-wo-object','ja','朝はコーヒーを飲みません。','早上不喝咖啡。','动作对象；新增正式例句覆盖：negative / restriction。',NULL,'[{"text":"朝はコーヒーを飲みません。","reading":"あさはこーひーをのみません。"}]',NULL,'3'),
('35e1a-ge-ja-wo-object-04','ja-wo-object','ja','この書類を確認しましたか。','你确认这份文件了吗？','动作对象；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"この書類を確認しましたか。","reading":"このしょるいをかくにんしましたか。"}]',NULL,'4'),
('35e1a-ge-ja-wo-object-05','ja-wo-object','ja','帰る前に窓を閉めてください。','回去前请关窗。','动作对象；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"帰る前に窓を閉めてください。","reading":"かえるまえにまどをしめてください。"}]',NULL,'5'),
('35e1a-ge-ja-wo-object-06','ja-wo-object','ja','週末に部屋を掃除します。','周末打扫房间。','动作对象；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"週末に部屋を掃除します。","reading":"しゅうまつにへやをそうじします。"}]',NULL,'6'),
('35e1a-ge-ja-wo-object-07','ja-wo-object','ja','どの電車を使いますか。','你坐哪趟电车？','动作对象；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"どの電車を使いますか。","reading":"どのでんしゃをつかいますか。"}]',NULL,'7'),
('35e1a-ge-ja-ni-time-01','ja-ni-time','ja','会議は九時に始まります。','会议九点开始。','时间点；新增正式例句覆盖：canonical/basic usage。',NULL,'[{"text":"会議は九時に始まります。","reading":"かいぎはくじにはじまります。"}]',NULL,'1'),
('35e1a-ge-ja-ni-time-02','ja-ni-time','ja','私は毎晩十一時に寝ます。','我每天晚上十一点睡觉。','时间点；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"私は毎晩十一時に寝ます。","reading":"わたしはまいばんじゅういちじにねます。"}]',NULL,'2'),
('35e1a-ge-ja-ni-time-03','ja-ni-time','ja','日曜日には仕事に行きません。','星期天不去上班。','时间点；新增正式例句覆盖：negative / restriction。',NULL,'[{"text":"日曜日には仕事に行きません。","reading":"にちようびにはしごとにいきません。"}]',NULL,'3'),
('35e1a-ge-ja-ni-time-04','ja-ni-time','ja','何時に駅に着きますか。','几点到车站？','时间点；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"何時に駅に着きますか。","reading":"なんじにえきにつきますか。"}]',NULL,'4'),
('35e1a-ge-ja-ni-time-05','ja-ni-time','ja','来週の月曜日に病院へ行きます。','下周一去医院。','时间点；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"来週の月曜日に病院へ行きます。","reading":"らいしゅうのげつようびにびょういんへいきます。"}]',NULL,'5'),
('35e1a-ge-ja-ni-time-06','ja-ni-time','ja','昼休みに友達と話しました。','午休时和朋友聊了天。','时间点；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"昼休みに友達と話しました。","reading":"ひるやすみにともだちとはなしました。"}]',NULL,'6'),
('35e1a-ge-ja-ni-time-07','ja-ni-time','ja','三時に受付で会いましょう。','三点在接待处见吧。','时间点；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"三時に受付で会いましょう。","reading":"さんじにうけつけであいましょう。"}]',NULL,'7'),
('35e1a-ge-ja-de-place-01','ja-de-place','ja','図書館で勉強します。','在图书馆学习。','动作场所；新增正式例句覆盖：canonical/basic usage。',NULL,'[{"text":"図書館で勉強します。","reading":"としょかんでべんきょうします。"}]',NULL,'1'),
('35e1a-ge-ja-de-place-02','ja-de-place','ja','家で昼ご飯を食べました。','在家吃了午饭。','动作场所；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"家で昼ご飯を食べました。","reading":"いえでひるごはんをたべました。"}]',NULL,'2'),
('35e1a-ge-ja-de-place-03','ja-de-place','ja','この部屋では電話を使わないでください。','请不要在这个房间打电话。','动作场所；新增正式例句覆盖：negative / restriction。',NULL,'[{"text":"この部屋では電話を使わないでください。","reading":"このへやではでんわをつかわないでください。"}]',NULL,'3'),
('35e1a-ge-ja-de-place-04','ja-de-place','ja','どこで切符を買えますか。','在哪里可以买票？','动作场所；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"どこで切符を買えますか。","reading":"どこできっぷをかえますか。"}]',NULL,'4'),
('35e1a-ge-ja-de-place-05','ja-de-place','ja','駅の前で友達を待っています。','正在车站前等朋友。','动作场所；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"駅の前で友達を待っています。","reading":"えきのまえでともだちをまっています。"}]',NULL,'5'),
('35e1a-ge-ja-de-place-06','ja-de-place','ja','会議は二階の部屋で行います。','会议在二楼的房间举行。','动作场所；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"会議は二階の部屋で行います。","reading":"かいぎはにかいのへやでおこないます。"}]',NULL,'6'),
('35e1a-ge-ja-de-place-07','ja-de-place','ja','週末は公園で走ります。','周末在公园跑步。','动作场所；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"週末は公園で走ります。","reading":"しゅうまつはこうえんではしります。"}]',NULL,'7'),
('35e1a-ge-ja-no-possession-01','ja-no-possession','ja','これは私の傘です。','这是我的伞。','所属与修饰；新增正式例句覆盖：canonical/basic usage。',NULL,'[{"text":"これは私の傘です。","reading":"これはわたしのかさです。"}]',NULL,'1'),
('35e1a-ge-ja-no-possession-02','ja-no-possession','ja','田中さんの電話番号を知っていますか。','你知道田中的电话号码吗？','所属与修饰；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"田中さんの電話番号を知っていますか。","reading":"たなかさんのでんわばんごうをしっていますか。"}]',NULL,'2'),
('35e1a-ge-ja-no-possession-03','ja-no-possession','ja','駅の入口はあちらです。','车站入口在那边。','所属与修饰；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"駅の入口はあちらです。","reading":"えきのいりぐちはあちらです。"}]',NULL,'3'),
('35e1a-ge-ja-no-possession-04','ja-no-possession','ja','この店の料理は辛くありません。','这家店的菜不辣。','所属与修饰；新增正式例句覆盖：negative / restriction。',NULL,'[{"text":"この店の料理は辛くありません。","reading":"このみせのりょうりはからくありません。"}]',NULL,'4'),
('35e1a-ge-ja-no-possession-05','ja-no-possession','ja','友達の家に泊まりました。','我住在朋友家了。','所属与修饰；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"友達の家に泊まりました。","reading":"ともだちのいえにとまりました。"}]',NULL,'5'),
('35e1a-ge-ja-no-possession-06','ja-no-possession','ja','明日の予定を確認しましょう。','我们确认一下明天的计划吧。','所属与修饰；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"明日の予定を確認しましょう。","reading":"あすのよていをかくにんしましょう。"}]',NULL,'6'),
('35e1a-ge-ja-no-possession-07','ja-no-possession','ja','会社の近くに小さな店があります。','公司附近有一家小店。','所属与修饰；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"会社の近くに小さな店があります。","reading":"かいしゃのちかくにちいさなみせがあります。"}]',NULL,'7'),
('35e1a-ge-ja-ka-question-01','ja-ka-question','ja','この席は空いていますか。','这个座位空着吗？','礼貌疑问；新增正式例句覆盖：canonical/basic usage。',NULL,'[{"text":"この席は空いていますか。","reading":"このせきはあいていますか。"}]',NULL,'1'),
('35e1a-ge-ja-ka-question-02','ja-ka-question','ja','カードで払えますか。','可以刷卡付款吗？','礼貌疑问；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"カードで払えますか。","reading":"かーどではらえますか。"}]',NULL,'2'),
('35e1a-ge-ja-ka-question-03','ja-ka-question','ja','明日の午後は大丈夫ですか。','明天下午方便吗？','礼貌疑问；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"明日の午後は大丈夫ですか。","reading":"あすのごごはだいじょうぶですか。"}]',NULL,'3'),
('35e1a-ge-ja-ka-question-04','ja-ka-question','ja','駅までどのくらいかかりますか。','到车站需要多久？','礼貌疑问；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"駅までどのくらいかかりますか。","reading":"えきまでどのくらいかかりますか。"}]',NULL,'4'),
('35e1a-ge-ja-ka-question-05','ja-ka-question','ja','何かアレルギーがありますか。','你有什么过敏吗？','礼貌疑问；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"何かアレルギーがありますか。","reading":"なにかあれるぎーがありますか。"}]',NULL,'5'),
('35e1a-ge-ja-ka-question-06','ja-ka-question','ja','もう予約を変更しましたか。','已经更改预约了吗？','礼貌疑问；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"もう予約を変更しましたか。","reading":"もうよやくをへんこうしましたか。"}]',NULL,'6'),
('35e1a-ge-ja-ka-question-07','ja-ka-question','ja','この席に座りますか。','你坐这个座位吗？','礼貌疑问；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"この席に座りますか。","reading":"このせきにすわりますか。"}]',NULL,'7'),
('35e1a-ge-ja-i-adjective-01','ja-i-adjective','ja','このかばんは軽いです。','这个包很轻。','い形容词陈述；新增正式例句覆盖：canonical/basic usage。',NULL,'[{"text":"このかばんは軽いです。","reading":"このかばんはかるいです。"}]',NULL,'1'),
('35e1a-ge-ja-i-adjective-02','ja-i-adjective','ja','今日はあまり寒くないです。','今天不太冷。','い形容词陈述；新增正式例句覆盖：negative / restriction。',NULL,'[{"text":"今日はあまり寒くないです。","reading":"きょうはあまりさむくないです。"}]',NULL,'2'),
('35e1a-ge-ja-i-adjective-03','ja-i-adjective','ja','その部屋は広いですか。','那个房间宽敞吗？','い形容词陈述；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"その部屋は広いですか。","reading":"そのへやはひろいですか。"}]',NULL,'3'),
('35e1a-ge-ja-i-adjective-04','ja-i-adjective','ja','昨日の試験は難しかったです。','昨天的考试很难。','い形容词陈述；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"昨日の試験は難しかったです。","reading":"きのうのしけんはむずかしかったです。"}]',NULL,'4'),
('35e1a-ge-ja-i-adjective-05','ja-i-adjective','ja','この料理は辛くありません。','这道菜不辣。','い形容词陈述；新增正式例句覆盖：negative / restriction。',NULL,'[{"text":"この料理は辛くありません。","reading":"このりょうりはからくありません。"}]',NULL,'5'),
('35e1a-ge-ja-i-adjective-06','ja-i-adjective','ja','駅から近い店を探しています。','我在找离车站近的店。','い形容词陈述；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"駅から近い店を探しています。","reading":"えきからちかいみせをさがしています。"}]',NULL,'6'),
('35e1a-ge-ja-i-adjective-07','ja-i-adjective','ja','朝の電車は人が多いです。','早上的电车人很多。','い形容词陈述；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"朝の電車は人が多いです。","reading":"あさのでんしゃはひとがおおいです。"}]',NULL,'7');
INSERT INTO v2_grammar_examples(id,grammar_id,language,text,translation_zh,explanation_zh,ipa,readings_json,source_expression_id,sort_order) VALUES
('35e1a-ge-ja-suki-01','ja-suki','ja','私は音楽が好きです。','我喜欢音乐。','表达喜好；新增正式例句覆盖：canonical/basic usage。',NULL,'[{"text":"私は音楽が好きです。","reading":"わたしはおんがくがすきです。"}]',NULL,'1'),
('35e1a-ge-ja-suki-02','ja-suki','ja','弟は辛い食べ物が好きではありません。','弟弟不喜欢辣的食物。','表达喜好；新增正式例句覆盖：negative / restriction。',NULL,'[{"text":"弟は辛い食べ物が好きではありません。","reading":"おとうとはからいたべものがすきではありません。"}]',NULL,'2'),
('35e1a-ge-ja-suki-03','ja-suki','ja','どんな映画が好きですか。','你喜欢什么样的电影？','表达喜好；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"どんな映画が好きですか。","reading":"どんなえいががすきですか。"}]',NULL,'3'),
('35e1a-ge-ja-suki-04','ja-suki','ja','母は料理をするのが好きです。','妈妈喜欢做饭。','表达喜好；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"母は料理をするのが好きです。","reading":"はははりょうりをするのがすきです。"}]',NULL,'4'),
('35e1a-ge-ja-suki-05','ja-suki','ja','この二つなら、青いほうが好きです。','这两个里面，我更喜欢蓝色的。','表达喜好；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"この二つなら、青いほうが好きです。","reading":"このふたつなら、あおいほうがすきです。"}]',NULL,'5'),
('35e1a-ge-ja-suki-06','ja-suki','ja','子どもの頃は読書が好きでした。','小时候我喜欢阅读。','表达喜好；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"子どもの頃は読書が好きでした。","reading":"こどものころはどくしょがすきでした。"}]',NULL,'6'),
('35e1a-ge-ja-suki-07','ja-suki','ja','静かな場所は好きですが、暗い部屋は苦手です。','我喜欢安静的地方，但不喜欢昏暗的房间。','表达喜好；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"静かな場所は好きですが、暗い部屋は苦手です。","reading":"しずかなばしょはすきですが、くらいへやはにがてです。"}]',NULL,'7'),
('35e1a-ge-ja-polite-present-01','ja-polite-present','ja','毎日、電車で会社へ行きます。','每天坐电车去公司。','动词礼貌非过去；新增正式例句覆盖：canonical/basic usage。',NULL,'[{"text":"毎日、電車で会社へ行きます。","reading":"まいにち、でんしゃでかいしゃへいきます。"}]',NULL,'1'),
('35e1a-ge-ja-polite-present-02','ja-polite-present','ja','今日は家で休みます。','今天在家休息。','动词礼貌非过去；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"今日は家で休みます。","reading":"きょうはいえでやすみます。"}]',NULL,'2'),
('35e1a-ge-ja-polite-present-03','ja-polite-present','ja','私は今日はカードを使いません。','我今天不用银行卡。','动词礼貌非过去；新增正式例句覆盖：negative / restriction。',NULL,'[{"text":"私は今日はカードを使いません。","reading":"わたしはきょうはかーどをつかいません。"}]',NULL,'3'),
('35e1a-ge-ja-polite-present-04','ja-polite-present','ja','何時に仕事が終わりますか。','工作几点结束？','动词礼貌非过去；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"何時に仕事が終わりますか。","reading":"なんじにしごとがおわりますか。"}]',NULL,'4'),
('35e1a-ge-ja-polite-present-05','ja-polite-present','ja','あとで資料を送ります。','稍后发送资料。','动词礼貌非过去；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"あとで資料を送ります。","reading":"あとでしりょうをおくります。"}]',NULL,'5'),
('35e1a-ge-ja-polite-present-06','ja-polite-present','ja','父は週末によく料理をします。','爸爸周末常做饭。','动词礼貌非过去；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"父は週末によく料理をします。","reading":"ちちはしゅうまつによくりょうりをします。"}]',NULL,'6'),
('35e1a-ge-ja-polite-present-07','ja-polite-present','ja','来月から日本語を勉強します。','从下个月开始学日语。','动词礼貌非过去；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"来月から日本語を勉強します。","reading":"らいげつからにほんごをべんきょうします。"}]',NULL,'7'),
('35e1a-ge-ja-greeting-01','ja-greeting','ja','こんにちは。今日は暑いですね。','你好。今天很热啊。','程式化社交回应；新增正式例句覆盖：canonical/basic usage。',NULL,'[{"text":"こんにちは。今日は暑いですね。","reading":"こんにちは。きょうはあついですね。"}]',NULL,'1'),
('35e1a-ge-ja-greeting-02','ja-greeting','ja','初めまして。山田と申します。','初次见面。我叫山田。','程式化社交回应；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"初めまして。山田と申します。","reading":"はじめまして。やまだともうします。"}]',NULL,'2'),
('35e1a-ge-ja-greeting-03','ja-greeting','ja','どうもありがとうございます。','非常感谢。','程式化社交回应；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"どうもありがとうございます。","reading":"どうもありがとうございます。"}]',NULL,'3'),
('35e1a-ge-ja-greeting-04','ja-greeting','ja','いいえ、どういたしまして。','不，不客气。','程式化社交回应；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"いいえ、どういたしまして。","reading":"いいえ、どういたしまして。"}]',NULL,'4'),
('35e1a-ge-ja-greeting-05','ja-greeting','ja','お先に失礼します。','我先告辞了。','程式化社交回应；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"お先に失礼します。","reading":"おさきにしつれいします。"}]',NULL,'5'),
('35e1a-ge-ja-greeting-06','ja-greeting','ja','お疲れさまでした。','辛苦了。','程式化社交回应；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"お疲れさまでした。","reading":"おつかれさまでした。"}]',NULL,'6'),
('35e1a-ge-ja-greeting-07','ja-greeting','ja','では、また明日。','那么，明天见。','程式化社交回应；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"では、また明日。","reading":"では、またあす。"}]',NULL,'7'),
('35e1a-ge-ja-plain-past-01','ja-plain-past','ja','昨日、駅で友達に会った。','昨天在车站见到了朋友。','普通体过去与完成；新增正式例句覆盖：canonical/basic usage。',NULL,'[{"text":"昨日、駅で友達に会った。","reading":"きのう、えきでともだちにあった。"}]',NULL,'1'),
('35e1a-ge-ja-plain-past-02','ja-plain-past','ja','朝ご飯は食べなかった。','没吃早饭。','普通体过去与完成；新增正式例句覆盖：negative / restriction。',NULL,'[{"text":"朝ご飯は食べなかった。","reading":"あさごはんはたべなかった。"}]',NULL,'2'),
('35e1a-ge-ja-plain-past-03','ja-plain-past','ja','もう先生に聞いた？','已经问老师了吗？','普通体过去与完成；新增正式例句覆盖：question / interaction。',NULL,'[{"text":"もう先生に聞いた？","reading":"もうせんせいにきいた？"}]',NULL,'3'),
('35e1a-ge-ja-plain-past-04','ja-plain-past','ja','先週、新しい靴を買った。','上周买了新鞋。','普通体过去与完成；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"先週、新しい靴を買った。","reading":"せんしゅう、あたらしいくつをかった。"}]',NULL,'4'),
('35e1a-ge-ja-plain-past-05','ja-plain-past','ja','電車が遅れて、会議に間に合わなかった。','电车晚点，没赶上会议。','普通体过去与完成；新增正式例句覆盖：negative / restriction。',NULL,'[{"text":"電車が遅れて、会議に間に合わなかった。","reading":"でんしゃがおくれて、かいぎにまにあわなかった。"}]',NULL,'5'),
('35e1a-ge-ja-plain-past-06','ja-plain-past','ja','週末は家でゆっくり休んだ。','周末在家好好休息了。','普通体过去与完成；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"週末は家でゆっくり休んだ。","reading":"しゅうまつはいえでゆっくりやすんだ。"}]',NULL,'6'),
('35e1a-ge-ja-plain-past-07','ja-plain-past','ja','どうして予定を変えたの？','为什么更改计划？','普通体过去与完成；新增正式例句覆盖：question / interaction。',NULL,'[{"text":"どうして予定を変えたの？","reading":"どうしてよていをかえたの？"}]',NULL,'7'),
('35e1a-ge-ja-te-form-01','ja-te-form','ja','窓を開けて、部屋の空気を入れ替えます。','打开窗户，给房间换气。','连接动作或接续补助形式；新增正式例句覆盖：canonical/basic usage。',NULL,'[{"text":"窓を開けて、部屋の空気を入れ替えます。","reading":"まどをあけて、へやのくうきをいれかえます。"}]',NULL,'1'),
('35e1a-ge-ja-te-form-02','ja-te-form','ja','駅で切符を買って、電車に乗ります。','在车站买票，然后坐电车。','连接动作或接续补助形式；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"駅で切符を買って、電車に乗ります。","reading":"えきできっぷをかって、でんしゃにのります。"}]',NULL,'2'),
('35e1a-ge-ja-te-form-03','ja-te-form','ja','ここに名前を書いてください。','请在这里写名字。','连接动作或接续补助形式；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"ここに名前を書いてください。","reading":"ここになまえをかいてください。"}]',NULL,'3'),
('35e1a-ge-ja-te-form-04','ja-te-form','ja','今、昼ご飯を食べています。','现在正在吃午饭。','连接动作或接续补助形式；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"今、昼ご飯を食べています。","reading":"いま、ひるごはんをたべています。"}]',NULL,'4'),
('35e1a-ge-ja-te-form-05','ja-te-form','ja','この薬を飲んで、少し休みました。','吃了这种药，然后休息了一会儿。','连接动作或接续补助形式；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"この薬を飲んで、少し休みました。","reading":"このくすりをのんで、すこしやすみました。"}]',NULL,'5'),
('35e1a-ge-ja-te-form-06','ja-te-form','ja','荷物を持って、こちらへ来てもらえますか。','能请你拿着行李来这里吗？','连接动作或接续补助形式；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"荷物を持って、こちらへ来てもらえますか。","reading":"にもつをもって、こちらへきてもらえますか。"}]',NULL,'6'),
('35e1a-ge-ja-te-form-07','ja-te-form','ja','朝起きて、まず水を飲みます。','早上起床后先喝水。','连接动作或接续补助形式；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"朝起きて、まず水を飲みます。","reading":"あさおきて、まずみずをのみます。"}]',NULL,'7'),
('35e1a-ge-ja-polite-negative-01','ja-polite-negative','ja','今日は残業しません。','今天不加班。','在礼貌语体中否定；新增正式例句覆盖：negative / restriction。',NULL,'[{"text":"今日は残業しません。","reading":"きょうはざんぎょうしません。"}]',NULL,'1'),
('35e1a-ge-ja-polite-negative-02','ja-polite-negative','ja','この電車は空港へ行きません。','这趟电车不去机场。','在礼貌语体中否定；新增正式例句覆盖：negative / restriction。',NULL,'[{"text":"この電車は空港へ行きません。","reading":"このでんしゃはくうこうへいきません。"}]',NULL,'2'),
('35e1a-ge-ja-polite-negative-03','ja-polite-negative','ja','今日は肉を食べません。','今天不吃肉。','在礼貌语体中否定；新增正式例句覆盖：negative / restriction。',NULL,'[{"text":"今日は肉を食べません。","reading":"きょうはにくをたべません。"}]',NULL,'3'),
('35e1a-ge-ja-polite-negative-04','ja-polite-negative','ja','まだ予約していません。','还没有预约。','在礼貌语体中否定；新增正式例句覆盖：negative / restriction。',NULL,'[{"text":"まだ予約していません。","reading":"まだよやくしていません。"}]',NULL,'4'),
('35e1a-ge-ja-polite-negative-05','ja-polite-negative','ja','週末は車を使いませんでした。','周末没有用车。','在礼貌语体中否定；新增正式例句覆盖：negative / restriction。',NULL,'[{"text":"週末は車を使いませんでした。","reading":"しゅうまつはくるまをつかいませんでした。"}]',NULL,'5');
INSERT INTO v2_grammar_examples(id,grammar_id,language,text,translation_zh,explanation_zh,ipa,readings_json,source_expression_id,sort_order) VALUES
('35e1a-ge-ja-polite-negative-06','ja-polite-negative','ja','その質問には今は答えません。','那个问题我现在不回答。','在礼貌语体中否定；新增正式例句覆盖：negative / restriction。',NULL,'[{"text":"その質問には今は答えません。","reading":"そのしつもんにはいまはこたえません。"}]',NULL,'6'),
('35e1a-ge-ja-polite-negative-07','ja-polite-negative','ja','このカードでは支払えません。','不能用这张卡付款。','在礼貌语体中否定；新增正式例句覆盖：negative / restriction。',NULL,'[{"text":"このカードでは支払えません。","reading":"このかーどではしはらえません。"}]',NULL,'7'),
('35e1a-ge-ja-polite-past-01','ja-polite-past','ja','昨日、病院へ行きました。','昨天去了医院。','讲述过去事件；新增正式例句覆盖：canonical/basic usage。',NULL,'[{"text":"昨日、病院へ行きました。","reading":"きのう、びょういんへいきました。"}]',NULL,'1'),
('35e1a-ge-ja-polite-past-02','ja-polite-past','ja','会議は予定どおり始まりました。','会议按计划开始了。','讲述过去事件；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"会議は予定どおり始まりました。","reading":"かいぎはよていどおりはじまりました。"}]',NULL,'2'),
('35e1a-ge-ja-polite-past-03','ja-polite-past','ja','朝は何も食べませんでした。','早上什么也没吃。','讲述过去事件；新增正式例句覆盖：negative / restriction。',NULL,'[{"text":"朝は何も食べませんでした。","reading":"あさはなにもたべませんでした。"}]',NULL,'3'),
('35e1a-ge-ja-polite-past-04','ja-polite-past','ja','もう書類を送りましたか。','已经发送文件了吗？','讲述过去事件；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"もう書類を送りましたか。","reading":"もうしょるいをおくりましたか。"}]',NULL,'4'),
('35e1a-ge-ja-polite-past-05','ja-polite-past','ja','駅で財布を落としました。','我在车站丢了钱包。','讲述过去事件；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"駅で財布を落としました。","reading":"えきでさいふをおとしました。"}]',NULL,'5'),
('35e1a-ge-ja-polite-past-06','ja-polite-past','ja','先週、新しい仕事を始めました。','上周开始了新工作。','讲述过去事件；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"先週、新しい仕事を始めました。","reading":"せんしゅう、あたらしいしごとをはじめました。"}]',NULL,'6'),
('35e1a-ge-ja-polite-past-07','ja-polite-past','ja','店員さんが丁寧に説明しました。','店员认真地进行了说明。','讲述过去事件；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"店員さんが丁寧に説明しました。","reading":"てんいんさんがていねいにせつめいしました。"}]',NULL,'7'),
('35e1a-ge-ja-te-kudasai-01','ja-te-kudasai','ja','荷物はここに置いてください。','请把行李放在这里。','请求帮助；新增正式例句覆盖：canonical/basic usage。',NULL,'[{"text":"荷物はここに置いてください。","reading":"にもつはここにおいてください。"}]',NULL,'1'),
('35e1a-ge-ja-te-kudasai-02','ja-te-kudasai','ja','次の角を右に曲がってください。','请在下一个路口右转。','请求帮助；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"次の角を右に曲がってください。","reading":"つぎのかどをみぎにまがってください。"}]',NULL,'2'),
('35e1a-ge-ja-te-kudasai-03','ja-te-kudasai','ja','少しゆっくり話してください。','请说慢一点。','请求帮助；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"少しゆっくり話してください。","reading":"すこしゆっくりはなしてください。"}]',NULL,'3'),
('35e1a-ge-ja-te-kudasai-04','ja-te-kudasai','ja','ここでは写真を撮らないでください。','请不要在这里拍照。','请求帮助；新增正式例句覆盖：negative / restriction。',NULL,'[{"text":"ここでは写真を撮らないでください。","reading":"ここではしゃしんをとらないでください。"}]',NULL,'4'),
('35e1a-ge-ja-te-kudasai-05','ja-te-kudasai','ja','名前と電話番号を書いてください。','请写下姓名和电话号码。','请求帮助；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"名前と電話番号を書いてください。","reading":"なまえとでんわばんごうをかいてください。"}]',NULL,'5'),
('35e1a-ge-ja-te-kudasai-06','ja-te-kudasai','ja','準備ができたら知らせてください。','准备好后请告诉我。','请求帮助；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"準備ができたら知らせてください。","reading":"じゅんびができたらしらせてください。"}]',NULL,'6'),
('35e1a-ge-ja-te-kudasai-07','ja-te-kudasai','ja','わからない言葉は先生に聞いてください。','不懂的词请问老师。','请求帮助；新增正式例句覆盖：negative / restriction。',NULL,'[{"text":"わからない言葉は先生に聞いてください。","reading":"わからないことばはせんせいにきいてください。"}]',NULL,'7'),
('35e1a-ge-ja-tai-01','ja-tai','ja','今日は早く帰りたいです。','今天想早点回去。','自己的愿望；新增正式例句覆盖：canonical/basic usage。',NULL,'[{"text":"今日は早く帰りたいです。","reading":"きょうははやくかえりたいです。"}]',NULL,'1'),
('35e1a-ge-ja-tai-02','ja-tai','ja','辛い物は食べたくありません。','不想吃辣的东西。','自己的愿望；新增正式例句覆盖：negative / restriction。',NULL,'[{"text":"辛い物は食べたくありません。","reading":"からいものはたべたくありません。"}]',NULL,'2'),
('35e1a-ge-ja-tai-03','ja-tai','ja','週末は何をしたいですか。','周末想做什么？','自己的愿望；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"週末は何をしたいですか。","reading":"しゅうまつはなにをしたいですか。"}]',NULL,'3'),
('35e1a-ge-ja-tai-04','ja-tai','ja','いつか京都に行きたいと思っています。','我想有一天去京都。','自己的愿望；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"いつか京都に行きたいと思っています。","reading":"いつかきょうとにいきたいとおもっています。"}]',NULL,'4'),
('35e1a-ge-ja-tai-05','ja-tai','ja','子どもの頃は医者になりたかったです。','小时候想当医生。','自己的愿望；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"子どもの頃は医者になりたかったです。","reading":"こどものころはいしゃになりたかったです。"}]',NULL,'5'),
('35e1a-ge-ja-tai-06','ja-tai','ja','もう少し詳しく話を聞きたいです。','我想再详细听一听。','自己的愿望；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"もう少し詳しく話を聞きたいです。","reading":"もうすこしくわしくはなしをききたいです。"}]',NULL,'6'),
('35e1a-ge-ja-tai-07','ja-tai','ja','どちらの部屋に泊まりたいですか。','你想住哪个房间？','自己的愿望；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"どちらの部屋に泊まりたいですか。","reading":"どちらのへやにとまりたいですか。"}]',NULL,'7'),
('35e1a-ge-ja-nai-01','ja-nai','ja','今日は車を使わない。','今天不开车。','普通体否定；新增正式例句覆盖：negative / restriction。',NULL,'[{"text":"今日は車を使わない。","reading":"きょうはくるまをつかわない。"}]',NULL,'1'),
('35e1a-ge-ja-nai-02','ja-nai','ja','この店では肉を買わない。','不在这家店买肉。','普通体否定；新增正式例句覆盖：negative / restriction。',NULL,'[{"text":"この店では肉を買わない。","reading":"このみせではにくをかわない。"}]',NULL,'2'),
('35e1a-ge-ja-nai-03','ja-nai','ja','まだ答えがわからない。','还不知道答案。','普通体否定；新增正式例句覆盖：negative / restriction。',NULL,'[{"text":"まだ答えがわからない。","reading":"まだこたえがわからない。"}]',NULL,'3'),
('35e1a-ge-ja-nai-04','ja-nai','ja','明日は会社に行かない？','明天不去公司吗？','普通体否定；新增正式例句覆盖：negative question / interaction。',NULL,'[{"text":"明日は会社に行かない？","reading":"あすはかいしゃにいかない？"}]',NULL,'4'),
('35e1a-ge-ja-nai-05','ja-nai','ja','忘れないように、予定を書いておく。','为了不忘记，先把计划写下来。','普通体否定；新增正式例句覆盖：negative / restriction。',NULL,'[{"text":"忘れないように、予定を書いておく。","reading":"わすれないように、よていをかいておく。"}]',NULL,'5'),
('35e1a-ge-ja-nai-06','ja-nai','ja','時間がないから、朝ご飯は作らない。','因为没时间，不做早饭。','普通体否定；新增正式例句覆盖：negative / restriction。',NULL,'[{"text":"時間がないから、朝ご飯は作らない。","reading":"じかんがないから、あさごはんはつくらない。"}]',NULL,'6'),
('35e1a-ge-ja-nai-07','ja-nai','ja','この薬を飲まないで。','不要吃这种药。','普通体否定；新增正式例句覆盖：negative / restriction。',NULL,'[{"text":"この薬を飲まないで。","reading":"このくすりをのまないで。"}]',NULL,'7'),
('35e1a-ge-ja-potential-01','ja-potential','ja','私は少し日本語が話せます。','我会说一点日语。','能够做到；新增正式例句覆盖：canonical/basic usage。',NULL,'[{"text":"私は少し日本語が話せます。","reading":"わたしはすこしにほんごがはなせます。"}]',NULL,'1'),
('35e1a-ge-ja-potential-02','ja-potential','ja','今日は車を運転できません。','今天不能开车。','能够做到；新增正式例句覆盖：negative / restriction。',NULL,'[{"text":"今日は車を運転できません。","reading":"きょうはくるまをうんてんできません。"}]',NULL,'2'),
('35e1a-ge-ja-potential-03','ja-potential','ja','この部屋でWi-Fiが使えますか。','这个房间可以使用无线网络吗？','能够做到；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"この部屋でWi-Fiが使えますか。","reading":"このへやでWi-Fiがつかえますか。"}]',NULL,'3'),
('35e1a-ge-ja-potential-04','ja-potential','ja','駅まで歩いて行けます。','可以步行到车站。','能够做到；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"駅まで歩いて行けます。","reading":"えきまであるいていけます。"}]',NULL,'4'),
('35e1a-ge-ja-potential-05','ja-potential','ja','昨日はよく眠れませんでした。','昨天没能睡好。','能够做到；新增正式例句覆盖：negative / restriction。',NULL,'[{"text":"昨日はよく眠れませんでした。","reading":"きのうはよくねむれませんでした。"}]',NULL,'5'),
('35e1a-ge-ja-potential-06','ja-potential','ja','何時まで予約を変更できますか。','预约最晚可以更改到几点？','能够做到；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"何時まで予約を変更できますか。","reading":"なんじまでよやくをへんこうできますか。"}]',NULL,'6'),
('35e1a-ge-ja-potential-07','ja-potential','ja','この窓は簡単に開けられます。','这扇窗很容易打开。','能够做到；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"この窓は簡単に開けられます。","reading":"このまどはかんたんにあけられます。"}]',NULL,'7'),
('35e1a-ge-ja-te-mo-ii-01','ja-te-mo-ii','ja','ここに座ってもいいですか。','可以坐在这里吗？','许可；新增正式例句覆盖：canonical/basic usage。',NULL,'[{"text":"ここに座ってもいいですか。","reading":"ここにすわってもいいですか。"}]',NULL,'1'),
('35e1a-ge-ja-te-mo-ii-02','ja-te-mo-ii','ja','この部屋では靴を脱がなくてもいいです。','在这个房间不用脱鞋也可以。','许可；新增正式例句覆盖：negative / restriction。',NULL,'[{"text":"この部屋では靴を脱がなくてもいいです。","reading":"このへやではくつをぬがなくてもいいです。"}]',NULL,'2'),
('35e1a-ge-ja-te-mo-ii-03','ja-te-mo-ii','ja','今日は少し早く帰ってもいいですよ。','今天可以早点回去。','许可；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"今日は少し早く帰ってもいいですよ。","reading":"きょうはすこしはやくかえってもいいですよ。"}]',NULL,'3');
INSERT INTO v2_grammar_examples(id,grammar_id,language,text,translation_zh,explanation_zh,ipa,readings_json,source_expression_id,sort_order) VALUES
('35e1a-ge-ja-te-mo-ii-04','ja-te-mo-ii','ja','このカードを使ってもいいですか。','可以用这张卡吗？','许可；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"このカードを使ってもいいですか。","reading":"このかーどをつかってもいいですか。"}]',NULL,'4'),
('35e1a-ge-ja-te-mo-ii-05','ja-te-mo-ii','ja','わからなければ、先生に聞いてもいいです。','不懂的话可以问老师。','许可；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"わからなければ、先生に聞いてもいいです。","reading":"わからなければ、せんせいにきいてもいいです。"}]',NULL,'5'),
('35e1a-ge-ja-te-mo-ii-06','ja-te-mo-ii','ja','窓を開けてもいいですか。','可以开窗吗？','许可；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"窓を開けてもいいですか。","reading":"まどをあけてもいいですか。"}]',NULL,'6'),
('35e1a-ge-ja-te-mo-ii-07','ja-te-mo-ii','ja','予約はあとで変更してもいいでしょうか。','预约可以稍后更改吗？','许可；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"予約はあとで変更してもいいでしょうか。","reading":"よやくはあとでへんこうしてもいいでしょうか。"}]',NULL,'7'),
('35e1a-ge-ja-mashou-01','ja-mashou','ja','少し休みましょう。','休息一下吧。','共同提议；新增正式例句覆盖：canonical/basic usage。',NULL,'[{"text":"少し休みましょう。","reading":"すこしやすみましょう。"}]',NULL,'1'),
('35e1a-ge-ja-mashou-02','ja-mashou','ja','今日は外で食べましょう。','今天在外面吃吧。','共同提议；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"今日は外で食べましょう。","reading":"きょうはそとでたべましょう。"}]',NULL,'2'),
('35e1a-ge-ja-mashou-03','ja-mashou','ja','まだ決めないでおきましょう。','我们先不要决定吧。','共同提议；新增正式例句覆盖：negative / restriction。',NULL,'[{"text":"まだ決めないでおきましょう。","reading":"まだきめないでおきましょう。"}]',NULL,'3'),
('35e1a-ge-ja-mashou-04','ja-mashou','ja','駅の入口で会いましょう。','在车站入口见吧。','共同提议；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"駅の入口で会いましょう。","reading":"えきのいりぐちであいましょう。"}]',NULL,'4'),
('35e1a-ge-ja-mashou-05','ja-mashou','ja','わからない点を一緒に確認しましょう。','一起确认不明白的地方吧。','共同提议；新增正式例句覆盖：negative / restriction。',NULL,'[{"text":"わからない点を一緒に確認しましょう。","reading":"わからないてんをいっしょにかくにんしましょう。"}]',NULL,'5'),
('35e1a-ge-ja-mashou-06','ja-mashou','ja','雨が降る前に帰りましょう。','趁下雨前回去吧。','共同提议；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"雨が降る前に帰りましょう。","reading":"あめがふるまえにかえりましょう。"}]',NULL,'6'),
('35e1a-ge-ja-mashou-07','ja-mashou','ja','次は別の方法を試しましょう。','下次试试别的方法吧。','共同提议；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"次は別の方法を試しましょう。","reading":"つぎはべつのほうほうをためしましょう。"}]',NULL,'7'),
('35e1a-ge-ja-masen-ka-01','ja-masen-ka','ja','一緒に映画を見ませんか。','一起看电影好吗？','邀请；新增正式例句覆盖：negative / restriction。',NULL,'[{"text":"一緒に映画を見ませんか。","reading":"いっしょにえいがをみませんか。"}]',NULL,'1'),
('35e1a-ge-ja-masen-ka-02','ja-masen-ka','ja','少し休みませんか。','休息一下好吗？','邀请；新增正式例句覆盖：negative / restriction。',NULL,'[{"text":"少し休みませんか。","reading":"すこしやすみませんか。"}]',NULL,'2'),
('35e1a-ge-ja-masen-ka-03','ja-masen-ka','ja','駅まで歩きませんか。','一起走到车站好吗？','邀请；新增正式例句覆盖：negative / restriction。',NULL,'[{"text":"駅まで歩きませんか。","reading":"えきまであるきませんか。"}]',NULL,'3'),
('35e1a-ge-ja-masen-ka-04','ja-masen-ka','ja','今度の日曜日に会いませんか。','下个星期天见面好吗？','邀请；新增正式例句覆盖：negative / restriction。',NULL,'[{"text":"今度の日曜日に会いませんか。","reading":"こんどのにちようびにあいませんか。"}]',NULL,'4'),
('35e1a-ge-ja-masen-ka-05','ja-masen-ka','ja','この案についてもう一度話しませんか。','要不要再谈谈这个方案？','邀请；新增正式例句覆盖：negative / restriction。',NULL,'[{"text":"この案についてもう一度話しませんか。","reading":"このあんについてもういちどはなしませんか。"}]',NULL,'5'),
('35e1a-ge-ja-masen-ka-06','ja-masen-ka','ja','窓を開けませんか。','要不要开窗？','邀请；新增正式例句覆盖：negative / restriction。',NULL,'[{"text":"窓を開けませんか。","reading":"まどをあけませんか。"}]',NULL,'6'),
('35e1a-ge-ja-masen-ka-07','ja-masen-ka','ja','昼ご飯は新しい店で食べませんか。','午饭去新店吃好吗？','邀请；新增正式例句覆盖：negative / restriction。',NULL,'[{"text":"昼ご飯は新しい店で食べませんか。","reading":"ひるごはんはあたらしいみせでたべませんか。"}]',NULL,'7'),
('35e1a-ge-ja-mae-ni-01','ja-mae-ni','ja','寝る前に薬を飲みます。','睡觉前吃药。','动作之前；新增正式例句覆盖：canonical/basic usage。',NULL,'[{"text":"寝る前に薬を飲みます。","reading":"ねるまえにくすりをのみます。"}]',NULL,'1'),
('35e1a-ge-ja-mae-ni-02','ja-mae-ni','ja','電車に乗る前に切符を買ってください。','坐电车前请买票。','动作之前；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"電車に乗る前に切符を買ってください。","reading":"でんしゃにのるまえにきっぷをかってください。"}]',NULL,'2'),
('35e1a-ge-ja-mae-ni-03','ja-mae-ni','ja','出かける前に天気を確認しました。','出门前确认了天气。','动作之前；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"出かける前に天気を確認しました。","reading":"でかけるまえにてんきをかくにんしました。"}]',NULL,'3'),
('35e1a-ge-ja-mae-ni-04','ja-mae-ni','ja','料理をする前に手を洗います。','做饭前洗手。','动作之前；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"料理をする前に手を洗います。","reading":"りょうりをするまえにてをあらいます。"}]',NULL,'4'),
('35e1a-ge-ja-mae-ni-05','ja-mae-ni','ja','会議が始まる前に質問はありますか。','会议开始前有问题吗？','动作之前；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"会議が始まる前に質問はありますか。","reading":"かいぎがはじまるまえにしつもんはありますか。"}]',NULL,'5'),
('35e1a-ge-ja-mae-ni-06','ja-mae-ni','ja','注文する前に値段を見ましょう。','点单前先看价格吧。','动作之前；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"注文する前に値段を見ましょう。","reading":"ちゅうもんするまえにねだんをみましょう。"}]',NULL,'6'),
('35e1a-ge-ja-mae-ni-07','ja-mae-ni','ja','日本へ来る前に少し日本語を勉強しました。','来日本前学了一点日语。','动作之前；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"日本へ来る前に少し日本語を勉強しました。","reading":"にほんへくるまえにすこしにほんごをべんきょうしました。"}]',NULL,'7'),
('35e1a-ge-ja-kara-after-01','ja-kara-after','ja','仕事が終わってから、友達に電話します。','工作结束后给朋友打电话。','完成后再做；新增正式例句覆盖：canonical/basic usage。',NULL,'[{"text":"仕事が終わってから、友達に電話します。","reading":"しごとがおわってから、ともだちにでんわします。"}]',NULL,'1'),
('35e1a-ge-ja-kara-after-02','ja-kara-after','ja','手を洗ってから、料理を始めてください。','洗手后再开始做饭。','完成后再做；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"手を洗ってから、料理を始めてください。","reading":"てをあらってから、りょうりをはじめてください。"}]',NULL,'2'),
('35e1a-ge-ja-kara-after-03','ja-kara-after','ja','駅に着いてから、連絡しました。','到车站后联系了对方。','完成后再做；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"駅に着いてから、連絡しました。","reading":"えきについてから、れんらくしました。"}]',NULL,'3'),
('35e1a-ge-ja-kara-after-04','ja-kara-after','ja','説明を聞いてから決めてもいいですか。','可以听完说明后再决定吗？','完成后再做；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"説明を聞いてから決めてもいいですか。","reading":"せつめいをきいてからきめてもいいですか。"}]',NULL,'4'),
('35e1a-ge-ja-kara-after-05','ja-kara-after','ja','薬を飲んでから、少し眠くなりました。','吃药后有点困了。','完成后再做；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"薬を飲んでから、少し眠くなりました。","reading":"くすりをのんでから、すこしねむくなりました。"}]',NULL,'5'),
('35e1a-ge-ja-kara-after-06','ja-kara-after','ja','部屋を確認してから、鍵を返します。','确认房间后归还钥匙。','完成后再做；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"部屋を確認してから、鍵を返します。","reading":"へやをかくにんしてから、かぎをかえします。"}]',NULL,'6'),
('35e1a-ge-ja-kara-after-07','ja-kara-after','ja','予約してから店へ行ったほうがいいです。','最好预约后再去店里。','完成后再做；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"予約してから店へ行ったほうがいいです。","reading":"よやくしてからみせへいったほうがいいです。"}]',NULL,'7'),
('35e1a-ge-ja-request-onegai-01','ja-request-onegai','ja','コーヒーを一つお願いします。','请给我一杯咖啡。','提出所需内容；新增正式例句覆盖：canonical/basic usage。',NULL,'[{"text":"コーヒーを一つお願いします。","reading":"こーひーをひとつおねがいします。"}]',NULL,'1'),
('35e1a-ge-ja-request-onegai-02','ja-request-onegai','ja','窓側の席でお願いします。','请安排靠窗的座位。','提出所需内容；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"窓側の席でお願いします。","reading":"まどがわのせきでおねがいします。"}]',NULL,'2'),
('35e1a-ge-ja-request-onegai-03','ja-request-onegai','ja','砂糖なしでお願いします。','请不要加糖。','提出所需内容；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"砂糖なしでお願いします。","reading":"さとうなしでおねがいします。"}]',NULL,'3'),
('35e1a-ge-ja-request-onegai-04','ja-request-onegai','ja','会計をお願いします。','请结账。','提出所需内容；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"会計をお願いします。","reading":"かいけいをおねがいします。"}]',NULL,'4'),
('35e1a-ge-ja-request-onegai-05','ja-request-onegai','ja','予約の変更をお願いします。','请帮我更改预约。','提出所需内容；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"予約の変更をお願いします。","reading":"よやくのへんこうをおねがいします。"}]',NULL,'5'),
('35e1a-ge-ja-request-onegai-06','ja-request-onegai','ja','もう少し小さいサイズをお願いします。','请给我再小一点的尺码。','提出所需内容；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"もう少し小さいサイズをお願いします。","reading":"もうすこしちいさいさいずをおねがいします。"}]',NULL,'6'),
('35e1a-ge-ja-request-onegai-07','ja-request-onegai','ja','明日の午後でお願いできますか。','可以安排在明天下午吗？','提出所需内容；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"明日の午後でお願いできますか。","reading":"あすのごごでおねがいできますか。"}]',NULL,'7'),
('35e1a-ge-ja-hodo-approx-01','ja-hodo-approx','ja','駅まで十分ほどかかります。','到车站大约需要十分钟。','大约的数量；新增正式例句覆盖：canonical/basic usage。',NULL,'[{"text":"駅まで十分ほどかかります。","reading":"えきまでじゅっぷんほどかかります。"}]',NULL,'1');
INSERT INTO v2_grammar_examples(id,grammar_id,language,text,translation_zh,explanation_zh,ipa,readings_json,source_expression_id,sort_order) VALUES
('35e1a-ge-ja-hodo-approx-02','ja-hodo-approx','ja','参加者は三十人ほどでした。','参加者大约有三十人。','大约的数量；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"参加者は三十人ほどでした。","reading":"さんかしゃはさんじゅうにんほどでした。"}]',NULL,'2'),
('35e1a-ge-ja-hodo-approx-03','ja-hodo-approx','ja','この箱には米が五キロほど入っています。','这个箱子里大约装了五公斤大米。','大约的数量；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"この箱には米が五キロほど入っています。","reading":"このはこにはこめがごきろほどはいっています。"}]',NULL,'3'),
('35e1a-ge-ja-hodo-approx-04','ja-hodo-approx','ja','あと一時間ほど待てますか。','还能等大约一个小时吗？','大约的数量；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"あと一時間ほど待てますか。","reading":"あといちじかんほどまてますか。"}]',NULL,'4'),
('35e1a-ge-ja-hodo-approx-05','ja-hodo-approx','ja','週に二回ほど運動します。','每周大约运动两次。','大约的数量；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"週に二回ほど運動します。","reading":"しゅうににかいほどうんどうします。"}]',NULL,'5'),
('35e1a-ge-ja-hodo-approx-06','ja-hodo-approx','ja','昼休みは四十分ほどです。','午休大约四十分钟。','大约的数量；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"昼休みは四十分ほどです。","reading":"ひるやすみはよんじゅっぷんほどです。"}]',NULL,'6'),
('35e1a-ge-ja-hodo-approx-07','ja-hodo-approx','ja','修理には二日ほどかかるそうです。','听说维修大约需要两天。','大约的数量；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"修理には二日ほどかかるそうです。","reading":"しゅうりにはふつかほどかかるそうです。"}]',NULL,'7'),
('35e1a-ge-ja-dake-01','ja-dake','ja','今日は水だけ飲みました。','今天只喝了水。','限定范围；新增正式例句覆盖：canonical/basic usage。',NULL,'[{"text":"今日は水だけ飲みました。","reading":"きょうはみずだけのみました。"}]',NULL,'1'),
('35e1a-ge-ja-dake-02','ja-dake','ja','必要な物だけ買いましょう。','只买需要的东西吧。','限定范围；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"必要な物だけ買いましょう。","reading":"ひつようなものだけかいましょう。"}]',NULL,'2'),
('35e1a-ge-ja-dake-03','ja-dake','ja','私は説明を聞いただけです。','我只是听了说明。','限定范围；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"私は説明を聞いただけです。","reading":"わたしはせつめいをきいただけです。"}]',NULL,'3'),
('35e1a-ge-ja-dake-04','ja-dake','ja','この部屋には椅子が一つだけあります。','这个房间里只有一把椅子。','限定范围；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"この部屋には椅子が一つだけあります。","reading":"このへやにはいすがひとつだけあります。"}]',NULL,'4'),
('35e1a-ge-ja-dake-05','ja-dake','ja','名前を書くだけで大丈夫です。','只写名字就可以。','限定范围；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"名前を書くだけで大丈夫です。","reading":"なまえをかくだけでだいじょうぶです。"}]',NULL,'5'),
('35e1a-ge-ja-dake-06','ja-dake','ja','一日だけ予定を延ばせますか。','可以只把日程延后一天吗？','限定范围；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"一日だけ予定を延ばせますか。","reading":"いちにちだけよていをのばせますか。"}]',NULL,'6'),
('35e1a-ge-ja-dake-07','ja-dake','ja','彼だけが答えを知っています。','只有他知道答案。','限定范围；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"彼だけが答えを知っています。","reading":"かれだけがこたえをしっています。"}]',NULL,'7'),
('35e1a-ge-ja-duration-01','ja-duration','ja','空港まで一時間かかります。','到机场需要一个小时。','所需时间；新增正式例句覆盖：canonical/basic usage。',NULL,'[{"text":"空港まで一時間かかります。","reading":"くうこうまでいちじかんかかります。"}]',NULL,'1'),
('35e1a-ge-ja-duration-02','ja-duration','ja','この料理は作るのに三十分かかります。','做这道菜需要三十分钟。','所需时间；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"この料理は作るのに三十分かかります。","reading":"このりょうりはつくるのにさんじゅっぷんかかります。"}]',NULL,'2'),
('35e1a-ge-ja-duration-03','ja-duration','ja','修理には何日かかりますか。','维修需要几天？','所需时间；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"修理には何日かかりますか。","reading":"しゅうりにはなんにちかかりますか。"}]',NULL,'3'),
('35e1a-ge-ja-duration-04','ja-duration','ja','昨日は帰るのに二時間かかりました。','昨天回家花了两个小时。','所需时间；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"昨日は帰るのに二時間かかりました。","reading":"きのうはかえるのににじかんかかりました。"}]',NULL,'4'),
('35e1a-ge-ja-duration-05','ja-duration','ja','修理にはあまり時間がかかりません。','维修不太花时间。','所需时间；新增正式例句覆盖：negative / restriction。',NULL,'[{"text":"修理にはあまり時間がかかりません。","reading":"しゅうりにはあまりじかんがかかりません。"}]',NULL,'5'),
('35e1a-ge-ja-duration-06','ja-duration','ja','手続きはあと十分ほどかかります。','手续还需要大约十分钟。','所需时间；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"手続きはあと十分ほどかかります。","reading":"てつづきはあとじゅっぷんほどかかります。"}]',NULL,'6'),
('35e1a-ge-ja-duration-07','ja-duration','ja','混んでいると、もっと時間がかかります。','拥挤时会花更长时间。','所需时间；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"混んでいると、もっと時間がかかります。","reading":"こんでいると、もっとじかんがかかります。"}]',NULL,'7'),
('35e1a-ge-ja-ni-naru-01','ja-ni-naru','ja','来月、大学生になります。','下个月就成为大学生了。','变成某种状态；新增正式例句覆盖：canonical/basic usage。',NULL,'[{"text":"来月、大学生になります。","reading":"らいげつ、だいがくせいになります。"}]',NULL,'1'),
('35e1a-ge-ja-ni-naru-02','ja-ni-naru','ja','夜になると、この道は静かになります。','到了晚上，这条路会变安静。','变成某种状态；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"夜になると、この道は静かになります。","reading":"よるになると、このみちはしずかになります。"}]',NULL,'2'),
('35e1a-ge-ja-ni-naru-03','ja-ni-naru','ja','部屋がきれいになりました。','房间变干净了。','变成某种状态；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"部屋がきれいになりました。","reading":"へやがきれいになりました。"}]',NULL,'3'),
('35e1a-ge-ja-ni-naru-04','ja-ni-naru','ja','会議は午後三時からになります。','会议改为下午三点开始。','变成某种状态；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"会議は午後三時からになります。","reading":"かいぎはごごさんじからになります。"}]',NULL,'4'),
('35e1a-ge-ja-ni-naru-05','ja-ni-naru','ja','この薬を飲むと眠くなることがあります。','吃这种药有时会犯困。','变成某种状态；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"この薬を飲むと眠くなることがあります。","reading":"このくすりをのむとねむくなることがあります。"}]',NULL,'5'),
('35e1a-ge-ja-ni-naru-06','ja-ni-naru','ja','練習すれば、もっと上手になります。','练习的话会变得更熟练。','变成某种状态；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"練習すれば、もっと上手になります。","reading":"れんしゅうすれば、もっとじょうずになります。"}]',NULL,'6'),
('35e1a-ge-ja-ni-naru-07','ja-ni-naru','ja','予定は来週に変更になりました。','日程改到下周了。','变成某种状态；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"予定は来週に変更になりました。","reading":"よていはらいしゅうにへんこうになりました。"}]',NULL,'7'),
('35e1a-ge-ja-te-iru-01','ja-te-iru','ja','今、駅で電車を待っています。','现在正在车站等电车。','描述进行、结果状态或到目前的完成状况；新增正式例句覆盖：canonical/basic usage。',NULL,'[{"text":"今、駅で電車を待っています。","reading":"いま、えきででんしゃをまっています。"}]',NULL,'1'),
('35e1a-ge-ja-te-iru-02','ja-te-iru','ja','姉は東京に住んでいます。','姐姐住在东京。','描述进行、结果状态或到目前的完成状况；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"姉は東京に住んでいます。","reading":"あねはとうきょうにすんでいます。"}]',NULL,'2'),
('35e1a-ge-ja-te-iru-03','ja-te-iru','ja','窓が開いています。','窗户开着。','描述进行、结果状态或到目前的完成状况；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"窓が開いています。","reading":"まどがあいています。"}]',NULL,'3'),
('35e1a-ge-ja-te-iru-04','ja-te-iru','ja','今日は車を使っていません。','今天没有在用车。','描述进行、结果状态或到目前的完成状况；新增正式例句覆盖：negative / restriction。',NULL,'[{"text":"今日は車を使っていません。","reading":"きょうはくるまをつかっていません。"}]',NULL,'4'),
('35e1a-ge-ja-te-iru-05','ja-te-iru','ja','何を読んでいますか。','你在读什么？','描述进行、结果状态或到目前的完成状况；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"何を読んでいますか。","reading":"なにをよんでいますか。"}]',NULL,'5'),
('35e1a-ge-ja-te-iru-06','ja-te-iru','ja','この店は十年前から営業しています。','这家店从十年前起一直营业。','描述进行、结果状态或到目前的完成状况；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"この店は十年前から営業しています。","reading":"このみせはじゅうねんまえからえいぎょうしています。"}]',NULL,'6'),
('35e1a-ge-ja-te-iru-07','ja-te-iru','ja','父は今、夕食を作っています。','爸爸现在正在做晚饭。','描述进行、结果状态或到目前的完成状况；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"父は今、夕食を作っています。","reading":"ちちはいま、ゆうしょくをつくっています。"}]',NULL,'7'),
('35e1a-ge-ja-tsumori-01','ja-tsumori','ja','来年、日本へ行くつもりです。','我打算明年去日本。','表达打算；新增正式例句覆盖：canonical/basic usage。',NULL,'[{"text":"来年、日本へ行くつもりです。","reading":"らいねん、にほんへいくつもりです。"}]',NULL,'1'),
('35e1a-ge-ja-tsumori-02','ja-tsumori','ja','今日は外出しないつもりです。','今天打算不出门。','表达打算；新增正式例句覆盖：negative / restriction。',NULL,'[{"text":"今日は外出しないつもりです。","reading":"きょうはがいしゅつしないつもりです。"}]',NULL,'2'),
('35e1a-ge-ja-tsumori-03','ja-tsumori','ja','何時に帰るつもりですか。','你打算几点回去？','表达打算；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"何時に帰るつもりですか。","reading":"なんじにかえるつもりですか。"}]',NULL,'3'),
('35e1a-ge-ja-tsumori-04','ja-tsumori','ja','週末に部屋を掃除するつもりでした。','我原打算周末打扫房间。','表达打算；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"週末に部屋を掃除するつもりでした。","reading":"しゅうまつにへやをそうじするつもりでした。"}]',NULL,'4'),
('35e1a-ge-ja-tsumori-05','ja-tsumori','ja','そんなことを言うつもりはありませんでした。','我没有打算说那样的话。','表达打算；新增正式例句覆盖：negative / restriction。',NULL,'[{"text":"そんなことを言うつもりはありませんでした。","reading":"そんなことをいうつもりはありませんでした。"}]',NULL,'5'),
('35e1a-ge-ja-tsumori-06','ja-tsumori','ja','卒業後は働くつもりです。','毕业后打算工作。','表达打算；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"卒業後は働くつもりです。","reading":"そつぎょうごははたらくつもりです。"}]',NULL,'6');
INSERT INTO v2_grammar_examples(id,grammar_id,language,text,translation_zh,explanation_zh,ipa,readings_json,source_expression_id,sort_order) VALUES
('35e1a-ge-ja-tsumori-07','ja-tsumori','ja','この計画を変えるつもりはありません。','我不打算改变这个计划。','表达打算；新增正式例句覆盖：negative / restriction。',NULL,'[{"text":"この計画を変えるつもりはありません。","reading":"このけいかくをかえるつもりはありません。"}]',NULL,'7'),
('35e1a-ge-ja-kamoshirenai-01','ja-kamoshirenai','ja','明日は雪になるかもしれません。','明天可能会下雪。','表达推测；新增正式例句覆盖：negative / restriction。',NULL,'[{"text":"明日は雪になるかもしれません。","reading":"あすはゆきになるかもしれません。"}]',NULL,'1'),
('35e1a-ge-ja-kamoshirenai-02','ja-kamoshirenai','ja','彼は今日は来ないかもしれない。','他今天可能不来。','表达推测；新增正式例句覆盖：negative / restriction。',NULL,'[{"text":"彼は今日は来ないかもしれない。","reading":"かれはきょうはこないかもしれない。"}]',NULL,'2'),
('35e1a-ge-ja-kamoshirenai-03','ja-kamoshirenai','ja','午後は雨が降るかもしれません。','下午可能会下雨。','表达推测；新增正式例句覆盖：negative / restriction。',NULL,'[{"text":"午後は雨が降るかもしれません。","reading":"ごごはあめがふるかもしれません。"}]',NULL,'3'),
('35e1a-ge-ja-kamoshirenai-04','ja-kamoshirenai','ja','この薬は眠くなるかもしれません。','这种药可能会让人犯困。','表达推测；新增正式例句覆盖：negative / restriction。',NULL,'[{"text":"この薬は眠くなるかもしれません。","reading":"このくすりはねむくなるかもしれません。"}]',NULL,'4'),
('35e1a-ge-ja-kamoshirenai-05','ja-kamoshirenai','ja','予約を変更できるかもしれません。','预约或许可以更改。','表达推测；新增正式例句覆盖：negative / restriction。',NULL,'[{"text":"予約を変更できるかもしれません。","reading":"よやくをへんこうできるかもしれません。"}]',NULL,'5'),
('35e1a-ge-ja-kamoshirenai-06','ja-kamoshirenai','ja','それは誤解だったかもしれない。','那可能是误会。','表达推测；新增正式例句覆盖：negative / restriction。',NULL,'[{"text":"それは誤解だったかもしれない。","reading":"それはごかいだったかもしれない。"}]',NULL,'6'),
('35e1a-ge-ja-kamoshirenai-07','ja-kamoshirenai','ja','駅よりバス停のほうが近いかもしれません。','公交车站可能比火车站更近。','表达推测；新增正式例句覆盖：negative / restriction。',NULL,'[{"text":"駅よりバス停のほうが近いかもしれません。","reading":"えきよりばすていのほうがちかいかもしれません。"}]',NULL,'7'),
('35e1a-ge-ja-sou-01','ja-sou','ja','この料理はおいしそうです。','这道菜看起来很好吃。','表达外观上的推测；新增正式例句覆盖：canonical/basic usage。',NULL,'[{"text":"この料理はおいしそうです。","reading":"このりょうりはおいしそうです。"}]',NULL,'1'),
('35e1a-ge-ja-sou-02','ja-sou','ja','今日は雨が降らなさそうです。','今天看起来不会下雨。','表达外观上的推测；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"今日は雨が降らなさそうです。","reading":"きょうはあめがふらなさそうです。"}]',NULL,'2'),
('35e1a-ge-ja-sou-03','ja-sou','ja','そのかばんは重そうですか。','那个包看起来重吗？','表达外观上的推测；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"そのかばんは重そうですか。","reading":"そのかばんはおもそうですか。"}]',NULL,'3'),
('35e1a-ge-ja-sou-04','ja-sou','ja','電車がすぐ来そうです。','电车看起来马上要来了。','表达外观上的推测；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"電車がすぐ来そうです。","reading":"でんしゃがすぐきそうです。"}]',NULL,'4'),
('35e1a-ge-ja-sou-05','ja-sou','ja','彼は少し疲れていそうです。','他看起来有点累。','表达外观上的推测；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"彼は少し疲れていそうです。","reading":"かれはすこしつかれていそうです。"}]',NULL,'5'),
('35e1a-ge-ja-sou-06','ja-sou','ja','この仕事は時間がかかりそうです。','这项工作看起来会花时间。','表达外观上的推测；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"この仕事は時間がかかりそうです。","reading":"このしごとはじかんがかかりそうです。"}]',NULL,'6'),
('35e1a-ge-ja-sou-07','ja-sou','ja','その店はもう閉まりそうです。','那家店看起来快关门了。','表达外观上的推测；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"その店はもう閉まりそうです。","reading":"そのみせはもうしまりそうです。"}]',NULL,'7'),
('35e1a-ge-ja-hou-ga-ii-01','ja-hou-ga-ii','ja','熱があるなら、今日は休んだほうがいいです。','如果发烧，今天最好休息。','建议；新增正式例句覆盖：canonical/basic usage。',NULL,'[{"text":"熱があるなら、今日は休んだほうがいいです。","reading":"ねつがあるなら、きょうはやすんだほうがいいです。"}]',NULL,'1'),
('35e1a-ge-ja-hou-ga-ii-02','ja-hou-ga-ii','ja','この道は夜一人で歩かないほうがいいです。','这条路晚上最好不要一个人走。','建议；新增正式例句覆盖：negative / restriction。',NULL,'[{"text":"この道は夜一人で歩かないほうがいいです。","reading":"このみちはよるひとりであるかないほうがいいです。"}]',NULL,'2'),
('35e1a-ge-ja-hou-ga-ii-03','ja-hou-ga-ii','ja','先に予約したほうがいいですか。','最好事先预约吗？','建议；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"先に予約したほうがいいですか。","reading":"さきによやくしたほうがいいですか。"}]',NULL,'3'),
('35e1a-ge-ja-hou-ga-ii-04','ja-hou-ga-ii','ja','大事な書類はコピーしておいたほうがいいです。','重要文件最好事先复印。','建议；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"大事な書類はコピーしておいたほうがいいです。","reading":"だいじなしょるいはこぴーしておいたほうがいいです。"}]',NULL,'4'),
('35e1a-ge-ja-hou-ga-ii-05','ja-hou-ga-ii','ja','そんなに心配しないほうがいいですよ。','最好不要那么担心。','建议；新增正式例句覆盖：negative / restriction。',NULL,'[{"text":"そんなに心配しないほうがいいですよ。","reading":"そんなにしんぱいしないほうがいいですよ。"}]',NULL,'5'),
('35e1a-ge-ja-hou-ga-ii-06','ja-hou-ga-ii','ja','電車よりバスで行ったほうがいいと思います。','我觉得最好坐公交车去，而不是坐电车。','建议；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"電車よりバスで行ったほうがいいと思います。","reading":"でんしゃよりばすでいったほうがいいとおもいます。"}]',NULL,'6'),
('35e1a-ge-ja-hou-ga-ii-07','ja-hou-ga-ii','ja','わからないときは、すぐ聞いたほうがいいです。','不懂的时候最好马上问。','建议；新增正式例句覆盖：negative / restriction。',NULL,'[{"text":"わからないときは、すぐ聞いたほうがいいです。","reading":"わからないときは、すぐきいたほうがいいです。"}]',NULL,'7'),
('35e1a-ge-ja-te-morau-01','ja-te-morau','ja','友達に駅まで送ってもらいました。','朋友送我到了车站。','请求受惠；新增正式例句覆盖：canonical/basic usage。',NULL,'[{"text":"友達に駅まで送ってもらいました。","reading":"ともだちにえきまでおくってもらいました。"}]',NULL,'1'),
('35e1a-ge-ja-te-morau-02','ja-te-morau','ja','ここに名前を書いてもらえますか。','能请你在这里写名字吗？','请求受惠；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"ここに名前を書いてもらえますか。","reading":"ここになまえをかいてもらえますか。"}]',NULL,'2'),
('35e1a-ge-ja-te-morau-03','ja-te-morau','ja','先生に文章を直してもらいました。','老师帮我修改了文章。','请求受惠；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"先生に文章を直してもらいました。","reading":"せんせいにぶんしょうをなおしてもらいました。"}]',NULL,'3'),
('35e1a-ge-ja-te-morau-04','ja-te-morau','ja','少し待ってもらえませんか。','能请你稍等一下吗？','请求受惠；新增正式例句覆盖：negative / restriction。',NULL,'[{"text":"少し待ってもらえませんか。","reading":"すこしまってもらえませんか。"}]',NULL,'4'),
('35e1a-ge-ja-te-morau-05','ja-te-morau','ja','店員さんに別のサイズを持ってきてもらいました。','店员给我拿来了别的尺码。','请求受惠；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"店員さんに別のサイズを持ってきてもらいました。","reading":"てんいんさんにべつのさいずをもってきてもらいました。"}]',NULL,'5'),
('35e1a-ge-ja-te-morau-06','ja-te-morau','ja','誰に手伝ってもらいましたか。','你请谁帮忙了？','请求受惠；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"誰に手伝ってもらいましたか。","reading":"だれにてつだってもらいましたか。"}]',NULL,'6'),
('35e1a-ge-ja-te-morau-07','ja-te-morau','ja','明日の午後に変更してもらえますか。','能请你改到明天下午吗？','请求受惠；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"明日の午後に変更してもらえますか。","reading":"あすのごごにへんこうしてもらえますか。"}]',NULL,'7'),
('35e1a-ge-ja-nara-01','ja-nara','ja','電車で行くなら、この駅で乗り換えてください。','如果坐电车去，请在这个车站换乘。','承接条件；新增正式例句覆盖：canonical/basic usage。',NULL,'[{"text":"電車で行くなら、この駅で乗り換えてください。","reading":"でんしゃでいくなら、このえきでのりかえてください。"}]',NULL,'1'),
('35e1a-ge-ja-nara-02','ja-nara','ja','辛い物が苦手なら、こちらの料理がおすすめです。','如果不喜欢辣的，推荐这道菜。','承接条件；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"辛い物が苦手なら、こちらの料理がおすすめです。","reading":"からいものがにがてなら、こちらのりょうりがおすすめです。"}]',NULL,'2'),
('35e1a-ge-ja-nara-03','ja-nara','ja','明日が無理なら、金曜日はどうですか。','如果明天不行，星期五怎么样？','承接条件；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"明日が無理なら、金曜日はどうですか。","reading":"あすがむりなら、きんようびはどうですか。"}]',NULL,'3'),
('35e1a-ge-ja-nara-04','ja-nara','ja','返品するなら、レシートを捨てないでください。','如果要退货，请不要丢掉收据。','承接条件；新增正式例句覆盖：negative / restriction。',NULL,'[{"text":"返品するなら、レシートを捨てないでください。","reading":"へんぴんするなら、れしーとをすてないでください。"}]',NULL,'4'),
('35e1a-ge-ja-nara-05','ja-nara','ja','静かな部屋なら、三階にあります。','如果要安静的房间，三楼有。','承接条件；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"静かな部屋なら、三階にあります。","reading":"しずかなへやなら、さんがいにあります。"}]',NULL,'5'),
('35e1a-ge-ja-nara-06','ja-nara','ja','田中さんも参加するなら、私も行きます。','如果田中也参加，我也去。','承接条件；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"田中さんも参加するなら、私も行きます。","reading":"たなかさんもさんかするなら、わたしもいきます。"}]',NULL,'6'),
('35e1a-ge-ja-nara-07','ja-nara','ja','わからないことがあるなら、今聞いてください。','如果有不懂的地方，现在请问。','承接条件；新增正式例句覆盖：negative / restriction。',NULL,'[{"text":"わからないことがあるなら、今聞いてください。","reading":"わからないことがあるなら、いまきいてください。"}]',NULL,'7'),
('35e1a-ge-ja-tara-01','ja-tara','ja','駅に着いたら、電話してください。','到了车站后请打电话。','条件或完成后；新增正式例句覆盖：canonical/basic usage。',NULL,'[{"text":"駅に着いたら、電話してください。","reading":"えきについたら、でんわしてください。"}]',NULL,'1'),
('35e1a-ge-ja-tara-02','ja-tara','ja','雨が降ったら、家で映画を見ましょう。','如果下雨，就在家看电影吧。','条件或完成后；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"雨が降ったら、家で映画を見ましょう。","reading":"あめがふったら、いえでえいがをみましょう。"}]',NULL,'2'),
('35e1a-ge-ja-tara-03','ja-tara','ja','時間がなかったら、明日でも大丈夫です。','如果没时间，明天也可以。','条件或完成后；新增正式例句覆盖：negative / restriction。',NULL,'[{"text":"時間がなかったら、明日でも大丈夫です。","reading":"じかんがなかったら、あすでもだいじょうぶです。"}]',NULL,'3'),
('35e1a-ge-ja-tara-04','ja-tara','ja','薬を飲んでも治らなかったら、病院へ行ってください。','吃药也不好转的话，请去医院。','条件或完成后；新增正式例句覆盖：negative / restriction。',NULL,'[{"text":"薬を飲んでも治らなかったら、病院へ行ってください。","reading":"くすりをのんでもなおらなかったら、びょういんへいってください。"}]',NULL,'4');
INSERT INTO v2_grammar_examples(id,grammar_id,language,text,translation_zh,explanation_zh,ipa,readings_json,source_expression_id,sort_order) VALUES
('35e1a-ge-ja-tara-05','ja-tara','ja','仕事が終わったら、何をしますか。','工作结束后做什么？','条件或完成后；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"仕事が終わったら、何をしますか。","reading":"しごとがおわったら、なにをしますか。"}]',NULL,'5'),
('35e1a-ge-ja-tara-06','ja-tara','ja','もっと安かったら、買いたいです。','如果再便宜一点，我想买。','条件或完成后；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"もっと安かったら、買いたいです。","reading":"もっとやすかったら、かいたいです。"}]',NULL,'6'),
('35e1a-ge-ja-tara-07','ja-tara','ja','道に迷ったら、駅員に聞きます。','如果迷路，就问车站工作人员。','条件或完成后；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"道に迷ったら、駅員に聞きます。","reading":"みちにまよったら、えきいんにききます。"}]',NULL,'7'),
('35e1a-ge-ja-koto-ga-aru-01','ja-koto-ga-aru','ja','私は北海道へ行ったことがあります。','我去过北海道。','过去经历；新增正式例句覆盖：canonical/basic usage。',NULL,'[{"text":"私は北海道へ行ったことがあります。","reading":"わたしはほっかいどうへいったことがあります。"}]',NULL,'1'),
('35e1a-ge-ja-koto-ga-aru-02','ja-koto-ga-aru','ja','この料理を食べたことはありません。','我没吃过这道菜。','过去经历；新增正式例句覆盖：negative / restriction。',NULL,'[{"text":"この料理を食べたことはありません。","reading":"このりょうりをたべたことはありません。"}]',NULL,'2'),
('35e1a-ge-ja-koto-ga-aru-03','ja-koto-ga-aru','ja','一人で海外へ行ったことがありますか。','你一个人去过国外吗？','过去经历；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"一人で海外へ行ったことがありますか。","reading":"ひとりでかいがいへいったことがありますか。"}]',NULL,'3'),
('35e1a-ge-ja-koto-ga-aru-04','ja-koto-ga-aru','ja','電車の中に財布を忘れたことがあります。','我曾经把钱包忘在电车里。','过去经历；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"電車の中に財布を忘れたことがあります。","reading":"でんしゃのなかにさいふをわすれたことがあります。"}]',NULL,'4'),
('35e1a-ge-ja-koto-ga-aru-05','ja-koto-ga-aru','ja','彼とは前に会ったことがあります。','我以前见过他。','过去经历；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"彼とは前に会ったことがあります。","reading":"かれとはまえにあったことがあります。"}]',NULL,'5'),
('35e1a-ge-ja-koto-ga-aru-06','ja-koto-ga-aru','ja','今までに入院したことがありますか。','你以前住过院吗？','过去经历；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"今までに入院したことがありますか。","reading":"いままでににゅういんしたことがありますか。"}]',NULL,'6'),
('35e1a-ge-ja-koto-ga-aru-07','ja-koto-ga-aru','ja','この店を利用したことがある人はいますか。','有人用过这家店吗？','过去经历；新增正式例句覆盖：natural context with appropriate inflection/register。',NULL,'[{"text":"この店を利用したことがある人はいますか。","reading":"このみせをりようしたことがあるひとはいますか。"}]',NULL,'7');
